jdieg0/coronavirus-dresden-data

latest-json
```diff -u pjson/2020-11-12T110404Z.json pjson/2020-11-12T124804Z.json```:
```
--- pjson/2020-11-12T110404Z.json	2020-11-12 11:04:04.717783616 +0000
+++ pjson/2020-11-12T124804Z.json	2020-11-12 12:48:05.040239751 +0000
@@ -5637,7 +5637,7 @@
{
"Datum": "11.11.2020",
-        "Fallzahl": 3551,
+        "Fallzahl": 3540,
"ObjectId": 250,
"Sterbefall": null,
"Genesungsfall": null,
@@ -5665,7 +5665,7 @@
"Genesungsfall": 2110,
"Hospitalisierung": 195,
-        "Zuwachs_Fallzahl": 64,
+        "Zuwachs_Fallzahl": 75,
"Zuwachs_Sterbefall": 3,
"Zuwachs_Krankenhauseinweisung": 1,
"Zuwachs_Genesung": 140,
```
=> New data set: 2020-11-12T124804Z

latest-json
```diff -u pjson/2020-11-12T124804Z.json pjson/2020-11-13T110903Z.json```:
```
--- pjson/2020-11-12T124804Z.json	2020-11-12 12:48:05.040239751 +0000
+++ pjson/2020-11-13T110903Z.json	2020-11-13 11:09:04.115986969 +0000
@@ -5320,7 +5320,7 @@
-        "F\u00e4lle_Meldedatum": 91,
+        "F\u00e4lle_Meldedatum": 92,
"Hosp_Meldedatum": 5
@@ -5386,7 +5386,7 @@
"Datum_neu": 1604016000000,
-        "F\u00e4lle_Meldedatum": 155,
+        "F\u00e4lle_Meldedatum": 154, …
```
=> New data set: 2020-11-13T110903Z

latest-json
```diff -u pjson/2020-11-14T110304Z.json pjson/2020-11-15T110104Z.json```:
```
--- pjson/2020-11-14T110304Z.json	2020-11-14 11:03:04.618845849 +0000
+++ pjson/2020-11-15T110104Z.json	2020-11-15 11:01:04.858352289 +0000
@@ -5345,7 +5345,7 @@
"F\u00e4lle_Meldedatum": 144,
-        "Hosp_Meldedatum": 5
+        "Hosp_Meldedatum": 6
}
},
{
@@ -5477,7 +5477,7 @@
"F\u00e4lle_Meldedatum": 149,
"SterbeF_Meldedatum": 4,
-        "Hosp_Meldedatum": 4
+        "Hosp_Meldedatum": 5
}
},
{
@@ -5538,9 +5538,9 @@
"Zuwachs_Genesung": 38,
- …
```
=> New data set: 2020-11-15T110104Z

latest-json
```diff -u pjson/2020-11-15T110104Z.json pjson/2020-11-16T110604Z.json```:
```
--- pjson/2020-11-15T110104Z.json	2020-11-15 11:01:04.858352289 +0000
+++ pjson/2020-11-16T110604Z.json	2020-11-16 11:06:04.757646175 +0000
@@ -5452,7 +5452,7 @@
"Datum_neu": 1604275200000,
-        "F\u00e4lle_Meldedatum": 170,
+        "F\u00e4lle_Meldedatum": 171,
"Hosp_Meldedatum": 5
@@ -5474,7 +5474,7 @@
-        "F\u00e4lle_Meldedatum": 149,
+        "F\u00e4lle_Meldedatum": 150,
"SterbeF_Meldedatum": 4, …
```
=> New data set: 2020-11-16T110604Z

latest-json
```diff -u pjson/2020-11-16T110604Z.json pjson/2020-11-17T110104Z.json```:
```
--- pjson/2020-11-16T110604Z.json	2020-11-16 11:06:04.757646175 +0000
+++ pjson/2020-11-17T110104Z.json	2020-11-17 11:01:04.433060353 +0000
@@ -5166,7 +5166,7 @@
"Datum_neu": 1603152000000,
-        "F\u00e4lle_Meldedatum": 85,
+        "F\u00e4lle_Meldedatum": 87,
"Hosp_Meldedatum": 3
@@ -5210,7 +5210,7 @@
"Datum_neu": 1603324800000,
-        "F\u00e4lle_Meldedatum": 89,
+        "F\u00e4lle_Meldedatum": 88, …
```
=> New data set: 2020-11-17T110104Z

latest-json
```diff -u pjson/2020-11-17T110104Z.json pjson/2020-11-18T111404Z.json```:
```
--- pjson/2020-11-17T110104Z.json	2020-11-17 11:01:04.433060353 +0000
+++ pjson/2020-11-18T111404Z.json	2020-11-18 11:14:04.833638025 +0000
@@ -4066,7 +4066,7 @@
"Datum_neu": 1598832000000,
-        "F\u00e4lle_Meldedatum": 6,
@@ -4198,7 +4198,7 @@
"Datum_neu": 1599350400000, …
```
=> New data set: 2020-11-18T111404Z

latest-json
```diff -u pjson/2020-11-18T111404Z.json pjson/2020-11-19T112104Z.json```:
```
--- pjson/2020-11-18T111404Z.json	2020-11-18 11:14:04.833638025 +0000
+++ pjson/2020-11-19T112104Z.json	2020-11-19 11:21:04.375907263 +0000
@@ -4066,7 +4066,7 @@
"Datum_neu": 1598832000000,
-        "F\u00e4lle_Meldedatum": 5,
@@ -4198,7 +4198,7 @@
"Datum_neu": 1599350400000,
+        "F\u00e4lle_Meldedatum": 3, …
```
=> New data set: 2020-11-19T112104Z

latest-json
```diff -u pjson/2020-11-20T110303Z.json pjson/2020-11-21T111004Z.json```:
```
--- pjson/2020-11-20T110303Z.json	2020-11-20 11:03:04.134065745 +0000
+++ pjson/2020-11-21T111004Z.json	2020-11-21 11:10:04.870376613 +0000
@@ -5543,7 +5543,7 @@
"F\u00e4lle_Meldedatum": 151,
-        "Hosp_Meldedatum": 6
+        "Hosp_Meldedatum": 7
}
},
{
@@ -5565,7 +5565,7 @@
"F\u00e4lle_Meldedatum": 68,
-        "Hosp_Meldedatum": 3
+        "Hosp_Meldedatum": 2
}
},
{
@@ -5631,7 +5631,7 @@
"F\u00e4lle_Meldedatum": 123,
-        "Hosp_Meldedatum": 3
+ …
```
=> New data set: 2020-11-21T111004Z

latest-json
```diff -u pjson/2020-11-21T111004Z.json pjson/2020-11-22T110504Z.json```:
```
--- pjson/2020-11-21T111004Z.json	2020-11-21 11:10:04.870376613 +0000
+++ pjson/2020-11-22T110504Z.json	2020-11-22 11:05:04.931221570 +0000
@@ -4198,7 +4198,7 @@
"Datum_neu": 1599350400000,
@@ -4374,7 +4374,7 @@
-        "F\u00e4lle_Meldedatum": 5, …
```
=> New data set: 2020-11-22T110504Z

latest-json
```diff -u pjson/2020-11-22T110504Z.json pjson/2020-11-23T113503Z.json```:
```
--- pjson/2020-11-22T110504Z.json	2020-11-22 11:05:04.931221570 +0000
+++ pjson/2020-11-23T113503Z.json	2020-11-23 11:35:03.837793693 +0000
@@ -5631,7 +5631,7 @@
"F\u00e4lle_Meldedatum": 123,
-        "Hosp_Meldedatum": 8
+        "Hosp_Meldedatum": 9
}
},
{
@@ -5694,10 +5694,10 @@
-        "F\u00e4lle_Meldedatum": 194,
+        "F\u00e4lle_Meldedatum": 197,
-        "Hosp_Meldedatum": 9
+        "Hosp_Meldedatum": 10
}
},
{
@@ …
```
=> New data set: 2020-11-23T113503Z

latest-json
```diff -u pjson/2020-11-23T113503Z.json pjson/2020-11-24T111303Z.json```:
```
--- pjson/2020-11-23T113503Z.json	2020-11-23 11:35:03.837793693 +0000
+++ pjson/2020-11-24T111303Z.json	2020-11-24 11:13:03.422233187 +0000
@@ -5100,7 +5100,7 @@
"Datum_neu": 1602892800000,
-        "F\u00e4lle_Meldedatum": 40,
+        "F\u00e4lle_Meldedatum": 43,
@@ -5144,7 +5144,7 @@
-        "F\u00e4lle_Meldedatum": 35,
+        "F\u00e4lle_Meldedatum": 34, …
```
=> New data set: 2020-11-24T111303Z

latest-json
```diff -u pjson/2020-11-24T111303Z.json pjson/2020-11-25T111503Z.json```:
```
--- pjson/2020-11-24T111303Z.json	2020-11-24 11:13:03.422233187 +0000
+++ pjson/2020-11-25T111503Z.json	2020-11-25 11:15:03.555581003 +0000
@@ -1624,7 +1624,7 @@
"Datum_neu": 1589241600000,
-        "F\u00e4lle_Meldedatum": 0,
+        "F\u00e4lle_Meldedatum": 1,
@@ -5719,7 +5719,7 @@
"F\u00e4lle_Meldedatum": 84,
-        "Hosp_Meldedatum": 0
+        "Hosp_Meldedatum": 1
}
},
{
@@ -5738,7 +5738,7 @@
"Inzidenz": …
```
=> New data set: 2020-11-25T111503Z

latest-json
```diff -u pjson/2020-11-26T112103Z.json pjson/2020-11-27T110203Z.json```:
```
--- pjson/2020-11-26T112103Z.json	2020-11-26 11:21:03.683008133 +0000
+++ pjson/2020-11-27T110203Z.json	2020-11-27 11:02:03.662379333 +0000
@@ -5188,7 +5188,7 @@
"Datum_neu": 1603238400000,
-        "F\u00e4lle_Meldedatum": 70,
+        "F\u00e4lle_Meldedatum": 71,
"Hosp_Meldedatum": 5
@@ -5298,7 +5298,7 @@
+        "F\u00e4lle_Meldedatum": 75, …
```
=> New data set: 2020-11-27T110203Z

latest-json
```diff -u pjson/2020-11-27T110203Z.json pjson/2020-11-28T110403Z.json```:
```
--- pjson/2020-11-27T110203Z.json	2020-11-27 11:02:03.662379333 +0000
+++ pjson/2020-11-28T110403Z.json	2020-11-28 11:04:03.757265090 +0000
@@ -5034,7 +5034,7 @@
"Datum_neu": 1602633600000,
-        "F\u00e4lle_Meldedatum": 27,
+        "F\u00e4lle_Meldedatum": 28,
"Hosp_Meldedatum": 1
@@ -5056,7 +5056,7 @@
"Datum_neu": 1602720000000,
-        "F\u00e4lle_Meldedatum": 61,
+        "F\u00e4lle_Meldedatum": 62, …
```
=> New data set: 2020-11-28T110403Z

latest-json
```diff -u pjson/2020-11-28T110403Z.json pjson/2020-11-29T110203Z.json```:
```
--- pjson/2020-11-28T110403Z.json	2020-11-28 11:04:03.757265090 +0000
+++ pjson/2020-11-29T110203Z.json	2020-11-29 11:02:03.215769531 +0000
@@ -4836,7 +4836,7 @@
"Datum_neu": 1601856000000,
-        "F\u00e4lle_Meldedatum": 22,
+        "F\u00e4lle_Meldedatum": 23,
@@ -5868,7 +5868,7 @@
"Zuwachs_Genesung": 68,
-        "Inzidenz": 136.5,
"Datum_neu": 1605916800000,
"F\u00e4lle_Meldedatum": …
```
=> New data set: 2020-11-29T110203Z

latest-json
```diff -u pjson/2020-11-30T122803Z.json pjson/2020-11-30T124004Z.json```:
```
--- pjson/2020-11-30T122803Z.json	2020-11-30 12:28:03.758099836 +0000
+++ pjson/2020-11-30T124004Z.json	2020-11-30 12:40:04.307371754 +0000
@@ -5953,7 +5953,7 @@
+        "F\u00e4lle_Meldedatum": 199,
@@ -6022,7 +6022,7 @@
-        "F\u00e4lle_Meldedatum": 224,
+        "F\u00e4lle_Meldedatum": 225, …
```
=> New data set: 2020-11-30T124004Z

latest-json
```diff -u pjson/2020-11-30T124004Z.json pjson/2020-11-30T145103Z.json```:
```
--- pjson/2020-11-30T124004Z.json	2020-11-30 12:40:04.307371754 +0000
+++ pjson/2020-11-30T145103Z.json	2020-11-30 14:51:04.020221816 +0000
@@ -6187,7 +6187,7 @@
-        "Inzidenz_RKI": null
+        "Inzidenz_RKI": 135.4
}
},
{
@@ -6210,7 +6210,7 @@
-        "Inzidenz_RKI": null
+        "Inzidenz_RKI": 126.4
}
},
{
@@ -6233,7 +6233,7 @@
-        "Inzidenz_RKI": null
+ …
```
=> New data set: 2020-11-30T145103Z

latest-json
```diff -u pjson/2020-11-30T145103Z.json pjson/2020-12-01T111103Z.json```:
```
--- pjson/2020-11-30T145103Z.json	2020-11-30 14:51:04.020221816 +0000
+++ pjson/2020-12-01T111103Z.json	2020-12-01 11:11:03.896401736 +0000
@@ -4987,7 +4987,7 @@
"Datum_neu": 1601596800000,
-        "F\u00e4lle_Meldedatum": 13,
@@ -5378,7 +5378,7 @@
-        "F\u00e4lle_Meldedatum": 34,
+        "F\u00e4lle_Meldedatum": 37, …
```
=> New data set: 2020-12-01T111103Z

latest-json
```diff -u pjson/2020-12-01T111103Z.json pjson/2020-12-02T111803Z.json```:
```
--- pjson/2020-12-01T111103Z.json	2020-12-01 11:11:03.896401736 +0000
+++ pjson/2020-12-02T111803Z.json	2020-12-02 11:18:03.341869304 +0000
@@ -5585,7 +5585,7 @@
"Datum_neu": 1603843200000,
+        "F\u00e4lle_Meldedatum": 147,
@@ -6025,7 +6025,7 @@
"F\u00e4lle_Meldedatum": 225,
"Inzidenz_RKI": null
}
},
@@ -6045,7 +6045,7 @@ …
```
=> New data set: 2020-12-02T111803Z

latest-json
```diff -u pjson/2020-12-03T111703Z.json pjson/2020-12-04T111003Z.json```:
```
--- pjson/2020-12-03T111703Z.json	2020-12-03 11:17:03.294037878 +0000
+++ pjson/2020-12-04T111003Z.json	2020-12-04 11:10:04.031798279 +0000
@@ -6137,7 +6137,7 @@
"Datum_neu": 1605916800000,
-        "F\u00e4lle_Meldedatum": 91,
+        "F\u00e4lle_Meldedatum": 90,
@@ -6183,7 +6183,7 @@
-        "F\u00e4lle_Meldedatum": 193,
+        "F\u00e4lle_Meldedatum": 194, …
```
=> New data set: 2020-12-04T111003Z

latest-json
```diff -u pjson/2020-12-04T111003Z.json pjson/2020-12-05T113603Z.json```:
```
--- pjson/2020-12-04T111003Z.json	2020-12-04 11:10:04.031798279 +0000
+++ pjson/2020-12-05T113603Z.json	2020-12-05 11:36:03.840108615 +0000
@@ -4274,7 +4274,7 @@
"Datum_neu": 1598918400000,
+        "F\u00e4lle_Meldedatum": 4,
@@ -4573,7 +4573,7 @@
-        "F\u00e4lle_Meldedatum": 6, …
```
=> New data set: 2020-12-05T113603Z

latest-json
```diff -u pjson/2020-12-05T113603Z.json pjson/2020-12-06T110103Z.json```:
```
--- pjson/2020-12-05T113603Z.json	2020-12-05 11:36:03.840108615 +0000
+++ pjson/2020-12-06T110103Z.json	2020-12-06 11:01:03.442563389 +0000
@@ -3676,7 +3676,7 @@
"Datum_neu": 1596672000000,
-        "F\u00e4lle_Meldedatum": 1,
@@ -4274,7 +4274,7 @@
"Datum_neu": 1598918400000,
+        "F\u00e4lle_Meldedatum": 3, …
```
=> New data set: 2020-12-06T110103Z

latest-json
```diff -u pjson/2020-12-06T110103Z.json pjson/2020-12-07T111105Z.json```:
```
--- pjson/2020-12-06T110103Z.json	2020-12-06 11:01:03.442563389 +0000
+++ pjson/2020-12-07T111105Z.json	2020-12-07 11:11:05.550823826 +0000
@@ -5631,7 +5631,7 @@
"Datum_neu": 1604016000000,
-        "F\u00e4lle_Meldedatum": 157,
+        "F\u00e4lle_Meldedatum": 158,
@@ -6252,7 +6252,7 @@
-        "F\u00e4lle_Meldedatum": 244,
+        "F\u00e4lle_Meldedatum": 246,
"SterbeF_Meldedatum": 7, …
```
=> New data set: 2020-12-07T111105Z

latest-json
```diff -u pjson/2020-12-07T111105Z.json pjson/2020-12-08T112603Z.json```:
```
--- pjson/2020-12-07T111105Z.json	2020-12-07 11:11:05.550823826 +0000
+++ pjson/2020-12-08T112603Z.json	2020-12-08 11:26:04.032600632 +0000
@@ -5748,7 +5748,7 @@
"F\u00e4lle_Meldedatum": 202,
-        "SterbeF_Meldedatum": 1,
+        "SterbeF_Meldedatum": 2,
"Inzidenz_RKI": null
}
@@ -6206,7 +6206,7 @@
-        "F\u00e4lle_Meldedatum": 267,
+        "F\u00e4lle_Meldedatum": 268,
@@ …
```
=> New data set: 2020-12-08T112603Z

latest-json
```diff -u pjson/2020-12-09T080904Z.json pjson/2020-12-09T120703Z.json```:
```
--- pjson/2020-12-09T080904Z.json	2020-12-09 08:09:04.341960398 +0000
+++ pjson/2020-12-09T120703Z.json	2020-12-09 12:07:03.993499451 +0000
@@ -5568,7 +5568,7 @@
+        "F\u00e4lle_Meldedatum": 8,
@@ -6940,7 +6940,7 @@
"Datum_neu": 1604275200000,
-        "F\u00e4lle_Meldedatum": 185,
+        "F\u00e4lle_Meldedatum": 186, …
```
=> New data set: 2020-12-09T120703Z

latest-json
```diff -u pjson/2020-12-09T123003Z.json pjson/2020-12-10T111803Z.json```:
```
--- pjson/2020-12-09T123003Z.json	2020-12-09 12:30:03.963396857 +0000
+++ pjson/2020-12-10T111803Z.json	2020-12-10 11:18:03.737862318 +0000
@@ -8025,7 +8025,7 @@
+        "F\u00e4lle_Meldedatum": 199,
@@ -8335,7 +8335,7 @@
-        "F\u00e4lle_Meldedatum": 195, …
```
=> New data set: 2020-12-10T111803Z

latest-json
```diff -u pjson/2020-12-10T111803Z.json pjson/2020-12-11T111703Z.json```:
```
--- pjson/2020-12-10T111803Z.json	2020-12-10 11:18:03.737862318 +0000
+++ pjson/2020-12-11T111703Z.json	2020-12-11 11:17:03.679611164 +0000
@@ -7033,7 +7033,7 @@
"Datum_neu": 1602460800000,
-        "F\u00e4lle_Meldedatum": 16,
+        "F\u00e4lle_Meldedatum": 18,
@@ -7064,7 +7064,7 @@
"Datum_neu": 1602547200000,
-        "F\u00e4lle_Meldedatum": 39,
+        "F\u00e4lle_Meldedatum": 40, …
```
=> New data set: 2020-12-11T111703Z

latest-json
```diff -u pjson/2020-12-11T111703Z.json pjson/2020-12-12T111803Z.json```:
```
--- pjson/2020-12-11T111703Z.json	2020-12-11 11:17:03.679611164 +0000
+++ pjson/2020-12-12T111803Z.json	2020-12-12 11:18:03.796645819 +0000
@@ -7777,7 +7777,7 @@
"Datum_neu": 1604534400000,
-        "F\u00e4lle_Meldedatum": 131,
+        "F\u00e4lle_Meldedatum": 132,
@@ -7901,7 +7901,7 @@
"Datum_neu": 1604880000000,
-        "F\u00e4lle_Meldedatum": 100,
+        "F\u00e4lle_Meldedatum": 101, …
```
=> New data set: 2020-12-12T111803Z

latest-json
```diff -u pjson/2020-12-12T111803Z.json pjson/2020-12-13T110904Z.json```:
```
--- pjson/2020-12-12T111803Z.json	2020-12-12 11:18:03.796645819 +0000
+++ pjson/2020-12-13T110904Z.json	2020-12-13 11:09:04.435678280 +0000
@@ -8369,7 +8369,7 @@
"F\u00e4lle_Meldedatum": 271,
+        "Hosp_Meldedatum": 8,
@@ -8397,7 +8397,7 @@
-        "F\u00e4lle_Meldedatum": 269,
+        "F\u00e4lle_Meldedatum": 270, …
```
=> New data set: 2020-12-13T110904Z

latest-json
```diff -u pjson/2020-12-13T110904Z.json pjson/2020-12-14T111203Z.json```:
```
--- pjson/2020-12-13T110904Z.json	2020-12-13 11:09:04.435678280 +0000
+++ pjson/2020-12-14T111203Z.json	2020-12-14 11:12:03.967281130 +0000
@@ -7128,7 +7128,7 @@
"Datum_neu": 1602720000000,
"F\u00e4lle_Meldedatum": 64,
-        "SterbeF_Meldedatum": 1,
+        "SterbeF_Meldedatum": 0,
@@ -7283,7 +7283,7 @@
"Datum_neu": 1603152000000,
"F\u00e4lle_Meldedatum": 88,
-        "SterbeF_Meldedatum": 0,
+        "SterbeF_Meldedatum": 1, …
```
=> New data set: 2020-12-14T111203Z

latest-json
```diff -u pjson/2020-12-14T155003Z.json pjson/2020-12-15T112404Z.json```:
```
--- pjson/2020-12-14T155003Z.json	2020-12-14 15:50:03.631339260 +0000
+++ pjson/2020-12-15T112404Z.json	2020-12-15 11:24:04.836423152 +0000
@@ -8583,7 +8583,7 @@
-        "F\u00e4lle_Meldedatum": 323,
+        "F\u00e4lle_Meldedatum": 322,
@@ -8645,7 +8645,7 @@
-        "F\u00e4lle_Meldedatum": 288,
+        "F\u00e4lle_Meldedatum": 287, …
```
=> New data set: 2020-12-15T112404Z

latest-json
```diff -u pjson/2020-12-15T112404Z.json pjson/2020-12-16T110604Z.json```:
```
--- pjson/2020-12-15T112404Z.json	2020-12-15 11:24:04.836423152 +0000
+++ pjson/2020-12-16T110604Z.json	2020-12-16 11:06:04.430770507 +0000
@@ -8583,7 +8583,7 @@
-        "F\u00e4lle_Meldedatum": 322,
+        "F\u00e4lle_Meldedatum": 323,
@@ -8769,7 +8769,7 @@
-        "F\u00e4lle_Meldedatum": 350,
+        "F\u00e4lle_Meldedatum": 349, …
```
=> New data set: 2020-12-16T110604Z

latest-json
```diff -u pjson/2020-12-16T113203Z.json pjson/2020-12-17T112304Z.json```:
```
--- pjson/2020-12-16T113203Z.json	2020-12-16 11:32:03.771083287 +0000
+++ pjson/2020-12-17T112304Z.json	2020-12-17 11:23:04.182785584 +0000
@@ -6847,7 +6847,7 @@
-        "F\u00e4lle_Meldedatum": 36,
+        "F\u00e4lle_Meldedatum": 38,
@@ -7064,7 +7064,7 @@
"Datum_neu": 1602547200000,
-        "F\u00e4lle_Meldedatum": 40, …
```
=> New data set: 2020-12-17T112304Z

latest-json
```diff -u pjson/2020-12-17T112304Z.json pjson/2020-12-17T113404Z.json```:
```
--- pjson/2020-12-17T112304Z.json	2020-12-17 11:23:04.182785584 +0000
+++ pjson/2020-12-17T113404Z.json	2020-12-17 11:34:04.586475806 +0000
@@ -9071,7 +9071,7 @@
"Sterbefall": 169,
"Genesungsfall": 7385,
-        "Hospitalisierung": null,
+        "Hospitalisierung": 644,
"Zuwachs_Fallzahl": 273,
"Zuwachs_Sterbefall": 0,
"Zuwachs_Krankenhauseinweisung": 22,
```
If there are no anomalies, you are welcome to **merge** this symlink pointing to the new data set so that the new statistics will become publicly available on the [Grafana …
=> New data set: 2020-12-17T113404Z

latest-json
```diff -u pjson/2020-12-18T063604Z.json pjson/2020-12-18T112203Z.json```:
```
--- pjson/2020-12-18T063604Z.json	2020-12-18 06:36:04.758303212 +0000
+++ pjson/2020-12-18T112203Z.json	2020-12-18 11:22:03.864677100 +0000
@@ -8413,7 +8413,7 @@
-        "F\u00e4lle_Meldedatum": 236,
+        "F\u00e4lle_Meldedatum": 237,
@@ -8637,9 +8637,9 @@
-        "F\u00e4lle_Meldedatum": 273,
+        "F\u00e4lle_Meldedatum": 275,
- …
```
=> New data set: 2020-12-18T112203Z

latest-json
```diff -u pjson/2020-12-18T112203Z.json pjson/2020-12-19T110303Z.json```:
```
--- pjson/2020-12-18T112203Z.json	2020-12-18 11:22:03.864677100 +0000
+++ pjson/2020-12-19T110303Z.json	2020-12-19 11:03:04.022023858 +0000
@@ -7357,7 +7357,7 @@
"Datum_neu": 1602720000000,
-        "F\u00e4lle_Meldedatum": 64,
+        "F\u00e4lle_Meldedatum": 65,
@@ -7901,7 +7901,7 @@
-        "F\u00e4lle_Meldedatum": 35,
+        "F\u00e4lle_Meldedatum": 37, …
```
=> New data set: 2020-12-19T110303Z

latest-json
```diff -u pjson/2020-12-19T110303Z.json pjson/2020-12-20T124103Z.json```:
```
--- pjson/2020-12-19T110303Z.json	2020-12-19 11:03:04.022023858 +0000
+++ pjson/2020-12-20T124103Z.json	2020-12-20 12:41:03.205850851 +0000
@@ -7965,7 +7965,7 @@
-        "F\u00e4lle_Meldedatum": 160,
+        "F\u00e4lle_Meldedatum": 161,
@@ -8701,7 +8701,7 @@
-        "F\u00e4lle_Meldedatum": 258,
+        "F\u00e4lle_Meldedatum": 261, …
```
=> New data set: 2020-12-20T124103Z

latest-json
```diff -u pjson/2020-12-20T124103Z.json pjson/2020-12-21T111503Z.json```:
```
--- pjson/2020-12-20T124103Z.json	2020-12-20 12:41:03.205850851 +0000
+++ pjson/2020-12-21T111503Z.json	2020-12-21 11:15:03.749326356 +0000
@@ -8639,7 +8639,7 @@
"F\u00e4lle_Meldedatum": 275,
-        "SterbeF_Meldedatum": 0,
+        "SterbeF_Meldedatum": 1,
@@ -8701,7 +8701,7 @@
-        "F\u00e4lle_Meldedatum": 261,
+        "F\u00e4lle_Meldedatum": 266, …
```
=> New data set: 2020-12-21T111503Z

latest-json
```diff -u pjson/2020-12-21T111503Z.json pjson/2020-12-22T111703Z.json```:
```
--- pjson/2020-12-21T111503Z.json	2020-12-21 11:15:03.749326356 +0000
+++ pjson/2020-12-22T111703Z.json	2020-12-22 11:17:04.004702414 +0000
@@ -7677,7 +7677,7 @@
"Datum_neu": 1603584000000,
@@ -7709,7 +7709,7 @@
-        "F\u00e4lle_Meldedatum": 84,
+        "F\u00e4lle_Meldedatum": 86, …
```
=> New data set: 2020-12-22T111703Z

latest-json
```diff -u pjson/2020-12-23T111403Z.json pjson/2020-12-23T111904Z.json```:
```
--- pjson/2020-12-23T111403Z.json	2020-12-23 11:14:03.740060385 +0000
+++ pjson/2020-12-23T111904Z.json	2020-12-23 11:19:04.134283045 +0000
@@ -9564,7 +9564,7 @@
"Zuwachs_Genesung": 377,
"Inzidenz": 388.663385897482,
-        "Datum_neu": 1640217600000,
+        "Datum_neu": 1608681600000,
"F\u00e4lle_Meldedatum": 92,
"Zeitraum": "16.12.2020 - 22.12.2020",
```
If there are no anomalies, you are welcome to **merge** this symlink pointing to the new data set so that the new statistics will become publicly available on the [Grafana …
=> New data set: 2020-12-23T111904Z

latest-json
```diff -u pjson/2020-12-23T111904Z.json pjson/2020-12-24T112303Z.json```:
```
--- pjson/2020-12-23T111904Z.json	2020-12-23 11:19:04.134283045 +0000
+++ pjson/2020-12-24T112303Z.json	2020-12-24 11:23:04.100727122 +0000
@@ -8477,7 +8477,7 @@
-        "F\u00e4lle_Meldedatum": 109,
+        "F\u00e4lle_Meldedatum": 110,
@@ -9053,7 +9053,7 @@
-        "F\u00e4lle_Meldedatum": 367,
+        "F\u00e4lle_Meldedatum": 368, …
```
=> New data set: 2020-12-24T112303Z

latest-json
```diff -u pjson/2020-12-24T112303Z.json pjson/2020-12-25T110903Z.json```:
```
--- pjson/2020-12-24T112303Z.json	2020-12-24 11:23:04.100727122 +0000
+++ pjson/2020-12-25T110903Z.json	2020-12-25 11:09:04.111963408 +0000
@@ -8736,7 +8736,7 @@
"F\u00e4lle_Meldedatum": 230,
@@ -8928,7 +8928,7 @@
"F\u00e4lle_Meldedatum": 294,
-        "Hosp_Meldedatum": 27,
+        "Hosp_Meldedatum": 26, …
```
=> New data set: 2020-12-25T110903Z

latest-json
```diff -u pjson/2020-12-25T110903Z.json pjson/2020-12-26T111903Z.json```:
```
--- pjson/2020-12-25T110903Z.json	2020-12-25 11:09:04.111963408 +0000
+++ pjson/2020-12-26T111903Z.json	2020-12-26 11:19:03.980632387 +0000
@@ -9403,13 +9403,13 @@
"Zuwachs_Genesung": 159,
-        "Inzidenz": 384.7,
"F\u00e4lle_Meldedatum": 401,
-        "Inzidenz_RKI": 295.8,
"Krh_N_frei": null,
@@ -9533,10 +9533,10 @@ …
```
=> New data set: 2020-12-26T111903Z

latest-json
```diff -u pjson/2020-12-26T111903Z.json pjson/2020-12-27T114403Z.json```:
```
--- pjson/2020-12-26T111903Z.json	2020-12-26 11:19:03.980632387 +0000
+++ pjson/2020-12-27T114403Z.json	2020-12-27 11:44:03.600044545 +0000
@@ -9117,7 +9117,7 @@
"Datum_neu": 1607472000000,
-        "F\u00e4lle_Meldedatum": 395,
+        "F\u00e4lle_Meldedatum": 394,
"SterbeF_Meldedatum": 19,
@@ -9277,7 +9277,7 @@
-        "F\u00e4lle_Meldedatum": 416,
+        "F\u00e4lle_Meldedatum": 417,
"SterbeF_Meldedatum": 17, …
```
=> New data set: 2020-12-27T114403Z

latest-json
```diff -u pjson/2020-12-28T111503Z.json pjson/2020-12-28T112004Z.json```:
```
--- pjson/2020-12-28T111503Z.json	2020-12-28 11:15:03.857384225 +0000
+++ pjson/2020-12-28T112004Z.json	2020-12-28 11:20:04.383310935 +0000
@@ -9499,13 +9499,13 @@
"Zuwachs_Genesung": 358,
-        "Inzidenz": null,
+        "Inzidenz": 379.3,
"Datum_neu": 1608508800000,
"F\u00e4lle_Meldedatum": 401,
"SterbeF_Meldedatum": 14,
-        "Inzidenz_RKI": null,
+        "Inzidenz_RKI": 306.6,
"Krh_N_frei": null,
```
If there are no …
=> New data set: 2020-12-28T112004Z

latest-json
```diff -u pjson/2020-12-28T112004Z.json pjson/2020-12-29T111104Z.json```:
```
--- pjson/2020-12-28T112004Z.json	2020-12-28 11:20:04.383310935 +0000
+++ pjson/2020-12-29T111104Z.json	2020-12-29 11:11:04.294344303 +0000
@@ -4573,7 +4573,7 @@
"Datum_neu": 1595203200000,
-        "F\u00e4lle_Meldedatum": 0,
+        "F\u00e4lle_Meldedatum": 1,
@@ -5117,7 +5117,7 @@
"Datum_neu": 1596672000000,
+        "F\u00e4lle_Meldedatum": 1, …
```
=> New data set: 2020-12-29T111104Z

latest-json
```diff -u pjson/2020-12-29T111104Z.json pjson/2020-12-30T110603Z.json```:
```
--- pjson/2020-12-29T111104Z.json	2020-12-29 11:11:04.294344303 +0000
+++ pjson/2020-12-30T110603Z.json	2020-12-30 11:06:04.110592417 +0000
@@ -7613,7 +7613,7 @@
"Datum_neu": 1603411200000,
-        "F\u00e4lle_Meldedatum": 37,
+        "F\u00e4lle_Meldedatum": 38,
@@ -8669,7 +8669,7 @@
-        "F\u00e4lle_Meldedatum": 275,
+        "F\u00e4lle_Meldedatum": 274, …
```
=> New data set: 2020-12-30T110603Z

latest-json
```diff -u pjson/2020-12-30T110603Z.json pjson/2020-12-31T111504Z.json```:
```
--- pjson/2020-12-30T110603Z.json	2020-12-30 11:06:04.110592417 +0000
+++ pjson/2020-12-31T111504Z.json	2020-12-31 11:15:04.647713798 +0000
@@ -9533,7 +9533,7 @@
-        "F\u00e4lle_Meldedatum": 472,
+        "F\u00e4lle_Meldedatum": 471,
@@ -9563,13 +9563,13 @@
"Zuwachs_Genesung": 377,
-        "Inzidenz": 388.7,
- …
```
=> New data set: 2020-12-31T111504Z

latest-json
```diff -u pjson/2020-12-31T111504Z.json pjson/2021-01-01T110903Z.json```:
```
--- pjson/2020-12-31T111504Z.json	2020-12-31 11:15:04.647713798 +0000
+++ pjson/2021-01-01T110903Z.json	2021-01-01 11:09:03.890645192 +0000
@@ -7069,7 +7069,7 @@
-        "F\u00e4lle_Meldedatum": 39,
+        "F\u00e4lle_Meldedatum": 40,
@@ -8605,7 +8605,7 @@ …
```
=> New data set: 2021-01-01T110903Z

latest-json
```diff -u pjson/2021-01-01T110903Z.json pjson/2021-01-02T112004Z.json```:
```
--- pjson/2021-01-01T110903Z.json	2021-01-01 11:09:03.890645192 +0000
+++ pjson/2021-01-02T112004Z.json	2021-01-02 11:20:04.632931019 +0000
@@ -4605,7 +4605,7 @@
"Datum_neu": 1595289600000,
+        "F\u00e4lle_Meldedatum": 3,
@@ -7485,7 +7485,7 @@
-        "F\u00e4lle_Meldedatum": 43,
+        "F\u00e4lle_Meldedatum": 44, …
```
=> New data set: 2021-01-02T112004Z

latest-json
```diff -u pjson/2021-01-02T112004Z.json pjson/2021-01-03T111105Z.json```:
```
--- pjson/2021-01-02T112004Z.json	2021-01-02 11:20:04.632931019 +0000
+++ pjson/2021-01-03T111105Z.json	2021-01-03 11:11:05.137768445 +0000
@@ -4573,7 +4573,7 @@
"Datum_neu": 1595203200000,
-        "F\u00e4lle_Meldedatum": 1,
@@ -6269,7 +6269,7 @@
"Datum_neu": 1599782400000,
-        "F\u00e4lle_Meldedatum": 5, …
```
=> New data set: 2021-01-03T111105Z

latest-json
```diff -u pjson/2021-01-03T111105Z.json pjson/2021-01-04T110203Z.json```:
```
--- pjson/2021-01-03T111105Z.json	2021-01-03 11:11:05.137768445 +0000
+++ pjson/2021-01-04T110203Z.json	2021-01-04 11:02:03.211715965 +0000
@@ -7965,7 +7965,7 @@
-        "F\u00e4lle_Meldedatum": 163,
+        "F\u00e4lle_Meldedatum": 165,
@@ -8029,7 +8029,7 @@
"Datum_neu": 1604534400000,
-        "F\u00e4lle_Meldedatum": 134,
+        "F\u00e4lle_Meldedatum": 135, …
```
=> New data set: 2021-01-04T110203Z

latest-json
```diff -u pjson/2021-01-04T110203Z.json pjson/2021-01-05T111103Z.json```:
```
--- pjson/2021-01-04T110203Z.json	2021-01-04 11:02:03.211715965 +0000
+++ pjson/2021-01-05T111103Z.json	2021-01-05 11:11:03.831114774 +0000
@@ -7901,7 +7901,7 @@
-        "F\u00e4lle_Meldedatum": 37,
+        "F\u00e4lle_Meldedatum": 38,
@@ -8445,7 +8445,7 @@
"Datum_neu": 1605657600000,
-        "F\u00e4lle_Meldedatum": 104,
+        "F\u00e4lle_Meldedatum": 105, …
```
=> New data set: 2021-01-05T111103Z

latest-json
```diff -u pjson/2021-01-05T111103Z.json pjson/2021-01-06T112803Z.json```:
```
--- pjson/2021-01-05T111103Z.json	2021-01-05 11:11:03.831114774 +0000
+++ pjson/2021-01-06T112803Z.json	2021-01-06 11:28:03.394540921 +0000
@@ -8605,7 +8605,7 @@
-        "F\u00e4lle_Meldedatum": 196,
+        "F\u00e4lle_Meldedatum": 198,
@@ -8701,7 +8701,7 @@
-        "F\u00e4lle_Meldedatum": 277,
+        "F\u00e4lle_Meldedatum": 276, …
```
=> New data set: 2021-01-06T112803Z

latest-json
```diff -u pjson/2021-01-06T112803Z.json pjson/2021-01-07T110603Z.json```:
```
--- pjson/2021-01-06T112803Z.json	2021-01-06 11:28:03.394540921 +0000
+++ pjson/2021-01-07T110603Z.json	2021-01-07 11:06:03.952161952 +0000
@@ -8829,7 +8829,7 @@
-        "F\u00e4lle_Meldedatum": 209,
+        "F\u00e4lle_Meldedatum": 210,
"SterbeF_Meldedatum": 12,
@@ -8861,7 +8861,7 @@
-        "F\u00e4lle_Meldedatum": 322,
+        "F\u00e4lle_Meldedatum": 324, …
```
=> New data set: 2021-01-07T110603Z

latest-json
```diff -u pjson/2021-01-07T110603Z.json pjson/2021-01-08T110603Z.json```:
```
--- pjson/2021-01-07T110603Z.json	2021-01-07 11:06:03.952161952 +0000
+++ pjson/2021-01-08T110603Z.json	2021-01-08 11:06:03.921235979 +0000
@@ -8893,7 +8893,7 @@
-        "F\u00e4lle_Meldedatum": 289,
+        "F\u00e4lle_Meldedatum": 290,
"SterbeF_Meldedatum": 4,
@@ -8925,7 +8925,7 @@
-        "F\u00e4lle_Meldedatum": 295,
+        "F\u00e4lle_Meldedatum": 296, …
```
=> New data set: 2021-01-08T110603Z

latest-json
```diff -u pjson/2021-01-08T110603Z.json pjson/2021-01-08T111103Z.json```:
```
--- pjson/2021-01-08T110603Z.json	2021-01-08 11:06:03.921235979 +0000
+++ pjson/2021-01-08T111103Z.json	2021-01-08 11:11:03.788144866 +0000
@@ -9851,13 +9851,13 @@
"Zuwachs_Genesung": 418,
-        "Inzidenz": null,
+        "Inzidenz": 224,
"Datum_neu": 1609459200000,
"F\u00e4lle_Meldedatum": 45,
-        "Inzidenz_RKI": null,
+        "Inzidenz_RKI": 217.1,
"Krh_N_frei": null,
```
If there are no anomalies, …
=> New data set: 2021-01-08T111103Z

latest-json
```diff -u pjson/2021-01-08T111103Z.json pjson/2021-01-09T110604Z.json```:
```
--- pjson/2021-01-08T111103Z.json	2021-01-08 11:11:03.788144866 +0000
+++ pjson/2021-01-09T110604Z.json	2021-01-09 11:06:04.755750930 +0000
@@ -8832,7 +8832,7 @@
"F\u00e4lle_Meldedatum": 210,
"SterbeF_Meldedatum": 12,
-        "Hosp_Meldedatum": 23,
+        "Hosp_Meldedatum": 24,
@@ -8864,7 +8864,7 @@
"F\u00e4lle_Meldedatum": 324,
-        "Hosp_Meldedatum": 23,
+        "Hosp_Meldedatum": 25, …
```
=> New data set: 2021-01-09T110604Z

latest-json
```diff -u pjson/2021-01-09T110604Z.json pjson/2021-01-10T110103Z.json```:
```
--- pjson/2021-01-09T110604Z.json	2021-01-09 11:06:04.755750930 +0000
+++ pjson/2021-01-10T110103Z.json	2021-01-10 11:01:03.438647628 +0000
@@ -7901,7 +7901,7 @@
+        "F\u00e4lle_Meldedatum": 39,
@@ -7965,7 +7965,7 @@
-        "F\u00e4lle_Meldedatum": 165,
+        "F\u00e4lle_Meldedatum": 175, …
```
=> New data set: 2021-01-10T110103Z

latest-json
```diff -u pjson/2021-01-10T110103Z.json pjson/2021-01-11T110404Z.json```:
```
--- pjson/2021-01-10T110103Z.json	2021-01-10 11:01:03.438647628 +0000
+++ pjson/2021-01-11T110404Z.json	2021-01-11 11:04:04.322624439 +0000
@@ -6013,7 +6013,7 @@
"Datum_neu": 1599091200000,
@@ -6269,7 +6269,7 @@
"Datum_neu": 1599782400000,
-        "F\u00e4lle_Meldedatum": 6, …
```
=> New data set: 2021-01-11T110404Z

latest-json
```diff -u pjson/2021-01-11T110404Z.json pjson/2021-01-12T110403Z.json```:
```
--- pjson/2021-01-11T110404Z.json	2021-01-11 11:04:04.322624439 +0000
+++ pjson/2021-01-12T110403Z.json	2021-01-12 11:04:03.809668796 +0000
@@ -9183,7 +9183,7 @@
"Datum_neu": 1607644800000,
"F\u00e4lle_Meldedatum": 341,
-        "SterbeF_Meldedatum": 4,
+        "SterbeF_Meldedatum": 5,
@@ -9373,7 +9373,7 @@
"Datum_neu": 1608163200000,
-        "F\u00e4lle_Meldedatum": 514,
+        "F\u00e4lle_Meldedatum": 515,
"SterbeF_Meldedatum": 14, …
```
=> New data set: 2021-01-12T110403Z

latest-json
```diff -u pjson/2021-01-13T110703Z.json pjson/2021-01-14T112003Z.json```:
```
--- pjson/2021-01-13T110703Z.json	2021-01-13 11:07:03.866772437 +0000
+++ pjson/2021-01-14T112003Z.json	2021-01-14 11:20:03.626083763 +0000
@@ -8861,7 +8861,7 @@
-        "F\u00e4lle_Meldedatum": 324,
+        "F\u00e4lle_Meldedatum": 327,
@@ -8925,7 +8925,7 @@
-        "F\u00e4lle_Meldedatum": 296,
+        "F\u00e4lle_Meldedatum": 297, …
```
=> New data set: 2021-01-14T112003Z

latest-json
```diff -u pjson/2021-01-14T112003Z.json pjson/2021-01-15T113704Z.json```:
```
--- pjson/2021-01-14T112003Z.json	2021-01-14 11:20:03.626083763 +0000
+++ pjson/2021-01-15T113704Z.json	2021-01-15 11:37:04.252825610 +0000
@@ -8573,7 +8573,7 @@
"Datum_neu": 1606003200000,
-        "F\u00e4lle_Meldedatum": 31,
+        "F\u00e4lle_Meldedatum": 30,
@@ -8605,7 +8605,7 @@
+        "F\u00e4lle_Meldedatum": 199, …
```
=> New data set: 2021-01-15T113704Z

latest-json
```diff -u pjson/2021-01-15T113704Z.json pjson/2021-01-16T111703Z.json```:
```
--- pjson/2021-01-15T113704Z.json	2021-01-15 11:37:04.252825610 +0000
+++ pjson/2021-01-16T111703Z.json	2021-01-16 11:17:03.329974301 +0000
@@ -8285,7 +8285,7 @@
-        "F\u00e4lle_Meldedatum": 199,
+        "F\u00e4lle_Meldedatum": 200,
@@ -8317,7 +8317,7 @@
"Datum_neu": 1605312000000,
-        "F\u00e4lle_Meldedatum": 83,
+        "F\u00e4lle_Meldedatum": 84, …
```
=> New data set: 2021-01-16T111703Z

latest-json
```diff -u pjson/2021-01-16T111703Z.json pjson/2021-01-17T111404Z.json```:
```
--- pjson/2021-01-16T111703Z.json	2021-01-16 11:17:03.329974301 +0000
+++ pjson/2021-01-17T111404Z.json	2021-01-17 11:14:04.185332947 +0000
@@ -9504,7 +9504,7 @@
"F\u00e4lle_Meldedatum": 444,
"SterbeF_Meldedatum": 16,
-        "Hosp_Meldedatum": 27,
+        "Hosp_Meldedatum": 28,
@@ -9568,7 +9568,7 @@
"F\u00e4lle_Meldedatum": 436,
"SterbeF_Meldedatum": 21,
-        "Hosp_Meldedatum": 27,
+        "Hosp_Meldedatum": 28, …
```
=> New data set: 2021-01-17T111404Z

latest-json
```diff -u pjson/2021-01-17T111404Z.json pjson/2021-01-18T114303Z.json```:
```
--- pjson/2021-01-17T111404Z.json	2021-01-17 11:14:04.185332947 +0000
+++ pjson/2021-01-18T114303Z.json	2021-01-18 11:43:03.966292812 +0000
@@ -767,7 +767,7 @@
"Datum_neu": 1584921600000,
"F\u00e4lle_Meldedatum": 17,
-        "SterbeF_Meldedatum": 1,
+        "SterbeF_Meldedatum": 0,
@@ -799,7 +799,7 @@
"Datum_neu": 1585008000000,
"F\u00e4lle_Meldedatum": 41,
-        "SterbeF_Meldedatum": 1,
+        "SterbeF_Meldedatum": 2, …
```
=> New data set: 2021-01-18T114303Z

latest-json
```diff -u pjson/2021-01-18T114303Z.json pjson/2021-01-19T110803Z.json```:
```
--- pjson/2021-01-18T114303Z.json	2021-01-18 11:43:03.966292812 +0000
+++ pjson/2021-01-19T110803Z.json	2021-01-19 11:08:03.249131292 +0000
@@ -8960,7 +8960,7 @@
"F\u00e4lle_Meldedatum": 212,
"SterbeF_Meldedatum": 14,
-        "Hosp_Meldedatum": 29,
+        "Hosp_Meldedatum": 28,
@@ -9152,7 +9152,7 @@
"F\u00e4lle_Meldedatum": 461,
"SterbeF_Meldedatum": 12,
+        "Hosp_Meldedatum": 31, …
```
=> New data set: 2021-01-19T110803Z

latest-json
```diff -u pjson/2021-01-19T125903Z.json pjson/2021-01-20T112402Z.json```:
```
--- pjson/2021-01-19T125903Z.json	2021-01-19 12:59:03.956055076 +0000
+++ pjson/2021-01-20T112402Z.json	2021-01-20 11:24:03.193557592 +0000
@@ -9415,7 +9415,7 @@
-        "F\u00e4lle_Meldedatum": 327,
+        "F\u00e4lle_Meldedatum": 328,
@@ -9449,7 +9449,7 @@
-        "F\u00e4lle_Meldedatum": 290,
+        "F\u00e4lle_Meldedatum": 291,
"SterbeF_Meldedatum": 6, …
```
=> New data set: 2021-01-20T112402Z

latest-json
```diff -u pjson/2021-01-21T065103Z.json pjson/2021-01-21T111303Z.json```:
```
--- pjson/2021-01-21T065103Z.json	2021-01-21 06:51:03.247668093 +0000
+++ pjson/2021-01-21T111303Z.json	2021-01-21 11:13:03.462552211 +0000
@@ -7137,7 +7137,7 @@
"Datum_neu": 1603411200000,
-        "F\u00e4lle_Meldedatum": 39,
@@ -7257,7 +7257,7 @@
-        "F\u00e4lle_Meldedatum": 102,
+        "F\u00e4lle_Meldedatum": 103, …
```
=> New data set: 2021-01-21T111303Z

latest-json
```diff -u pjson/2021-01-21T111303Z.json pjson/2021-01-22T112603Z.json```:
```
--- pjson/2021-01-21T111303Z.json	2021-01-21 11:13:03.462552211 +0000
+++ pjson/2021-01-22T112603Z.json	2021-01-22 11:26:03.895549904 +0000
@@ -359,7 +359,7 @@
"Datum_neu": 1583884800000,
+        "Hosp_Meldedatum": 0,
@@ -479,7 +479,7 @@
"Datum_neu": 1584230400000,
+        "Hosp_Meldedatum": 0, …
```
=> New data set: 2021-01-22T112603Z

latest-json
```diff -u pjson/2021-01-22T112603Z.json pjson/2021-01-23T110203Z.json```:
```
--- pjson/2021-01-22T112603Z.json	2021-01-22 11:26:03.895549904 +0000
+++ pjson/2021-01-23T110203Z.json	2021-01-23 11:02:03.478022677 +0000
@@ -4347,7 +4347,7 @@
"Datum_neu": 1595376000000,
-        "F\u00e4lle_Meldedatum": 0,
+        "F\u00e4lle_Meldedatum": 1,
@@ -8217,7 +8217,7 @@
"Datum_neu": 1606521600000,
+        "F\u00e4lle_Meldedatum": 141, …
```
=> New data set: 2021-01-23T110203Z

latest-json
```diff -u pjson/2021-01-23T110203Z.json pjson/2021-01-24T110403Z.json```:
```
--- pjson/2021-01-23T110203Z.json	2021-01-23 11:02:03.478022677 +0000
+++ pjson/2021-01-24T110403Z.json	2021-01-24 11:04:03.991647870 +0000
@@ -9029,7 +9029,7 @@
"Datum_neu": 1608854400000,
"F\u00e4lle_Meldedatum": 41,
@@ -9089,7 +9089,7 @@
"Datum_neu": 1609027200000,
"F\u00e4lle_Meldedatum": 110,
+        "Hosp_Meldedatum": 6, …
```
=> New data set: 2021-01-24T110403Z

latest-json
```diff -u pjson/2021-01-24T110403Z.json pjson/2021-01-25T111903Z.json```:
```
--- pjson/2021-01-24T110403Z.json	2021-01-24 11:04:03.991647870 +0000
+++ pjson/2021-01-25T111903Z.json	2021-01-25 11:19:03.476008297 +0000
@@ -8729,7 +8729,7 @@
"Datum_neu": 1607990400000,
"F\u00e4lle_Meldedatum": 418,
-        "Hosp_Meldedatum": 36,
+        "Hosp_Meldedatum": 39,
@@ -8759,7 +8759,7 @@
"F\u00e4lle_Meldedatum": 353,
+        "Hosp_Meldedatum": 37, …
```
=> New data set: 2021-01-25T111903Z

latest-json
```diff -u pjson/2021-01-25T111903Z.json pjson/2021-01-26T110903Z.json```:
```
--- pjson/2021-01-25T111903Z.json	2021-01-25 11:19:03.476008297 +0000
+++ pjson/2021-01-26T110903Z.json	2021-01-26 11:09:04.108720121 +0000
@@ -6807,7 +6807,7 @@
"Datum_neu": 1602460800000,
-        "F\u00e4lle_Meldedatum": 18,
+        "F\u00e4lle_Meldedatum": 17,
@@ -7767,7 +7767,7 @@
-        "F\u00e4lle_Meldedatum": 201,
+        "F\u00e4lle_Meldedatum": 202, …
```
=> New data set: 2021-01-26T110903Z

latest-json
```diff -u pjson/2021-01-26T110903Z.json pjson/2021-01-27T111904Z.json```:
```
--- pjson/2021-01-26T110903Z.json	2021-01-26 11:09:04.108720121 +0000
+++ pjson/2021-01-27T111904Z.json	2021-01-27 11:19:04.747917173 +0000
@@ -4169,7 +4169,7 @@
"Datum_neu": 1594857600000,
"F\u00e4lle_Meldedatum": 1,
@@ -6177,7 +6177,7 @@
"Datum_neu": 1600646400000,
+        "F\u00e4lle_Meldedatum": 16, …
```
=> New data set: 2021-01-27T111904Z

latest-json
```diff -u pjson/2021-01-27T111904Z.json pjson/2021-01-28T112603Z.json```:
```
--- pjson/2021-01-27T111904Z.json	2021-01-27 11:19:04.747917173 +0000
+++ pjson/2021-01-28T112603Z.json	2021-01-28 11:26:03.517776152 +0000
@@ -7017,7 +7017,7 @@
-        "F\u00e4lle_Meldedatum": 44,
@@ -7947,7 +7947,7 @@
-        "F\u00e4lle_Meldedatum": 112,
+        "F\u00e4lle_Meldedatum": 113, …
```
=> New data set: 2021-01-28T112603Z

latest-json
```diff -u pjson/2021-01-28T112603Z.json pjson/2021-01-29T110803Z.json```:
```
--- pjson/2021-01-28T112603Z.json	2021-01-28 11:26:03.517776152 +0000
+++ pjson/2021-01-29T110803Z.json	2021-01-29 11:08:04.021113275 +0000
@@ -7197,7 +7197,7 @@
"Datum_neu": 1603584000000,
+        "F\u00e4lle_Meldedatum": 43,
@@ -8367,7 +8367,7 @@
-        "F\u00e4lle_Meldedatum": 298,
+        "F\u00e4lle_Meldedatum": 299, …
```
=> New data set: 2021-01-29T110803Z

latest-json
```diff -u pjson/2021-01-29T110803Z.json pjson/2021-01-30T110404Z.json```:
```
--- pjson/2021-01-29T110803Z.json	2021-01-29 11:08:04.021113275 +0000
+++ pjson/2021-01-30T110404Z.json	2021-01-30 11:04:04.823321069 +0000
@@ -7947,7 +7947,7 @@
-        "F\u00e4lle_Meldedatum": 113,
+        "F\u00e4lle_Meldedatum": 114,
@@ -8817,7 +8817,7 @@
-        "F\u00e4lle_Meldedatum": 457,
+        "F\u00e4lle_Meldedatum": 458, …
```
=> New data set: 2021-01-30T110404Z

latest-json
```diff -u pjson/2021-01-30T110404Z.json pjson/2021-01-31T110303Z.json```:
```
--- pjson/2021-01-30T110404Z.json	2021-01-30 11:04:04.823321069 +0000
+++ pjson/2021-01-31T110303Z.json	2021-01-31 11:03:03.630863257 +0000
@@ -8307,7 +8307,7 @@
-        "F\u00e4lle_Meldedatum": 329,
+        "F\u00e4lle_Meldedatum": 330,
@@ -8937,7 +8937,7 @@
-        "F\u00e4lle_Meldedatum": 482,
+        "F\u00e4lle_Meldedatum": 483, …
```
=> New data set: 2021-01-31T110303Z

latest-json
```diff -u pjson/2021-01-31T110303Z.json pjson/2021-02-01T110104Z.json```:
```
--- pjson/2021-01-31T110303Z.json	2021-01-31 11:03:03.630863257 +0000
+++ pjson/2021-02-01T110104Z.json	2021-02-01 11:01:04.411204247 +0000
@@ -7107,7 +7107,7 @@
"Datum_neu": 1603324800000,
-        "F\u00e4lle_Meldedatum": 88,
@@ -7977,7 +7977,7 @@
"Datum_neu": 1605830400000,
-        "F\u00e4lle_Meldedatum": 195,
+        "F\u00e4lle_Meldedatum": 197, …
```
=> New data set: 2021-02-01T110104Z

latest-json
```diff -u pjson/2021-02-01T110104Z.json pjson/2021-02-02T110104Z.json```:
```
--- pjson/2021-02-01T110104Z.json	2021-02-01 11:01:04.411204247 +0000
+++ pjson/2021-02-02T110104Z.json	2021-02-02 11:01:04.295677583 +0000
@@ -6627,7 +6627,7 @@
-        "F\u00e4lle_Meldedatum": 40,
@@ -7047,7 +7047,7 @@
"Datum_neu": 1603152000000,
-        "F\u00e4lle_Meldedatum": 88, …
```
=> New data set: 2021-02-02T110104Z

latest-json
```diff -u pjson/2021-02-02T110104Z.json pjson/2021-02-03T110104Z.json```:
```
--- pjson/2021-02-02T110104Z.json	2021-02-02 11:01:04.295677583 +0000
+++ pjson/2021-02-03T110104Z.json	2021-02-03 11:01:04.244076000 +0000
@@ -5967,7 +5967,7 @@
+        "F\u00e4lle_Meldedatum": 9,
@@ -7707,7 +7707,7 @@
"Datum_neu": 1605052800000,
-        "F\u00e4lle_Meldedatum": 57,
+        "F\u00e4lle_Meldedatum": 58, …
```
=> New data set: 2021-02-03T110104Z

latest-json
```diff -u pjson/2021-02-03T110104Z.json pjson/2021-02-04T114404Z.json```:
```
--- pjson/2021-02-03T110104Z.json	2021-02-03 11:01:04.244076000 +0000
+++ pjson/2021-02-04T114404Z.json	2021-02-04 11:44:04.443331266 +0000
@@ -9509,7 +9509,7 @@
"Datum_neu": 1610236800000,
"F\u00e4lle_Meldedatum": 11,
@@ -9668,7 +9668,7 @@
"Krh_I": null,
-        "SterbeF_Sterbedatum": 14
+        "SterbeF_Sterbedatum": 15
}
},
{
@@ -9848,7 +9848,7 @@
"Krh_I": null, …
```
=> New data set: 2021-02-04T114404Z

latest-json
```diff -u pjson/2021-02-04T114404Z.json pjson/2021-02-05T111004Z.json```:
```
--- pjson/2021-02-04T114404Z.json	2021-02-04 11:44:04.443331266 +0000
+++ pjson/2021-02-05T111004Z.json	2021-02-05 11:10:04.213985516 +0000
@@ -7767,7 +7767,7 @@
-        "F\u00e4lle_Meldedatum": 204,
+        "F\u00e4lle_Meldedatum": 207,
@@ -7797,7 +7797,7 @@
"Datum_neu": 1605312000000,
-        "F\u00e4lle_Meldedatum": 84,
+        "F\u00e4lle_Meldedatum": 85, …
```
=> New data set: 2021-02-05T111004Z

latest-json
```diff -u pjson/2021-02-05T111004Z.json pjson/2021-02-06T110304Z.json```:
```
--- pjson/2021-02-05T111004Z.json	2021-02-05 11:10:04.213985516 +0000
+++ pjson/2021-02-06T110304Z.json	2021-02-06 11:03:04.501561249 +0000
@@ -5577,7 +5577,7 @@
"Datum_neu": 1598918400000,
+        "F\u00e4lle_Meldedatum": 4,
@@ -7317,7 +7317,7 @@
"Datum_neu": 1603929600000,
+        "F\u00e4lle_Meldedatum": 147, …
```
=> New data set: 2021-02-06T110304Z

latest-json
```diff -u pjson/2021-02-06T110304Z.json pjson/2021-02-07T110403Z.json```:
```
--- pjson/2021-02-06T110304Z.json	2021-02-06 11:03:04.501561249 +0000
+++ pjson/2021-02-07T110403Z.json	2021-02-07 11:04:04.087126108 +0000
@@ -359,7 +359,7 @@
"Datum_neu": 1583884800000,
+        "Hosp_Meldedatum": null,
@@ -389,7 +389,7 @@
"Datum_neu": 1583971200000,
"F\u00e4lle_Meldedatum": 6,
+        "Hosp_Meldedatum": null,
"Krh_I_belegt": …
```
=> New data set: 2021-02-07T110403Z

latest-json
```diff -u pjson/2021-02-07T110403Z.json pjson/2021-02-08T111604Z.json```:
```
--- pjson/2021-02-07T110403Z.json	2021-02-07 11:04:04.087126108 +0000
+++ pjson/2021-02-08T111604Z.json	2021-02-08 11:16:04.879375009 +0000
@@ -6627,7 +6627,7 @@
+        "F\u00e4lle_Meldedatum": 40,
@@ -7047,7 +7047,7 @@
"Datum_neu": 1603152000000,
-        "F\u00e4lle_Meldedatum": 90, …
```
=> New data set: 2021-02-08T111604Z

latest-json
```diff -u pjson/2021-02-08T111604Z.json pjson/2021-02-09T111503Z.json```:
```
--- pjson/2021-02-08T111604Z.json	2021-02-08 11:16:04.879375009 +0000
+++ pjson/2021-02-09T111503Z.json	2021-02-09 11:15:03.737627552 +0000
@@ -5577,7 +5577,7 @@
"Datum_neu": 1598918400000,
+        "F\u00e4lle_Meldedatum": 3,
@@ -7467,7 +7467,7 @@
-        "F\u00e4lle_Meldedatum": 177,
+        "F\u00e4lle_Meldedatum": 176, …
```
=> New data set: 2021-02-09T111503Z

latest-json
```diff -u pjson/2021-02-09T111503Z.json pjson/2021-02-10T111504Z.json```:
```
--- pjson/2021-02-09T111503Z.json	2021-02-09 11:15:03.737627552 +0000
+++ pjson/2021-02-10T111504Z.json	2021-02-10 11:15:05.069986181 +0000
@@ -7437,7 +7437,7 @@
"Datum_neu": 1604275200000,
-        "F\u00e4lle_Meldedatum": 187,
+        "F\u00e4lle_Meldedatum": 185,
@@ -7467,7 +7467,7 @@
-        "F\u00e4lle_Meldedatum": 176,
+        "F\u00e4lle_Meldedatum": 175, …
```
=> New data set: 2021-02-10T111504Z

latest-json
```diff -u pjson/2021-02-10T111504Z.json pjson/2021-02-11T110903Z.json```:
```
--- pjson/2021-02-10T111504Z.json	2021-02-10 11:15:05.069986181 +0000
+++ pjson/2021-02-11T110903Z.json	2021-02-11 11:09:03.727600395 +0000
@@ -6867,7 +6867,7 @@
"Datum_neu": 1602633600000,
-        "F\u00e4lle_Meldedatum": 30,
+        "F\u00e4lle_Meldedatum": 31,
@@ -7227,7 +7227,7 @@
-        "F\u00e4lle_Meldedatum": 85,
+        "F\u00e4lle_Meldedatum": 84, …
```
=> New data set: 2021-02-11T110903Z

latest-json
```diff -u pjson/2021-02-12T070503Z.json pjson/2021-02-12T110404Z.json```:
```
--- pjson/2021-02-12T070503Z.json	2021-02-12 07:05:03.710239853 +0000
+++ pjson/2021-02-12T110404Z.json	2021-02-12 11:04:04.283370031 +0000
@@ -7158,7 +7158,7 @@
"Datum_neu": 1602806400000,
-        "F\u00e4lle_Meldedatum": 45,
+        "F\u00e4lle_Meldedatum": 46,
@@ -7747,7 +7747,7 @@
-        "F\u00e4lle_Meldedatum": 205,
+        "F\u00e4lle_Meldedatum": 204, …
```
=> New data set: 2021-02-12T110404Z

latest-json
```diff -u pjson/2021-02-12T110404Z.json pjson/2021-02-13T112103Z.json```:
```
--- pjson/2021-02-12T110404Z.json	2021-02-12 11:04:04.283370031 +0000
+++ pjson/2021-02-13T112103Z.json	2021-02-13 11:21:03.592535129 +0000
@@ -7747,7 +7747,7 @@
-        "F\u00e4lle_Meldedatum": 204,
+        "F\u00e4lle_Meldedatum": 203,
@@ -8150,7 +8150,7 @@
-        "F\u00e4lle_Meldedatum": 237,
+        "F\u00e4lle_Meldedatum": 236, …
```
=> New data set: 2021-02-13T112103Z

latest-json
```diff -u pjson/2021-02-13T112103Z.json pjson/2021-02-14T105504Z.json```:
```
--- pjson/2021-02-13T112103Z.json	2021-02-13 11:21:03.592535129 +0000
+++ pjson/2021-02-14T105504Z.json	2021-02-14 10:55:04.606797228 +0000
@@ -9731,7 +9731,7 @@
-        "F\u00e4lle_Meldedatum": 281,
+        "F\u00e4lle_Meldedatum": 285,
@@ -9804,7 +9804,7 @@
"Krh_I": null,
-        "SterbeF_Sterbedatum": 6,
+        "SterbeF_Sterbedatum": 7,
"Inzi_SN_RKI": 339.123240317772
}
},
@@ -9979,7 +9979,7 @@ …
```
=> New data set: 2021-02-14T105504Z

latest-json
```diff -u pjson/2021-02-14T105504Z.json pjson/2021-02-15T110504Z.json```:
```
--- pjson/2021-02-14T105504Z.json	2021-02-14 10:55:04.606797228 +0000
+++ pjson/2021-02-15T110504Z.json	2021-02-15 11:05:04.312967050 +0000
@@ -7437,7 +7437,7 @@
"Datum_neu": 1603584000000,
-        "F\u00e4lle_Meldedatum": 43,
@@ -7499,7 +7499,7 @@
-        "F\u00e4lle_Meldedatum": 103,
+        "F\u00e4lle_Meldedatum": 102, …
```
=> New data set: 2021-02-15T110504Z

latest-json
```diff -u pjson/2021-02-15T145804Z.json pjson/2021-02-15T164104Z.json```:
```
--- pjson/2021-02-15T145804Z.json	2021-02-15 14:58:04.805614211 +0000
+++ pjson/2021-02-15T164104Z.json	2021-02-15 16:41:04.673723237 +0000
@@ -10952,7 +10952,7 @@
"Krh_I_covid": 35,
-        "Inzi_SN_RKI": null
+        "Inzi_SN_RKI": 68.1488154016814
}
}
]
```
If there are no anomalies, you are welcome to **merge** this symlink pointing to the new data set so that the new statistics will become publicly available on the [Grafana Dashboard](https://coronavirus-dresden.de/) within 5 minutes.
Thanks!
=> New data set: 2021-02-15T164104Z

latest-json
```diff -u pjson/2021-02-15T164104Z.json pjson/2021-02-16T112304Z.json```:
```
--- pjson/2021-02-15T164104Z.json	2021-02-15 16:41:04.673723237 +0000
+++ pjson/2021-02-16T112304Z.json	2021-02-16 11:23:04.450503524 +0000
@@ -8243,7 +8243,7 @@
"Datum_neu": 1605830400000,
-        "F\u00e4lle_Meldedatum": 197,
@@ -8553,7 +8553,7 @@
+        "F\u00e4lle_Meldedatum": 212, …
```
=> New data set: 2021-02-16T112304Z

latest-json
```diff -u pjson/2021-02-16T112304Z.json pjson/2021-02-17T110103Z.json```:
```
--- pjson/2021-02-16T112304Z.json	2021-02-16 11:23:04.450503524 +0000
+++ pjson/2021-02-17T110103Z.json	2021-02-17 11:01:03.759757500 +0000
@@ -8026,7 +8026,7 @@
-        "F\u00e4lle_Meldedatum": 205,
+        "F\u00e4lle_Meldedatum": 206,
@@ -8429,7 +8429,7 @@
-        "F\u00e4lle_Meldedatum": 276,
+        "F\u00e4lle_Meldedatum": 277, …
```
=> New data set: 2021-02-17T110103Z

latest-json
```diff -u pjson/2021-02-17T110103Z.json pjson/2021-02-18T112203Z.json```:
```
--- pjson/2021-02-17T110103Z.json	2021-02-17 11:01:03.759757500 +0000
+++ pjson/2021-02-18T112203Z.json	2021-02-18 11:22:03.972488719 +0000
@@ -8212,7 +8212,7 @@
-        "F\u00e4lle_Meldedatum": 115,
+        "F\u00e4lle_Meldedatum": 116,
@@ -8336,7 +8336,7 @@
-        "F\u00e4lle_Meldedatum": 199,
+        "F\u00e4lle_Meldedatum": 198, …
```
=> New data set: 2021-02-18T112203Z

latest-json
```diff -u pjson/2021-02-18T112203Z.json pjson/2021-02-19T111403Z.json```:
```
--- pjson/2021-02-18T112203Z.json	2021-02-18 11:22:03.972488719 +0000
+++ pjson/2021-02-19T111403Z.json	2021-02-19 11:14:03.838305904 +0000
@@ -7716,7 +7716,7 @@
-        "F\u00e4lle_Meldedatum": 175,
+        "F\u00e4lle_Meldedatum": 176,
@@ -8150,7 +8150,7 @@
-        "F\u00e4lle_Meldedatum": 236,
+        "F\u00e4lle_Meldedatum": 237, …
```
=> New data set: 2021-02-19T111403Z

latest-json
```diff -u pjson/2021-02-20T112403Z.json pjson/2021-02-20T113004Z.json```:
```
--- pjson/2021-02-20T112403Z.json	2021-02-20 11:24:03.601875488 +0000
+++ pjson/2021-02-20T113004Z.json	2021-02-20 11:30:04.848495501 +0000
@@ -11107,7 +11107,7 @@
"Krh_I_covid": 36,
-        "Inzi_SN_RKI": null
+        "Inzi_SN_RKI": 64.8
}
}
]
```
If there are no anomalies, you are welcome to **merge** this symlink pointing to the new data set so that the new statistics will become publicly available on the [Grafana Dashboard](https://coronavirus-dresden.de/) within 5 minutes.
Thanks!
=> New data set: 2021-02-20T113004Z

latest-json
```diff -u pjson/2021-02-20T113004Z.json pjson/2021-02-21T105603Z.json```:
```
--- pjson/2021-02-20T113004Z.json	2021-02-20 11:30:04.848495501 +0000
+++ pjson/2021-02-21T105603Z.json	2021-02-21 10:56:03.501358591 +0000
@@ -9049,7 +9049,7 @@
-        "F\u00e4lle_Meldedatum": 357,
+        "F\u00e4lle_Meldedatum": 358,
@@ -9235,7 +9235,7 @@
-        "F\u00e4lle_Meldedatum": 483,
+        "F\u00e4lle_Meldedatum": 484, …
```
=> New data set: 2021-02-21T105603Z

latest-json
```diff -u pjson/2021-02-21T142004Z.json pjson/2021-02-21T142104Z.json```:
```
--- pjson/2021-02-21T142004Z.json	2021-02-21 14:20:04.293085822 +0000
+++ pjson/2021-02-21T142104Z.json	2021-02-21 14:21:04.225517480 +0000
@@ -11138,7 +11138,7 @@
"Krh_I_covid": 37,
-        "Inzi_SN_RKI": null
+        "Inzi_SN_RKI": 69.9
}
}
]
```
If there are no anomalies, you are welcome to **merge** this symlink pointing to the new data set so that the new statistics will become publicly available on the [Grafana Dashboard](https://coronavirus-dresden.de/) within 5 minutes.
Thanks!
=> New data set: 2021-02-21T142104Z

latest-json
```diff -u pjson/2021-02-21T142104Z.json pjson/2021-02-22T111707Z.json```:
```
--- pjson/2021-02-21T142104Z.json	2021-02-21 14:21:04.225517480 +0000
+++ pjson/2021-02-22T111707Z.json	2021-02-22 11:17:07.208058570 +0000
@@ -7997,7 +7997,7 @@
"Datum_neu": 1605139200000,
"F\u00e4lle_Meldedatum": 197,
+        "Hosp_Meldedatum": 13,
@@ -10610,7 +10610,7 @@
"Krh_I": null,
-        "SterbeF_Sterbedatum": 4,
+        "SterbeF_Sterbedatum": 5,
"Inzi_SN_RKI": 100.1235028442
}
},
@@ -10734,7 +10734,7 @@ …
```
=> New data set: 2021-02-22T111707Z

latest-json
```diff -u pjson/2021-02-23T062704Z.json pjson/2021-02-23T112603Z.json```:
```
--- pjson/2021-02-23T062704Z.json	2021-02-23 06:27:04.376326358 +0000
+++ pjson/2021-02-23T112603Z.json	2021-02-23 11:26:04.051929872 +0000
@@ -6972,7 +6972,7 @@
@@ -8026,7 +8026,7 @@
-        "F\u00e4lle_Meldedatum": 207,
+        "F\u00e4lle_Meldedatum": 206, …
```
=> New data set: 2021-02-23T112603Z

latest-json
```diff -u pjson/2021-02-23T112603Z.json pjson/2021-02-24T111703Z.json```:
```
--- pjson/2021-02-23T112603Z.json	2021-02-23 11:26:04.051929872 +0000
+++ pjson/2021-02-24T111703Z.json	2021-02-24 11:17:03.694700278 +0000
@@ -1558,7 +1558,7 @@
"Krh_I": null,
"Inzi_SN_RKI": null
}
},
@@ -1837,7 +1837,7 @@
"Krh_I": null,
"Inzi_SN_RKI": null
}
},
@@ -1930,7 +1930,7 @@
"Krh_I": null,
- …
```
=> New data set: 2021-02-24T111703Z

latest-json
```diff -u pjson/2021-02-24T111703Z.json pjson/2021-02-25T111403Z.json```:
```
--- pjson/2021-02-24T111703Z.json	2021-02-24 11:17:03.694700278 +0000
+++ pjson/2021-02-25T111403Z.json	2021-02-25 11:14:04.147504816 +0000
@@ -8615,7 +8615,7 @@
-        "F\u00e4lle_Meldedatum": 292,
+        "F\u00e4lle_Meldedatum": 291,
@@ -9215,7 +9215,7 @@
"Krh_I": null,
-        "SterbeF_Sterbedatum": 14,
+        "SterbeF_Sterbedatum": 15,
"Inzi_SN_RKI": null
}
},
@@ -9246,7 +9246,7 @@
"Krh_I": null, …
```
=> New data set: 2021-02-25T111403Z

latest-json
```diff -u pjson/2021-02-25T111403Z.json pjson/2021-02-26T110303Z.json```:
```
--- pjson/2021-02-25T111403Z.json	2021-02-25 11:14:04.147504816 +0000
+++ pjson/2021-02-26T110303Z.json	2021-02-26 11:03:03.628622781 +0000
@@ -7747,7 +7747,7 @@
-        "F\u00e4lle_Meldedatum": 203,
+        "F\u00e4lle_Meldedatum": 205,
@@ -8863,7 +8863,7 @@
-        "F\u00e4lle_Meldedatum": 468,
+        "F\u00e4lle_Meldedatum": 467, …
```
=> New data set: 2021-02-26T110303Z

latest-json
```diff -u pjson/2021-02-26T110303Z.json pjson/2021-02-27T110204Z.json```:
```
--- pjson/2021-02-26T110303Z.json	2021-02-26 11:03:03.628622781 +0000
+++ pjson/2021-02-27T110204Z.json	2021-02-27 11:02:04.730230102 +0000
@@ -8708,7 +8708,7 @@
"Datum_neu": 1607126400000,
-        "F\u00e4lle_Meldedatum": 108,
+        "F\u00e4lle_Meldedatum": 109,
@@ -8770,7 +8770,7 @@
-        "F\u00e4lle_Meldedatum": 377,
+        "F\u00e4lle_Meldedatum": 378, …
```
=> New data set: 2021-02-27T110204Z

latest-json
```diff -u pjson/2021-02-27T110204Z.json pjson/2021-02-28T110203Z.json```:
```
--- pjson/2021-02-27T110204Z.json	2021-02-27 11:02:04.730230102 +0000
+++ pjson/2021-02-28T110203Z.json	2021-02-28 11:02:03.626767682 +0000
@@ -8832,7 +8832,7 @@
"Datum_neu": 1607472000000,
-        "F\u00e4lle_Meldedatum": 394,
+        "F\u00e4lle_Meldedatum": 395,
@@ -10940,7 +10940,7 @@
"Datum_neu": 1613347200000,
-        "F\u00e4lle_Meldedatum": 71,
+        "F\u00e4lle_Meldedatum": 72, …
```
=> New data set: 2021-02-28T110203Z

latest-json
```diff -u pjson/2021-03-01T082704Z.json pjson/2021-03-01T110503Z.json```:
```
--- pjson/2021-03-01T082704Z.json	2021-03-01 08:27:04.373572520 +0000
+++ pjson/2021-03-01T110503Z.json	2021-03-01 11:05:03.751711029 +0000
@@ -11624,7 +11624,7 @@
"Krh_I": null,
-        "SterbeF_Sterbedatum": 5,
+        "SterbeF_Sterbedatum": 6,
@@ -11657,7 +11657,7 @@
"Krh_I": null,
@@ -11745,7 …
```
=> New data set: 2021-03-01T110503Z

latest-json
```diff -u pjson/2021-03-02T090404Z.json pjson/2021-03-02T111304Z.json```:
```
--- pjson/2021-03-02T090404Z.json	2021-03-02 09:04:04.534814693 +0000
+++ pjson/2021-03-02T111304Z.json	2021-03-02 11:13:04.424460415 +0000
@@ -9809,7 +9809,7 @@
"Krh_I": null,
-        "SterbeF_Sterbedatum": 15,
+        "SterbeF_Sterbedatum": 16,
@@ -9833,7 +9833,7 @@
"F\u00e4lle_Meldedatum": 486,
-        "Hosp_Meldedatum": 31,
+        "Hosp_Meldedatum": 32, …
```
=> New data set: 2021-03-02T111304Z

latest-json
```diff -u pjson/2021-03-02T111603Z.json pjson/2021-03-03T111404Z.json```:
```
--- pjson/2021-03-02T111603Z.json	2021-03-02 11:16:03.985307353 +0000
+++ pjson/2021-03-03T111404Z.json	2021-03-03 11:14:04.339092793 +0000
@@ -7719,7 +7719,7 @@
-        "F\u00e4lle_Meldedatum": 45,
+        "F\u00e4lle_Meldedatum": 44,
@@ -7983,7 +7983,7 @@
-        "F\u00e4lle_Meldedatum": 101,
+        "F\u00e4lle_Meldedatum": 100, …
```
=> New data set: 2021-03-03T111404Z

latest-json
```diff -u pjson/2021-03-05T111303Z.json pjson/2021-03-06T110903Z.json```:
```
--- pjson/2021-03-05T111303Z.json	2021-03-05 11:13:03.717603518 +0000
+++ pjson/2021-03-06T110903Z.json	2021-03-06 11:09:03.189554016 +0000
@@ -8313,7 +8313,7 @@
"Datum_neu": 1604620800000, …
```
=> New data set: 2021-03-06T110903Z

latest-json
```diff -u pjson/2021-03-06T110903Z.json pjson/2021-03-07T111403Z.json```:
```
--- pjson/2021-03-06T110903Z.json	2021-03-06 11:09:03.189554016 +0000
+++ pjson/2021-03-07T111403Z.json	2021-03-07 11:14:04.049519529 +0000
@@ -12040,12 +12040,12 @@
"Zuwachs_Genesung": 2,
-        "Inzidenz": 62.3226408994576,
"Datum_neu": 1614384000000,
"F\u00e4lle_Meldedatum": 26,
-        "Inzidenz_RKI": 53.3,
@@ -12054,7 +12054,7 @@ …
```
=> New data set: 2021-03-07T111403Z

latest-json
```diff -u pjson/2021-03-07T111403Z.json pjson/2021-03-08T110303Z.json```:
```
--- pjson/2021-03-07T111403Z.json	2021-03-07 11:14:04.049519529 +0000
+++ pjson/2021-03-08T110303Z.json	2021-03-08 11:03:03.552926640 +0000
@@ -10238,7 +10238,7 @@
"Krh_I": null,
-        "SterbeF_Sterbedatum": 16,
+        "SterbeF_Sterbedatum": 17, …
```
=> New data set: 2021-03-08T110303Z

latest-json
```diff -u pjson/2021-03-09T110403Z.json pjson/2021-03-10T110403Z.json```:
```
--- pjson/2021-03-09T110403Z.json	2021-03-09 11:04:03.543407387 +0000
+++ pjson/2021-03-10T110403Z.json	2021-03-10 11:04:03.633041198 +0000
@@ -9336,7 +9336,7 @@
-        "F\u00e4lle_Meldedatum": 377,
+        "F\u00e4lle_Meldedatum": 378,
@@ -9633,7 +9633,7 @@
-        "F\u00e4lle_Meldedatum": 358,
+        "F\u00e4lle_Meldedatum": 359, …
```
=> New data set: 2021-03-10T110403Z

latest-json
```diff -u pjson/2021-03-10T110403Z.json pjson/2021-03-11T110404Z.json```:
```
--- pjson/2021-03-10T110403Z.json	2021-03-10 11:04:03.633041198 +0000
+++ pjson/2021-03-11T110404Z.json	2021-03-11 11:04:04.132010808 +0000
@@ -8874,7 +8874,7 @@
+        "F\u00e4lle_Meldedatum": 199,
@@ -9798,7 +9798,7 @@
"Datum_neu": 1608508800000,
-        "F\u00e4lle_Meldedatum": 462,
+        "F\u00e4lle_Meldedatum": 461,
"Hosp_Meldedatum": 47, …
```
=> New data set: 2021-03-11T110404Z

latest-json
```diff -u pjson/2021-03-11T110404Z.json pjson/2021-03-12T111603Z.json```:
```
--- pjson/2021-03-11T110404Z.json	2021-03-11 11:04:04.132010808 +0000
+++ pjson/2021-03-12T111603Z.json	2021-03-12 11:16:03.741818869 +0000
@@ -8414,7 +8414,7 @@
"Datum_neu": 1604880000000,
"F\u00e4lle_Meldedatum": 100,
+        "Hosp_Meldedatum": 10,
@@ -8513,7 +8513,7 @@
"Datum_neu": 1605139200000,
"F\u00e4lle_Meldedatum": 197,
-        "Hosp_Meldedatum": 13, …
```
=> New data set: 2021-03-12T111603Z

latest-json
```diff -u pjson/2021-03-12T111603Z.json pjson/2021-03-13T110203Z.json```:
```
--- pjson/2021-03-12T111603Z.json	2021-03-12 11:16:03.741818869 +0000
+++ pjson/2021-03-13T110203Z.json	2021-03-13 11:02:03.096110935 +0000
@@ -8414,7 +8414,7 @@
"Datum_neu": 1604880000000,
"F\u00e4lle_Meldedatum": 100, …
```
=> New data set: 2021-03-13T110203Z

latest-json
```diff -u pjson/2021-03-13T110203Z.json pjson/2021-03-14T110004Z.json```:
```
--- pjson/2021-03-13T110203Z.json	2021-03-13 11:02:03.096110935 +0000
+++ pjson/2021-03-14T110004Z.json	2021-03-14 11:00:04.399798224 +0000
@@ -12339,7 +12339,7 @@
"Inzidenz": 71.8,
-        "F\u00e4lle_Meldedatum": 97,
+        "F\u00e4lle_Meldedatum": 98,
"Inzidenz_RKI": 70.6,
@@ -12438,7 +12438,7 @@
"Inzidenz": 73.9969108085779,
"Datum_neu": 1615420800000,
+        "F\u00e4lle_Meldedatum": 75,
"Hosp_Meldedatum": …
```
=> New data set: 2021-03-14T110004Z

latest-json
```diff -u pjson/2021-03-14T110004Z.json pjson/2021-03-15T111504Z.json```:
```
--- pjson/2021-03-14T110004Z.json	2021-03-14 11:00:04.399798224 +0000
+++ pjson/2021-03-15T111504Z.json	2021-03-15 11:15:05.070096419 +0000
@@ -11879,7 +11879,7 @@
"Datum_neu": 1613952000000,
"F\u00e4lle_Meldedatum": 64, …
```
=> New data set: 2021-03-15T111504Z

latest-json
```diff -u pjson/2021-03-15T111504Z.json pjson/2021-03-16T112504Z.json```:
```
--- pjson/2021-03-15T111504Z.json	2021-03-15 11:15:05.070096419 +0000
+++ pjson/2021-03-16T112504Z.json	2021-03-16 11:25:05.063238414 +0000
@@ -11294,7 +11294,7 @@
"Krh_I": null,
-        "SterbeF_Sterbedatum": 4,
+        "SterbeF_Sterbedatum": 5,
@@ -12053,7 +12053,7 @@
"Krh_I": null,
+        "SterbeF_Sterbedatum": 0,
@@ -12086,7 …
```
=> New data set: 2021-03-16T112504Z

latest-json
```diff -u pjson/2021-03-16T112504Z.json pjson/2021-03-17T112303Z.json```:
```
--- pjson/2021-03-16T112504Z.json	2021-03-16 11:25:05.063238414 +0000
+++ pjson/2021-03-17T112303Z.json	2021-03-17 11:23:03.391688171 +0000
@@ -7851,7 +7851,7 @@
"Datum_neu": 1603411200000,
@@ -9633,7 +9633,7 @@
-        "F\u00e4lle_Meldedatum": 360,
+        "F\u00e4lle_Meldedatum": 359, …
```
=> New data set: 2021-03-17T112303Z

latest-json
```diff -u pjson/2021-03-17T112303Z.json pjson/2021-03-18T112103Z.json```:
```
--- pjson/2021-03-17T112303Z.json	2021-03-17 11:23:03.391688171 +0000
+++ pjson/2021-03-18T112103Z.json	2021-03-18 11:21:03.422966744 +0000
@@ -6234,7 +6234,7 @@
"Datum_neu": 1599177600000,
+        "F\u00e4lle_Meldedatum": 8,
@@ -11943,7 +11943,7 @@
"Datum_neu": 1614124800000,
+        "F\u00e4lle_Meldedatum": 75, …
```
=> New data set: 2021-03-18T112103Z

latest-json
```diff -u pjson/2021-03-18T112103Z.json pjson/2021-03-19T112104Z.json```:
```
--- pjson/2021-03-18T112103Z.json	2021-03-18 11:21:03.422966744 +0000
+++ pjson/2021-03-19T112104Z.json	2021-03-19 11:21:04.230376251 +0000
@@ -6234,7 +6234,7 @@
"Datum_neu": 1599177600000,
@@ -7719,7 +7719,7 @@
-        "F\u00e4lle_Meldedatum": 45,
+        "F\u00e4lle_Meldedatum": 46, …
```
=> New data set: 2021-03-19T112104Z

latest-json
```diff -u pjson/2021-03-19T112104Z.json pjson/2021-03-20T111003Z.json```:
```
--- pjson/2021-03-19T112104Z.json	2021-03-19 11:21:04.230376251 +0000
+++ pjson/2021-03-20T111003Z.json	2021-03-20 11:10:03.695087771 +0000
@@ -9765,7 +9765,7 @@
"Datum_neu": 1608422400000,
-        "F\u00e4lle_Meldedatum": 105,
+        "F\u00e4lle_Meldedatum": 104, …
```
=> New data set: 2021-03-20T111003Z

latest-json
```diff -u pjson/2021-03-20T111003Z.json pjson/2021-03-21T110203Z.json```:
```
--- pjson/2021-03-20T111003Z.json	2021-03-20 11:10:03.695087771 +0000
+++ pjson/2021-03-21T110203Z.json	2021-03-21 11:02:03.936144498 +0000
@@ -12405,7 +12405,7 @@
"Datum_neu": 1615334400000,
-        "F\u00e4lle_Meldedatum": 77,
+        "F\u00e4lle_Meldedatum": 78,
@@ -12502,12 +12502,12 @@
"Zuwachs_Genesung": 32,
-        "Inzidenz": 78.666618772226,
"Datum_neu": 1615593600000, …
```
=> New data set: 2021-03-21T110203Z

latest-json
```diff -u pjson/2021-03-21T110203Z.json pjson/2021-03-22T111603Z.json```:
```
--- pjson/2021-03-21T110203Z.json	2021-03-21 11:02:03.936144498 +0000
+++ pjson/2021-03-22T111603Z.json	2021-03-22 11:16:03.657377957 +0000
@@ -11019,7 +11019,7 @@
"Datum_neu": 1611705600000,
-        "F\u00e4lle_Meldedatum": 150,
@@ -11912,7 +11912,7 @@
"Datum_neu": 1614038400000,
"F\u00e4lle_Meldedatum": 66, …
```
=> New data set: 2021-03-22T111603Z

latest-json
```diff -u pjson/2021-03-22T111603Z.json pjson/2021-03-23T110903Z.json```:
```
--- pjson/2021-03-22T111603Z.json	2021-03-22 11:16:03.657377957 +0000
+++ pjson/2021-03-23T110903Z.json	2021-03-23 11:09:03.341530390 +0000
@@ -9336,7 +9336,7 @@
-        "F\u00e4lle_Meldedatum": 378,
+        "F\u00e4lle_Meldedatum": 377,
@@ -11780,7 +11780,7 @@
"Datum_neu": 1613692800000,
"F\u00e4lle_Meldedatum": 68,
+        "Hosp_Meldedatum": 8, …
```
=> New data set: 2021-03-23T110903Z

latest-json
```diff -u pjson/2021-03-23T110903Z.json pjson/2021-03-24T110403Z.json```:
```
--- pjson/2021-03-23T110903Z.json	2021-03-23 11:09:03.341530390 +0000
+++ pjson/2021-03-24T110403Z.json	2021-03-24 11:04:03.441352295 +0000
@@ -11910,7 +11910,7 @@
"Datum_neu": 1614038400000,
-        "F\u00e4lle_Meldedatum": 67,
+        "F\u00e4lle_Meldedatum": 66,
@@ -12341,7 +12341,7 @@
"F\u00e4lle_Meldedatum": 100,
+        "Hosp_Meldedatum": 13, …
```
=> New data set: 2021-03-24T110403Z

latest-json
```diff -u pjson/2021-03-24T110403Z.json pjson/2021-03-25T110303Z.json```:
```
--- pjson/2021-03-24T110403Z.json	2021-03-24 11:04:03.441352295 +0000
+++ pjson/2021-03-25T110303Z.json	2021-03-25 11:03:03.635667882 +0000
@@ -8940,7 +8940,7 @@
-        "F\u00e4lle_Meldedatum": 271,
+        "F\u00e4lle_Meldedatum": 272, …
```
=> New data set: 2021-03-25T110303Z

latest-json
```diff -u pjson/2021-03-25T110303Z.json pjson/2021-03-26T110503Z.json```:
```
--- pjson/2021-03-25T110303Z.json	2021-03-25 11:03:03.635667882 +0000
+++ pjson/2021-03-26T110503Z.json	2021-03-26 11:05:03.691843966 +0000
@@ -12306,7 +12306,7 @@
"Datum_neu": 1615075200000,
-        "F\u00e4lle_Meldedatum": 12,
+        "F\u00e4lle_Meldedatum": 13,
@@ -12339,7 +12339,7 @@
-        "F\u00e4lle_Meldedatum": 100,
+        "F\u00e4lle_Meldedatum": 101, …
```
=> New data set: 2021-03-26T110503Z

latest-json
```diff -u pjson/2021-03-26T110503Z.json pjson/2021-03-27T110803Z.json```:
```
--- pjson/2021-03-26T110503Z.json	2021-03-26 11:05:03.691843966 +0000
+++ pjson/2021-03-27T110803Z.json	2021-03-27 11:08:04.035351095 +0000
@@ -10788,7 +10788,7 @@
"Datum_neu": 1611100800000,
-        "F\u00e4lle_Meldedatum": 144,
@@ -12405,7 +12405,7 @@
"Datum_neu": 1615334400000,
-        "F\u00e4lle_Meldedatum": 78,
+        "F\u00e4lle_Meldedatum": 79, …
```
=> New data set: 2021-03-27T110803Z

latest-json
```diff -u pjson/2021-03-27T110803Z.json pjson/2021-03-28T100204Z.json```:
```
--- pjson/2021-03-27T110803Z.json	2021-03-27 11:08:04.035351095 +0000
+++ pjson/2021-03-28T100204Z.json	2021-03-28 10:02:04.431835867 +0000
@@ -9699,7 +9699,7 @@
-        "F\u00e4lle_Meldedatum": 460,
+        "F\u00e4lle_Meldedatum": 461,
@@ -11778,7 +11778,7 @@
"Datum_neu": 1613692800000,
-        "F\u00e4lle_Meldedatum": 68,
+        "F\u00e4lle_Meldedatum": 69, …
```
=> New data set: 2021-03-28T100204Z

latest-json
```diff -u pjson/2021-03-28T100204Z.json pjson/2021-03-29T102303Z.json```:
```
--- pjson/2021-03-28T100204Z.json	2021-03-28 10:02:04.431835867 +0000
+++ pjson/2021-03-29T102303Z.json	2021-03-29 10:23:03.754059774 +0000
@@ -8078,7 +8078,7 @@
-        "Zuwachs_Genesung": 28,
+        "Zuwachs_Genesung": 54,
"Datum_neu": 1604016000000,
@@ -9138,9 +9138,9 @@
-        "F\u00e4lle_Meldedatum": 331,
+        "F\u00e4lle_Meldedatum": 332,
- …
```
=> New data set: 2021-03-29T102303Z

latest-json
```diff -u pjson/2021-03-29T102303Z.json pjson/2021-03-30T102003Z.json```:
```
--- pjson/2021-03-29T102303Z.json	2021-03-29 10:23:03.754059774 +0000
+++ pjson/2021-03-30T102003Z.json	2021-03-30 10:20:03.655227225 +0000
@@ -8214,7 +8214,7 @@
-        "F\u00e4lle_Meldedatum": 174,
+        "F\u00e4lle_Meldedatum": 173,
@@ -10095,7 +10095,7 @@
"Datum_neu": 1609286400000,
-        "F\u00e4lle_Meldedatum": 449,
+        "F\u00e4lle_Meldedatum": 450, …
```
=> New data set: 2021-03-30T102003Z

latest-json
```diff -u pjson/2021-03-30T102003Z.json pjson/2021-03-31T100404Z.json```:
```
--- pjson/2021-03-30T102003Z.json	2021-03-30 10:20:03.655227225 +0000
+++ pjson/2021-03-31T100404Z.json	2021-03-31 10:04:04.145734076 +0000
@@ -9138,7 +9138,7 @@
-        "F\u00e4lle_Meldedatum": 332,
+        "F\u00e4lle_Meldedatum": 333,
@@ -11283,7 +11283,7 @@
"Datum_neu": 1612396800000,
+        "F\u00e4lle_Meldedatum": 75, …
```
=> New data set: 2021-03-31T100404Z

latest-json
```diff -u pjson/2021-03-31T100404Z.json pjson/2021-04-01T100902Z.json```:
```
--- pjson/2021-03-31T100404Z.json	2021-03-31 10:04:04.145734076 +0000
+++ pjson/2021-04-01T100902Z.json	2021-04-01 10:09:02.993462598 +0000
@@ -7950,7 +7950,7 @@
-        "F\u00e4lle_Meldedatum": 84,
+        "F\u00e4lle_Meldedatum": 86,
@@ -9173,7 +9173,7 @@
"F\u00e4lle_Meldedatum": 291,
-        "Hosp_Meldedatum": 29,
+        "Hosp_Meldedatum": 31, …
```
=> New data set: 2021-04-01T100902Z

latest-json
```diff -u pjson/2021-04-01T100902Z.json pjson/2021-04-02T100903Z.json```:
```
--- pjson/2021-04-01T100902Z.json	2021-04-01 10:09:02.993462598 +0000
+++ pjson/2021-04-02T100903Z.json	2021-04-02 10:09:03.114601704 +0000
@@ -9435,7 +9435,7 @@
-        "F\u00e4lle_Meldedatum": 464,
+        "F\u00e4lle_Meldedatum": 465,
@@ -10095,7 +10095,7 @@
"Datum_neu": 1609286400000,
-        "F\u00e4lle_Meldedatum": 450,
+        "F\u00e4lle_Meldedatum": 451, …
```
=> New data set: 2021-04-02T100903Z

latest-json
```diff -u pjson/2021-04-02T100903Z.json pjson/2021-04-03T095603Z.json```:
```
--- pjson/2021-04-02T100903Z.json	2021-04-02 10:09:03.114601704 +0000
+++ pjson/2021-04-03T095603Z.json	2021-04-03 09:56:03.732930761 +0000
@@ -12253,8 +12253,8 @@
"SterbeF_Sterbedatum": 1,
-        "Mutation": null,
-        "Zuwachs_Mutation": null
+        "Mutation": 96,
+        "Zuwachs_Mutation": 9
}
},
{
@@ -12286,8 +12286,8 @@
"SterbeF_Sterbedatum": 1,
-        "Mutation": null,
-        "Zuwachs_Mutation": null
+        "Mutation": 99,
+        "Zuwachs_Mutation": 3
}
},
{
@@ -12319,8 …
```
=> New data set: 2021-04-03T095603Z

latest-json
```diff -u pjson/2021-04-03T095603Z.json pjson/2021-04-04T100404Z.json```:
```
--- pjson/2021-04-03T095603Z.json	2021-04-03 09:56:03.732930761 +0000
+++ pjson/2021-04-04T100404Z.json	2021-04-04 10:04:04.325487559 +0000
@@ -12253,8 +12253,8 @@
"SterbeF_Sterbedatum": 1,
-        "Mutation": 96,
-        "Zuwachs_Mutation": 9
+        "Mutation": null,
+        "Zuwachs_Mutation": null
}
},
{
@@ -12286,8 +12286,8 @@
"SterbeF_Sterbedatum": 1,
-        "Mutation": 99,
-        "Zuwachs_Mutation": 3
+        "Mutation": null,
+        "Zuwachs_Mutation": null
}
},
{
@@ -12319,8 …
```
=> New data set: 2021-04-04T100404Z

latest-json
```diff -u pjson/2021-04-04T100404Z.json pjson/2021-04-05T100103Z.json```:
```
--- pjson/2021-04-04T100404Z.json	2021-04-04 10:04:04.325487559 +0000
+++ pjson/2021-04-05T100103Z.json	2021-04-05 10:01:03.743623733 +0000
@@ -10095,7 +10095,7 @@
"Datum_neu": 1609286400000,
-        "F\u00e4lle_Meldedatum": 451,
+        "F\u00e4lle_Meldedatum": 450,
@@ -12253,8 +12253,8 @@
"SterbeF_Sterbedatum": 1,
-        "Mutation": null,
-        "Zuwachs_Mutation": null
+        "Mutation": 96,
+        "Zuwachs_Mutation": 9
}
},
{ …
```
=> New data set: 2021-04-05T100103Z

latest-json
```diff -u pjson/2021-04-05T100103Z.json pjson/2021-04-06T101003Z.json```:
```
--- pjson/2021-04-05T100103Z.json	2021-04-05 10:01:03.743623733 +0000
+++ pjson/2021-04-06T101003Z.json	2021-04-06 10:10:03.416145251 +0000
@@ -7950,7 +7950,7 @@
-        "F\u00e4lle_Meldedatum": 86,
+        "F\u00e4lle_Meldedatum": 85,
@@ -12834,7 +12834,7 @@
"Datum_neu": 1616457600000,
-        "F\u00e4lle_Meldedatum": 170,
+        "F\u00e4lle_Meldedatum": 171, …
```
=> New data set: 2021-04-06T101003Z

latest-json
```diff -u pjson/2021-04-06T101003Z.json pjson/2021-04-07T100504Z.json```:
```
--- pjson/2021-04-06T101003Z.json	2021-04-06 10:10:03.416145251 +0000
+++ pjson/2021-04-07T100504Z.json	2021-04-07 10:05:04.281733181 +0000
@@ -6564,7 +6564,7 @@
-        "F\u00e4lle_Meldedatum": 9,
+        "F\u00e4lle_Meldedatum": 10,
@@ -10326,7 +10326,7 @@
"Datum_neu": 1609891200000,
-        "F\u00e4lle_Meldedatum": 348,
+        "F\u00e4lle_Meldedatum": 347, …
```
=> New data set: 2021-04-07T100504Z

latest-json
```diff -u pjson/2021-04-07T100504Z.json pjson/2021-04-08T100603Z.json```:
```
--- pjson/2021-04-07T100504Z.json	2021-04-07 10:05:04.281733181 +0000
+++ pjson/2021-04-08T100603Z.json	2021-04-08 10:06:03.660227658 +0000
@@ -12438,7 +12438,7 @@
"Datum_neu": 1615420800000,
-        "F\u00e4lle_Meldedatum": 91,
+        "F\u00e4lle_Meldedatum": 92,
@@ -12803,7 +12803,7 @@
"Datum_neu": 1616371200000,
"F\u00e4lle_Meldedatum": 132,
-        "Hosp_Meldedatum": 17,
+        "Hosp_Meldedatum": 16, …
```
=> New data set: 2021-04-08T100603Z

latest-json
```diff -u pjson/2021-04-08T100603Z.json pjson/2021-04-09T100503Z.json```:
```
--- pjson/2021-04-08T100603Z.json	2021-04-08 10:06:03.660227658 +0000
+++ pjson/2021-04-09T100503Z.json	2021-04-09 10:05:03.688223293 +0000
@@ -8907,7 +8907,7 @@
-        "F\u00e4lle_Meldedatum": 275,
+        "F\u00e4lle_Meldedatum": 274,
@@ -10293,7 +10293,7 @@
"Datum_neu": 1609804800000,
-        "F\u00e4lle_Meldedatum": 389,
+        "F\u00e4lle_Meldedatum": 390, …
```
=> New data set: 2021-04-09T100503Z

latest-json
```diff -u pjson/2021-04-09T100503Z.json pjson/2021-04-10T100603Z.json```:
```
--- pjson/2021-04-09T100503Z.json	2021-04-09 10:05:03.688223293 +0000
+++ pjson/2021-04-10T100603Z.json	2021-04-10 10:06:03.826406799 +0000
@@ -12405,7 +12405,7 @@
"Datum_neu": 1615334400000,
-        "F\u00e4lle_Meldedatum": 79,
@@ -12900,7 +12900,7 @@
-        "F\u00e4lle_Meldedatum": 191,
+        "F\u00e4lle_Meldedatum": 192, …
```
=> New data set: 2021-04-10T100603Z

latest-json
```diff -u pjson/2021-04-10T100603Z.json pjson/2021-04-11T100403Z.json```:
```
--- pjson/2021-04-10T100603Z.json	2021-04-10 10:06:03.826406799 +0000
+++ pjson/2021-04-11T100403Z.json	2021-04-11 10:04:03.999196293 +0000
@@ -12405,7 +12405,7 @@
"Datum_neu": 1615334400000,
-        "F\u00e4lle_Meldedatum": 80,
+        "F\u00e4lle_Meldedatum": 81,
@@ -12867,7 +12867,7 @@
"Datum_neu": 1616544000000,
-        "F\u00e4lle_Meldedatum": 111,
+        "F\u00e4lle_Meldedatum": 110, …
```
=> New data set: 2021-04-11T100403Z

latest-json
```diff -u pjson/2021-04-11T100403Z.json pjson/2021-04-12T101603Z.json```:
```
--- pjson/2021-04-11T100403Z.json	2021-04-11 10:04:03.999196293 +0000
+++ pjson/2021-04-12T101603Z.json	2021-04-12 10:16:03.521881292 +0000
@@ -9105,7 +9105,7 @@
+        "F\u00e4lle_Meldedatum": 212,
@@ -10755,7 +10755,7 @@
"Datum_neu": 1611014400000,
-        "F\u00e4lle_Meldedatum": 123,
+        "F\u00e4lle_Meldedatum": 122, …
```
=> New data set: 2021-04-12T101603Z

latest-json
```diff -u pjson/2021-04-12T101603Z.json pjson/2021-04-13T103802Z.json```:
```
--- pjson/2021-04-12T101603Z.json	2021-04-12 10:16:03.521881292 +0000
+++ pjson/2021-04-13T103802Z.json	2021-04-13 10:38:03.064868638 +0000
@@ -9105,7 +9105,7 @@
-        "F\u00e4lle_Meldedatum": 212,
+        "F\u00e4lle_Meldedatum": 211,
@@ -12647,7 +12647,7 @@
"Krh_I": null,
+        "SterbeF_Sterbedatum": 3,
"Mutation": 284,
"Zuwachs_Mutation": 44 …
```
=> New data set: 2021-04-13T103802Z

latest-json
```diff -u pjson/2021-04-13T103802Z.json pjson/2021-04-14T101702Z.json```:
```
--- pjson/2021-04-13T103802Z.json	2021-04-13 10:38:03.064868638 +0000
+++ pjson/2021-04-14T101702Z.json	2021-04-14 10:17:02.856391325 +0000
@@ -9600,7 +9600,7 @@
"Datum_neu": 1607990400000,
-        "F\u00e4lle_Meldedatum": 417,
+        "F\u00e4lle_Meldedatum": 416,
@@ -10260,7 +10260,7 @@
"Datum_neu": 1609718400000,
-        "F\u00e4lle_Meldedatum": 239,
+        "F\u00e4lle_Meldedatum": 240, …
```
=> New data set: 2021-04-14T101702Z

latest-json
```diff -u pjson/2021-04-14T101702Z.json pjson/2021-04-15T100604Z.json```:
```
--- pjson/2021-04-14T101702Z.json	2021-04-14 10:17:02.856391325 +0000
+++ pjson/2021-04-15T100604Z.json	2021-04-15 10:06:04.381854571 +0000
@@ -10359,7 +10359,7 @@
-        "F\u00e4lle_Meldedatum": 271,
+        "F\u00e4lle_Meldedatum": 270,
@@ -10392,7 +10392,7 @@
"Datum_neu": 1610064000000,
+        "F\u00e4lle_Meldedatum": 212, …
```
=> New data set: 2021-04-15T100604Z

latest-json
```diff -u pjson/2021-04-15T100604Z.json pjson/2021-04-16T100403Z.json```:
```
--- pjson/2021-04-15T100604Z.json	2021-04-15 10:06:04.381854571 +0000
+++ pjson/2021-04-16T100403Z.json	2021-04-16 10:04:03.962152992 +0000
@@ -9831,7 +9831,7 @@
-        "F\u00e4lle_Meldedatum": 485,
+        "F\u00e4lle_Meldedatum": 484,
@@ -10293,7 +10293,7 @@
"Datum_neu": 1609804800000,
-        "F\u00e4lle_Meldedatum": 390,
+        "F\u00e4lle_Meldedatum": 389, …
```
=> New data set: 2021-04-16T100403Z

latest-json
```diff -u pjson/2021-04-16T100403Z.json pjson/2021-04-17T100304Z.json```:
```
--- pjson/2021-04-16T100403Z.json	2021-04-16 10:04:03.962152992 +0000
+++ pjson/2021-04-17T100304Z.json	2021-04-17 10:03:04.172259394 +0000
@@ -9435,7 +9435,7 @@
-        "F\u00e4lle_Meldedatum": 465,
+        "F\u00e4lle_Meldedatum": 466, …
```
=> New data set: 2021-04-17T100304Z

latest-json
```diff -u pjson/2021-04-17T100304Z.json pjson/2021-04-18T095903Z.json```:
```
--- pjson/2021-04-17T100304Z.json	2021-04-17 10:03:04.172259394 +0000
+++ pjson/2021-04-18T095903Z.json	2021-04-18 09:59:03.469668492 +0000
@@ -8643,7 +8643,7 @@
-        "F\u00e4lle_Meldedatum": 224,
+        "F\u00e4lle_Meldedatum": 225,
@@ -9534,7 +9534,7 @@
"Datum_neu": 1607817600000,
-        "F\u00e4lle_Meldedatum": 123,
+        "F\u00e4lle_Meldedatum": 124, …
```
=> New data set: 2021-04-18T095903Z

latest-json
```diff -u pjson/2021-04-18T095903Z.json pjson/2021-04-19T103704Z.json```:
```
--- pjson/2021-04-18T095903Z.json	2021-04-18 09:59:03.469668492 +0000
+++ pjson/2021-04-19T103704Z.json	2021-04-19 10:37:04.119316356 +0000
@@ -9864,7 +9864,7 @@
-        "F\u00e4lle_Meldedatum": 445,
+        "F\u00e4lle_Meldedatum": 444, …
```
=> New data set: 2021-04-19T103704Z

latest-json
```diff -u pjson/2021-04-19T103704Z.json pjson/2021-04-20T100903Z.json```:
```
--- pjson/2021-04-19T103704Z.json	2021-04-19 10:37:04.119316356 +0000
+++ pjson/2021-04-20T100903Z.json	2021-04-20 10:09:03.339869831 +0000
@@ -8643,7 +8643,7 @@
-        "F\u00e4lle_Meldedatum": 225,
+        "F\u00e4lle_Meldedatum": 224,
@@ -9171,7 +9171,7 @@
-        "F\u00e4lle_Meldedatum": 291,
+        "F\u00e4lle_Meldedatum": 292, …
```
=> New data set: 2021-04-20T100903Z

latest-json
```diff -u pjson/2021-04-20T100903Z.json pjson/2021-04-21T105605Z.json```:
```
--- pjson/2021-04-20T100903Z.json	2021-04-20 10:09:03.339869831 +0000
+++ pjson/2021-04-21T105605Z.json	2021-04-21 10:56:05.197850436 +0000
@@ -12383,7 +12383,7 @@
"Krh_I": null,
@@ -13065,7 +13065,7 @@
"Datum_neu": 1617062400000,
-        "F\u00e4lle_Meldedatum": 219,
+        "F\u00e4lle_Meldedatum": 222, …
```
=> New data set: 2021-04-21T105605Z

latest-json
```diff -u pjson/2021-04-21T105605Z.json pjson/2021-04-22T102504Z.json```:
```
--- pjson/2021-04-21T105605Z.json	2021-04-21 10:56:05.197850436 +0000
+++ pjson/2021-04-22T102504Z.json	2021-04-22 10:25:04.216775263 +0000
@@ -12900,7 +12900,7 @@
-        "F\u00e4lle_Meldedatum": 193,
+        "F\u00e4lle_Meldedatum": 194,
@@ -12966,7 +12966,7 @@
"Datum_neu": 1616803200000,
-        "F\u00e4lle_Meldedatum": 64,
+        "F\u00e4lle_Meldedatum": 65, …
```
=> New data set: 2021-04-22T102504Z

latest-json
```diff -u pjson/2021-04-22T102504Z.json pjson/2021-04-23T101403Z.json```:
```
--- pjson/2021-04-22T102504Z.json	2021-04-22 10:25:04.216775263 +0000
+++ pjson/2021-04-23T101403Z.json	2021-04-23 10:14:03.496493782 +0000
@@ -7917,7 +7917,7 @@
"Datum_neu": 1603584000000, …
```
=> New data set: 2021-04-23T101403Z

latest-json
```diff -u pjson/2021-04-23T101403Z.json pjson/2021-04-24T100703Z.json```:
```
--- pjson/2021-04-23T101403Z.json	2021-04-23 10:14:03.496493782 +0000
+++ pjson/2021-04-24T100703Z.json	2021-04-24 10:07:03.096600653 +0000
@@ -7521,7 +7521,7 @@
"Datum_neu": 1602547200000,
@@ -9633,7 +9633,7 @@
-        "F\u00e4lle_Meldedatum": 359,
+        "F\u00e4lle_Meldedatum": 360, …
```
=> New data set: 2021-04-24T100703Z

latest-json
```diff -u pjson/2021-04-24T100703Z.json pjson/2021-04-25T100503Z.json```:
```
--- pjson/2021-04-24T100703Z.json	2021-04-24 10:07:03.096600653 +0000
+++ pjson/2021-04-25T100503Z.json	2021-04-25 10:05:03.767808264 +0000
@@ -7521,7 +7521,7 @@
"Datum_neu": 1602547200000,
@@ -8544,7 +8544,7 @@
-        "F\u00e4lle_Meldedatum": 207,
+        "F\u00e4lle_Meldedatum": 206, …
```
=> New data set: 2021-04-25T100503Z

latest-json
```diff -u pjson/2021-04-25T100503Z.json pjson/2021-04-26T100603Z.json```:
```
--- pjson/2021-04-25T100503Z.json	2021-04-25 10:05:03.767808264 +0000
+++ pjson/2021-04-26T100603Z.json	2021-04-26 10:06:03.797440339 +0000
@@ -12176,7 +12176,7 @@
"Datum_neu": 1614729600000,
"F\u00e4lle_Meldedatum": 63,
@@ -12605,7 +12605,7 @@
"Datum_neu": 1615852800000,
"F\u00e4lle_Meldedatum": 120,
-        "Hosp_Meldedatum": 6, …
```
=> New data set: 2021-04-26T100603Z

latest-json
```diff -u pjson/2021-04-26T100603Z.json pjson/2021-04-27T100603Z.json```:
```
--- pjson/2021-04-26T100603Z.json	2021-04-26 10:06:03.797440339 +0000
+++ pjson/2021-04-27T100603Z.json	2021-04-27 10:06:03.487122313 +0000
@@ -13296,7 +13296,7 @@
"Datum_neu": 1617667200000,
-        "F\u00e4lle_Meldedatum": 154,
+        "F\u00e4lle_Meldedatum": 155,
@@ -13560,7 +13560,7 @@
"Datum_neu": 1618358400000,
-        "F\u00e4lle_Meldedatum": 189,
+        "F\u00e4lle_Meldedatum": 190, …
```
=> New data set: 2021-04-27T100603Z

latest-json
```diff -u pjson/2021-04-27T100603Z.json pjson/2021-04-28T100504Z.json```:
```
--- pjson/2021-04-27T100603Z.json	2021-04-27 10:06:03.487122313 +0000
+++ pjson/2021-04-28T100504Z.json	2021-04-28 10:05:04.300019584 +0000
@@ -8709,7 +8709,7 @@
"Datum_neu": 1605657600000,
-        "F\u00e4lle_Meldedatum": 106,
+        "F\u00e4lle_Meldedatum": 105,
@@ -9105,7 +9105,7 @@
+        "F\u00e4lle_Meldedatum": 210, …
```
=> New data set: 2021-04-28T100504Z

latest-json
```diff -u pjson/2021-04-29T100703Z.json pjson/2021-04-30T100403Z.json```:
```
--- pjson/2021-04-29T100703Z.json	2021-04-29 10:07:03.315411546 +0000
+++ pjson/2021-04-30T100403Z.json	2021-04-30 10:04:03.851480195 +0000
@@ -9435,7 +9435,7 @@
-        "F\u00e4lle_Meldedatum": 465,
+        "F\u00e4lle_Meldedatum": 464,
@@ -13164,7 +13164,7 @@
"Datum_neu": 1617321600000,
-        "F\u00e4lle_Meldedatum": 48,
+        "F\u00e4lle_Meldedatum": 49, …
```
=> New data set: 2021-04-30T100403Z

latest-json
```diff -u pjson/2021-04-30T100403Z.json pjson/2021-05-01T100207Z.json```:
```
--- pjson/2021-04-30T100403Z.json	2021-04-30 10:04:03.851480195 +0000
+++ pjson/2021-05-01T100207Z.json	2021-05-01 10:02:07.282411790 +0000
@@ -9567,7 +9567,7 @@
-        "F\u00e4lle_Meldedatum": 419,
+        "F\u00e4lle_Meldedatum": 418,
@@ -10986,7 +10986,7 @@
"Datum_neu": 1611619200000,
-        "F\u00e4lle_Meldedatum": 155,
+        "F\u00e4lle_Meldedatum": 154, …
```
=> New data set: 2021-05-01T100207Z

latest-json
```diff -u pjson/2021-05-01T100207Z.json pjson/2021-05-02T100203Z.json```:
```
--- pjson/2021-05-01T100207Z.json	2021-05-01 10:02:07.282411790 +0000
+++ pjson/2021-05-02T100203Z.json	2021-05-02 10:02:03.778243016 +0000
@@ -13595,7 +13595,7 @@
"Datum_neu": 1618444800000,
"F\u00e4lle_Meldedatum": 134,
@@ -13659,7 +13659,7 @@
"Datum_neu": 1618617600000,
-        "F\u00e4lle_Meldedatum": 90, …
```
=> New data set: 2021-05-02T100203Z

latest-json
```diff -u pjson/2021-05-02T100203Z.json pjson/2021-05-03T100302Z.json```:
```
--- pjson/2021-05-02T100203Z.json	2021-05-02 10:02:03.778243016 +0000
+++ pjson/2021-05-03T100302Z.json	2021-05-03 10:03:02.924427358 +0000
@@ -11382,7 +11382,7 @@
"Datum_neu": 1612656000000,
-        "F\u00e4lle_Meldedatum": 10,
+        "F\u00e4lle_Meldedatum": 11,
@@ -12438,7 +12438,7 @@
"Datum_neu": 1615420800000,
-        "F\u00e4lle_Meldedatum": 92,
+        "F\u00e4lle_Meldedatum": 91, …
```
=> New data set: 2021-05-03T100302Z

latest-json
```diff -u pjson/2021-05-03T100302Z.json pjson/2021-05-04T100703Z.json```:
```
--- pjson/2021-05-03T100302Z.json	2021-05-03 10:03:02.924427358 +0000
+++ pjson/2021-05-04T100703Z.json	2021-05-04 10:07:03.442143270 +0000
@@ -13758,7 +13758,7 @@
"Datum_neu": 1618876800000,
-        "F\u00e4lle_Meldedatum": 228,
+        "F\u00e4lle_Meldedatum": 229,
@@ -13791,7 +13791,7 @@
"Datum_neu": 1618963200000,
-        "F\u00e4lle_Meldedatum": 175,
+        "F\u00e4lle_Meldedatum": 177, …
```
=> New data set: 2021-05-04T100703Z

latest-json
```diff -u pjson/2021-05-04T100703Z.json pjson/2021-05-05T100403Z.json```:
```
--- pjson/2021-05-04T100703Z.json	2021-05-04 10:07:03.442143270 +0000
+++ pjson/2021-05-05T100403Z.json	2021-05-05 10:04:03.548985936 +0000
@@ -13791,7 +13791,7 @@
"Datum_neu": 1618963200000,
-        "F\u00e4lle_Meldedatum": 177,
+        "F\u00e4lle_Meldedatum": 179,
@@ -13824,7 +13824,7 @@
"Datum_neu": 1619049600000,
+        "F\u00e4lle_Meldedatum": 154, …
```
=> New data set: 2021-05-05T100403Z

latest-json
```diff -u pjson/2021-05-05T100403Z.json pjson/2021-05-06T100604Z.json```:
```
--- pjson/2021-05-05T100403Z.json	2021-05-05 10:04:03.548985936 +0000
+++ pjson/2021-05-06T100604Z.json	2021-05-06 10:06:04.857642492 +0000
@@ -9336,7 +9336,7 @@
-        "F\u00e4lle_Meldedatum": 377,
+        "F\u00e4lle_Meldedatum": 378,
@@ -13527,7 +13527,7 @@
"Datum_neu": 1618272000000,
-        "F\u00e4lle_Meldedatum": 201,
+        "F\u00e4lle_Meldedatum": 200, …
```
=> New data set: 2021-05-06T100604Z

latest-json
```diff -u pjson/2021-05-06T100604Z.json pjson/2021-05-07T100803Z.json```:
```
--- pjson/2021-05-06T100604Z.json	2021-05-06 10:06:04.857642492 +0000
+++ pjson/2021-05-07T100803Z.json	2021-05-07 10:08:03.302019248 +0000
@@ -9336,7 +9336,7 @@
-        "F\u00e4lle_Meldedatum": 378,
+        "F\u00e4lle_Meldedatum": 377,
@@ -13362,7 +13362,7 @@
"Datum_neu": 1617840000000,
-        "F\u00e4lle_Meldedatum": 143,
+        "F\u00e4lle_Meldedatum": 144, …
```
=> New data set: 2021-05-07T100803Z

latest-json
```diff -u pjson/2021-05-07T100803Z.json pjson/2021-05-08T100403Z.json```:
```
--- pjson/2021-05-07T100803Z.json	2021-05-07 10:08:03.302019248 +0000
+++ pjson/2021-05-08T100403Z.json	2021-05-08 10:04:03.811631317 +0000
@@ -13857,7 +13857,7 @@
"Datum_neu": 1619136000000,
+        "F\u00e4lle_Meldedatum": 147,
-        "F\u00e4lle_Meldedatum": 183,
+        "F\u00e4lle_Meldedatum": 184, …
```
=> New data set: 2021-05-08T100403Z

latest-json
```diff -u pjson/2021-05-08T100403Z.json pjson/2021-05-09T095803Z.json```:
```
--- pjson/2021-05-08T100403Z.json	2021-05-08 10:04:03.811631317 +0000
+++ pjson/2021-05-09T095803Z.json	2021-05-09 09:58:03.152192380 +0000
@@ -12867,7 +12867,7 @@
"Datum_neu": 1616544000000,
-        "F\u00e4lle_Meldedatum": 108,
+        "F\u00e4lle_Meldedatum": 109,
-        "F\u00e4lle_Meldedatum": 184,
+        "F\u00e4lle_Meldedatum": 185, …
```
=> New data set: 2021-05-09T095803Z

latest-json
```diff -u pjson/2021-05-10T070403Z.json pjson/2021-05-10T104703Z.json```:
```
--- pjson/2021-05-10T070403Z.json	2021-05-10 07:04:03.544859340 +0000
+++ pjson/2021-05-10T104703Z.json	2021-05-10 10:47:03.534757230 +0000
@@ -13197,7 +13197,7 @@
"Datum_neu": 1617408000000,
-        "F\u00e4lle_Meldedatum": 56,
+        "F\u00e4lle_Meldedatum": 55,
@@ -14066,7 +14066,7 @@
"Krh_I": null,
+        "SterbeF_Sterbedatum": 3, …
```
=> New data set: 2021-05-10T104703Z

latest-json
```diff -u pjson/2021-05-10T104703Z.json pjson/2021-05-11T100603Z.json```:
```
--- pjson/2021-05-10T104703Z.json	2021-05-10 10:47:03.534757230 +0000
+++ pjson/2021-05-11T100603Z.json	2021-05-11 10:06:04.030396026 +0000
@@ -13857,7 +13857,7 @@
"Datum_neu": 1619136000000,
-        "F\u00e4lle_Meldedatum": 147,
+        "F\u00e4lle_Meldedatum": 146,
@@ -13934,7 +13934,7 @@
"Krh_I": null, …
```
=> New data set: 2021-05-11T100603Z

latest-json
```diff -u pjson/2021-05-11T100603Z.json pjson/2021-05-12T101104Z.json```:
```
--- pjson/2021-05-11T100603Z.json	2021-05-11 10:06:04.030396026 +0000
+++ pjson/2021-05-12T101104Z.json	2021-05-12 10:11:04.129359350 +0000
@@ -11019,7 +11019,7 @@
"Datum_neu": 1611705600000,
+        "F\u00e4lle_Meldedatum": 150,
@@ -12867,7 +12867,7 @@
"Datum_neu": 1616544000000,
-        "F\u00e4lle_Meldedatum": 109,
+        "F\u00e4lle_Meldedatum": 108, …
```
=> New data set: 2021-05-12T101104Z

latest-json
```diff -u pjson/2021-05-12T101104Z.json pjson/2021-05-13T100303Z.json```:
```
--- pjson/2021-05-12T101104Z.json	2021-05-12 10:11:04.129359350 +0000
+++ pjson/2021-05-13T100303Z.json	2021-05-13 10:03:03.339435639 +0000
-        "F\u00e4lle_Meldedatum": 184,
+        "F\u00e4lle_Meldedatum": 183,
@@ -13989,7 +13989,7 @@
"Datum_neu": 1619481600000,
-        "F\u00e4lle_Meldedatum": 185,
+        "F\u00e4lle_Meldedatum": 184, …
```
=> New data set: 2021-05-13T100303Z

latest-json
```diff -u pjson/2021-05-13T100303Z.json pjson/2021-05-14T100205Z.json```:
```
--- pjson/2021-05-13T100303Z.json	2021-05-13 10:03:03.339435639 +0000
+++ pjson/2021-05-14T100205Z.json	2021-05-14 10:02:05.457074595 +0000
-        "F\u00e4lle_Meldedatum": 183,
+        "F\u00e4lle_Meldedatum": 184,
@@ -14187,7 +14187,7 @@
"Datum_neu": 1620000000000,
+        "F\u00e4lle_Meldedatum": 141, …
```
=> New data set: 2021-05-14T100205Z

latest-json
```diff -u pjson/2021-05-14T100205Z.json pjson/2021-05-15T100130Z.json```:
```
--- pjson/2021-05-14T100205Z.json	2021-05-14 10:02:05.457074595 +0000
+++ pjson/2021-05-15T100130Z.json	2021-05-15 10:01:31.088685938 +0000
-        "F\u00e4lle_Meldedatum": 184,
+        "F\u00e4lle_Meldedatum": 183,
@@ -14121,7 +14121,7 @@
"Datum_neu": 1619827200000,
+        "F\u00e4lle_Meldedatum": 73, …
```
=> New data set: 2021-05-15T100130Z

latest-json
```diff -u pjson/2021-05-15T100130Z.json pjson/2021-05-16T100903Z.json```:
```
--- pjson/2021-05-15T100130Z.json	2021-05-15 10:01:31.088685938 +0000
+++ pjson/2021-05-16T100903Z.json	2021-05-16 10:09:03.677222091 +0000
@@ -9930,7 +9930,7 @@
"Datum_neu": 1608854400000,
-        "F\u00e4lle_Meldedatum": 43,
@@ -10953,7 +10953,7 @@
"Datum_neu": 1611532800000,
-        "F\u00e4lle_Meldedatum": 115,
+        "F\u00e4lle_Meldedatum": 116, …
```
=> New data set: 2021-05-16T100903Z

latest-json
```diff -u pjson/2021-05-16T100903Z.json pjson/2021-05-17T103703Z.json```:
```
--- pjson/2021-05-16T100903Z.json	2021-05-16 10:09:03.677222091 +0000
+++ pjson/2021-05-17T103703Z.json	2021-05-17 10:37:03.961196571 +0000
@@ -14286,7 +14286,7 @@
"Datum_neu": 1620259200000,
-        "F\u00e4lle_Meldedatum": 112,
+        "F\u00e4lle_Meldedatum": 111,
@@ -14383,12 +14383,12 @@
"Zuwachs_Genesung": 33,
-        "Inzidenz": 124.5,
"Datum_neu": 1620518400000, …
```
=> New data set: 2021-05-17T103703Z

latest-json
```diff -u pjson/2021-05-17T103703Z.json pjson/2021-05-18T101103Z.json```:
```
--- pjson/2021-05-17T103703Z.json	2021-05-17 10:37:03.961196571 +0000
+++ pjson/2021-05-18T101103Z.json	2021-05-18 10:11:03.984198263 +0000
@@ -14165,7 +14165,7 @@
"Krh_I": null,
@@ -14187,7 +14187,7 @@
"Datum_neu": 1620000000000,
-        "F\u00e4lle_Meldedatum": 141,
+        "F\u00e4lle_Meldedatum": 142, …
```
=> New data set: 2021-05-18T101103Z

latest-json
```diff -u pjson/2021-05-18T101103Z.json pjson/2021-05-19T100215Z.json```:
```
--- pjson/2021-05-18T101103Z.json	2021-05-18 10:11:03.984198263 +0000
+++ pjson/2021-05-19T100215Z.json	2021-05-19 10:02:15.776258463 +0000
@@ -11085,7 +11085,7 @@
"Datum_neu": 1611878400000,
-        "F\u00e4lle_Meldedatum": 67,
+        "F\u00e4lle_Meldedatum": 68,
@@ -12702,7 +12702,7 @@
"Datum_neu": 1616112000000,
-        "F\u00e4lle_Meldedatum": 111,
+        "F\u00e4lle_Meldedatum": 112, …
```
=> New data set: 2021-05-19T100215Z

latest-json
```diff -u pjson/2021-05-19T100215Z.json pjson/2021-05-20T100903Z.json```:
```
--- pjson/2021-05-19T100215Z.json	2021-05-19 10:02:15.776258463 +0000
+++ pjson/2021-05-20T100903Z.json	2021-05-20 10:09:03.932651886 +0000
@@ -8544,7 +8544,7 @@
-        "F\u00e4lle_Meldedatum": 206,
+        "F\u00e4lle_Meldedatum": 207,
@@ -14220,7 +14220,7 @@
"Datum_neu": 1620086400000,
-        "F\u00e4lle_Meldedatum": 174,
+        "F\u00e4lle_Meldedatum": 175, …
```
=> New data set: 2021-05-20T100903Z

latest-json
```diff -u pjson/2021-05-20T100903Z.json pjson/2021-05-21T100803Z.json```:
```
--- pjson/2021-05-20T100903Z.json	2021-05-20 10:09:03.932651886 +0000
+++ pjson/2021-05-21T100803Z.json	2021-05-21 10:08:03.473979314 +0000
@@ -8544,7 +8544,7 @@
-        "F\u00e4lle_Meldedatum": 207,
+        "F\u00e4lle_Meldedatum": 206,
@@ -13802,7 +13802,7 @@
"Krh_I": null,
-        "SterbeF_Sterbedatum": 4,
+        "SterbeF_Sterbedatum": 5, …
```
=> New data set: 2021-05-21T100803Z

latest-json
```diff -u pjson/2021-05-21T100803Z.json pjson/2021-05-22T100203Z.json```:
```
--- pjson/2021-05-21T100803Z.json	2021-05-21 10:08:03.473979314 +0000
+++ pjson/2021-05-22T100203Z.json	2021-05-22 10:02:03.693105571 +0000
@@ -14187,7 +14187,7 @@
"Datum_neu": 1620000000000,
-        "F\u00e4lle_Meldedatum": 142,
+        "F\u00e4lle_Meldedatum": 143,
@@ -14253,7 +14253,7 @@
"Datum_neu": 1620172800000,
-        "F\u00e4lle_Meldedatum": 115,
+        "F\u00e4lle_Meldedatum": 114, …
```
=> New data set: 2021-05-22T100203Z

latest-json
```diff -u pjson/2021-05-22T100203Z.json pjson/2021-05-23T100203Z.json```:
```
--- pjson/2021-05-22T100203Z.json	2021-05-22 10:02:03.693105571 +0000
+++ pjson/2021-05-23T100203Z.json	2021-05-23 10:02:03.999406243 +0000
@@ -14022,7 +14022,7 @@
"Datum_neu": 1619568000000,
+        "F\u00e4lle_Meldedatum": 152,
@@ -14484,7 +14484,7 @@
"Datum_neu": 1620777600000,
-        "F\u00e4lle_Meldedatum": 93,
+        "F\u00e4lle_Meldedatum": 94, …
```
=> New data set: 2021-05-23T100203Z

latest-json
```diff -u pjson/2021-05-23T100203Z.json pjson/2021-05-24T100703Z.json```:
```
--- pjson/2021-05-23T100203Z.json	2021-05-23 10:02:03.999406243 +0000
+++ pjson/2021-05-24T100703Z.json	2021-05-24 10:07:03.202845653 +0000
@@ -14614,12 +14614,12 @@
"Zuwachs_Genesung": 22,
-        "Inzidenz": 83.7,
"Datum_neu": 1621123200000,
-        "Inzidenz_RKI": 79.9,
@@ -14628,7 +14628,7 @@ …
```
=> New data set: 2021-05-24T100703Z

latest-json
```diff -u pjson/2021-05-25T100303Z.json pjson/2021-05-26T100204Z.json```:
```
--- pjson/2021-05-25T100303Z.json	2021-05-25 10:03:03.876249943 +0000
+++ pjson/2021-05-26T100204Z.json	2021-05-26 10:02:04.276031283 +0000
@@ -9371,7 +9371,7 @@
"Datum_neu": 1607385600000,
"F\u00e4lle_Meldedatum": 333,
-        "Hosp_Meldedatum": 41,
+        "Hosp_Meldedatum": 40,
@@ -9866,7 +9866,7 @@
"F\u00e4lle_Meldedatum": 445,
-        "Hosp_Meldedatum": 41,
+        "Hosp_Meldedatum": 40, …
```
=> New data set: 2021-05-26T100204Z

latest-json
```diff -u pjson/2021-05-26T100204Z.json pjson/2021-05-27T100304Z.json```:
```
--- pjson/2021-05-26T100204Z.json	2021-05-26 10:02:04.276031283 +0000
+++ pjson/2021-05-27T100304Z.json	2021-05-27 10:03:05.057906796 +0000
@@ -7950,7 +7950,7 @@
-        "F\u00e4lle_Meldedatum": 85,
+        "F\u00e4lle_Meldedatum": 86,
@@ -14022,7 +14022,7 @@
"Datum_neu": 1619568000000, …
```
=> New data set: 2021-05-27T100304Z

latest-json
```diff -u pjson/2021-05-28T100904Z.json pjson/2021-05-29T100503Z.json```:
```
--- pjson/2021-05-28T100904Z.json	2021-05-28 10:09:04.168153300 +0000
+++ pjson/2021-05-29T100503Z.json	2021-05-29 10:05:03.730095524 +0000
@@ -13824,7 +13824,7 @@
"Datum_neu": 1619049600000,
@@ -14363,7 +14363,7 @@
"Krh_I": null, …
```
=> New data set: 2021-05-29T100503Z

latest-json
```diff -u pjson/2021-05-29T100503Z.json pjson/2021-05-30T100302Z.json```:
```
--- pjson/2021-05-29T100503Z.json	2021-05-29 10:05:03.730095524 +0000
+++ pjson/2021-05-30T100302Z.json	2021-05-30 10:03:02.980354137 +0000
@@ -14812,12 +14812,12 @@
"Zuwachs_Genesung": 61,
-        "Inzidenz": 76.3,
"Datum_neu": 1621641600000,
"F\u00e4lle_Meldedatum": 23,
-        "Inzidenz_RKI": 73.5,
@@ -14826,7 +14826,7 @@ …
```
=> New data set: 2021-05-30T100302Z

latest-json
```diff -u pjson/2021-05-30T100302Z.json pjson/2021-05-31T100603Z.json```:
```
--- pjson/2021-05-30T100302Z.json	2021-05-30 10:03:02.980354137 +0000
+++ pjson/2021-05-31T100603Z.json	2021-05-31 10:06:03.376174000 +0000
@@ -14845,12 +14845,12 @@
"Zuwachs_Genesung": 13,
-        "Inzidenz": 68.6,
"Datum_neu": 1621728000000,
"F\u00e4lle_Meldedatum": 16,
-        "Inzidenz_RKI": 68.1,
@@ -14859,7 +14859,7 @@ …
```
=> New data set: 2021-05-31T100603Z

latest-json
```diff -u pjson/2021-06-01T100803Z.json pjson/2021-06-02T101204Z.json```:
```
--- pjson/2021-06-01T100803Z.json	2021-06-01 10:08:04.092033699 +0000
+++ pjson/2021-06-02T101204Z.json	2021-06-02 10:12:04.120423767 +0000
@@ -8775,7 +8775,7 @@
"Datum_neu": 1605830400000,
-        "F\u00e4lle_Meldedatum": 195,
@@ -13296,7 +13296,7 @@
"Datum_neu": 1617667200000,
-        "F\u00e4lle_Meldedatum": 155,
+        "F\u00e4lle_Meldedatum": 154, …
```
=> New data set: 2021-06-02T101204Z

latest-json
```diff -u pjson/2021-06-02T101204Z.json pjson/2021-06-03T102303Z.json```:
```
--- pjson/2021-06-02T101204Z.json	2021-06-02 10:12:04.120423767 +0000
+++ pjson/2021-06-03T102303Z.json	2021-06-03 10:23:03.536629773 +0000
@@ -14814,7 +14814,7 @@
"Datum_neu": 1621641600000,
-        "F\u00e4lle_Meldedatum": 23,
+        "F\u00e4lle_Meldedatum": 24,
@@ -14944,12 +14944,12 @@
"Zuwachs_Genesung": 110,
-        "Inzidenz": 47.1,
"Datum_neu": 1621987200000, …
```
=> New data set: 2021-06-03T102303Z

latest-json
Correct data for today. First try today (2021-06-04T100103Z) was again missing half of the days.
=> Auto-update 'latest-json'.

latest-json
```diff -u pjson/2021-06-05T100203Z.json pjson/2021-06-06T100203Z.json```:
```
--- pjson/2021-06-05T100203Z.json	2021-06-05 10:02:03.755165819 +0000
+++ pjson/2021-06-06T100203Z.json	2021-06-06 10:02:03.948535301 +0000
@@ -15043,12 +15043,12 @@
"Zuwachs_Genesung": 62,
-        "Inzidenz": 34.5,
"Datum_neu": 1622246400000,
"F\u00e4lle_Meldedatum": 24,
-        "Inzidenz_RKI": 30.9,
@@ -15057,7 +15057,7 @@ …
```
=> New data set: 2021-06-06T100203Z

latest-json
```diff -u pjson/2021-06-06T100203Z.json pjson/2021-06-07T100403Z.json```:
```
--- pjson/2021-06-06T100203Z.json	2021-06-06 10:02:03.948535301 +0000
+++ pjson/2021-06-07T100403Z.json	2021-06-07 10:04:03.155433232 +0000
@@ -9699,7 +9699,7 @@
-        "F\u00e4lle_Meldedatum": 459,
+        "F\u00e4lle_Meldedatum": 460,
@@ -13725,7 +13725,7 @@
"Datum_neu": 1618790400000,
-        "F\u00e4lle_Meldedatum": 137,
+        "F\u00e4lle_Meldedatum": 138, …
```
=> New data set: 2021-06-07T100403Z

latest-json
```diff -u pjson/2021-06-09T101404Z.json pjson/2021-06-10T101103Z.json```:
```
--- pjson/2021-06-09T101404Z.json	2021-06-09 10:14:04.306894937 +0000
+++ pjson/2021-06-10T101103Z.json	2021-06-10 10:11:03.378899138 +0000
@@ -9171,7 +9171,7 @@
-        "F\u00e4lle_Meldedatum": 290,
+        "F\u00e4lle_Meldedatum": 291,
@@ -14519,7 +14519,7 @@
"Datum_neu": 1620864000000,
"F\u00e4lle_Meldedatum": 55,
+        "Hosp_Meldedatum": 0, …
```
=> New data set: 2021-06-10T101103Z

latest-json
```diff -u pjson/2021-06-10T101103Z.json pjson/2021-06-11T102504Z.json```:
```
--- pjson/2021-06-10T101103Z.json	2021-06-10 10:11:03.378899138 +0000
+++ pjson/2021-06-11T102504Z.json	2021-06-11 10:25:04.208122049 +0000
@@ -7719,7 +7719,7 @@
-        "F\u00e4lle_Meldedatum": 46,
@@ -9173,7 +9173,7 @@
"F\u00e4lle_Meldedatum": 291,
-        "Hosp_Meldedatum": 31, …
```
=> New data set: 2021-06-11T102504Z

latest-json
```diff -u pjson/2021-06-12T102405Z.json pjson/2021-06-13T100104Z.json```:
```
--- pjson/2021-06-12T102405Z.json	2021-06-12 10:24:05.182632377 +0000
+++ pjson/2021-06-13T100104Z.json	2021-06-13 10:01:04.430667276 +0000
@@ -15274,12 +15274,12 @@
"Zuwachs_Genesung": 29,
-        "Inzidenz": 21.1932899888645,
"Datum_neu": 1622851200000,
"F\u00e4lle_Meldedatum": 14,
-        "Inzidenz_RKI": 20.5,
@@ -15288,7 +15288,7 @@ …
```
=> New data set: 2021-06-13T100104Z

latest-json
```diff -u pjson/2021-06-13T100104Z.json pjson/2021-06-14T100903Z.json```:
```
--- pjson/2021-06-13T100104Z.json	2021-06-13 10:01:04.430667276 +0000
+++ pjson/2021-06-14T100903Z.json	2021-06-14 10:09:03.768736835 +0000
@@ -13529,7 +13529,7 @@
"Datum_neu": 1618272000000,
"F\u00e4lle_Meldedatum": 201,
-        "Hosp_Meldedatum": 13,
@@ -15307,12 +15307,12 @@
"Zuwachs_Genesung": 20,
-        "Inzidenz": 19.4,
"Datum_neu": 1622937600000, …
```
=> New data set: 2021-06-14T100903Z

latest-json
```diff -u pjson/2021-06-14T100903Z.json pjson/2021-06-15T100303Z.json```:
```
--- pjson/2021-06-14T100903Z.json	2021-06-14 10:09:03.768736835 +0000
+++ pjson/2021-06-15T100303Z.json	2021-06-15 10:03:03.820513177 +0000
@@ -15340,12 +15340,12 @@
"Zuwachs_Genesung": 17,
-        "Inzidenz": 19.0380401594885,
"Datum_neu": 1623024000000,
"F\u00e4lle_Meldedatum": 8,
-        "Inzidenz_RKI": 18.9,
@@ -15354,7 +15354,7 @@ …
```
=> New data set: 2021-06-15T100303Z

latest-json
```diff -u pjson/2021-06-15T100303Z.json pjson/2021-06-16T101303Z.json```:
```
--- pjson/2021-06-15T100303Z.json	2021-06-15 10:03:03.820513177 +0000
+++ pjson/2021-06-16T101303Z.json	2021-06-16 10:13:03.823374016 +0000
@@ -13824,7 +13824,7 @@
"Datum_neu": 1619049600000,
+        "F\u00e4lle_Meldedatum": 150,
@@ -15243,7 +15243,7 @@
"Datum_neu": 1622764800000, …
```
=> New data set: 2021-06-16T101303Z

latest-json
```diff -u pjson/2021-06-16T101303Z.json pjson/2021-06-17T101404Z.json```:
```
--- pjson/2021-06-16T101303Z.json	2021-06-16 10:13:03.823374016 +0000
+++ pjson/2021-06-17T101404Z.json	2021-06-17 10:14:04.102323511 +0000
@@ -15221,7 +15221,7 @@
"Krh_I": null,
+        "SterbeF_Sterbedatum": 3,
@@ -15353,7 +15353,7 @@
"Krh_I": null,
@@ …
```
=> New data set: 2021-06-17T101404Z

latest-json
```diff -u pjson/2021-06-17T101404Z.json pjson/2021-06-18T101103Z.json```:
```
--- pjson/2021-06-17T101404Z.json	2021-06-17 10:14:04.102323511 +0000
+++ pjson/2021-06-18T101103Z.json	2021-06-18 10:11:03.406640112 +0000
@@ -9767,7 +9767,7 @@
"Datum_neu": 1608422400000,
"F\u00e4lle_Meldedatum": 104,
+        "Hosp_Meldedatum": 7,
@@ -9833,7 +9833,7 @@
"F\u00e4lle_Meldedatum": 484,
-        "Hosp_Meldedatum": 32,
+        "Hosp_Meldedatum": 29, …
```
=> New data set: 2021-06-18T101103Z

latest-json
```diff -u pjson/2021-06-18T101103Z.json pjson/2021-06-19T100503Z.json```:
```
--- pjson/2021-06-18T101103Z.json	2021-06-18 10:11:03.406640112 +0000
+++ pjson/2021-06-19T100503Z.json	2021-06-19 10:05:03.751672944 +0000
@@ -15439,12 +15439,12 @@
"Zuwachs_Genesung": 38,
-        "Inzidenz": 10.6,
"Datum_neu": 1623283200000,
-        "F\u00e4lle_Meldedatum": 16,
+        "F\u00e4lle_Meldedatum": 17,
-        "Inzidenz_RKI": 9.9,
@@ -15453,7 …
```
=> New data set: 2021-06-19T100503Z

latest-json
```diff -u pjson/2021-06-21T095203Z.json pjson/2021-06-22T102203Z.json```:
```
--- pjson/2021-06-21T095203Z.json	2021-06-21 09:52:03.680583144 +0000
+++ pjson/2021-06-22T102203Z.json	2021-06-22 10:22:03.532895280 +0000
@@ -15342,7 +15342,7 @@
"Datum_neu": 1623024000000,
+        "F\u00e4lle_Meldedatum": 9,
@@ -15474,7 +15474,7 @@
"Datum_neu": 1623369600000,
+        "F\u00e4lle_Meldedatum": 4, …
```
=> New data set: 2021-06-22T102203Z

latest-json
```diff -u pjson/2021-06-22T102203Z.json pjson/2021-06-23T101803Z.json```:
```
--- pjson/2021-06-22T102203Z.json	2021-06-22 10:22:03.532895280 +0000
+++ pjson/2021-06-23T101803Z.json	2021-06-23 10:18:03.745910914 +0000
@@ -15571,7 +15571,7 @@
"Zuwachs_Genesung": 24,
-        "Inzidenz": 8.4,
"Datum_neu": 1623628800000,
"F\u00e4lle_Meldedatum": 5,
@@ -15604,12 +15604,12 @@
"Zuwachs_Genesung": 34,
-        "Inzidenz": 7.5,
"Datum_neu": 1623715200000, …
```
=> New data set: 2021-06-23T101803Z

latest-json
```diff -u pjson/2021-06-23T101803Z.json pjson/2021-06-24T100803Z.json```:
```
--- pjson/2021-06-23T101803Z.json	2021-06-23 10:18:03.745910914 +0000
+++ pjson/2021-06-24T100803Z.json	2021-06-24 10:08:04.002429270 +0000
@@ -8775,7 +8775,7 @@
"Datum_neu": 1605830400000,
-        "F\u00e4lle_Meldedatum": 196,
+        "F\u00e4lle_Meldedatum": 191,
@@ -8874,7 +8874,7 @@
+        "F\u00e4lle_Meldedatum": 201, …
```
=> New data set: 2021-06-24T100803Z

latest-json
```diff -u pjson/2021-06-24T100803Z.json pjson/2021-06-25T100603Z.json```:
```
--- pjson/2021-06-24T100803Z.json	2021-06-24 10:08:04.002429270 +0000
+++ pjson/2021-06-25T100603Z.json	2021-06-25 10:06:04.022350225 +0000
@@ -4452,7 +4452,7 @@
"Datum_neu": 1594512000000,
-        "F\u00e4lle_Meldedatum": 0,
+        "F\u00e4lle_Meldedatum": 1,
@@ -9831,7 +9831,7 @@
-        "F\u00e4lle_Meldedatum": 480,
+        "F\u00e4lle_Meldedatum": 481, …
```
=> New data set: 2021-06-25T100603Z

latest-json
```diff -u pjson/2021-06-25T100603Z.json pjson/2021-06-26T100203Z.json```:
```
--- pjson/2021-06-25T100603Z.json	2021-06-25 10:06:04.022350225 +0000
+++ pjson/2021-06-26T100203Z.json	2021-06-26 10:02:03.480480451 +0000
@@ -15703,7 +15703,7 @@
"Zuwachs_Genesung": 8,
-        "Inzidenz": 5.7,
"Datum_neu": 1623974400000,
@@ -15717,7 +15717,7 @@
"SterbeF_Sterbedatum": 1,
-        "Inzi_SN_RKI": 6.1,
}
@@ -15892,31 …
```
=> New data set: 2021-06-26T100203Z

latest-json
```diff -u pjson/2021-06-26T100203Z.json pjson/2021-06-28T101103Z.json```:
```
--- pjson/2021-06-26T100203Z.json	2021-06-26 10:02:03.480480451 +0000
+++ pjson/2021-06-28T101103Z.json	2021-06-28 10:11:03.991923846 +0000
@@ -15708,7 +15708,7 @@
-        "Inzidenz_RKI": 4.5,
@@ -15736,12 +15736,12 @@
"Zuwachs_Genesung": 18,
-        "Inzidenz": 6.6,
"Datum_neu": 1624060800000,
"F\u00e4lle_Meldedatum": 3, …
```
=> New data set: 2021-06-28T101103Z

latest-json
```diff -u pjson/2021-06-29T102503Z.json pjson/2021-06-30T100303Z.json```:
```
--- pjson/2021-06-29T102503Z.json	2021-06-29 10:25:03.486987496 +0000
+++ pjson/2021-06-30T100303Z.json	2021-06-30 10:03:03.538338099 +0000
@@ -15835,12 +15835,12 @@
-        "Inzidenz": 6.6,
"Datum_neu": 1624320000000,
-        "Inzidenz_RKI": 6.1,
@@ -15849,7 +15849,7 @@ …
```
=> New data set: 2021-06-30T100303Z

latest-json
```diff -u pjson/2021-06-30T100303Z.json pjson/2021-07-01T100803Z.json```:
```
--- pjson/2021-06-30T100303Z.json	2021-06-30 10:03:03.538338099 +0000
+++ pjson/2021-07-01T100803Z.json	2021-07-01 10:08:04.077446657 +0000
@@ -15276,7 +15276,7 @@
"Datum_neu": 1622851200000,
+        "F\u00e4lle_Meldedatum": 13,
@@ -15639,7 +15639,7 @@
"Datum_neu": 1623801600000, …
```
=> New data set: 2021-07-01T100803Z

latest-json
```diff -u pjson/2021-07-01T151303Z.json pjson/2021-07-02T101104Z.json```:
```
--- pjson/2021-07-01T151303Z.json	2021-07-01 15:13:03.716626564 +0000
+++ pjson/2021-07-02T101104Z.json	2021-07-02 10:11:04.147265699 +0000
@@ -10199,7 +10199,7 @@
"Datum_neu": 1608768000000,
"F\u00e4lle_Meldedatum": 125,
-        "Hosp_Meldedatum": 15,
+        "Hosp_Meldedatum": 16,
@@ -10743,7 +10743,7 @@
"Datum_neu": 1610150400000,
"F\u00e4lle_Meldedatum": 86, …
```
=> New data set: 2021-07-02T101104Z

latest-json
```diff -u pjson/2021-07-02T101104Z.json pjson/2021-07-03T100103Z.json```:
```
--- pjson/2021-07-02T101104Z.json	2021-07-02 10:11:04.147265699 +0000
+++ pjson/2021-07-03T100103Z.json	2021-07-03 10:01:03.973638233 +0000
@@ -16417,12 +16417,12 @@
"Zuwachs_Genesung": 5,
-        "Inzidenz": 5.92693703078415,
"Datum_neu": 1624579200000,
-        "Inzidenz_RKI": 5.6,
@@ -16432,7 +16432,7 @@ …
```
=> New data set: 2021-07-03T100103Z

latest-json
```diff -u pjson/2021-07-05T070503Z.json pjson/2021-07-05T100814Z.json```:
```
--- pjson/2021-07-05T070503Z.json	2021-07-05 07:05:04.057495205 +0000
+++ pjson/2021-07-05T100814Z.json	2021-07-05 10:08:14.330331965 +0000
@@ -14517,7 +14517,7 @@
"Datum_neu": 1619740800000,
"F\u00e4lle_Meldedatum": 106,
@@ -16485,12 +16485,12 @@
"Zuwachs_Genesung": 7,
-        "Inzidenz": 7.4,
"Datum_neu": 1624752000000,
"F\u00e4lle_Meldedatum": …
```
=> New data set: 2021-07-05T100814Z

latest-json
```diff -u pjson/2021-07-05T100814Z.json pjson/2021-07-06T100403Z.json```:
```
--- pjson/2021-07-05T100814Z.json	2021-07-05 10:08:14.330331965 +0000
+++ pjson/2021-07-06T100403Z.json	2021-07-06 10:04:03.459204553 +0000
@@ -16519,12 +16519,12 @@
-        "Inzidenz": 7.4,
"Datum_neu": 1624838400000,
-        "Inzidenz_RKI": 7.2,
@@ -16534,7 +16534,7 @@ …
```
=> New data set: 2021-07-06T100403Z

latest-json
```diff -u pjson/2021-07-06T100403Z.json pjson/2021-07-07T101203Z.json```:
```
--- pjson/2021-07-06T100403Z.json	2021-07-06 10:04:03.459204553 +0000
+++ pjson/2021-07-07T101203Z.json	2021-07-07 10:12:03.939904292 +0000
@@ -16283,7 +16283,7 @@
"Datum_neu": 1624233600000,
@@ -16553,12 +16553,12 @@
"Zuwachs_Genesung": 7,
-        "Inzidenz": 8.4,
"Datum_neu": 1624924800000,
"F\u00e4lle_Meldedatum": 7, …
```
=> New data set: 2021-07-07T101203Z

latest-json
```diff -u pjson/2021-07-07T101203Z.json pjson/2021-07-08T100203Z.json```:
```
--- pjson/2021-07-07T101203Z.json	2021-07-07 10:12:03.939904292 +0000
+++ pjson/2021-07-08T100203Z.json	2021-07-08 10:02:03.802005756 +0000
@@ -16587,12 +16587,12 @@
"Zuwachs_Genesung": 10,
-        "Inzidenz": 7.4,
"Datum_neu": 1625011200000,
"F\u00e4lle_Meldedatum": 2,
-        "Inzidenz_RKI": 6.8,
@@ -16602,7 +16602,7 @@ …
```
=> New data set: 2021-07-08T100203Z

latest-json
```diff -u pjson/2021-07-08T100203Z.json pjson/2021-07-09T100203Z.json```:
```
--- pjson/2021-07-08T100203Z.json	2021-07-08 10:02:03.802005756 +0000
+++ pjson/2021-07-09T100203Z.json	2021-07-09 10:02:03.812249460 +0000
@@ -16621,12 +16621,12 @@
"Zuwachs_Genesung": 29,
-        "Inzidenz": 7.5,
"Datum_neu": 1625097600000,
"F\u00e4lle_Meldedatum": 6,
-        "Inzidenz_RKI": 7,
@@ -16636,7 +16636,7 @@ …
```
=> New data set: 2021-07-09T100203Z

latest-json
```diff -u pjson/2021-07-09T100203Z.json pjson/2021-07-10T100103Z.json```:
```
--- pjson/2021-07-09T100203Z.json	2021-07-09 10:02:03.812249460 +0000
+++ pjson/2021-07-10T100103Z.json	2021-07-10 10:01:03.381983546 +0000
@@ -16351,7 +16351,7 @@
"Datum_neu": 1624406400000,
@@ -16655,12 +16655,12 @@
"Zuwachs_Genesung": 11,
-        "Inzidenz": 6.8,
"Datum_neu": 1625184000000,
"F\u00e4lle_Meldedatum": 1, …
```
=> New data set: 2021-07-10T100103Z

latest-json
```diff -u pjson/2021-07-10T100103Z.json pjson/2021-07-11T100203Z.json```:
```
--- pjson/2021-07-10T100103Z.json	2021-07-10 10:01:03.381983546 +0000
+++ pjson/2021-07-11T100203Z.json	2021-07-11 10:02:03.682002246 +0000
@@ -16689,12 +16689,12 @@
"Zuwachs_Genesung": 4,
-        "Inzidenz": 5.4,
"Datum_neu": 1625270400000,
"F\u00e4lle_Meldedatum": 1,
-        "Inzidenz_RKI": 5,
@@ -16704,7 +16704,7 @@ …
```
=> New data set: 2021-07-11T100203Z

latest-json
```diff -u pjson/2021-07-11T100203Z.json pjson/2021-07-12T100003Z.json```:
```
--- pjson/2021-07-11T100203Z.json	2021-07-11 10:02:03.682002246 +0000
+++ pjson/2021-07-12T100003Z.json	2021-07-12 10:00:03.763497358 +0000
@@ -15095,7 +15095,7 @@
"Datum_neu": 1621209600000,
"F\u00e4lle_Meldedatum": 77,
-        "Hosp_Meldedatum": 16,
@@ -15129,7 +15129,7 @@
"Datum_neu": 1621296000000,
"F\u00e4lle_Meldedatum": 114, …
```
=> New data set: 2021-07-12T100003Z

latest-json
```diff -u pjson/2021-07-12T100003Z.json pjson/2021-07-13T095703Z.json```:
```
--- pjson/2021-07-12T100003Z.json	2021-07-12 10:00:03.763497358 +0000
+++ pjson/2021-07-13T095703Z.json	2021-07-13 09:57:03.315544025 +0000
@@ -16861,7 +16861,7 @@
"Inzidenz": 4.13089550630411,
"Datum_neu": 1625702400000,
+        "F\u00e4lle_Meldedatum": 4,
"Inzidenz_RKI": 3.4,
@@ -16929,7 +16929,7 @@
"Inzidenz": 3.9512913538561,
"Datum_neu": 1625875200000,
+        "F\u00e4lle_Meldedatum": 10, …
```
=> New data set: 2021-07-13T095703Z

latest-json
```diff -u pjson/2021-07-13T095703Z.json pjson/2021-07-14T101603Z.json```:
```
--- pjson/2021-07-13T095703Z.json	2021-07-13 09:57:03.315544025 +0000
+++ pjson/2021-07-14T101603Z.json	2021-07-14 10:16:03.561421686 +0000
@@ -15921,7 +15921,7 @@
"Krh_I": null,
@@ -16555,7 +16555,7 @@
"Datum_neu": 1624924800000,
+        "F\u00e4lle_Meldedatum": 8, …
```
=> New data set: 2021-07-14T101603Z

latest-json
```diff -u pjson/2021-07-14T101603Z.json pjson/2021-07-15T100503Z.json```:
```
--- pjson/2021-07-14T101603Z.json	2021-07-14 10:16:03.561421686 +0000
+++ pjson/2021-07-15T100503Z.json	2021-07-15 10:05:03.395841462 +0000
@@ -16791,12 +16791,12 @@
"Zuwachs_Genesung": 10,
-        "Inzidenz": 3.1,
"Datum_neu": 1625529600000,
"F\u00e4lle_Meldedatum": 9,
-        "Inzidenz_RKI": 3.1,
@@ -16806,7 +16806,7 @@ …
```
=> New data set: 2021-07-15T100503Z

latest-json
```diff -u pjson/2021-07-15T100503Z.json pjson/2021-07-16T100903Z.json```:
```
--- pjson/2021-07-15T100503Z.json	2021-07-15 10:05:03.395841462 +0000
+++ pjson/2021-07-16T100903Z.json	2021-07-16 10:09:03.924247553 +0000
@@ -16771,7 +16771,7 @@
"Krh_I": null,
@@ -16859,12 +16859,12 @@
-        "Inzidenz": 4.1,
"Datum_neu": 1625702400000,
+ …
```
=> New data set: 2021-07-16T100903Z

latest-json
```diff -u pjson/2021-07-16T100903Z.json pjson/2021-07-17T100504Z.json```:
```
--- pjson/2021-07-16T100903Z.json	2021-07-16 10:09:03.924247553 +0000
+++ pjson/2021-07-17T100504Z.json	2021-07-17 10:05:04.933348278 +0000
@@ -16861,7 +16861,7 @@
"Datum_neu": 1625702400000,
@@ -16893,12 +16893,12 @@
"Zuwachs_Genesung": 13,
-        "Inzidenz": 3.4,
"Datum_neu": 1625788800000,
"F\u00e4lle_Meldedatum": 2, …
```
=> New data set: 2021-07-17T100504Z

latest-json
```diff -u pjson/2021-07-17T100504Z.json pjson/2021-07-18T101104Z.json```:
```
--- pjson/2021-07-17T100504Z.json	2021-07-17 10:05:04.933348278 +0000
+++ pjson/2021-07-18T101104Z.json	2021-07-18 10:11:04.242336202 +0000
@@ -16927,12 +16927,12 @@
"Zuwachs_Genesung": 4,
-        "Inzidenz": 4,
"Datum_neu": 1625875200000,
-        "Inzidenz_RKI": 3.6,
@@ -16942,7 +16942,7 @@ …
```
=> New data set: 2021-07-18T101104Z

latest-json
```diff -u pjson/2021-07-20T100504Z.json pjson/2021-07-21T100104Z.json```:
```
--- pjson/2021-07-20T100504Z.json	2021-07-20 10:05:04.145787747 +0000
+++ pjson/2021-07-21T100104Z.json	2021-07-21 10:01:04.799707262 +0000
@@ -13495,7 +13495,7 @@
"Datum_neu": 1617148800000,
-        "F\u00e4lle_Meldedatum": 105,
+        "F\u00e4lle_Meldedatum": 104,
@@ -14073,7 +14073,7 @@
"Datum_neu": 1618617600000,
-        "F\u00e4lle_Meldedatum": 81, …
```
=> New data set: 2021-07-21T100104Z

latest-json
```diff -u pjson/2021-07-21T100104Z.json pjson/2021-07-22T100304Z.json```:
```
--- pjson/2021-07-21T100104Z.json	2021-07-21 10:01:04.799707262 +0000
+++ pjson/2021-07-22T100304Z.json	2021-07-22 10:03:04.229732349 +0000
@@ -17000,7 +17000,7 @@
"F\u00e4lle_Meldedatum": 6,
-        "Inzidenz_RKI": 5,
@@ -17010,7 +17010,7 @@
-        "Inzi_SN_RKI": 2.2,
}
@@ -17029,12 +17029,12 @@ …
```
=> New data set: 2021-07-22T100304Z

latest-json
```diff -u pjson/2021-07-22T100304Z.json pjson/2021-07-23T100304Z.json```:
```
--- pjson/2021-07-22T100304Z.json	2021-07-22 10:03:04.229732349 +0000
+++ pjson/2021-07-23T100304Z.json	2021-07-23 10:03:04.387689444 +0000
@@ -17097,12 +17097,12 @@
"Zuwachs_Genesung": 5,
-        "Inzidenz": 7.5,
"Datum_neu": 1626307200000,
"F\u00e4lle_Meldedatum": 7,
-        "Inzidenz_RKI": 7.2,
@@ -17112,7 +17112,7 @@ …
```
=> New data set: 2021-07-23T100304Z

latest-json
```diff -u pjson/2021-07-23T100304Z.json pjson/2021-07-25T094504Z.json```:
```
--- pjson/2021-07-23T100304Z.json	2021-07-23 10:03:04.387689444 +0000
+++ pjson/2021-07-25T094504Z.json	2021-07-25 09:45:04.181258066 +0000
@@ -16861,7 +16861,7 @@
"Datum_neu": 1625702400000,
@@ -17031,7 +17031,7 @@
"Datum_neu": 1626134400000,
-        "F\u00e4lle_Meldedatum": 20,
+        "F\u00e4lle_Meldedatum": 21, …
```
=> New data set: 2021-07-25T094504Z

latest-json
```diff -u pjson/2021-07-26T100603Z.json pjson/2021-07-26T110703Z.json```:
```
--- pjson/2021-07-26T100603Z.json	2021-07-26 10:06:03.559196031 +0000
+++ pjson/2021-07-26T110703Z.json	2021-07-26 11:07:03.354396078 +0000
@@ -17459,7 +17459,7 @@
},
{
-        "Datum": "25.07.2021",
+        "Datum": "26.07.2021",
"Fallzahl": 30841,
"ObjectId": 507,
"Sterbefall": 1106,
@@ -17472,7 +17472,7 @@
"Zuwachs_Genesung": 1,
"Inzidenz": 11.4946657566723,
-        "Datum_neu": 1627171200000,
+        "Datum_neu": 1627257600000,
"F\u00e4lle_Meldedatum": 0,
"Zeitraum": "19.07.2021 - 25.07.2021",
```
If there are no …
=> New data set: 2021-07-26T110703Z

latest-json
```diff -u pjson/2021-07-26T110703Z.json pjson/2021-07-27T100404Z.json```:
```
--- pjson/2021-07-26T110703Z.json	2021-07-26 11:07:03.354396078 +0000
+++ pjson/2021-07-27T100404Z.json	2021-07-27 10:04:04.654257173 +0000
@@ -17165,12 +17165,12 @@
"Zuwachs_Genesung": 1,
-        "Inzidenz": 10.1,
"Datum_neu": 1626480000000,
"F\u00e4lle_Meldedatum": 9,
-        "Inzidenz_RKI": 8.8,
@@ -17180,7 +17180,7 @@ …
```
=> New data set: 2021-07-27T100404Z

latest-json
```diff -u pjson/2021-07-27T100404Z.json pjson/2021-07-28T104804Z.json```:
```
--- pjson/2021-07-27T100404Z.json	2021-07-27 10:04:04.654257173 +0000
+++ pjson/2021-07-28T104804Z.json	2021-07-28 10:48:04.327653501 +0000
@@ -16295,7 +16295,7 @@
"Krh_I": null,
@@ -17405,7 +17405,7 @@
"Inzidenz": 12.2130823664643,
"Datum_neu": 1627084800000, …
```
=> New data set: 2021-07-28T104804Z

latest-json
```diff -u pjson/2021-07-28T104804Z.json pjson/2021-07-29T102203Z.json```:
```
--- pjson/2021-07-28T104804Z.json	2021-07-28 10:48:04.327653501 +0000
+++ pjson/2021-07-29T102203Z.json	2021-07-29 10:22:03.920027609 +0000
@@ -17267,12 +17267,12 @@
"Zuwachs_Genesung": 3,
-        "Inzidenz": 10.4,
"Datum_neu": 1626739200000,
-        "Inzidenz_RKI": 10.2,
@@ -17282,7 +17282,7 @@ …
```
=> New data set: 2021-07-29T102203Z

latest-json
```diff -u pjson/2021-07-29T102203Z.json pjson/2021-07-30T102603Z.json```:
```
--- pjson/2021-07-29T102203Z.json	2021-07-29 10:22:03.920027609 +0000
+++ pjson/2021-07-30T102603Z.json	2021-07-30 10:26:03.605341135 +0000
@@ -4587,7 +4587,7 @@
"Datum_neu": 1594512000000,
-        "F\u00e4lle_Meldedatum": 1,
+        "F\u00e4lle_Meldedatum": 0,
@@ -8021,7 +8021,7 @@
"Datum_neu": 1603238400000,
+        "F\u00e4lle_Meldedatum": 73, …
```
=> New data set: 2021-07-30T102603Z

latest-json
```diff -u pjson/2021-07-30T102603Z.json pjson/2021-08-02T100203Z.json```:
```
--- pjson/2021-07-30T102603Z.json	2021-07-30 10:26:03.605341135 +0000
+++ pjson/2021-08-02T100203Z.json	2021-08-02 10:02:03.665588568 +0000
@@ -17369,12 +17369,12 @@
"Zuwachs_Genesung": 1,
-        "Inzidenz": 10.7762491468803,
"Datum_neu": 1626998400000,
"F\u00e4lle_Meldedatum": 22,
-        "Inzidenz_RKI": 10.2,
@@ -17384,7 +17384,7 @@ …
```
=> New data set: 2021-08-02T100203Z

latest-json
```diff -u pjson/2021-08-04T102003Z.json pjson/2021-08-05T100503Z.json```:
```
--- pjson/2021-08-04T102003Z.json	2021-08-04 10:20:03.322535835 +0000
+++ pjson/2021-08-05T100503Z.json	2021-08-05 10:05:04.094891022 +0000
@@ -17471,7 +17471,7 @@
"Zuwachs_Genesung": 1,
-        "Inzidenz": 11.4946657566723,
"Datum_neu": 1627257600000,
"F\u00e4lle_Meldedatum": 3,
@@ -17505,7 +17505,7 @@
"Zuwachs_Genesung": 11,
-        "Inzidenz": 11.4946657566723,
"Datum_neu": …
```
=> New data set: 2021-08-05T100503Z

latest-json
```diff -u pjson/2021-08-05T100503Z.json pjson/2021-08-06T100504Z.json```:
```
--- pjson/2021-08-05T100503Z.json	2021-08-05 10:05:04.094891022 +0000
+++ pjson/2021-08-06T100504Z.json	2021-08-06 10:05:04.237348749 +0000
@@ -17476,7 +17476,7 @@
"F\u00e4lle_Meldedatum": 3,
-        "Inzidenz_RKI": 10.8,
@@ -17486,7 +17486,7 @@
-        "Inzi_SN_RKI": 4.7,
}
@@ -17510,7 +17510,7 @@ …
```
=> New data set: 2021-08-06T100504Z

latest-json
```diff -u pjson/2021-08-06T100504Z.json pjson/2021-08-09T103004Z.json```:
```
--- pjson/2021-08-06T100504Z.json	2021-08-06 10:05:04.237348749 +0000
+++ pjson/2021-08-09T103004Z.json	2021-08-09 10:30:04.539352033 +0000
@@ -17133,7 +17133,7 @@
"Datum_neu": 1626393600000,
-        "F\u00e4lle_Meldedatum": 17,
+        "F\u00e4lle_Meldedatum": 16,
@@ -17303,7 +17303,7 @@
"Datum_neu": 1626825600000,
-        "F\u00e4lle_Meldedatum": 11,
+        "F\u00e4lle_Meldedatum": 10, …
```
=> New data set: 2021-08-09T103004Z

latest-json
```diff -u pjson/2021-08-10T100203Z.json pjson/2021-08-10T102004Z.json```:
```
--- pjson/2021-08-10T100203Z.json	2021-08-10 10:02:03.891630234 +0000
+++ pjson/2021-08-10T102004Z.json	2021-08-10 10:20:04.399601987 +0000
@@ -17976,7 +17976,7 @@
"Genesungsfall": 29745,
"Hospitalisierung": 2657,
-        "Zuwachs_Fallzahl": 23,
+        "Zuwachs_Fallzahl": 19,
"Zuwachs_Sterbefall": 0,
"Zuwachs_Krankenhauseinweisung": 1,
"Zuwachs_Genesung": 19,
@@ -17991,9 +17991,9 @@
"Krh_N_belegt": 102,
"Krh_I_belegt": 23,
-        "Fallzahl_aktiv_Zuwachs": 4,
+        "Fallzahl_aktiv_Zuwachs": 0,
"Krh_I": null,
- …
```
=> New data set: 2021-08-10T102004Z

latest-json
```diff -u pjson/2021-08-11T100504Z.json pjson/2021-08-12T100103Z.json```:
```
--- pjson/2021-08-11T100504Z.json	2021-08-11 10:05:04.160445436 +0000
+++ pjson/2021-08-12T100103Z.json	2021-08-12 10:01:03.706541805 +0000
@@ -17609,7 +17609,7 @@
"Datum_neu": 1627603200000,
+        "F\u00e4lle_Meldedatum": 9,
@@ -17621,7 +17621,7 @@
"Krh_I": null, …
```
=> New data set: 2021-08-12T100103Z

latest-json
```diff -u pjson/2021-08-13T100203Z.json pjson/2021-08-14T100103Z.json```:
```
--- pjson/2021-08-13T100203Z.json	2021-08-13 10:02:03.219963388 +0000
+++ pjson/2021-08-14T100103Z.json	2021-08-14 10:01:04.012678753 +0000
@@ -17845,12 +17845,12 @@
"Zuwachs_Genesung": 21,
-        "Inzidenz": 10.7762491468803,
"Datum_neu": 1628208000000,
"F\u00e4lle_Meldedatum": 9,
-        "Inzidenz_RKI": 8.4,
@@ -17860,7 +17860,7 @@ …
```
=> New data set: 2021-08-14T100103Z

latest-json
```diff -u pjson/2021-08-16T101004Z.json pjson/2021-08-16T112203Z.json```:
```
--- pjson/2021-08-16T101004Z.json	2021-08-16 10:10:04.419641265 +0000
+++ pjson/2021-08-16T112203Z.json	2021-08-16 11:22:03.267789089 +0000
@@ -18180,10 +18180,10 @@
"Genesungsfall": 29786,
"Hospitalisierung": 2662,
-        "Zuwachs_Fallzahl": 33,
+        "Zuwachs_Fallzahl": 14,
"Zuwachs_Sterbefall": 0,
"Zuwachs_Krankenhauseinweisung": 4,
-        "Zuwachs_Genesung": 16,
+        "Zuwachs_Genesung": 9,
"Inzidenz": 20.8340816839685,
"Datum_neu": 1629072000000,
@@ -18195,7 +18195,7 @@
"Krh_N_belegt": 101,
"Krh_I_belegt": 17, …
```
=> New data set: 2021-08-16T112203Z

latest-json
```diff -u pjson/2021-08-17T100603Z.json pjson/2021-08-18T100303Z.json```:
```
--- pjson/2021-08-17T100603Z.json	2021-08-17 10:06:03.757671927 +0000
+++ pjson/2021-08-18T100303Z.json	2021-08-18 10:03:03.999087243 +0000
@@ -17952,7 +17952,7 @@
"F\u00e4lle_Meldedatum": 14,
-        "Inzidenz_RKI": 9.2,
@@ -17962,7 +17962,7 @@
-        "Inzi_SN_RKI": 7.6,
}
@@ -18155,7 +18155,7 @@ …
```
=> New data set: 2021-08-18T100303Z

latest-json
```diff -u pjson/2021-08-23T101503Z.json pjson/2021-08-23T101903Z.json```:
```
--- pjson/2021-08-23T101503Z.json	2021-08-23 10:15:03.646554812 +0000
+++ pjson/2021-08-23T101903Z.json	2021-08-23 10:19:03.319367808 +0000
@@ -18355,7 +18355,7 @@
"Zuwachs_Genesung": null,
-        "Inzidenz": null,
+        "Inzidenz": 29.5,
"Datum_neu": 1629504000000,
"F\u00e4lle_Meldedatum": 11,
@@ -18389,7 +18389,7 @@
"Zuwachs_Genesung": null,
-        "Inzidenz": null,
+        "Inzidenz": 26.6,
"Datum_neu": 1629590400000, …
```
=> New data set: 2021-08-23T101903Z

latest-json
```diff -u pjson/2021-08-23T101903Z.json pjson/2021-08-24T100602Z.json```:
```
--- pjson/2021-08-23T101903Z.json	2021-08-23 10:19:03.319367808 +0000
+++ pjson/2021-08-24T100602Z.json	2021-08-24 10:06:02.675503199 +0000
@@ -18323,7 +18323,7 @@
"Inzidenz": 26.5814145623047,
"Datum_neu": 1629417600000,
-        "F\u00e4lle_Meldedatum": 23,
+        "F\u00e4lle_Meldedatum": 25,
"Inzidenz_RKI": 23.5,
@@ -18355,9 +18355,9 @@
"Zuwachs_Genesung": null,
-        "Inzidenz": 29.5,
+        "Inzidenz": 29.4550810014728,
"Datum_neu": 1629504000000, …
```
=> New data set: 2021-08-24T100602Z

latest-json
```diff -u pjson/2021-08-24T102603Z.json pjson/2021-08-25T100302Z.json```:
```
--- pjson/2021-08-24T102603Z.json	2021-08-24 10:26:03.139844398 +0000
+++ pjson/2021-08-25T100302Z.json	2021-08-25 10:03:02.926013705 +0000
@@ -18049,7 +18049,7 @@
-        "Inzidenz": 15.0867488056324,
"Datum_neu": 1628726400000,
"F\u00e4lle_Meldedatum": 31,
@@ -18289,7 +18289,7 @@
"Inzidenz": 26.7610187147527,
"Datum_neu": 1629331200000,
-        "F\u00e4lle_Meldedatum": 31,
+        "F\u00e4lle_Meldedatum": 32, …
```
=> New data set: 2021-08-25T100302Z

latest-json
```diff -u pjson/2021-08-27T101203Z.json pjson/2021-08-30T101103Z.json```:
```
--- pjson/2021-08-27T101203Z.json	2021-08-27 10:12:03.433939047 +0000
+++ pjson/2021-08-30T101103Z.json	2021-08-30 10:11:03.707802938 +0000
@@ -18189,7 +18189,7 @@
"Datum_neu": 1629072000000,
"F\u00e4lle_Meldedatum": 19,
@@ -18321,12 +18321,12 @@
"Zuwachs_Genesung": 8,
-        "Inzidenz": 26.5814145623047,
"Datum_neu": 1629417600000, …
```
=> New data set: 2021-08-30T101103Z

latest-json
```diff -u pjson/2021-08-31T101103Z.json pjson/2021-08-31T121903Z.json```:
```
--- pjson/2021-08-31T101103Z.json	2021-08-31 10:11:03.578470602 +0000
+++ pjson/2021-08-31T121903Z.json	2021-08-31 12:19:03.519205590 +0000
@@ -18683,7 +18683,7 @@
},
{
-        "Datum": "31.08.2022",
+        "Datum": "31.08.2021",
"Fallzahl": 31501,
"ObjectId": 543,
"Sterbefall": 1111,
@@ -18696,7 +18696,7 @@
"Zuwachs_Genesung": 31,
"Inzidenz": 40.051725995905,
-        "Datum_neu": 1661904000000,
+        "Datum_neu": 1630368000000,
"F\u00e4lle_Meldedatum": 8,
"Zeitraum": "24.08.2021 - 30.08.2021",
```
If there are no …
=> New data set: 2021-08-31T121903Z

latest-json
```diff -u pjson/2021-08-31T121903Z.json pjson/2021-09-01T101003Z.json```:
```
--- pjson/2021-08-31T121903Z.json	2021-08-31 12:19:03.519205590 +0000
+++ pjson/2021-09-01T101003Z.json	2021-09-01 10:10:03.974687735 +0000
@@ -18389,12 +18389,12 @@
"Zuwachs_Genesung": 2,
-        "Inzidenz": 26.5814145623047,
"Datum_neu": 1629590400000,
"F\u00e4lle_Meldedatum": 12,
-        "Inzidenz_RKI": 23.9,
@@ -18404,7 +18404,7 @@ …
```
=> New data set: 2021-09-01T101003Z

latest-json
```diff -u pjson/2021-09-01T101003Z.json pjson/2021-09-02T100203Z.json```:
```
--- pjson/2021-09-01T101003Z.json	2021-09-01 10:10:03.974687735 +0000
+++ pjson/2021-09-02T100203Z.json	2021-09-02 10:02:03.606574379 +0000
@@ -18323,7 +18323,7 @@
"Datum_neu": 1629417600000,
-        "F\u00e4lle_Meldedatum": 25,
+        "F\u00e4lle_Meldedatum": 26,
@@ -18425,7 +18425,7 @@
"Datum_neu": 1629676800000,
-        "F\u00e4lle_Meldedatum": 17,
+        "F\u00e4lle_Meldedatum": 18, …
```
=> New data set: 2021-09-02T100203Z

latest-json
```diff -u pjson/2021-09-02T100203Z.json pjson/2021-09-03T100603Z.json```:
```
--- pjson/2021-09-02T100203Z.json	2021-09-02 10:02:03.606574379 +0000
+++ pjson/2021-09-03T100603Z.json	2021-09-03 10:06:03.390685131 +0000
@@ -18561,7 +18561,7 @@
"Inzidenz": 37.178059556737,
"Datum_neu": 1630022400000,
-        "F\u00e4lle_Meldedatum": 28,
+        "F\u00e4lle_Meldedatum": 27,
"Inzidenz_RKI": 34.5,
@@ -18731,7 +18731,7 @@
"Inzidenz": 34.6636014224649,
"Datum_neu": 1630454400000,
+        "F\u00e4lle_Meldedatum": 37, …
```
=> New data set: 2021-09-03T100603Z

latest-json
```diff -u pjson/2021-09-06T101402Z.json pjson/2021-09-06T102002Z.json```:
```
--- pjson/2021-09-06T101402Z.json	2021-09-06 10:14:03.026974255 +0000
+++ pjson/2021-09-06T102002Z.json	2021-09-06 10:20:02.764282495 +0000
@@ -18591,7 +18591,7 @@
-        "Zuwachs_Genesung": null,
+        "Zuwachs_Genesung": 27,
"Inzidenz": 39,
"Datum_neu": 1630108800000,
@@ -18625,7 +18625,7 @@
-        "Zuwachs_Genesung": null,
+        "Zuwachs_Genesung": 1, …
```
=> New data set: 2021-09-06T102002Z

latest-json
```diff -u pjson/2021-09-07T100204Z.json pjson/2021-09-08T103704Z.json```:
```
--- pjson/2021-09-07T100204Z.json	2021-09-07 10:02:04.104176012 +0000
+++ pjson/2021-09-08T103704Z.json	2021-09-08 10:37:04.418175661 +0000
@@ -14515,7 +14515,7 @@
"Datum_neu": 1619740800000,
-        "F\u00e4lle_Meldedatum": 106,
+        "F\u00e4lle_Meldedatum": 105,
@@ -16285,7 +16285,7 @@
"Datum_neu": 1624233600000,
"F\u00e4lle_Meldedatum": 5, …
```
=> New data set: 2021-09-08T103704Z

latest-json
```diff -u pjson/2021-09-08T103704Z.json pjson/2021-09-09T100303Z.json```:
```
--- pjson/2021-09-08T103704Z.json	2021-09-08 10:37:04.418175661 +0000
+++ pjson/2021-09-09T100303Z.json	2021-09-09 10:03:03.804441771 +0000
@@ -15127,7 +15127,7 @@
"Datum_neu": 1621296000000,
-        "F\u00e4lle_Meldedatum": 114,
+        "F\u00e4lle_Meldedatum": 115,
@@ -18754,28 +18754,28 @@
"Datum": "02.09.2021",
"Fallzahl": 31606,
"ObjectId": 545,
-        "Sterbefall": null,
-        "Genesungsfall": null,
+        "Sterbefall": 1111,
+        "Genesungsfall": 30074, …
```
=> New data set: 2021-09-09T100303Z

latest-json
```diff -u pjson/2021-09-10T100804Z.json pjson/2021-09-13T102003Z.json```:
```
--- pjson/2021-09-10T100804Z.json	2021-09-10 10:08:04.178634227 +0000
+++ pjson/2021-09-13T102003Z.json	2021-09-13 10:20:04.072226678 +0000
@@ -10809,7 +10809,7 @@
"Datum_neu": 1610323200000,
-        "F\u00e4lle_Meldedatum": 180,
+        "F\u00e4lle_Meldedatum": 181,
@@ -18525,7 +18525,7 @@
"Zuwachs_Genesung": 32,
-        "Inzidenz": 35.9208304896009,
"Datum_neu": 1629936000000, …
```
=> New data set: 2021-09-13T102003Z

latest-json
```diff -u pjson/2021-09-13T102003Z.json pjson/2021-09-14T100702Z.json```:
```
--- pjson/2021-09-13T102003Z.json	2021-09-13 10:20:04.072226678 +0000
+++ pjson/2021-09-14T100702Z.json	2021-09-14 10:07:02.400451773 +0000
@@ -18530,7 +18530,7 @@
"F\u00e4lle_Meldedatum": 35,
-        "Inzidenz_RKI": 32.9,
@@ -18540,7 +18540,7 @@
-        "Inzi_SN_RKI": 17.9,
}
@@ -18564,7 +18564,7 @@ …
```
=> New data set: 2021-09-14T100702Z

latest-json
```diff -u pjson/2021-09-14T100702Z.json pjson/2021-09-15T103004Z.json```:
```
--- pjson/2021-09-14T100702Z.json	2021-09-14 10:07:02.400451773 +0000
+++ pjson/2021-09-15T103004Z.json	2021-09-15 10:30:04.328399745 +0000
@@ -18523,7 +18523,7 @@
-        "Zuwachs_Genesung": 32,
+        "Zuwachs_Genesung": 33,
"Datum_neu": 1629936000000,
@@ -18795,7 +18795,7 @@
-        "Zuwachs_Genesung": 23,
+        "Zuwachs_Genesung": 24, …
```
=> New data set: 2021-09-15T103004Z

latest-json
```diff -u pjson/2021-09-15T103004Z.json pjson/2021-09-16T100104Z.json```:
```
--- pjson/2021-09-15T103004Z.json	2021-09-15 10:30:04.328399745 +0000
+++ pjson/2021-09-16T100104Z.json	2021-09-16 10:01:04.292721001 +0000
@@ -18697,7 +18697,7 @@
"Datum_neu": 1630368000000,
+        "F\u00e4lle_Meldedatum": 39,
@@ -18901,7 +18901,7 @@
"Datum_neu": 1630886400000,
-        "F\u00e4lle_Meldedatum": 56,
+        "F\u00e4lle_Meldedatum": 57, …
```
=> New data set: 2021-09-16T100104Z

latest-json
```diff -u pjson/2021-09-16T100104Z.json pjson/2021-09-17T103004Z.json```:
```
--- pjson/2021-09-16T100104Z.json	2021-09-16 10:01:04.292721001 +0000
+++ pjson/2021-09-17T103004Z.json	2021-09-17 10:30:04.574927158 +0000
@@ -9857,7 +9857,7 @@
-        "F\u00e4lle_Meldedatum": 429,
+        "F\u00e4lle_Meldedatum": 430,
@@ -9959,7 +9959,7 @@
"Datum_neu": 1608163200000,
-        "F\u00e4lle_Meldedatum": 514,
+        "F\u00e4lle_Meldedatum": 513, …
```
=> New data set: 2021-09-17T103004Z

latest-json
```diff -u pjson/2021-09-17T103004Z.json pjson/2021-09-18T111004Z.json```:
```
--- pjson/2021-09-17T103004Z.json	2021-09-17 10:30:04.574927158 +0000
+++ pjson/2021-09-18T111004Z.json	2021-09-18 11:10:04.509340214 +0000
@@ -9857,7 +9857,7 @@
-        "F\u00e4lle_Meldedatum": 430,
+        "F\u00e4lle_Meldedatum": 429,
@@ -12883,7 +12883,7 @@
"Datum_neu": 1615593600000,
-        "F\u00e4lle_Meldedatum": 59,
+        "F\u00e4lle_Meldedatum": 58, …
```
=> New data set: 2021-09-18T111004Z

latest-json
```diff -u pjson/2021-09-18T111004Z.json pjson/2021-09-19T101304Z.json```:
```
--- pjson/2021-09-18T111004Z.json	2021-09-18 11:10:04.509340214 +0000
+++ pjson/2021-09-19T101304Z.json	2021-09-19 10:13:04.331145389 +0000
@@ -11183,7 +11183,7 @@
"Datum_neu": 1611273600000,
-        "F\u00e4lle_Meldedatum": 115,
+        "F\u00e4lle_Meldedatum": 116,
@@ -12849,7 +12849,7 @@
"Datum_neu": 1615507200000,
-        "F\u00e4lle_Meldedatum": 86,
+        "F\u00e4lle_Meldedatum": 87, …
```
=> New data set: 2021-09-19T101304Z

latest-json
```diff -u pjson/2021-09-19T101304Z.json pjson/2021-09-20T101704Z.json```:
```
--- pjson/2021-09-19T101304Z.json	2021-09-19 10:13:04.331145389 +0000
+++ pjson/2021-09-20T101704Z.json	2021-09-20 10:17:04.164084401 +0000
@@ -18935,7 +18935,7 @@
"Datum_neu": 1630972800000,
-        "F\u00e4lle_Meldedatum": 86,
+        "F\u00e4lle_Meldedatum": 85,
@@ -19003,7 +19003,7 @@
"Datum_neu": 1631145600000,
-        "F\u00e4lle_Meldedatum": 43,
+        "F\u00e4lle_Meldedatum": 44, …
```
=> New data set: 2021-09-20T101704Z

latest-json
```diff -u pjson/2021-09-20T101704Z.json pjson/2021-09-21T102303Z.json```:
```
--- pjson/2021-09-20T101704Z.json	2021-09-20 10:17:04.164084401 +0000
+++ pjson/2021-09-21T102303Z.json	2021-09-21 10:23:03.452658917 +0000
@@ -11183,7 +11183,7 @@
"Datum_neu": 1611273600000,
-        "F\u00e4lle_Meldedatum": 116,
+        "F\u00e4lle_Meldedatum": 115,
@@ -13393,7 +13393,7 @@
"Datum_neu": 1616889600000,
-        "F\u00e4lle_Meldedatum": 16, …
```
=> New data set: 2021-09-21T102303Z

latest-json
```diff -u pjson/2021-09-21T102303Z.json pjson/2021-09-22T100403Z.json```:
```
--- pjson/2021-09-21T102303Z.json	2021-09-21 10:23:03.452658917 +0000
+++ pjson/2021-09-22T100403Z.json	2021-09-22 10:04:03.320506546 +0000
@@ -19037,9 +19037,9 @@
"Datum_neu": 1631232000000,
-        "F\u00e4lle_Meldedatum": 40,
@@ -19071,7 +19071,7 @@
"Datum_neu": 1631318400000,
-        "F\u00e4lle_Meldedatum": 56,
+ …
```
=> New data set: 2021-09-22T100403Z

latest-json
```diff -u pjson/2021-09-22T100403Z.json pjson/2021-09-23T103602Z.json```:
```
--- pjson/2021-09-22T100403Z.json	2021-09-22 10:04:03.320506546 +0000
+++ pjson/2021-09-23T103602Z.json	2021-09-23 10:36:02.830826018 +0000
@@ -18665,7 +18665,7 @@
"Datum_neu": 1630281600000,
"F\u00e4lle_Meldedatum": 47,
@@ -19139,7 +19139,7 @@
"Datum_neu": 1631491200000,
-        "F\u00e4lle_Meldedatum": 59,
+        "F\u00e4lle_Meldedatum": 61, …
```
=> New data set: 2021-09-23T103602Z

latest-json
```diff -u pjson/2021-09-24T103203Z.json pjson/2021-09-24T103302Z.json```:
```
--- pjson/2021-09-24T103203Z.json	2021-09-24 10:32:03.223650657 +0000
+++ pjson/2021-09-24T103302Z.json	2021-09-24 10:33:02.923608946 +0000
@@ -19858,7 +19858,7 @@
"Inzi_SN_RKI": 37.9,
-        "H_Inzidenz": null
+        "H_Inzidenz": 1.5
}
},
{
@@ -19893,7 +19893,7 @@
"Inzi_SN_RKI": 36.6,
-        "H_Inzidenz": null
+        "H_Inzidenz": 1.28
}
},
{
@@ -19928,7 +19928,7 @@
"Inzi_SN_RKI": 31.7,
-        "H_Inzidenz": null
+        "H_Inzidenz": 1.23
} …
```
=> New data set: 2021-09-24T103302Z

latest-json
```diff -u pjson/2021-09-24T104803Z.json pjson/2021-09-25T103403Z.json```:
```
--- pjson/2021-09-24T104803Z.json	2021-09-24 10:48:03.571139579 +0000
+++ pjson/2021-09-25T103403Z.json	2021-09-25 10:34:03.760738002 +0000
@@ -13948,7 +13948,7 @@
"Datum_neu": 1615420800000,
-        "F\u00e4lle_Meldedatum": 92,
+        "F\u00e4lle_Meldedatum": 91,
@@ -20349,7 +20349,7 @@
"Datum_neu": 1630368000000,
+        "F\u00e4lle_Meldedatum": 37, …
```
=> New data set: 2021-09-25T103403Z

latest-json
```diff -u pjson/2021-09-25T103403Z.json pjson/2021-09-26T100203Z.json```:
```
--- pjson/2021-09-25T103403Z.json	2021-09-25 10:34:03.760738002 +0000
+++ pjson/2021-09-26T100203Z.json	2021-09-26 10:02:03.261854781 +0000
@@ -13393,7 +13393,7 @@
"Datum_neu": 1614124800000,
-        "F\u00e4lle_Meldedatum": 75,
+        "F\u00e4lle_Meldedatum": 76,
@@ -20756,7 +20756,7 @@
"Datum_neu": 1631318400000,
-        "F\u00e4lle_Meldedatum": 52,
+        "F\u00e4lle_Meldedatum": 50, …
```
=> New data set: 2021-09-26T100203Z

latest-json
```diff -u pjson/2021-09-26T100203Z.json pjson/2021-09-27T101503Z.json```:
```
--- pjson/2021-09-26T100203Z.json	2021-09-26 10:02:03.261854781 +0000
+++ pjson/2021-09-27T101503Z.json	2021-09-27 10:15:03.566373447 +0000
@@ -20904,7 +20904,7 @@
"Datum_neu": 1631664000000,
-        "F\u00e4lle_Meldedatum": 44,
+        "F\u00e4lle_Meldedatum": 43,
@@ -21015,7 +21015,7 @@
"Datum_neu": 1631923200000,
-        "F\u00e4lle_Meldedatum": 31,
+        "F\u00e4lle_Meldedatum": 30, …
```
=> New data set: 2021-09-27T101503Z

latest-json
```diff -u pjson/2021-09-27T195004Z.json pjson/2021-09-28T101903Z.json```:
```
--- pjson/2021-09-27T195004Z.json	2021-09-27 19:50:04.139579925 +0000
+++ pjson/2021-09-28T101903Z.json	2021-09-28 10:19:03.181492732 +0000
@@ -20386,7 +20386,7 @@
"Datum_neu": 1630454400000,
+        "F\u00e4lle_Meldedatum": 39,
@@ -20756,7 +20756,7 @@
"Datum_neu": 1631318400000,
-        "F\u00e4lle_Meldedatum": 50,
+        "F\u00e4lle_Meldedatum": 51, …
```
=> New data set: 2021-09-28T101903Z

latest-json
```diff -u pjson/2021-09-28T101903Z.json pjson/2021-09-29T104102Z.json```:
```
--- pjson/2021-09-28T101903Z.json	2021-09-28 10:19:03.181492732 +0000
+++ pjson/2021-09-29T104102Z.json	2021-09-29 10:41:02.994980673 +0000
@@ -20361,7 +20361,7 @@
"Krh_I": null,
@@ -20472,7 +20472,7 @@
"Krh_I": null,
@@ …
```
=> New data set: 2021-09-29T104102Z

latest-json
```diff -u pjson/2021-09-29T104102Z.json pjson/2021-09-29T164003Z.json```:
```
--- pjson/2021-09-29T104102Z.json	2021-09-29 10:41:02.994980673 +0000
+++ pjson/2021-09-29T164003Z.json	2021-09-29 16:40:03.122734380 +0000
@@ -21412,13 +21412,13 @@
"Fallzahl": 32859,
"ObjectId": 572,
"Sterbefall": 1119,
-        "Genesungsfall": 31041,
+        "Genesungsfall": 31083,
"Hospitalisierung": 2732,
"Zuwachs_Fallzahl": 134,
"Zuwachs_Sterbefall": 2,
"Zuwachs_Krankenhauseinweisung": 0,
-        "Zuwachs_Genesung": 1,
+        "Zuwachs_Genesung": 43,
"Inzidenz": 60.1673910700815,
"Datum_neu": 1632873600000,
@@ -21426,11 …
```
=> New data set: 2021-09-29T164003Z

latest-json
```diff -u pjson/2021-09-30T100902Z.json pjson/2021-09-30T101103Z.json```:
```
--- pjson/2021-09-30T100902Z.json	2021-09-30 10:09:03.032310936 +0000
+++ pjson/2021-09-30T101103Z.json	2021-09-30 10:11:03.096308789 +0000
@@ -21477,7 +21477,7 @@
"H_Inzidenz": 0.79,
"H_Zeitraum": "22.09.2021 - 28.09.2021",
-        "H_Datum": "44468.0"
+        "H_Datum": "29.09.2021"
}
}
]
```
If there are no anomalies, you are welcome to **merge** this symlink pointing to the new data set so that the new statistics will become publicly available on the [Grafana Dashboard](https://coronavirus-dresden.de/) within 5 minutes.
Thanks!
=> New data set: 2021-09-30T101103Z

latest-json
```diff -u pjson/2021-09-30T101103Z.json pjson/2021-10-01T104902Z.json```:
```
--- pjson/2021-09-30T101103Z.json	2021-09-30 10:11:03.096308789 +0000
+++ pjson/2021-10-01T104902Z.json	2021-10-01 10:49:02.983302760 +0000
@@ -21163,7 +21163,7 @@
"Datum_neu": 1632268800000,
-        "F\u00e4lle_Meldedatum": 62,
+        "F\u00e4lle_Meldedatum": 63,
@@ -21198,12 +21198,12 @@
"Zuwachs_Genesung": 43,
-        "Inzidenz": 52.4444125148173,
"Datum_neu": 1632355200000, …
```
=> New data set: 2021-10-01T104902Z

latest-json
```diff -u pjson/2021-10-01T104902Z.json pjson/2021-10-02T102303Z.json```:
```
--- pjson/2021-10-01T104902Z.json	2021-10-01 10:49:02.983302760 +0000
+++ pjson/2021-10-02T102303Z.json	2021-10-02 10:23:03.931132561 +0000
@@ -21089,7 +21089,7 @@
"Datum_neu": 1632096000000,
-        "F\u00e4lle_Meldedatum": 30,
+        "F\u00e4lle_Meldedatum": 31,
@@ -21235,12 +21235,12 @@
"Zuwachs_Genesung": 44,
-        "Inzidenz": 55.4976831064334,
"Datum_neu": 1632441600000,
- …
```
=> New data set: 2021-10-02T102303Z

latest-json
```diff -u pjson/2021-10-02T102303Z.json pjson/2021-10-03T095003Z.json```:
```
--- pjson/2021-10-02T102303Z.json	2021-10-02 10:23:03.931132561 +0000
+++ pjson/2021-10-03T095003Z.json	2021-10-03 09:50:03.594193163 +0000
@@ -21272,12 +21272,12 @@
"Zuwachs_Genesung": 49,
-        "Inzidenz": 51.9056000574733,
"Datum_neu": 1632528000000,
"F\u00e4lle_Meldedatum": 32,
-        "Inzidenz_RKI": 45.8,
@@ -21290,7 +21290,7 @@ …
```
=> New data set: 2021-10-03T095003Z

latest-json
```diff -u pjson/2021-10-03T095003Z.json pjson/2021-10-04T100505Z.json```:
```
--- pjson/2021-10-03T095003Z.json	2021-10-03 09:50:03.594193163 +0000
+++ pjson/2021-10-04T100505Z.json	2021-10-04 10:05:05.576093833 +0000
@@ -21309,12 +21309,12 @@
-        "Inzidenz": 53.8812457344014,
"Datum_neu": 1632614400000,
"F\u00e4lle_Meldedatum": 9,
-        "Inzidenz_RKI": 49.3,
@@ -21327,7 +21327,7 @@ …
```
=> New data set: 2021-10-04T100505Z

latest-json
```diff -u pjson/2021-10-04T100505Z.json pjson/2021-10-05T101803Z.json```:
```
--- pjson/2021-10-04T100505Z.json	2021-10-04 10:05:05.576093833 +0000
+++ pjson/2021-10-05T101803Z.json	2021-10-05 10:18:04.051678435 +0000
@@ -21346,12 +21346,12 @@
"Zuwachs_Genesung": 58,
-        "Inzidenz": 52.6240166672654,
"Datum_neu": 1632700800000,
"F\u00e4lle_Meldedatum": 53,
-        "Inzidenz_RKI": 51.2,
@@ -21364,7 +21364,7 @@ …
```
=> New data set: 2021-10-05T101803Z

latest-json
```diff -u pjson/2021-11-02T113303Z.json pjson/2021-11-03T112903Z.json```:
```
--- pjson/2021-11-02T113303Z.json	2021-11-02 11:33:03.482574978 +0000
+++ pjson/2021-11-03T112903Z.json	2021-11-03 11:29:04.091066760 +0000
@@ -22310,7 +22310,7 @@
"Datum_neu": 1634947200000,
-        "F\u00e4lle_Meldedatum": 50,
+        "F\u00e4lle_Meldedatum": 51,
@@ -22322,7 +22322,7 @@
"Krh_I": null, …
```
=> New data set: 2021-11-03T112903Z

latest-json
```diff -u pjson/2021-11-03T112903Z.json pjson/2021-11-04T110504Z.json```:
```
--- pjson/2021-11-03T112903Z.json	2021-11-03 11:29:04.091066760 +0000
+++ pjson/2021-11-04T110504Z.json	2021-11-04 11:05:04.733946166 +0000
@@ -22125,7 +22125,7 @@
"Datum_neu": 1634515200000,
-        "F\u00e4lle_Meldedatum": 112,
+        "F\u00e4lle_Meldedatum": 113,
@@ -22199,7 +22199,7 @@
"Datum_neu": 1634688000000,
-        "F\u00e4lle_Meldedatum": 283,
+        "F\u00e4lle_Meldedatum": 282, …
```
=> New data set: 2021-11-04T110504Z

latest-json
```diff -u pjson/2021-11-05T074803Z.json pjson/2021-11-05T110504Z.json```:
```
--- pjson/2021-11-05T074803Z.json	2021-11-05 07:48:04.099546158 +0000
+++ pjson/2021-11-05T110504Z.json	2021-11-05 11:05:04.685693095 +0000
@@ -21942,7 +21942,7 @@
"Datum_neu": 1634083200000,
"F\u00e4lle_Meldedatum": 119,
@@ -22014,7 +22014,7 @@
"Datum_neu": 1634256000000,
-        "F\u00e4lle_Meldedatum": 162,
+        "F\u00e4lle_Meldedatum": 163, …
```
=> New data set: 2021-11-05T110504Z

latest-json
```diff -u pjson/2021-11-05T110504Z.json pjson/2021-11-08T110803Z.json```:
```
--- pjson/2021-11-05T110504Z.json	2021-11-05 11:05:04.685693095 +0000
+++ pjson/2021-11-08T110803Z.json	2021-11-08 11:08:03.819735802 +0000
@@ -22162,7 +22162,7 @@
"Datum_neu": 1634601600000,
-        "F\u00e4lle_Meldedatum": 292,
+        "F\u00e4lle_Meldedatum": 293,
@@ -22236,7 +22236,7 @@
"Datum_neu": 1634774400000,
-        "F\u00e4lle_Meldedatum": 230,
+        "F\u00e4lle_Meldedatum": 229, …
```
=> New data set: 2021-11-08T110803Z

latest-json
```diff -u pjson/2021-11-08T110803Z.json pjson/2021-11-09T110704Z.json```:
```
--- pjson/2021-11-08T110803Z.json	2021-11-08 11:08:03.819735802 +0000
+++ pjson/2021-11-09T110704Z.json	2021-11-09 11:07:04.467581648 +0000
@@ -21866,7 +21866,7 @@
"Datum_neu": 1633910400000,
-        "F\u00e4lle_Meldedatum": 75,
+        "F\u00e4lle_Meldedatum": 76,
@@ -22384,7 +22384,7 @@
"Datum_neu": 1635120000000,
-        "F\u00e4lle_Meldedatum": 210,
+        "F\u00e4lle_Meldedatum": 211, …
```
=> New data set: 2021-11-09T110704Z

latest-json
```diff -u pjson/2021-11-09T110704Z.json pjson/2021-11-10T111302Z.json```:
```
--- pjson/2021-11-09T110704Z.json	2021-11-09 11:07:04.467581648 +0000
+++ pjson/2021-11-10T111302Z.json	2021-11-10 11:13:03.099182534 +0000
@@ -21866,7 +21866,7 @@
"Datum_neu": 1633910400000,
-        "F\u00e4lle_Meldedatum": 76,
+        "F\u00e4lle_Meldedatum": 77,
@@ -22384,7 +22384,7 @@
"Datum_neu": 1635120000000,
+        "F\u00e4lle_Meldedatum": 212, …
```
=> New data set: 2021-11-10T111302Z

latest-json
```diff -u pjson/2021-11-10T111302Z.json pjson/2021-11-11T110803Z.json```:
```
--- pjson/2021-11-10T111302Z.json	2021-11-10 11:13:03.099182534 +0000
+++ pjson/2021-11-11T110803Z.json	2021-11-11 11:08:03.131035811 +0000
@@ -12949,7 +12949,7 @@
"Datum_neu": 1613088000000,
-        "F\u00e4lle_Meldedatum": 72,
+        "F\u00e4lle_Meldedatum": 73,
@@ -14355,7 +14355,7 @@
"Datum_neu": 1616371200000,
-        "F\u00e4lle_Meldedatum": 131,
+        "F\u00e4lle_Meldedatum": 130, …
```
=> New data set: 2021-11-11T110803Z

latest-json
```diff -u pjson/2021-11-11T110803Z.json pjson/2021-11-12T112504Z.json```:
```
--- pjson/2021-11-11T110803Z.json	2021-11-11 11:08:03.131035811 +0000
+++ pjson/2021-11-12T112504Z.json	2021-11-12 11:25:04.510884488 +0000
@@ -22458,7 +22458,7 @@
"Datum_neu": 1635292800000,
-        "F\u00e4lle_Meldedatum": 353,
+        "F\u00e4lle_Meldedatum": 354,
@@ -22532,7 +22532,7 @@
"Datum_neu": 1635465600000,
-        "F\u00e4lle_Meldedatum": 221,
+        "F\u00e4lle_Meldedatum": 223, …
```
=> New data set: 2021-11-12T112504Z

latest-json
```diff -u pjson/2021-11-12T112504Z.json pjson/2021-11-15T111203Z.json```:
```
--- pjson/2021-11-12T112504Z.json	2021-11-12 11:25:04.510884488 +0000
+++ pjson/2021-11-15T111203Z.json	2021-11-15 11:12:03.297011155 +0000
@@ -9804,7 +9804,7 @@
-        "F\u00e4lle_Meldedatum": 117,
+        "F\u00e4lle_Meldedatum": 118,
@@ -10803,7 +10803,7 @@
-        "F\u00e4lle_Meldedatum": 360,
+        "F\u00e4lle_Meldedatum": 361,
"Hosp_Meldedatum": 36, …
```
=> New data set: 2021-11-15T111203Z

latest-json
```diff -u pjson/2021-11-15T111203Z.json pjson/2021-11-16T110603Z.json```:
```
--- pjson/2021-11-15T111203Z.json	2021-11-15 11:12:03.297011155 +0000
+++ pjson/2021-11-16T110603Z.json	2021-11-16 11:06:03.700068724 +0000
@@ -9027,7 +9027,7 @@
"Datum_neu": 1603929600000,
-        "F\u00e4lle_Meldedatum": 147,
+        "F\u00e4lle_Meldedatum": 148,
@@ -10729,7 +10729,7 @@
-        "F\u00e4lle_Meldedatum": 428,
+        "F\u00e4lle_Meldedatum": 429, …
```
=> New data set: 2021-11-16T110603Z

latest-json
```diff -u pjson/2021-11-16T110603Z.json pjson/2021-11-17T113104Z.json```:
```
--- pjson/2021-11-16T110603Z.json	2021-11-16 11:06:03.700068724 +0000
+++ pjson/2021-11-17T113104Z.json	2021-11-17 11:31:04.220147728 +0000
@@ -21977,7 +21977,7 @@
"Datum_neu": 1634169600000,
-        "F\u00e4lle_Meldedatum": 103,
+        "F\u00e4lle_Meldedatum": 104,
@@ -22199,7 +22199,7 @@
"Datum_neu": 1634688000000,
-        "F\u00e4lle_Meldedatum": 279,
+        "F\u00e4lle_Meldedatum": 280, …
```
=> New data set: 2021-11-17T113104Z

latest-json
```diff -u pjson/2021-11-18T105003Z.json pjson/2021-11-18T112203Z.json```:
```
--- pjson/2021-11-18T105003Z.json	2021-11-18 10:50:03.451958050 +0000
+++ pjson/2021-11-18T112203Z.json	2021-11-18 11:22:03.412495008 +0000
@@ -22800,7 +22800,7 @@
"Datum_neu": 1634688000000,
-        "F\u00e4lle_Meldedatum": 280,
+        "F\u00e4lle_Meldedatum": 281,
@@ -22838,7 +22838,7 @@
"Datum_neu": 1634774400000,
-        "F\u00e4lle_Meldedatum": 229,
+        "F\u00e4lle_Meldedatum": 230, …
```
=> New data set: 2021-11-18T112203Z

latest-json
```diff -u pjson/2021-11-18T112203Z.json pjson/2021-11-19T113203Z.json```:
```
--- pjson/2021-11-18T112203Z.json	2021-11-18 11:22:03.412495008 +0000
+++ pjson/2021-11-19T113203Z.json	2021-11-19 11:32:03.883691873 +0000
@@ -23104,7 +23104,7 @@
"Datum_neu": 1635379200000,
-        "F\u00e4lle_Meldedatum": 310,
+        "F\u00e4lle_Meldedatum": 311,
@@ -23332,7 +23332,7 @@
"Datum_neu": 1635897600000,
-        "F\u00e4lle_Meldedatum": 555,
+        "F\u00e4lle_Meldedatum": 558, …
```
=> New data set: 2021-11-19T113203Z

latest-json
```diff -u pjson/2021-11-19T113203Z.json pjson/2021-11-22T113103Z.json```:
```
--- pjson/2021-11-19T113203Z.json	2021-11-19 11:32:03.883691873 +0000
+++ pjson/2021-11-22T113103Z.json	2021-11-22 11:31:04.034493335 +0000
@@ -10982,7 +10982,7 @@
"Datum_neu": 1607817600000,
-        "F\u00e4lle_Meldedatum": 121,
+        "F\u00e4lle_Meldedatum": 122,
@@ -11020,7 +11020,7 @@
-        "F\u00e4lle_Meldedatum": 429,
+        "F\u00e4lle_Meldedatum": 428, …
```
=> New data set: 2021-11-22T113103Z

latest-json
```diff -u pjson/2021-11-22T113103Z.json pjson/2021-11-23T110403Z.json```:
```
--- pjson/2021-11-22T113103Z.json	2021-11-22 11:31:04.034493335 +0000
+++ pjson/2021-11-23T110403Z.json	2021-11-23 11:04:03.425338567 +0000
@@ -18240,7 +18240,7 @@
"Datum_neu": 1624320000000,
-        "F\u00e4lle_Meldedatum": 10,
+        "F\u00e4lle_Meldedatum": 12,
@@ -21280,7 +21280,7 @@
"Datum_neu": 1631232000000, …
```
=> New data set: 2021-11-23T110403Z

latest-json
```diff -u pjson/2021-11-23T112904Z.json pjson/2021-11-24T113103Z.json```:
```
--- pjson/2021-11-23T112904Z.json	2021-11-23 11:29:05.437731298 +0000
+++ pjson/2021-11-24T113103Z.json	2021-11-24 11:31:04.007096839 +0000
@@ -9804,7 +9804,7 @@
"Datum_neu": 1605139200000,
-        "F\u00e4lle_Meldedatum": 197,
+        "F\u00e4lle_Meldedatum": 198,
@@ -11058,7 +11058,7 @@
"Datum_neu": 1607990400000,
-        "F\u00e4lle_Meldedatum": 420,
+        "F\u00e4lle_Meldedatum": 421, …
```
=> New data set: 2021-11-24T113103Z

latest-json
```diff -u pjson/2021-11-24T113103Z.json pjson/2021-11-24T121003Z.json```:
```
--- pjson/2021-11-24T113103Z.json	2021-11-24 11:31:04.007096839 +0000
+++ pjson/2021-11-24T121003Z.json	2021-11-24 12:10:03.976234927 +0000
@@ -24116,7 +24116,7 @@
},
{
-        "Datum": "24.11.2022",
+        "Datum": "24.11.2021",
"Fallzahl": 53314,
"ObjectId": 628,
"Sterbefall": 1209,
@@ -24129,7 +24129,7 @@
"Zuwachs_Genesung": 932,
"Inzidenz": 664.894572362513,
-        "Datum_neu": 1669248000000,
+        "Datum_neu": 1637712000000,
"F\u00e4lle_Meldedatum": 219,
"Zeitraum": "17.11.2021 - 23.11.2021",
@@ -24149,7 …
```
=> New data set: 2021-11-24T121003Z

latest-json
```diff -u pjson/2021-11-25T110604Z.json pjson/2021-11-25T112003Z.json```:
```
--- pjson/2021-11-25T110604Z.json	2021-11-25 11:06:04.799635407 +0000
+++ pjson/2021-11-25T112003Z.json	2021-11-25 11:20:03.859806104 +0000
@@ -24116,12 +24116,50 @@
},
{
+        "Datum": "24.11.2021",
+        "Fallzahl": 53314,
+        "ObjectId": 628,
+        "Sterbefall": null,
+        "Genesungsfall": null,
+        "Anzeige_Indikator": null,
+        "Hospitalisierung": null,
+        "Zuwachs_Fallzahl": null,
+        "Zuwachs_Sterbefall": null,
+        "Zuwachs_Krankenhauseinweisung": null,
+        "Zuwachs_Genesung": 932,
+        "BelegteBetten": …
```
=> New data set: 2021-11-25T112003Z

latest-json
```diff -u pjson/2021-11-25T112003Z.json pjson/2021-11-26T121503Z.json```:
```
--- pjson/2021-11-25T112003Z.json	2021-11-25 11:20:03.859806104 +0000
+++ pjson/2021-11-26T121503Z.json	2021-11-26 12:15:04.113737508 +0000
@@ -9804,7 +9804,7 @@
"Datum_neu": 1605139200000,
+        "F\u00e4lle_Meldedatum": 197,
@@ -9956,7 +9956,7 @@
-        "F\u00e4lle_Meldedatum": 224,
+        "F\u00e4lle_Meldedatum": 223, …
```
=> New data set: 2021-11-26T121503Z

latest-json
```diff -u pjson/2021-11-26T121503Z.json pjson/2021-11-29T110904Z.json```:
```
--- pjson/2021-11-26T121503Z.json	2021-11-26 12:15:04.113737508 +0000
+++ pjson/2021-11-29T110904Z.json	2021-11-29 11:09:04.517968463 +0000
@@ -9994,7 +9994,7 @@
-        "F\u00e4lle_Meldedatum": 234,
+        "F\u00e4lle_Meldedatum": 235,
@@ -10298,7 +10298,7 @@
-        "F\u00e4lle_Meldedatum": 273,
+        "F\u00e4lle_Meldedatum": 274, …
```
=> New data set: 2021-11-29T110904Z

latest-json
```diff -u pjson/2021-11-29T110904Z.json pjson/2021-11-30T111004Z.json```:
```
--- pjson/2021-11-29T110904Z.json	2021-11-29 11:09:04.517968463 +0000
+++ pjson/2021-11-30T111004Z.json	2021-11-30 11:10:04.751709753 +0000
@@ -9994,7 +9994,7 @@
-        "F\u00e4lle_Meldedatum": 235,
+        "F\u00e4lle_Meldedatum": 236,
@@ -10298,7 +10298,7 @@
-        "F\u00e4lle_Meldedatum": 274,
+        "F\u00e4lle_Meldedatum": 275, …
```
=> New data set: 2021-11-30T111004Z

latest-json
```diff -u pjson/2021-11-30T111004Z.json pjson/2021-12-01T112304Z.json```:
```
--- pjson/2021-11-30T111004Z.json	2021-11-30 11:10:04.751709753 +0000
+++ pjson/2021-12-01T112304Z.json	2021-12-01 11:23:04.260395274 +0000
@@ -10374,7 +10374,7 @@
"Datum_neu": 1606435200000,
-        "F\u00e4lle_Meldedatum": 231,
+        "F\u00e4lle_Meldedatum": 230,
@@ -10754,7 +10754,7 @@
-        "F\u00e4lle_Meldedatum": 384,
+        "F\u00e4lle_Meldedatum": 385, …
```
=> New data set: 2021-12-01T112304Z

latest-json
```diff -u pjson/2021-12-02T083904Z.json pjson/2021-12-02T111404Z.json```:
```
--- pjson/2021-12-02T083904Z.json	2021-12-02 08:39:04.574980824 +0000
+++ pjson/2021-12-02T111404Z.json	2021-12-02 11:14:04.229150396 +0000
@@ -7334,7 +7334,7 @@
"Datum_neu": 1599523200000,
+        "F\u00e4lle_Meldedatum": 8,
@@ -20862,7 +20862,7 @@
"Datum_neu": 1630281600000,
-        "F\u00e4lle_Meldedatum": 46, …
```
=> New data set: 2021-12-02T111404Z

latest-json
```diff -u pjson/2021-12-02T111404Z.json pjson/2021-12-03T111304Z.json```:
```
--- pjson/2021-12-02T111404Z.json	2021-12-02 11:14:04.229150396 +0000
+++ pjson/2021-12-03T111304Z.json	2021-12-03 11:13:04.561832032 +0000
@@ -10526,7 +10526,7 @@
-        "F\u00e4lle_Meldedatum": 338,
+        "F\u00e4lle_Meldedatum": 339,
@@ -11970,7 +11970,7 @@
"Datum_neu": 1610064000000,
-        "F\u00e4lle_Meldedatum": 217,
+        "F\u00e4lle_Meldedatum": 218, …
```
=> New data set: 2021-12-03T111304Z

latest-json
```diff -u pjson/2021-12-03T111304Z.json pjson/2021-12-06T111803Z.json```:
```
--- pjson/2021-12-03T111304Z.json	2021-12-03 11:13:04.561832032 +0000
+++ pjson/2021-12-06T111803Z.json	2021-12-06 11:18:03.980253409 +0000
@@ -22268,7 +22268,7 @@
"Datum_neu": 1633478400000,
-        "F\u00e4lle_Meldedatum": 88,
@@ -22990,7 +22990,7 @@
"Datum_neu": 1635120000000,
-        "F\u00e4lle_Meldedatum": 213,
+        "F\u00e4lle_Meldedatum": 214, …
```
=> New data set: 2021-12-06T111803Z

latest-json
```diff -u pjson/2021-12-06T125604Z.json pjson/2021-12-07T124104Z.json```:
```
--- pjson/2021-12-06T125604Z.json	2021-12-06 12:56:04.125110474 +0000
+++ pjson/2021-12-07T124104Z.json	2021-12-07 12:41:04.200865047 +0000
@@ -22724,7 +22724,7 @@
"Datum_neu": 1634515200000,
-        "F\u00e4lle_Meldedatum": 116,
+        "F\u00e4lle_Meldedatum": 117,
@@ -23332,7 +23332,7 @@
"Datum_neu": 1635897600000,
-        "F\u00e4lle_Meldedatum": 554,
+        "F\u00e4lle_Meldedatum": 555, …
```
=> New data set: 2021-12-07T124104Z

latest-json
```diff -u pjson/2021-12-07T124104Z.json pjson/2021-12-08T110203Z.json```:
```
--- pjson/2021-12-07T124104Z.json	2021-12-07 12:41:04.200865047 +0000
+++ pjson/2021-12-08T110203Z.json	2021-12-08 11:02:03.937861506 +0000
@@ -23370,7 +23370,7 @@
"Datum_neu": 1635984000000,
-        "F\u00e4lle_Meldedatum": 683,
+        "F\u00e4lle_Meldedatum": 684,
@@ -23522,7 +23522,7 @@
"Datum_neu": 1636329600000,
-        "F\u00e4lle_Meldedatum": 710,
+        "F\u00e4lle_Meldedatum": 712, …
```
=> New data set: 2021-12-08T110203Z

latest-json
```diff -u pjson/2021-12-08T110203Z.json pjson/2021-12-08T111003Z.json```:
```
--- pjson/2021-12-08T110203Z.json	2021-12-08 11:02:03.937861506 +0000
+++ pjson/2021-12-08T111003Z.json	2021-12-08 11:10:04.194006919 +0000
@@ -24611,7 +24611,7 @@
{
"Datum": "07.12.2021",
-        "Fallzahl": 69843,
+        "Fallzahl": 68691,
"ObjectId": 641,
"Sterbefall": 1291,
"Genesungsfall": 55612,
@@ -24628,7 +24628,7 @@
"Inzidenz_RKI": 798.4,
-        "Fallzahl_aktiv": 12940,
+        "Fallzahl_aktiv": 11788,
"Krh_N_belegt": 2111,
"Krh_I_belegt": 601,
@@ -24655,7 +24655,7 @@
"Genesungsfall": 56776, …
```
=> New data set: 2021-12-08T111003Z

latest-json
```diff -u pjson/2021-12-08T111003Z.json pjson/2021-12-09T110603Z.json```:
```
--- pjson/2021-12-08T111003Z.json	2021-12-08 11:10:04.194006919 +0000
+++ pjson/2021-12-09T110603Z.json	2021-12-09 11:06:04.127322100 +0000
@@ -23142,7 +23142,7 @@
"Datum_neu": 1635465600000,
-        "F\u00e4lle_Meldedatum": 227,
+        "F\u00e4lle_Meldedatum": 228,
@@ -23180,7 +23180,7 @@
"Datum_neu": 1635552000000,
-        "F\u00e4lle_Meldedatum": 292,
+        "F\u00e4lle_Meldedatum": 291, …
```
=> New data set: 2021-12-09T110603Z

latest-json
```diff -u pjson/2021-12-10T113204Z.json pjson/2021-12-10T143604Z.json```:
```
--- pjson/2021-12-10T113204Z.json	2021-12-10 11:32:04.167792146 +0000
+++ pjson/2021-12-10T143604Z.json	2021-12-10 14:36:04.194825729 +0000
@@ -24432,7 +24432,7 @@
"Zuwachs_Genesung": 1039,
-        "Inzidenz": 1214.48327885341,
"Datum_neu": 1638403200000,
"F\u00e4lle_Meldedatum": 881,
@@ -24477,7 +24477,7 @@
"Inzidenz_RKI": 1005.5,
-        "Krh_N_belegt": 2074,
+        "Krh_N_belegt": 2059,
"Krh_I_belegt": 597,
"Krh_I_frei": …
```
=> New data set: 2021-12-10T143604Z

latest-json
```diff -u pjson/2021-12-10T143903Z.json pjson/2021-12-13T113104Z.json```:
```
--- pjson/2021-12-10T143903Z.json	2021-12-10 14:39:03.222704590 +0000
+++ pjson/2021-12-13T113104Z.json	2021-12-13 11:31:04.454036671 +0000
@@ -19836,7 +19836,7 @@
"Datum_neu": 1627948800000,
@@ -22074,7 +22074,7 @@
-        "Zuwachs_Genesung": 50,
+        "Zuwachs_Genesung": 76,
"Inzidenz": …
```
=> New data set: 2021-12-13T113104Z

latest-json
```diff -u pjson/2021-12-13T143603Z.json pjson/2021-12-14T112204Z.json```:
```
--- pjson/2021-12-13T143603Z.json	2021-12-13 14:36:03.640362691 +0000
+++ pjson/2021-12-14T112204Z.json	2021-12-14 11:22:04.184931385 +0000
@@ -22042,7 +22042,7 @@
"Datum_neu": 1632960000000,
"F\u00e4lle_Meldedatum": 78,
@@ -22346,7 +22346,7 @@
"Datum_neu": 1633651200000,
"F\u00e4lle_Meldedatum": 79, …
```
=> New data set: 2021-12-14T112204Z

latest-json
```diff -u pjson/2021-12-14T112204Z.json pjson/2021-12-15T111904Z.json```:
```
--- pjson/2021-12-14T112204Z.json	2021-12-14 11:22:04.184931385 +0000
+++ pjson/2021-12-15T111904Z.json	2021-12-15 11:19:04.615570292 +0000
@@ -21016,7 +21016,7 @@
"Datum_neu": 1630627200000,
"F\u00e4lle_Meldedatum": 24,
@@ -22080,7 +22080,7 @@
"Datum_neu": 1633046400000,
"F\u00e4lle_Meldedatum": 76, …
```
=> New data set: 2021-12-15T111904Z

latest-json
```diff -u pjson/2021-12-15T111904Z.json pjson/2021-12-16T112004Z.json```:
```
--- pjson/2021-12-15T111904Z.json	2021-12-15 11:19:04.615570292 +0000
+++ pjson/2021-12-16T112004Z.json	2021-12-16 11:20:05.091386993 +0000
@@ -23294,7 +23294,7 @@
"Datum_neu": 1635811200000,
-        "F\u00e4lle_Meldedatum": 691,
+        "F\u00e4lle_Meldedatum": 689,
@@ -23332,7 +23332,7 @@
"Datum_neu": 1635897600000,
-        "F\u00e4lle_Meldedatum": 556,
+        "F\u00e4lle_Meldedatum": 557, …
```
=> New data set: 2021-12-16T112004Z

latest-json
```diff -u pjson/2021-12-17T113803Z.json pjson/2021-12-20T111503Z.json```:
```
--- pjson/2021-12-17T113803Z.json	2021-12-17 11:38:03.281894728 +0000
+++ pjson/2021-12-20T111503Z.json	2021-12-20 11:15:03.948421695 +0000
@@ -10868,7 +10868,7 @@
-        "F\u00e4lle_Meldedatum": 462,
+        "F\u00e4lle_Meldedatum": 463,
@@ -11172,7 +11172,7 @@
-        "F\u00e4lle_Meldedatum": 445,
+        "F\u00e4lle_Meldedatum": 446, …
```
=> New data set: 2021-12-20T111503Z

latest-json
```diff -u pjson/2021-12-20T111503Z.json pjson/2021-12-21T111804Z.json```:
```
--- pjson/2021-12-20T111503Z.json	2021-12-20 11:15:03.948421695 +0000
+++ pjson/2021-12-21T111804Z.json	2021-12-21 11:18:04.255907746 +0000
@@ -12768,7 +12768,7 @@
"Datum_neu": 1611878400000,
-        "F\u00e4lle_Meldedatum": 68,
+        "F\u00e4lle_Meldedatum": 69,
@@ -22116,7 +22116,7 @@
"Datum_neu": 1633132800000,
-        "F\u00e4lle_Meldedatum": 48,
+        "F\u00e4lle_Meldedatum": 47, …
```
=> New data set: 2021-12-21T111804Z

latest-json
```diff -u pjson/2021-12-21T111804Z.json pjson/2021-12-22T111303Z.json```:
```
--- pjson/2021-12-21T111804Z.json	2021-12-21 11:18:04.255907746 +0000
+++ pjson/2021-12-22T111303Z.json	2021-12-22 11:13:04.068036184 +0000
@@ -13606,7 +13606,7 @@
"Datum_neu": 1613779200000,
"F\u00e4lle_Meldedatum": 21,
@@ -15240,7 +15240,7 @@
"Datum_neu": 1617494400000,
"F\u00e4lle_Meldedatum": 15, …
```
=> New data set: 2021-12-22T111303Z

latest-json
```diff -u pjson/2021-12-22T111303Z.json pjson/2021-12-23T112503Z.json```:
```
--- pjson/2021-12-22T111303Z.json	2021-12-22 11:13:04.068036184 +0000
+++ pjson/2021-12-23T112503Z.json	2021-12-23 11:25:04.115089770 +0000
@@ -23144,7 +23144,7 @@
"Datum_neu": 1635465600000,
"F\u00e4lle_Meldedatum": 228,
@@ -23560,7 +23560,7 @@
"Datum_neu": 1636416000000,
-        "F\u00e4lle_Meldedatum": 1239,
+        "F\u00e4lle_Meldedatum": 1240, …
```
=> New data set: 2021-12-23T112503Z

latest-json
```diff -u pjson/2021-12-27T121503Z.json pjson/2021-12-28T110103Z.json```:
```
--- pjson/2021-12-27T121503Z.json	2021-12-27 12:15:03.784961134 +0000
+++ pjson/2021-12-28T110103Z.json	2021-12-28 11:01:03.553297200 +0000
@@ -10602,7 +10602,7 @@
-        "F\u00e4lle_Meldedatum": 300,
+        "F\u00e4lle_Meldedatum": 301,
@@ -13528,7 +13528,7 @@
"Datum_neu": 1613606400000,
-        "F\u00e4lle_Meldedatum": 48,
+        "F\u00e4lle_Meldedatum": 49, …
```
=> New data set: 2021-12-28T110103Z

latest-json
```diff -u pjson/2021-12-28T110103Z.json pjson/2021-12-29T113103Z.json```:
```
--- pjson/2021-12-28T110103Z.json	2021-12-28 11:01:03.553297200 +0000
+++ pjson/2021-12-29T113103Z.json	2021-12-29 11:31:03.642155186 +0000
@@ -10602,7 +10602,7 @@
-        "F\u00e4lle_Meldedatum": 301,
+        "F\u00e4lle_Meldedatum": 300,
@@ -10868,7 +10868,7 @@
-        "F\u00e4lle_Meldedatum": 463,
+        "F\u00e4lle_Meldedatum": 462, …
```
=> New data set: 2021-12-29T113103Z

latest-json
```diff -u pjson/2021-12-29T113103Z.json pjson/2021-12-30T110503Z.json```:
```
--- pjson/2021-12-29T113103Z.json	2021-12-29 11:31:03.642155186 +0000
+++ pjson/2021-12-30T110503Z.json	2021-12-30 11:05:04.103201654 +0000
@@ -23332,7 +23332,7 @@
"Datum_neu": 1635897600000,
-        "F\u00e4lle_Meldedatum": 561,
+        "F\u00e4lle_Meldedatum": 562,
@@ -23788,7 +23788,7 @@
"Datum_neu": 1636934400000,
-        "F\u00e4lle_Meldedatum": 1144,
+        "F\u00e4lle_Meldedatum": 1145,
"Hosp_Meldedatum": 30, …
```
=> New data set: 2021-12-30T110503Z

latest-json
```diff -u pjson/2021-12-30T110503Z.json pjson/2022-01-03T113403Z.json```:
```
--- pjson/2021-12-30T110503Z.json	2021-12-30 11:05:04.103201654 +0000
+++ pjson/2022-01-03T113403Z.json	2022-01-03 11:34:03.941776547 +0000
@@ -12616,7 +12616,7 @@
"Datum_neu": 1611532800000,
-        "F\u00e4lle_Meldedatum": 117,
+        "F\u00e4lle_Meldedatum": 118,
@@ -12692,7 +12692,7 @@
"Datum_neu": 1611705600000,
+        "F\u00e4lle_Meldedatum": 150, …
```
=> New data set: 2022-01-03T113403Z

latest-json
```diff -u pjson/2022-01-03T113403Z.json pjson/2022-01-04T110803Z.json```:
```
--- pjson/2022-01-03T113403Z.json	2022-01-03 11:34:03.941776547 +0000
+++ pjson/2022-01-04T110803Z.json	2022-01-04 11:08:04.100260250 +0000
@@ -23294,7 +23294,7 @@
"Datum_neu": 1635811200000,
-        "F\u00e4lle_Meldedatum": 691,
+        "F\u00e4lle_Meldedatum": 692,
@@ -23408,7 +23408,7 @@
"Datum_neu": 1636070400000,
-        "F\u00e4lle_Meldedatum": 543,
+        "F\u00e4lle_Meldedatum": 542, …
```
=> New data set: 2022-01-04T110803Z

latest-json
```diff -u pjson/2022-01-04T110803Z.json pjson/2022-01-05T110905Z.json```:
```
--- pjson/2022-01-04T110803Z.json	2022-01-04 11:08:04.100260250 +0000
+++ pjson/2022-01-05T110905Z.json	2022-01-05 11:09:05.767704298 +0000
@@ -10642,7 +10642,7 @@
"Datum_neu": 1607040000000,
"F\u00e4lle_Meldedatum": 226,
@@ -11820,7 +11820,7 @@
"Datum_neu": 1609718400000,
"F\u00e4lle_Meldedatum": 239,
-        "Hosp_Meldedatum": 25,
+        "Hosp_Meldedatum": 26, …
```
=> New data set: 2022-01-05T110905Z

latest-json
```diff -u pjson/2022-01-05T110905Z.json pjson/2022-01-06T112406Z.json```:
```
--- pjson/2022-01-05T110905Z.json	2022-01-05 11:09:05.767704298 +0000
+++ pjson/2022-01-06T112406Z.json	2022-01-06 11:24:06.543152973 +0000
@@ -8398,7 +8398,7 @@
@@ -9956,7 +9956,7 @@
-        "F\u00e4lle_Meldedatum": 223,
+        "F\u00e4lle_Meldedatum": 224, …
```
=> New data set: 2022-01-06T112406Z

latest-json
```diff -u pjson/2022-01-06T112406Z.json pjson/2022-01-07T111503Z.json```:
```
--- pjson/2022-01-06T112406Z.json	2022-01-06 11:24:06.543152973 +0000
+++ pjson/2022-01-07T111503Z.json	2022-01-07 11:15:03.984140281 +0000
@@ -12236,7 +12236,7 @@
"Datum_neu": 1610668800000,
-        "F\u00e4lle_Meldedatum": 145,
+        "F\u00e4lle_Meldedatum": 147,
@@ -19684,7 +19684,7 @@
"Datum_neu": 1627603200000,
+        "F\u00e4lle_Meldedatum": 10, …
```
=> New data set: 2022-01-07T111503Z

latest-json
```diff -u pjson/2022-01-07T111503Z.json pjson/2022-01-10T111804Z.json```:
```
--- pjson/2022-01-07T111503Z.json	2022-01-07 11:15:03.984140281 +0000
+++ pjson/2022-01-10T111804Z.json	2022-01-10 11:18:04.386176087 +0000
@@ -11362,7 +11362,7 @@
-        "F\u00e4lle_Meldedatum": 446,
+        "F\u00e4lle_Meldedatum": 445,
@@ -11932,9 +11932,9 @@
-        "F\u00e4lle_Meldedatum": 265,
+        "F\u00e4lle_Meldedatum": 266,
- …
```
=> New data set: 2022-01-10T111804Z

latest-json
```diff -u pjson/2022-01-10T111804Z.json pjson/2022-01-11T111903Z.json```:
```
--- pjson/2022-01-10T111804Z.json	2022-01-10 11:18:04.386176087 +0000
+++ pjson/2022-01-11T111903Z.json	2022-01-11 11:19:03.949578371 +0000
@@ -8246,7 +8246,7 @@
"Datum_neu": 1601596800000,
+        "F\u00e4lle_Meldedatum": 13,
@@ -8398,7 +8398,7 @@ …
```
=> New data set: 2022-01-11T111903Z

latest-json
```diff -u pjson/2022-01-11T111903Z.json pjson/2022-01-12T112303Z.json```:
```
--- pjson/2022-01-11T111903Z.json	2022-01-11 11:19:03.949578371 +0000
+++ pjson/2022-01-12T112303Z.json	2022-01-12 11:23:03.725864657 +0000
@@ -10652,7 +10652,7 @@
"Krh_I": null,
-        "SterbeF_Sterbedatum": 10,
+        "SterbeF_Sterbedatum": 11,
@@ -11934,7 +11934,7 @@
"F\u00e4lle_Meldedatum": 265,
-        "Hosp_Meldedatum": 25,
+        "Hosp_Meldedatum": 23, …
```
=> New data set: 2022-01-12T112303Z

latest-json
```diff -u pjson/2022-01-12T112303Z.json pjson/2022-01-13T112303Z.json```:
```
--- pjson/2022-01-12T112303Z.json	2022-01-12 11:23:03.725864657 +0000
+++ pjson/2022-01-13T112303Z.json	2022-01-13 11:23:04.127579786 +0000
@@ -11856,7 +11856,7 @@
"Datum_neu": 1609804800000,
-        "F\u00e4lle_Meldedatum": 389,
+        "F\u00e4lle_Meldedatum": 388,
@@ -11970,7 +11970,7 @@
"Datum_neu": 1610064000000,
-        "F\u00e4lle_Meldedatum": 217,
+        "F\u00e4lle_Meldedatum": 218, …
```
=> New data set: 2022-01-13T112303Z

latest-json
```diff -u pjson/2022-01-13T112303Z.json pjson/2022-01-14T111503Z.json```:
```
--- pjson/2022-01-13T112303Z.json	2022-01-13 11:23:04.127579786 +0000
+++ pjson/2022-01-14T111503Z.json	2022-01-14 11:15:03.245122074 +0000
@@ -12160,7 +12160,7 @@
"Datum_neu": 1610496000000,
-        "F\u00e4lle_Meldedatum": 236,
+        "F\u00e4lle_Meldedatum": 237,
@@ -15010,7 +15010,7 @@
"Datum_neu": 1616976000000,
-        "F\u00e4lle_Meldedatum": 127,
+        "F\u00e4lle_Meldedatum": 126, …
```
=> New data set: 2022-01-14T111503Z

latest-json
```diff -u pjson/2022-01-14T111503Z.json pjson/2022-01-17T112302Z.json```:
```
--- pjson/2022-01-14T111503Z.json	2022-01-14 11:15:03.245122074 +0000
+++ pjson/2022-01-17T112302Z.json	2022-01-17 11:23:02.839750065 +0000
@@ -11058,7 +11058,7 @@
"Datum_neu": 1607990400000,
-        "F\u00e4lle_Meldedatum": 422,
+        "F\u00e4lle_Meldedatum": 421,
@@ -11590,7 +11590,7 @@
"Datum_neu": 1609200000000,
-        "F\u00e4lle_Meldedatum": 576,
+        "F\u00e4lle_Meldedatum": 575, …
```
=> New data set: 2022-01-17T112302Z

latest-json
```diff -u pjson/2022-01-17T112302Z.json pjson/2022-01-18T113404Z.json```:
```
--- pjson/2022-01-17T112302Z.json	2022-01-17 11:23:02.839750065 +0000
+++ pjson/2022-01-18T113404Z.json	2022-01-18 11:34:04.710914376 +0000
@@ -9234,7 +9234,7 @@
"Datum_neu": 1603843200000,
-        "F\u00e4lle_Meldedatum": 147,
+        "F\u00e4lle_Meldedatum": 146,
@@ -10260,7 +10260,7 @@
-        "F\u00e4lle_Meldedatum": 264,
+        "F\u00e4lle_Meldedatum": 263, …
```
=> New data set: 2022-01-18T113404Z

latest-json
```diff -u pjson/2022-01-18T113404Z.json pjson/2022-01-19T111704Z.json```:
```
--- pjson/2022-01-18T113404Z.json	2022-01-18 11:34:04.710914376 +0000
+++ pjson/2022-01-19T111704Z.json	2022-01-19 11:17:04.744784448 +0000
@@ -10262,7 +10262,7 @@
"F\u00e4lle_Meldedatum": 263,
-        "Hosp_Meldedatum": 15,
@@ -11020,7 +11020,7 @@
-        "F\u00e4lle_Meldedatum": 429,
+        "F\u00e4lle_Meldedatum": 428, …
```
=> New data set: 2022-01-19T111704Z

latest-json
```diff -u pjson/2022-01-20T114304Z.json pjson/2022-01-21T111204Z.json```:
```
--- pjson/2022-01-20T114304Z.json	2022-01-20 11:43:04.294913702 +0000
+++ pjson/2022-01-21T111204Z.json	2022-01-21 11:12:04.388045706 +0000
@@ -22458,7 +22458,7 @@
"Datum_neu": 1633910400000,
-        "F\u00e4lle_Meldedatum": 80,
+        "F\u00e4lle_Meldedatum": 81,
@@ -22496,7 +22496,7 @@
"Datum_neu": 1633996800000, …
```
=> New data set: 2022-01-21T111204Z

latest-json
```diff -u pjson/2022-01-21T111204Z.json pjson/2022-01-24T112104Z.json```:
```
--- pjson/2022-01-21T111204Z.json	2022-01-21 11:12:04.388045706 +0000
+++ pjson/2022-01-24T112104Z.json	2022-01-24 11:21:04.131914463 +0000
@@ -16492,7 +16492,7 @@
"Datum_neu": 1620345600000,
-        "F\u00e4lle_Meldedatum": 93,
+        "F\u00e4lle_Meldedatum": 94,
@@ -22610,7 +22610,7 @@
"Datum_neu": 1634256000000,
-        "F\u00e4lle_Meldedatum": 163,
+        "F\u00e4lle_Meldedatum": 164, …
```
=> New data set: 2022-01-24T112104Z

latest-json
```diff -u pjson/2022-01-25T112002Z.json pjson/2022-01-26T112103Z.json```:
```
--- pjson/2022-01-25T112002Z.json	2022-01-25 11:20:02.888079886 +0000
+++ pjson/2022-01-26T112103Z.json	2022-01-26 11:21:03.761294291 +0000
@@ -10792,7 +10792,7 @@
"Datum_neu": 1607385600000,
-        "F\u00e4lle_Meldedatum": 333,
+        "F\u00e4lle_Meldedatum": 332,
@@ -22496,7 +22496,7 @@
"Datum_neu": 1633996800000,
-        "F\u00e4lle_Meldedatum": 145,
+        "F\u00e4lle_Meldedatum": 144, …
```
=> New data set: 2022-01-26T112103Z

latest-json
```diff -u pjson/2022-01-26T112103Z.json pjson/2022-01-27T120005Z.json```:
```
--- pjson/2022-01-26T112103Z.json	2022-01-26 11:21:03.761294291 +0000
+++ pjson/2022-01-27T120005Z.json	2022-01-27 12:00:05.851293597 +0000
@@ -16378,7 +16378,7 @@
"Datum_neu": 1620086400000,
-        "F\u00e4lle_Meldedatum": 172,
+        "F\u00e4lle_Meldedatum": 173,
@@ -23560,7 +23560,7 @@
"Datum_neu": 1636416000000,
-        "F\u00e4lle_Meldedatum": 1232,
+        "F\u00e4lle_Meldedatum": 1233, …
```
=> New data set: 2022-01-27T120005Z

latest-json
```diff -u pjson/2022-01-27T120005Z.json pjson/2022-01-28T112204Z.json```:
```
--- pjson/2022-01-27T120005Z.json	2022-01-27 12:00:05.851293597 +0000
+++ pjson/2022-01-28T112204Z.json	2022-01-28 11:22:04.451329628 +0000
@@ -11096,7 +11096,7 @@
-        "F\u00e4lle_Meldedatum": 361,
+        "F\u00e4lle_Meldedatum": 360,
"Hosp_Meldedatum": 36,
@@ -12350,7 +12350,7 @@
"Datum_neu": 1610928000000, …
```
=> New data set: 2022-01-28T112204Z

latest-json
```diff -u pjson/2022-01-31T112603Z.json pjson/2022-02-01T112003Z.json```:
```
--- pjson/2022-01-31T112603Z.json	2022-01-31 11:26:03.940307969 +0000
+++ pjson/2022-02-01T112003Z.json	2022-02-01 11:20:04.136007230 +0000
@@ -24130,7 +24130,7 @@
"Datum_neu": 1637712000000,
-        "F\u00e4lle_Meldedatum": 1085,
+        "F\u00e4lle_Meldedatum": 1086,
"Hosp_Meldedatum": 34,
@@ -24548,7 +24548,7 @@
"Datum_neu": 1638662400000,
-        "F\u00e4lle_Meldedatum": 193,
+        "F\u00e4lle_Meldedatum": 194, …
```
=> New data set: 2022-02-01T112003Z

latest-json
```diff -u pjson/2022-02-01T112003Z.json pjson/2022-02-02T112403Z.json```:
```
--- pjson/2022-02-01T112003Z.json	2022-02-01 11:20:04.136007230 +0000
+++ pjson/2022-02-02T112403Z.json	2022-02-02 11:24:03.880833518 +0000
@@ -12084,7 +12084,7 @@
"Datum_neu": 1610323200000,
-        "F\u00e4lle_Meldedatum": 181,
+        "F\u00e4lle_Meldedatum": 182,
"Hosp_Meldedatum": 44,
@@ -12884,7 +12884,7 @@
"Datum_neu": 1612137600000,
"F\u00e4lle_Meldedatum": 75,
-        "Hosp_Meldedatum": 13, …
```
=> New data set: 2022-02-02T112403Z

latest-json
```diff -u pjson/2022-02-02T112403Z.json pjson/2022-02-03T112004Z.json```:
```
--- pjson/2022-02-02T112403Z.json	2022-02-02 11:24:03.880833518 +0000
+++ pjson/2022-02-03T112004Z.json	2022-02-03 11:20:04.370941823 +0000
@@ -12160,7 +12160,7 @@
"Datum_neu": 1610496000000,
-        "F\u00e4lle_Meldedatum": 237,
+        "F\u00e4lle_Meldedatum": 238,
@@ -23636,7 +23636,7 @@
"Datum_neu": 1636588800000,
-        "F\u00e4lle_Meldedatum": 1038,
+        "F\u00e4lle_Meldedatum": 1037, …
```
=> New data set: 2022-02-03T112004Z

latest-json
```diff -u pjson/2022-02-03T112004Z.json pjson/2022-02-04T113103Z.json```:
```
--- pjson/2022-02-03T112004Z.json	2022-02-03 11:20:04.370941823 +0000
+++ pjson/2022-02-04T113103Z.json	2022-02-04 11:31:04.089931771 +0000
@@ -12160,7 +12160,7 @@
"Datum_neu": 1610496000000,
-        "F\u00e4lle_Meldedatum": 238,
+        "F\u00e4lle_Meldedatum": 237,
@@ -14680,7 +14680,7 @@
"Krh_I": null, …
```
=> New data set: 2022-02-04T113103Z

latest-json
```diff -u pjson/2022-02-04T113103Z.json pjson/2022-02-07T112403Z.json```:
```
--- pjson/2022-02-04T113103Z.json	2022-02-04 11:31:04.089931771 +0000
+++ pjson/2022-02-07T112403Z.json	2022-02-07 11:24:03.648340251 +0000
@@ -24396,7 +24396,7 @@
"Datum_neu": 1638316800000,
-        "F\u00e4lle_Meldedatum": 1116,
+        "F\u00e4lle_Meldedatum": 1117,
@@ -24624,7 +24624,7 @@
"Datum_neu": 1638835200000,
-        "F\u00e4lle_Meldedatum": 1252,
+        "F\u00e4lle_Meldedatum": 1253, …
```
=> New data set: 2022-02-07T112403Z

latest-json
```diff -u pjson/2022-02-07T112403Z.json pjson/2022-02-08T112303Z.json```:
```
--- pjson/2022-02-07T112403Z.json	2022-02-07 11:24:03.648340251 +0000
+++ pjson/2022-02-08T112303Z.json	2022-02-08 11:23:03.481153358 +0000
@@ -25612,7 +25612,7 @@
"Datum_neu": 1641081600000,
-        "F\u00e4lle_Meldedatum": 60,
+        "F\u00e4lle_Meldedatum": 59,
@@ -25726,7 +25726,7 @@
"Datum_neu": 1641340800000,
-        "F\u00e4lle_Meldedatum": 337,
+        "F\u00e4lle_Meldedatum": 338, …
```
=> New data set: 2022-02-08T112303Z

latest-json
```diff -u pjson/2022-02-08T112303Z.json pjson/2022-02-09T115603Z.json```:
```
--- pjson/2022-02-08T112303Z.json	2022-02-08 11:23:03.481153358 +0000
+++ pjson/2022-02-09T115603Z.json	2022-02-09 11:56:03.462151056 +0000
@@ -13008,7 +13008,7 @@
"Krh_I": null,
-        "SterbeF_Sterbedatum": 5,
@@ -22116,7 +22116,7 @@
"Datum_neu": 1633132800000,
-        "F\u00e4lle_Meldedatum": 47,
+        "F\u00e4lle_Meldedatum": 48, …
```
=> New data set: 2022-02-09T115603Z

latest-json
```diff -u pjson/2022-02-09T115603Z.json pjson/2022-02-10T112303Z.json```:
```
--- pjson/2022-02-09T115603Z.json	2022-02-09 11:56:03.462151056 +0000
+++ pjson/2022-02-10T112303Z.json	2022-02-10 11:23:03.531644427 +0000
@@ -10298,7 +10298,7 @@
-        "F\u00e4lle_Meldedatum": 274,
+        "F\u00e4lle_Meldedatum": 273,
@@ -12996,7 +12996,7 @@
"Datum_neu": 1612396800000,
-        "F\u00e4lle_Meldedatum": 75,
+        "F\u00e4lle_Meldedatum": 77, …
```
=> New data set: 2022-02-10T112303Z

latest-json
```diff -u pjson/2022-02-10T112303Z.json pjson/2022-02-11T115803Z.json```:
```
--- pjson/2022-02-10T112303Z.json	2022-02-10 11:23:03.531644427 +0000
+++ pjson/2022-02-11T115803Z.json	2022-02-11 11:58:03.821033558 +0000
@@ -11324,7 +11324,7 @@
-        "F\u00e4lle_Meldedatum": 477,
+        "F\u00e4lle_Meldedatum": 476,
@@ -23636,7 +23636,7 @@
"Datum_neu": 1636588800000,
-        "F\u00e4lle_Meldedatum": 1037,
+        "F\u00e4lle_Meldedatum": 1038, …
```
=> New data set: 2022-02-11T115803Z

latest-json
```diff -u pjson/2022-02-14T112702Z.json pjson/2022-02-14T120803Z.json```:
```
--- pjson/2022-02-14T112702Z.json	2022-02-14 11:27:02.667393398 +0000
+++ pjson/2022-02-14T120803Z.json	2022-02-14 12:08:03.650814213 +0000
@@ -27260,7 +27260,7 @@
-        "Mutation": 3144,
+        "Mutation": 3380,
"H_Inzidenz": 5.08,
"H_Zeitraum": "07.02.2022 - 13.02.2022",
```
If there are no anomalies, you are welcome to **merge** this symlink pointing to the new data set so that the new statistics will become publicly available on the [Grafana …
=> New data set: 2022-02-14T120803Z

latest-json
```diff -u pjson/2022-02-14T120803Z.json pjson/2022-02-15T115004Z.json```:
```
--- pjson/2022-02-14T120803Z.json	2022-02-14 12:08:03.650814213 +0000
+++ pjson/2022-02-15T115004Z.json	2022-02-15 11:50:04.907065544 +0000
@@ -11286,7 +11286,7 @@
"Datum_neu": 1608508800000,
-        "F\u00e4lle_Meldedatum": 435,
+        "F\u00e4lle_Meldedatum": 434,
"Hosp_Meldedatum": 47,
@@ -11932,7 +11932,7 @@
-        "F\u00e4lle_Meldedatum": 264,
+        "F\u00e4lle_Meldedatum": 263, …
```
=> New data set: 2022-02-15T115004Z

latest-json
```diff -u pjson/2022-02-15T115004Z.json pjson/2022-02-16T114904Z.json```:
```
--- pjson/2022-02-15T115004Z.json	2022-02-15 11:50:04.907065544 +0000
+++ pjson/2022-02-16T114904Z.json	2022-02-16 11:49:04.327928284 +0000
@@ -23902,7 +23902,7 @@
"Datum_neu": 1637193600000,
-        "F\u00e4lle_Meldedatum": 1106,
+        "F\u00e4lle_Meldedatum": 1105,
@@ -26562,7 +26562,7 @@
"Datum_neu": 1643241600000,
-        "F\u00e4lle_Meldedatum": 937,
+        "F\u00e4lle_Meldedatum": 936, …
```
=> New data set: 2022-02-16T114904Z

latest-json
```diff -u pjson/2022-02-16T114904Z.json pjson/2022-02-17T112803Z.json```:
```
--- pjson/2022-02-16T114904Z.json	2022-02-16 11:49:04.327928284 +0000
+++ pjson/2022-02-17T112803Z.json	2022-02-17 11:28:03.758043216 +0000
@@ -11362,7 +11362,7 @@
-        "F\u00e4lle_Meldedatum": 446,
+        "F\u00e4lle_Meldedatum": 445,
@@ -23598,7 +23598,7 @@
"Datum_neu": 1636502400000,
-        "F\u00e4lle_Meldedatum": 973,
+        "F\u00e4lle_Meldedatum": 972, …
```
=> New data set: 2022-02-17T112803Z

latest-json
```diff -u pjson/2022-02-18T114102Z.json pjson/2022-02-21T112402Z.json```:
```
--- pjson/2022-02-18T114102Z.json	2022-02-18 11:41:02.602876588 +0000
+++ pjson/2022-02-21T112402Z.json	2022-02-21 11:24:02.931138820 +0000
@@ -12616,7 +12616,7 @@
"Datum_neu": 1611532800000,
-        "F\u00e4lle_Meldedatum": 118,
+        "F\u00e4lle_Meldedatum": 117,
@@ -16758,7 +16758,7 @@
"Datum_neu": 1620950400000,
-        "F\u00e4lle_Meldedatum": 50,
+        "F\u00e4lle_Meldedatum": 49, …
```
=> New data set: 2022-02-21T112402Z

latest-json
```diff -u pjson/2022-02-21T112402Z.json pjson/2022-02-22T112902Z.json```:
```
--- pjson/2022-02-21T112402Z.json	2022-02-21 11:24:02.931138820 +0000
+++ pjson/2022-02-22T112902Z.json	2022-02-22 11:29:03.119279574 +0000
@@ -11820,7 +11820,7 @@
"Datum_neu": 1609718400000,
"F\u00e4lle_Meldedatum": 240,
@@ -12010,7 +12010,7 @@
"Datum_neu": 1610150400000,
"F\u00e4lle_Meldedatum": 82, …
```
=> New data set: 2022-02-22T112902Z

latest-json
```diff -u pjson/2022-02-22T112902Z.json pjson/2022-02-23T112802Z.json```:
```
--- pjson/2022-02-22T112902Z.json	2022-02-22 11:29:03.119279574 +0000
+++ pjson/2022-02-23T112802Z.json	2022-02-23 11:28:02.993307230 +0000
@@ -23636,7 +23636,7 @@
"Datum_neu": 1636588800000,
-        "F\u00e4lle_Meldedatum": 1038,
+        "F\u00e4lle_Meldedatum": 1039,
@@ -26258,7 +26258,7 @@
"Datum_neu": 1642550400000,
-        "F\u00e4lle_Meldedatum": 683,
+        "F\u00e4lle_Meldedatum": 684, …
```
=> New data set: 2022-02-23T112802Z

latest-json
```diff -u pjson/2022-02-23T112802Z.json pjson/2022-02-24T115103Z.json```:
```
--- pjson/2022-02-23T112802Z.json	2022-02-23 11:28:02.993307230 +0000
+++ pjson/2022-02-24T115103Z.json	2022-02-24 11:51:03.369815969 +0000
@@ -14782,7 +14782,7 @@
"Datum_neu": 1616457600000,
-        "F\u00e4lle_Meldedatum": 171,
+        "F\u00e4lle_Meldedatum": 172,
@@ -23560,7 +23560,7 @@
"Datum_neu": 1636416000000,
-        "F\u00e4lle_Meldedatum": 1233,
+        "F\u00e4lle_Meldedatum": 1232, …
```
=> New data set: 2022-02-24T115103Z

latest-json
```diff -u pjson/2022-02-25T112903Z.json pjson/2022-02-28T114103Z.json```:
```
--- pjson/2022-02-25T112903Z.json	2022-02-25 11:29:03.742934778 +0000
+++ pjson/2022-02-28T114103Z.json	2022-02-28 11:41:03.741037620 +0000
@@ -11096,7 +11096,7 @@
-        "F\u00e4lle_Meldedatum": 359,
+        "F\u00e4lle_Meldedatum": 360,
"Hosp_Meldedatum": 36,
@@ -11134,7 +11134,7 @@
"Datum_neu": 1608163200000,
-        "F\u00e4lle_Meldedatum": 513,
+        "F\u00e4lle_Meldedatum": 512, …
```
=> New data set: 2022-02-28T114103Z

latest-json
```diff -u pjson/2022-02-28T114103Z.json pjson/2022-03-01T113104Z.json```:
```
--- pjson/2022-02-28T114103Z.json	2022-02-28 11:41:03.741037620 +0000
+++ pjson/2022-03-01T113104Z.json	2022-03-01 11:31:04.284424360 +0000
@@ -11020,7 +11020,7 @@
-        "F\u00e4lle_Meldedatum": 427,
+        "F\u00e4lle_Meldedatum": 428,
@@ -14604,7 +14604,7 @@
"Krh_I": null,
+        "SterbeF_Sterbedatum": 0, …
```
=> New data set: 2022-03-01T113104Z

latest-json
```diff -u pjson/2022-03-01T113104Z.json pjson/2022-03-02T113504Z.json```:
```
--- pjson/2022-03-01T113104Z.json	2022-03-01 11:31:04.284424360 +0000
+++ pjson/2022-03-02T113504Z.json	2022-03-02 11:35:04.308267147 +0000
@@ -25156,7 +25156,7 @@
"Datum_neu": 1640044800000,
-        "F\u00e4lle_Meldedatum": 939,
+        "F\u00e4lle_Meldedatum": 938,
"Hosp_Meldedatum": 33,
@@ -25422,7 +25422,7 @@
"Datum_neu": 1640649600000,
-        "F\u00e4lle_Meldedatum": 485,
+        "F\u00e4lle_Meldedatum": 486, …
```
=> New data set: 2022-03-02T113504Z

latest-json
```diff -u pjson/2022-03-02T114603Z.json pjson/2022-03-03T114103Z.json```:
```
--- pjson/2022-03-02T114603Z.json	2022-03-02 11:46:03.580743859 +0000
+++ pjson/2022-03-03T114103Z.json	2022-03-03 11:41:03.191328870 +0000
@@ -24206,7 +24206,7 @@
"Datum_neu": 1637884800000,
-        "F\u00e4lle_Meldedatum": 1196,
+        "F\u00e4lle_Meldedatum": 1195,
@@ -25764,7 +25764,7 @@
"Datum_neu": 1641427200000,
-        "F\u00e4lle_Meldedatum": 311,
+        "F\u00e4lle_Meldedatum": 312, …
```
=> New data set: 2022-03-03T114103Z

latest-json
```diff -u pjson/2022-03-03T114103Z.json pjson/2022-03-04T115203Z.json```:
```
--- pjson/2022-03-03T114103Z.json	2022-03-03 11:41:03.191328870 +0000
+++ pjson/2022-03-04T115203Z.json	2022-03-04 11:52:03.247837135 +0000
@@ -24586,7 +24586,7 @@
"Datum_neu": 1638748800000,
-        "F\u00e4lle_Meldedatum": 982,
+        "F\u00e4lle_Meldedatum": 981,
"Hosp_Meldedatum": 42,
@@ -25156,7 +25156,7 @@
"Datum_neu": 1640044800000,
-        "F\u00e4lle_Meldedatum": 938,
+        "F\u00e4lle_Meldedatum": 937,
"Hosp_Meldedatum": 33, …
```
=> New data set: 2022-03-04T115203Z

latest-json
```diff -u pjson/2022-03-04T115203Z.json pjson/2022-03-07T112703Z.json```:
```
--- pjson/2022-03-04T115203Z.json	2022-03-04 11:52:03.247837135 +0000
+++ pjson/2022-03-07T112703Z.json	2022-03-07 11:27:04.033235523 +0000
@@ -25764,7 +25764,7 @@
"Datum_neu": 1641427200000,
-        "F\u00e4lle_Meldedatum": 312,
+        "F\u00e4lle_Meldedatum": 313,
@@ -26258,7 +26258,7 @@
"Datum_neu": 1642550400000,
-        "F\u00e4lle_Meldedatum": 683,
+        "F\u00e4lle_Meldedatum": 684, …
```
=> New data set: 2022-03-07T112703Z

latest-json
```diff -u pjson/2022-03-07T112703Z.json pjson/2022-03-08T113104Z.json```:
```
--- pjson/2022-03-07T112703Z.json	2022-03-07 11:27:04.033235523 +0000
+++ pjson/2022-03-08T113104Z.json	2022-03-08 11:31:04.181583097 +0000
@@ -25612,7 +25612,7 @@
"Datum_neu": 1641081600000,
-        "F\u00e4lle_Meldedatum": 60,
+        "F\u00e4lle_Meldedatum": 61,
@@ -25650,7 +25650,7 @@
"Datum_neu": 1641168000000,
-        "F\u00e4lle_Meldedatum": 658,
+        "F\u00e4lle_Meldedatum": 657, …
```
=> New data set: 2022-03-08T113104Z

latest-json
```diff -u pjson/2022-03-08T113104Z.json pjson/2022-03-09T115404Z.json```:
```
--- pjson/2022-03-08T113104Z.json	2022-03-08 11:31:04.181583097 +0000
+++ pjson/2022-03-09T115404Z.json	2022-03-09 11:54:04.425922667 +0000
@@ -13414,7 +13414,7 @@
"Datum_neu": 1613347200000,
-        "F\u00e4lle_Meldedatum": 75,
+        "F\u00e4lle_Meldedatum": 74,
@@ -14060,7 +14060,7 @@
"Datum_neu": 1614816000000,
-        "F\u00e4lle_Meldedatum": 57,
+        "F\u00e4lle_Meldedatum": 58, …
```
=> New data set: 2022-03-09T115404Z

latest-json
```diff -u pjson/2022-03-09T115404Z.json pjson/2022-03-10T113104Z.json```:
```
--- pjson/2022-03-09T115404Z.json	2022-03-09 11:54:04.425922667 +0000
+++ pjson/2022-03-10T113104Z.json	2022-03-10 11:31:04.192585475 +0000
@@ -23752,7 +23752,7 @@
"Datum_neu": 1636848000000,
"F\u00e4lle_Meldedatum": 294,
+        "Hosp_Meldedatum": 6,
@@ -23904,7 +23904,7 @@
"Datum_neu": 1637193600000,
"F\u00e4lle_Meldedatum": 1104,
-        "Hosp_Meldedatum": 37,
+        "Hosp_Meldedatum": 35, …
```
=> New data set: 2022-03-10T113104Z

latest-json
```diff -u pjson/2022-03-10T113104Z.json pjson/2022-03-11T112104Z.json```:
```
--- pjson/2022-03-10T113104Z.json	2022-03-10 11:31:04.192585475 +0000
+++ pjson/2022-03-11T112104Z.json	2022-03-11 11:21:04.345086713 +0000
@@ -20674,7 +20674,7 @@
"Datum_neu": 1629849600000,
"F\u00e4lle_Meldedatum": 50,
@@ -20978,7 +20978,7 @@
"Datum_neu": 1630540800000,
"F\u00e4lle_Meldedatum": 71, …
```
=> New data set: 2022-03-11T112104Z

latest-json
```diff -u pjson/2022-03-16T113503Z.json pjson/2022-03-17T113403Z.json```:
```
--- pjson/2022-03-16T113503Z.json	2022-03-16 11:35:03.475073107 +0000
+++ pjson/2022-03-17T113403Z.json	2022-03-17 11:34:03.999269492 +0000
@@ -25878,7 +25878,7 @@
"Datum_neu": 1641686400000,
-        "F\u00e4lle_Meldedatum": 82,
+        "F\u00e4lle_Meldedatum": 81,
@@ -26714,7 +26714,7 @@
"Datum_neu": 1643587200000,
-        "F\u00e4lle_Meldedatum": 1498,
+        "F\u00e4lle_Meldedatum": 1497, …
```
=> New data set: 2022-03-17T113403Z

latest-json
```diff -u pjson/2022-03-17T113403Z.json pjson/2022-03-18T113404Z.json```:
```
--- pjson/2022-03-17T113403Z.json	2022-03-17 11:34:03.999269492 +0000
+++ pjson/2022-03-18T113404Z.json	2022-03-18 11:34:04.343033051 +0000
@@ -14212,7 +14212,7 @@
-        "F\u00e4lle_Meldedatum": 102,
+        "F\u00e4lle_Meldedatum": 103,
@@ -26524,7 +26524,7 @@
"Datum_neu": 1643155200000,
-        "F\u00e4lle_Meldedatum": 1145,
+        "F\u00e4lle_Meldedatum": 1144, …
```
=> New data set: 2022-03-18T113404Z

latest-json
```diff -u pjson/2022-03-21T120502Z.json pjson/2022-03-22T113702Z.json```:
```
--- pjson/2022-03-21T120502Z.json	2022-03-21 12:05:02.965255822 +0000
+++ pjson/2022-03-22T113702Z.json	2022-03-22 11:37:03.088999004 +0000
@@ -25726,7 +25726,7 @@
"Datum_neu": 1641340800000,
-        "F\u00e4lle_Meldedatum": 340,
+        "F\u00e4lle_Meldedatum": 339,
@@ -26980,7 +26980,7 @@
"Datum_neu": 1644192000000,
-        "F\u00e4lle_Meldedatum": 1802,
+        "F\u00e4lle_Meldedatum": 1803, …
```
=> New data set: 2022-03-22T113702Z

latest-json
```diff -u pjson/2022-03-22T113702Z.json pjson/2022-03-23T111502Z.json```:
```
--- pjson/2022-03-22T113702Z.json	2022-03-22 11:37:03.088999004 +0000
+++ pjson/2022-03-23T111502Z.json	2022-03-23 11:15:02.875564825 +0000
@@ -10146,7 +10146,7 @@
"Datum_neu": 1605916800000,
-        "F\u00e4lle_Meldedatum": 87,
+        "F\u00e4lle_Meldedatum": 86,
@@ -13794,7 +13794,7 @@
"Datum_neu": 1614211200000,
-        "F\u00e4lle_Meldedatum": 67,
+        "F\u00e4lle_Meldedatum": 68, …
```
=> New data set: 2022-03-23T111502Z

latest-json
```diff -u pjson/2022-03-23T111502Z.json pjson/2022-03-24T111703Z.json```:
```
--- pjson/2022-03-23T111502Z.json	2022-03-23 11:15:02.875564825 +0000
+++ pjson/2022-03-24T111703Z.json	2022-03-24 11:17:03.838244101 +0000
@@ -23294,7 +23294,7 @@
"Datum_neu": 1635811200000,
-        "F\u00e4lle_Meldedatum": 691,
+        "F\u00e4lle_Meldedatum": 692,
@@ -25004,7 +25004,7 @@
"Datum_neu": 1639699200000,
-        "F\u00e4lle_Meldedatum": 541,
+        "F\u00e4lle_Meldedatum": 542, …
```
=> New data set: 2022-03-24T111703Z

latest-json
```diff -u pjson/2022-03-24T111703Z.json pjson/2022-03-25T110903Z.json```:
```
--- pjson/2022-03-24T111703Z.json	2022-03-24 11:17:03.838244101 +0000
+++ pjson/2022-03-25T110903Z.json	2022-03-25 11:09:03.263126096 +0000
@@ -10754,7 +10754,7 @@
-        "F\u00e4lle_Meldedatum": 386,
+        "F\u00e4lle_Meldedatum": 385,
@@ -14250,7 +14250,7 @@
"Datum_neu": 1615248000000,
-        "F\u00e4lle_Meldedatum": 98,
+        "F\u00e4lle_Meldedatum": 99, …
```
=> New data set: 2022-03-25T110903Z

latest-json
```diff -u pjson/2022-03-25T110903Z.json pjson/2022-03-28T104404Z.json```:
```
--- pjson/2022-03-25T110903Z.json	2022-03-25 11:09:03.263126096 +0000
+++ pjson/2022-03-28T104404Z.json	2022-03-28 10:44:04.428831544 +0000
@@ -14820,7 +14820,7 @@
"Datum_neu": 1616544000000,
-        "F\u00e4lle_Meldedatum": 108,
+        "F\u00e4lle_Meldedatum": 109,
@@ -26600,7 +26600,7 @@
"Datum_neu": 1643328000000,
-        "F\u00e4lle_Meldedatum": 1006,
+        "F\u00e4lle_Meldedatum": 1007, …
```
=> New data set: 2022-03-28T104404Z

latest-json
```diff -u pjson/2022-03-28T104404Z.json pjson/2022-03-29T104203Z.json```:
```
--- pjson/2022-03-28T104404Z.json	2022-03-28 10:44:04.428831544 +0000
+++ pjson/2022-03-29T104203Z.json	2022-03-29 10:42:03.826059156 +0000
@@ -11438,7 +11438,7 @@
"Datum_neu": 1608854400000,
+        "F\u00e4lle_Meldedatum": 43,
@@ -14478,7 +14478,7 @@
"Datum_neu": 1615766400000,
-        "F\u00e4lle_Meldedatum": 101,
+        "F\u00e4lle_Meldedatum": 102, …
```
=> New data set: 2022-03-29T104203Z

latest-json
```diff -u pjson/2022-03-29T104203Z.json pjson/2022-03-30T102704Z.json```:
```
--- pjson/2022-03-29T104203Z.json	2022-03-29 10:42:03.826059156 +0000
+++ pjson/2022-03-30T102704Z.json	2022-03-30 10:27:04.200998220 +0000
@@ -12350,7 +12350,7 @@
"Datum_neu": 1610928000000,
+        "F\u00e4lle_Meldedatum": 152,
"Hosp_Meldedatum": 30,
@@ -13832,7 +13832,7 @@
"Datum_neu": 1614297600000,
-        "F\u00e4lle_Meldedatum": 53,
+        "F\u00e4lle_Meldedatum": 54, …
```
=> New data set: 2022-03-30T102704Z

latest-json
```diff -u pjson/2022-03-30T102704Z.json pjson/2022-03-31T105004Z.json```:
```
--- pjson/2022-03-30T102704Z.json	2022-03-30 10:27:04.200998220 +0000
+++ pjson/2022-03-31T105004Z.json	2022-03-31 10:50:04.479694184 +0000
@@ -11324,7 +11324,7 @@
-        "F\u00e4lle_Meldedatum": 476,
+        "F\u00e4lle_Meldedatum": 477,
@@ -11362,7 +11362,7 @@
-        "F\u00e4lle_Meldedatum": 445,
+        "F\u00e4lle_Meldedatum": 444,
"Hosp_Meldedatum": 39, …
```
=> New data set: 2022-03-31T105004Z

latest-json
```diff -u pjson/2022-03-31T105004Z.json pjson/2022-04-01T104704Z.json```:
```
--- pjson/2022-03-31T105004Z.json	2022-03-31 10:50:04.479694184 +0000
+++ pjson/2022-04-01T104704Z.json	2022-04-01 10:47:04.300272531 +0000
@@ -9350,7 +9350,7 @@
"Datum_neu": 1604102400000,
"F\u00e4lle_Meldedatum": 71,
@@ -9388,7 +9388,7 @@
"F\u00e4lle_Meldedatum": 37,
+        "Hosp_Meldedatum": 6, …
```
=> New data set: 2022-04-01T104704Z

latest-json
```diff -u pjson/2022-04-01T104704Z.json pjson/2022-04-04T104703Z.json```:
```
--- pjson/2022-04-01T104704Z.json	2022-04-01 10:47:04.300272531 +0000
+++ pjson/2022-04-04T104703Z.json	2022-04-04 10:47:04.138995289 +0000
@@ -14896,7 +14896,7 @@
"Datum_neu": 1616716800000,
-        "F\u00e4lle_Meldedatum": 142,
+        "F\u00e4lle_Meldedatum": 143,
@@ -15124,7 +15124,7 @@
"Datum_neu": 1617235200000,
+        "F\u00e4lle_Meldedatum": 141, …
```
=> New data set: 2022-04-04T104703Z

latest-json
```diff -u pjson/2022-04-04T104703Z.json pjson/2022-04-05T112104Z.json```:
```
--- pjson/2022-04-04T104703Z.json	2022-04-04 10:47:04.138995289 +0000
+++ pjson/2022-04-05T112104Z.json	2022-04-05 11:21:04.381011896 +0000
@@ -14744,7 +14744,7 @@
"Datum_neu": 1616371200000,
-        "F\u00e4lle_Meldedatum": 130,
+        "F\u00e4lle_Meldedatum": 131,
@@ -15428,7 +15428,7 @@
"Datum_neu": 1617926400000,
-        "F\u00e4lle_Meldedatum": 182,
+        "F\u00e4lle_Meldedatum": 183, …
```
=> New data set: 2022-04-05T112104Z

latest-json
```diff -u pjson/2022-04-05T112104Z.json pjson/2022-04-06T103703Z.json```:
```
--- pjson/2022-04-05T112104Z.json	2022-04-05 11:21:04.381011896 +0000
+++ pjson/2022-04-06T103703Z.json	2022-04-06 10:37:04.122078679 +0000
@@ -14858,7 +14858,7 @@
-        "F\u00e4lle_Meldedatum": 188,
+        "F\u00e4lle_Meldedatum": 189,
@@ -15428,7 +15428,7 @@
"Datum_neu": 1617926400000,
-        "F\u00e4lle_Meldedatum": 183,
+        "F\u00e4lle_Meldedatum": 182, …
```
=> New data set: 2022-04-06T103703Z

latest-json
```diff -u pjson/2022-04-06T103703Z.json pjson/2022-04-07T105704Z.json```:
```
--- pjson/2022-04-06T103703Z.json	2022-04-06 10:37:04.122078679 +0000
+++ pjson/2022-04-07T105704Z.json	2022-04-07 10:57:04.406911958 +0000
@@ -26030,7 +26030,7 @@
"Datum_neu": 1642032000000,
-        "F\u00e4lle_Meldedatum": 301,
+        "F\u00e4lle_Meldedatum": 302,
@@ -26182,7 +26182,7 @@
"Datum_neu": 1642377600000,
-        "F\u00e4lle_Meldedatum": 701,
+        "F\u00e4lle_Meldedatum": 702, …
```
=> New data set: 2022-04-07T105704Z

latest-json
```diff -u pjson/2022-04-07T105704Z.json pjson/2022-04-08T104404Z.json```:
```
--- pjson/2022-04-07T105704Z.json	2022-04-07 10:57:04.406911958 +0000
+++ pjson/2022-04-08T104404Z.json	2022-04-08 10:44:05.046311015 +0000
@@ -14212,7 +14212,7 @@
-        "F\u00e4lle_Meldedatum": 103,
+        "F\u00e4lle_Meldedatum": 102,
@@ -14630,7 +14630,7 @@
"Datum_neu": 1616112000000,
-        "F\u00e4lle_Meldedatum": 113,
+        "F\u00e4lle_Meldedatum": 114, …
```
=> New data set: 2022-04-08T104404Z

latest-json
```diff -u pjson/2022-04-08T104404Z.json pjson/2022-04-11T100303Z.json```:
```
--- pjson/2022-04-08T104404Z.json	2022-04-08 10:44:05.046311015 +0000
+++ pjson/2022-04-11T100303Z.json	2022-04-11 10:03:03.920506098 +0000
@@ -20446,7 +20446,7 @@
"Datum_neu": 1629331200000,
"F\u00e4lle_Meldedatum": 31,
@@ -20484,7 +20484,7 @@
"Datum_neu": 1629417600000,
"F\u00e4lle_Meldedatum": 25, …
```
=> New data set: 2022-04-11T100303Z

latest-json
```diff -u pjson/2022-04-11T100303Z.json pjson/2022-04-12T101903Z.json```:
```
--- pjson/2022-04-11T100303Z.json	2022-04-11 10:03:03.920506098 +0000
+++ pjson/2022-04-12T101903Z.json	2022-04-12 10:19:03.214080846 +0000
@@ -9350,7 +9350,7 @@
"Datum_neu": 1604102400000,
"F\u00e4lle_Meldedatum": 71,
+        "Hosp_Meldedatum": 0,
@@ -9388,7 +9388,7 @@
"F\u00e4lle_Meldedatum": 37,
-        "Hosp_Meldedatum": 6, …
```
=> New data set: 2022-04-12T101903Z

latest-json
```diff -u pjson/2022-04-12T101903Z.json pjson/2022-04-13T101403Z.json```:
```
--- pjson/2022-04-12T101903Z.json	2022-04-12 10:19:03.214080846 +0000
+++ pjson/2022-04-13T101403Z.json	2022-04-13 10:14:03.591116183 +0000
@@ -26486,7 +26486,7 @@
"Datum_neu": 1643068800000,
-        "F\u00e4lle_Meldedatum": 1319,
+        "F\u00e4lle_Meldedatum": 1318,
@@ -26980,7 +26980,7 @@
"Datum_neu": 1644192000000,
-        "F\u00e4lle_Meldedatum": 1802,
+        "F\u00e4lle_Meldedatum": 1803, …
```
=> New data set: 2022-04-13T101403Z

latest-json
```diff -u pjson/2022-04-13T101403Z.json pjson/2022-04-14T101704Z.json```:
```
--- pjson/2022-04-13T101403Z.json	2022-04-13 10:14:03.591116183 +0000
+++ pjson/2022-04-14T101704Z.json	2022-04-14 10:17:04.532069318 +0000
-        "F\u00e4lle_Meldedatum": 2037,
+        "F\u00e4lle_Meldedatum": 2038,
@@ -28272,7 +28272,7 @@
"Datum_neu": 1647129600000,
-        "F\u00e4lle_Meldedatum": 388,
+        "F\u00e4lle_Meldedatum": 391, …
```
=> New data set: 2022-04-14T101704Z

latest-json
```diff -u pjson/2022-04-14T101704Z.json pjson/2022-04-19T102304Z.json```:
```
--- pjson/2022-04-14T101704Z.json	2022-04-14 10:17:04.532069318 +0000
+++ pjson/2022-04-19T102304Z.json	2022-04-19 10:23:04.378743810 +0000
@@ -27246,7 +27246,7 @@
"Datum_neu": 1644796800000,
-        "F\u00e4lle_Meldedatum": 1485,
+        "F\u00e4lle_Meldedatum": 1484,
-        "F\u00e4lle_Meldedatum": 1827,
+        "F\u00e4lle_Meldedatum": 1826, …
```
=> New data set: 2022-04-19T102304Z

latest-json
```diff -u pjson/2022-04-19T102304Z.json pjson/2022-04-20T103003Z.json```:
```
--- pjson/2022-04-19T102304Z.json	2022-04-19 10:23:04.378743810 +0000
+++ pjson/2022-04-20T103003Z.json	2022-04-20 10:30:04.072170766 +0000
@@ -25954,7 +25954,7 @@
"Datum_neu": 1641859200000,
-        "F\u00e4lle_Meldedatum": 355,
+        "F\u00e4lle_Meldedatum": 356,
@@ -26258,7 +26258,7 @@
"Datum_neu": 1642550400000,
-        "F\u00e4lle_Meldedatum": 684,
+        "F\u00e4lle_Meldedatum": 683, …
```
=> New data set: 2022-04-20T103003Z

latest-json
```diff -u pjson/2022-04-20T103003Z.json pjson/2022-04-21T101505Z.json```:
```
--- pjson/2022-04-20T103003Z.json	2022-04-20 10:30:04.072170766 +0000
+++ pjson/2022-04-21T101505Z.json	2022-04-21 10:15:05.976920630 +0000
@@ -25688,7 +25688,7 @@
"Datum_neu": 1641254400000,
-        "F\u00e4lle_Meldedatum": 528,
+        "F\u00e4lle_Meldedatum": 529,
@@ -28462,7 +28462,7 @@
"Datum_neu": 1647561600000,
-        "F\u00e4lle_Meldedatum": 2597,
+        "F\u00e4lle_Meldedatum": 2598, …
```
=> New data set: 2022-04-21T101505Z

latest-json
```diff -u pjson/2022-04-21T101505Z.json pjson/2022-04-22T101303Z.json```:
```
--- pjson/2022-04-21T101505Z.json	2022-04-21 10:15:05.976920630 +0000
+++ pjson/2022-04-22T101303Z.json	2022-04-22 10:13:04.110795100 +0000
@@ -27512,7 +27512,7 @@
"Datum_neu": 1645401600000,
-        "F\u00e4lle_Meldedatum": 1483,
+        "F\u00e4lle_Meldedatum": 1484,
@@ -27550,7 +27550,7 @@
"Datum_neu": 1645488000000,
-        "F\u00e4lle_Meldedatum": 1193,
+        "F\u00e4lle_Meldedatum": 1192, …
```
=> New data set: 2022-04-22T101303Z

latest-json
```diff -u pjson/2022-04-22T101303Z.json pjson/2022-04-25T102604Z.json```:
```
--- pjson/2022-04-22T101303Z.json	2022-04-22 10:13:04.110795100 +0000
+++ pjson/2022-04-25T102604Z.json	2022-04-25 10:26:04.354311318 +0000
@@ -26790,7 +26790,7 @@
"Datum_neu": 1643760000000,
-        "F\u00e4lle_Meldedatum": 1348,
+        "F\u00e4lle_Meldedatum": 1349,
@@ -28272,7 +28272,7 @@
"Datum_neu": 1647129600000,
-        "F\u00e4lle_Meldedatum": 391,
+        "F\u00e4lle_Meldedatum": 392, …
```
=> New data set: 2022-04-25T102604Z

latest-json
```diff -u pjson/2022-04-25T102604Z.json pjson/2022-04-26T102004Z.json```:
```
--- pjson/2022-04-25T102604Z.json	2022-04-25 10:26:04.354311318 +0000
+++ pjson/2022-04-26T102004Z.json	2022-04-26 10:20:04.785233641 +0000
@@ -26562,7 +26562,7 @@
"Datum_neu": 1643241600000,
-        "F\u00e4lle_Meldedatum": 942,
+        "F\u00e4lle_Meldedatum": 943,
-        "F\u00e4lle_Meldedatum": 1826,
+        "F\u00e4lle_Meldedatum": 1827, …
```
=> New data set: 2022-04-26T102004Z

latest-json
```diff -u pjson/2022-04-26T102004Z.json pjson/2022-04-27T101204Z.json```:
```
--- pjson/2022-04-26T102004Z.json	2022-04-26 10:20:04.785233641 +0000
+++ pjson/2022-04-27T101204Z.json	2022-04-27 10:12:04.796149052 +0000
-        "F\u00e4lle_Meldedatum": 1827,
+        "F\u00e4lle_Meldedatum": 1828,
@@ -27968,7 +27968,7 @@
"Datum_neu": 1646438400000,
-        "F\u00e4lle_Meldedatum": 793,
+        "F\u00e4lle_Meldedatum": 792, …
```
=> New data set: 2022-04-27T101204Z

latest-json
```diff -u pjson/2022-04-27T103004Z.json pjson/2022-04-28T112004Z.json```:
```
--- pjson/2022-04-27T103004Z.json	2022-04-27 10:30:05.140639399 +0000
+++ pjson/2022-04-28T112004Z.json	2022-04-28 11:20:04.615281005 +0000
@@ -27170,7 +27170,7 @@
"Datum_neu": 1644624000000,
-        "F\u00e4lle_Meldedatum": 872,
+        "F\u00e4lle_Meldedatum": 873,
@@ -27626,7 +27626,7 @@
"Datum_neu": 1645660800000,
-        "F\u00e4lle_Meldedatum": 1198,
+        "F\u00e4lle_Meldedatum": 1199, …
```
=> New data set: 2022-04-28T112004Z

latest-json
```diff -u pjson/2022-04-29T100304Z.json pjson/2022-05-02T102504Z.json```:
```
--- pjson/2022-04-29T100304Z.json	2022-04-29 10:03:04.291713186 +0000
+++ pjson/2022-05-02T102504Z.json	2022-05-02 10:25:04.208976161 +0000
@@ -27892,7 +27892,7 @@
"Datum_neu": 1646265600000,
-        "F\u00e4lle_Meldedatum": 1205,
+        "F\u00e4lle_Meldedatum": 1206,
@@ -28462,7 +28462,7 @@
"Datum_neu": 1647561600000,
-        "F\u00e4lle_Meldedatum": 2597,
+        "F\u00e4lle_Meldedatum": 2598, …
```
=> New data set: 2022-05-02T102504Z

latest-json
```diff -u pjson/2022-05-02T102504Z.json pjson/2022-05-03T113303Z.json```:
```
--- pjson/2022-05-02T102504Z.json	2022-05-02 10:25:04.208976161 +0000
+++ pjson/2022-05-03T113303Z.json	2022-05-03 11:33:03.300386781 +0000
@@ -29792,7 +29792,7 @@
"Datum_neu": 1650585600000,
-        "F\u00e4lle_Meldedatum": 500,
+        "F\u00e4lle_Meldedatum": 501,
@@ -29904,15 +29904,15 @@
"Zuwachs_Genesung": 1296,
-        "Inzidenz": 742.124357915155,
"Datum_neu": 1650844800000, …
```
=> New data set: 2022-05-03T113303Z

latest-json
```diff -u pjson/2022-05-03T113303Z.json pjson/2022-05-04T112303Z.json```:
```
--- pjson/2022-05-03T113303Z.json	2022-05-03 11:33:03.300386781 +0000
+++ pjson/2022-05-04T112303Z.json	2022-05-04 11:23:03.590735352 +0000
@@ -28728,7 +28728,7 @@
"Datum_neu": 1648166400000,
-        "F\u00e4lle_Meldedatum": 1780,
+        "F\u00e4lle_Meldedatum": 1781,
@@ -28766,7 +28766,7 @@
"Datum_neu": 1648252800000,
-        "F\u00e4lle_Meldedatum": 829,
+        "F\u00e4lle_Meldedatum": 830, …
```
=> New data set: 2022-05-04T112303Z

latest-json
```diff -u pjson/2022-05-04T112303Z.json pjson/2022-05-05T102004Z.json```:
```
--- pjson/2022-05-04T112303Z.json	2022-05-04 11:23:03.590735352 +0000
+++ pjson/2022-05-05T102004Z.json	2022-05-05 10:20:04.905401438 +0000
@@ -28006,7 +28006,7 @@
"Datum_neu": 1646524800000,
-        "F\u00e4lle_Meldedatum": 373,
+        "F\u00e4lle_Meldedatum": 374,
@@ -28614,7 +28614,7 @@
"Datum_neu": 1647907200000,
-        "F\u00e4lle_Meldedatum": 2970,
+        "F\u00e4lle_Meldedatum": 2971, …
```
=> New data set: 2022-05-05T102004Z

latest-json
```diff -u pjson/2022-05-06T101504Z.json pjson/2022-05-09T105004Z.json```:
```
--- pjson/2022-05-06T101504Z.json	2022-05-06 10:15:04.259092709 +0000
+++ pjson/2022-05-09T105004Z.json	2022-05-09 10:50:04.368586631 +0000
@@ -25802,7 +25802,7 @@
"Datum_neu": 1641513600000,
-        "F\u00e4lle_Meldedatum": 241,
+        "F\u00e4lle_Meldedatum": 242,
-        "F\u00e4lle_Meldedatum": 1828,
+        "F\u00e4lle_Meldedatum": 1829, …
```
=> New data set: 2022-05-09T105004Z

latest-json
```diff -u pjson/2022-05-09T111903Z.json pjson/2022-05-10T104904Z.json```:
```
--- pjson/2022-05-09T111903Z.json	2022-05-09 11:19:04.017620435 +0000
+++ pjson/2022-05-10T104904Z.json	2022-05-10 10:49:04.529523134 +0000
@@ -29678,7 +29678,7 @@
"Datum_neu": 1650326400000,
-        "F\u00e4lle_Meldedatum": 1405,
+        "F\u00e4lle_Meldedatum": 1406,
"Hosp_Meldedatum": 35,
@@ -29716,7 +29716,7 @@
"Datum_neu": 1650412800000,
-        "F\u00e4lle_Meldedatum": 835,
+        "F\u00e4lle_Meldedatum": 836, …
```
=> New data set: 2022-05-10T104904Z

latest-json
```diff -u pjson/2022-05-10T104904Z.json pjson/2022-05-11T100303Z.json```:
```
--- pjson/2022-05-10T104904Z.json	2022-05-10 10:49:04.529523134 +0000
+++ pjson/2022-05-11T100303Z.json	2022-05-11 10:03:03.449774679 +0000
@@ -30172,7 +30172,7 @@
"Datum_neu": 1651449600000,
-        "F\u00e4lle_Meldedatum": 703,
+        "F\u00e4lle_Meldedatum": 704,
@@ -30208,15 +30208,15 @@
"Zuwachs_Genesung": 1378,
-        "Inzidenz": 512.6,
"Datum_neu": 1651536000000, …
```
=> New data set: 2022-05-11T100303Z

latest-json
```diff -u pjson/2022-05-11T100303Z.json pjson/2022-05-12T103203Z.json```:
```
--- pjson/2022-05-11T100303Z.json	2022-05-11 10:03:03.449774679 +0000
+++ pjson/2022-05-12T103203Z.json	2022-05-12 10:32:03.431664113 +0000
@@ -27322,7 +27322,7 @@
"Datum_neu": 1644969600000,
-        "F\u00e4lle_Meldedatum": 951,
+        "F\u00e4lle_Meldedatum": 952,
-        "F\u00e4lle_Meldedatum": 2040,
+        "F\u00e4lle_Meldedatum": 2041, …
```
=> New data set: 2022-05-12T103203Z

latest-json
```diff -u pjson/2022-05-12T103203Z.json pjson/2022-05-13T104003Z.json```:
```
--- pjson/2022-05-12T103203Z.json	2022-05-12 10:32:03.431664113 +0000
+++ pjson/2022-05-13T104003Z.json	2022-05-13 10:40:03.639601556 +0000
@@ -27322,7 +27322,7 @@
"Datum_neu": 1644969600000,
-        "F\u00e4lle_Meldedatum": 952,
+        "F\u00e4lle_Meldedatum": 953,
@@ -29146,7 +29146,7 @@
"Datum_neu": 1649116800000,
-        "F\u00e4lle_Meldedatum": 1440,
+        "F\u00e4lle_Meldedatum": 1441, …
```
=> New data set: 2022-05-13T104003Z

latest-json
```diff -u pjson/2022-05-13T104003Z.json pjson/2022-05-16T102803Z.json```:
```
--- pjson/2022-05-13T104003Z.json	2022-05-13 10:40:03.639601556 +0000
+++ pjson/2022-05-16T102803Z.json	2022-05-16 10:28:03.890933804 +0000
@@ -15012,7 +15012,7 @@
"Datum_neu": 1616976000000,
"F\u00e4lle_Meldedatum": 126,
-        "Hosp_Meldedatum": 21,
+        "Hosp_Meldedatum": 22,
@@ -15050,7 +15050,7 @@
"Datum_neu": 1617062400000,
"F\u00e4lle_Meldedatum": 221, …
```
=> New data set: 2022-05-16T102803Z

latest-json
```diff -u pjson/2022-05-16T102803Z.json pjson/2022-05-17T102004Z.json```:
```
--- pjson/2022-05-16T102803Z.json	2022-05-16 10:28:03.890933804 +0000
+++ pjson/2022-05-17T102004Z.json	2022-05-17 10:20:04.212444700 +0000
@@ -27284,7 +27284,7 @@
"Datum_neu": 1644883200000,
-        "F\u00e4lle_Meldedatum": 1249,
+        "F\u00e4lle_Meldedatum": 1250,
-        "F\u00e4lle_Meldedatum": 2041,
+        "F\u00e4lle_Meldedatum": 2042, …
```
=> New data set: 2022-05-17T102004Z

latest-json
```diff -u pjson/2022-05-17T102004Z.json pjson/2022-05-18T101403Z.json```:
```
--- pjson/2022-05-17T102004Z.json	2022-05-17 10:20:04.212444700 +0000
+++ pjson/2022-05-18T101403Z.json	2022-05-18 10:14:04.022141029 +0000
-        "F\u00e4lle_Meldedatum": 1829,
+        "F\u00e4lle_Meldedatum": 1830,
@@ -29222,7 +29222,7 @@
"Datum_neu": 1649289600000,
-        "F\u00e4lle_Meldedatum": 1063,
+        "F\u00e4lle_Meldedatum": 1064, …
```
=> New data set: 2022-05-18T101403Z

latest-json
```diff -u pjson/2022-05-19T103304Z.json pjson/2022-05-23T101603Z.json```:
```
--- pjson/2022-05-19T103304Z.json	2022-05-19 10:33:04.204831467 +0000
+++ pjson/2022-05-23T101603Z.json	2022-05-23 10:16:03.762516271 +0000
@@ -29602,7 +29602,7 @@
"Datum_neu": 1650153600000,
-        "F\u00e4lle_Meldedatum": 162,
+        "F\u00e4lle_Meldedatum": 163,
@@ -29680,7 +29680,7 @@
"Datum_neu": 1650326400000,
"F\u00e4lle_Meldedatum": 1406,
-        "Hosp_Meldedatum": 32,
+        "Hosp_Meldedatum": 33, …
```
=> New data set: 2022-05-23T101603Z

latest-json
```diff -u pjson/2022-05-23T101603Z.json pjson/2022-05-24T101902Z.json```:
```
--- pjson/2022-05-23T101603Z.json	2022-05-23 10:16:03.762516271 +0000
+++ pjson/2022-05-24T101902Z.json	2022-05-24 10:19:03.070041280 +0000
@@ -26638,7 +26638,7 @@
"Datum_neu": 1643414400000,
-        "F\u00e4lle_Meldedatum": 425,
+        "F\u00e4lle_Meldedatum": 424,
@@ -27018,7 +27018,7 @@
"Datum_neu": 1644278400000,
-        "F\u00e4lle_Meldedatum": 1770,
+        "F\u00e4lle_Meldedatum": 1769, …
```
=> New data set: 2022-05-24T101902Z

latest-json
```diff -u pjson/2022-05-24T101902Z.json pjson/2022-05-25T102804Z.json```:
```
--- pjson/2022-05-24T101902Z.json	2022-05-24 10:19:03.070041280 +0000
+++ pjson/2022-05-25T102804Z.json	2022-05-25 10:28:04.689534336 +0000
@@ -30336,7 +30336,7 @@
"Krh_I": null,
@@ -30440,7 +30440,7 @@
"Datum_neu": 1652054400000,
"F\u00e4lle_Meldedatum": 509, …
```
=> New data set: 2022-05-25T102804Z

latest-json
```diff -u pjson/2022-05-25T102804Z.json pjson/2022-05-27T102903Z.json```:
```
--- pjson/2022-05-25T102804Z.json	2022-05-25 10:28:04.689534336 +0000
+++ pjson/2022-05-27T102903Z.json	2022-05-27 10:29:03.443891105 +0000
@@ -16682,7 +16682,7 @@
"Datum_neu": 1620777600000,
-        "F\u00e4lle_Meldedatum": 94,
+        "F\u00e4lle_Meldedatum": 93,
@@ -16720,7 +16720,7 @@
"Datum_neu": 1620864000000,
-        "F\u00e4lle_Meldedatum": 55,
+        "F\u00e4lle_Meldedatum": 54, …
```
=> New data set: 2022-05-27T102903Z

latest-json
```diff -u pjson/2022-05-30T104403Z.json pjson/2022-05-30T110503Z.json```:
```
--- pjson/2022-05-30T104403Z.json	2022-05-30 10:44:03.638451110 +0000
+++ pjson/2022-05-30T110503Z.json	2022-05-30 11:05:03.631338237 +0000
@@ -31163,7 +31163,7 @@
"F\u00e4lle_Meldedatum": 28,
-        "Inzidenz_RKI": null,
+        "Inzidenz_RKI": 133,
"Krh_N_belegt": 331,
"Krh_I_belegt": 63,
@@ -31201,7 +31201,7 @@
"F\u00e4lle_Meldedatum": 22,
-        "Inzidenz_RKI": null,
+        "Inzidenz_RKI": 120.5,
"Krh_N_belegt": 331,
"Krh_I_belegt": 63,
```
If …
=> New data set: 2022-05-30T110503Z

latest-json
```diff -u pjson/2022-05-30T110503Z.json pjson/2022-05-31T100303Z.json```:
```
--- pjson/2022-05-30T110503Z.json	2022-05-30 11:05:03.631338237 +0000
+++ pjson/2022-05-31T100303Z.json	2022-05-31 10:03:03.209607862 +0000
@@ -26030,7 +26030,7 @@
"Datum_neu": 1642032000000,
-        "F\u00e4lle_Meldedatum": 302,
+        "F\u00e4lle_Meldedatum": 303,
@@ -30968,15 +30968,15 @@
"Zuwachs_Genesung": 504,
-        "Inzidenz": 199.719817522181,
"Datum_neu": 1653264000000,
- …
```
=> New data set: 2022-05-31T100303Z

latest-json
```diff -u pjson/2022-05-31T100303Z.json pjson/2022-06-01T100303Z.json```:
```
--- pjson/2022-05-31T100303Z.json	2022-05-31 10:03:03.209607862 +0000
+++ pjson/2022-06-01T100303Z.json	2022-06-01 10:03:03.621276875 +0000
@@ -25954,7 +25954,7 @@
"Datum_neu": 1641859200000,
-        "F\u00e4lle_Meldedatum": 356,
+        "F\u00e4lle_Meldedatum": 357,
@@ -28348,7 +28348,7 @@
"Datum_neu": 1647302400000,
-        "F\u00e4lle_Meldedatum": 2597,
+        "F\u00e4lle_Meldedatum": 2595, …
```
=> New data set: 2022-06-01T100303Z

latest-json
```diff -u pjson/2022-06-01T100303Z.json pjson/2022-06-02T100203Z.json```:
```
--- pjson/2022-06-01T100303Z.json	2022-06-01 10:03:03.621276875 +0000
+++ pjson/2022-06-02T100203Z.json	2022-06-02 10:02:03.913181906 +0000
@@ -27930,7 +27930,7 @@
"Datum_neu": 1646352000000,
-        "F\u00e4lle_Meldedatum": 981,
+        "F\u00e4lle_Meldedatum": 982,
@@ -28006,7 +28006,7 @@
"Datum_neu": 1646524800000,
-        "F\u00e4lle_Meldedatum": 374,
+        "F\u00e4lle_Meldedatum": 375, …
```
=> New data set: 2022-06-02T100203Z

latest-json
```diff -u pjson/2022-06-02T100203Z.json pjson/2022-06-03T100503Z.json```:
```
--- pjson/2022-06-02T100203Z.json	2022-06-02 10:02:03.913181906 +0000
+++ pjson/2022-06-03T100503Z.json	2022-06-03 10:05:03.181188145 +0000
@@ -31082,15 +31082,15 @@
"Zuwachs_Genesung": 255,
-        "Inzidenz": 193.972484643845,
"Datum_neu": 1653523200000,
"F\u00e4lle_Meldedatum": 66,
-        "Inzidenz_RKI": 175.5,
-        "Krh_N_belegt": 331,
-        "Krh_I_belegt": 63,
+        "Krh_N_belegt": …
```
=> New data set: 2022-06-03T100503Z

latest-json
```diff -u pjson/2022-06-03T100503Z.json pjson/2022-06-07T103003Z.json```:
```
--- pjson/2022-06-03T100503Z.json	2022-06-03 10:05:03.181188145 +0000
+++ pjson/2022-06-07T103003Z.json	2022-06-07 10:30:04.121992743 +0000
@@ -24434,7 +24434,7 @@
"Datum_neu": 1638403200000,
-        "F\u00e4lle_Meldedatum": 884,
+        "F\u00e4lle_Meldedatum": 883,
"Hosp_Meldedatum": 35,
@@ -24548,7 +24548,7 @@
"Datum_neu": 1638662400000,
-        "F\u00e4lle_Meldedatum": 194,
+        "F\u00e4lle_Meldedatum": 193, …
```
=> New data set: 2022-06-07T103003Z

latest-json
```diff -u pjson/2022-06-07T103003Z.json pjson/2022-06-08T102303Z.json```:
```
--- pjson/2022-06-07T103003Z.json	2022-06-07 10:30:04.121992743 +0000
+++ pjson/2022-06-08T102303Z.json	2022-06-08 10:23:03.775265932 +0000
@@ -26866,7 +26866,7 @@
"Datum_neu": 1643932800000,
-        "F\u00e4lle_Meldedatum": 1103,
+        "F\u00e4lle_Meldedatum": 1104,
@@ -28462,7 +28462,7 @@
"Datum_neu": 1647561600000,
-        "F\u00e4lle_Meldedatum": 2598,
+        "F\u00e4lle_Meldedatum": 2599, …
```
=> New data set: 2022-06-08T102303Z

latest-json
```diff -u pjson/2022-06-08T102303Z.json pjson/2022-06-09T100404Z.json```:
```
--- pjson/2022-06-08T102303Z.json	2022-06-08 10:23:03.775265932 +0000
+++ pjson/2022-06-09T100404Z.json	2022-06-09 10:04:04.194364612 +0000
@@ -31310,15 +31310,15 @@
"Zuwachs_Genesung": 206,
-        "Inzidenz": 161.823341355652,
"Datum_neu": 1654041600000,
-        "F\u00e4lle_Meldedatum": 172,
+        "F\u00e4lle_Meldedatum": 173,
-        "Inzidenz_RKI": 127.5,
-        "Krh_N_belegt": 263,
- …
```
=> New data set: 2022-06-09T100404Z

latest-json
```diff -u pjson/2022-06-09T100404Z.json pjson/2022-06-10T102704Z.json```:
```
--- pjson/2022-06-09T100404Z.json	2022-06-09 10:04:04.194364612 +0000
+++ pjson/2022-06-10T102704Z.json	2022-06-10 10:27:04.152747604 +0000
@@ -29452,7 +29452,7 @@
"Datum_neu": 1649808000000,
"F\u00e4lle_Meldedatum": 747,
-        "Hosp_Meldedatum": 16,
+        "Hosp_Meldedatum": 17,
@@ -29680,7 +29680,7 @@
"Datum_neu": 1650326400000,
"F\u00e4lle_Meldedatum": 1406,
-        "Hosp_Meldedatum": 33,
+        "Hosp_Meldedatum": 36, …
```
=> New data set: 2022-06-10T102704Z

latest-json
```diff -u pjson/2022-06-14T100403Z.json pjson/2022-06-15T100103Z.json```:
```
--- pjson/2022-06-14T100403Z.json	2022-06-14 10:04:04.043275036 +0000
+++ pjson/2022-06-15T100103Z.json	2022-06-15 10:01:03.981667230 +0000
@@ -25650,7 +25650,7 @@
"Datum_neu": 1641168000000,
-        "F\u00e4lle_Meldedatum": 658,
+        "F\u00e4lle_Meldedatum": 657,
@@ -25878,7 +25878,7 @@
"Datum_neu": 1641686400000,
-        "F\u00e4lle_Meldedatum": 81, …
```
=> New data set: 2022-06-15T100103Z

latest-json
```diff -u pjson/2022-06-15T100103Z.json pjson/2022-06-16T104703Z.json```:
```
--- pjson/2022-06-15T100103Z.json	2022-06-15 10:01:03.981667230 +0000
+++ pjson/2022-06-16T104703Z.json	2022-06-16 10:47:03.318315989 +0000
@@ -24434,7 +24434,7 @@
"Datum_neu": 1638403200000,
-        "F\u00e4lle_Meldedatum": 883,
+        "F\u00e4lle_Meldedatum": 882,
"Hosp_Meldedatum": 35,
@@ -31466,7 +31466,7 @@
"Datum_neu": 1654387200000,
"F\u00e4lle_Meldedatum": 62, …
```
=> New data set: 2022-06-16T104703Z

latest-json
```diff -u pjson/2022-06-16T104703Z.json pjson/2022-06-17T101303Z.json```:
```
--- pjson/2022-06-16T104703Z.json	2022-06-16 10:47:03.318315989 +0000
+++ pjson/2022-06-17T101303Z.json	2022-06-17 10:13:03.993704744 +0000
@@ -23788,7 +23788,7 @@
"Datum_neu": 1636934400000,
-        "F\u00e4lle_Meldedatum": 1145,
+        "F\u00e4lle_Meldedatum": 1144,
@@ -23940,7 +23940,7 @@
"Datum_neu": 1637280000000,
-        "F\u00e4lle_Meldedatum": 1482,
+        "F\u00e4lle_Meldedatum": 1481, …
```
=> New data set: 2022-06-17T101303Z

latest-json
```diff -u pjson/2022-06-17T101303Z.json pjson/2022-06-20T100703Z.json```:
```
--- pjson/2022-06-17T101303Z.json	2022-06-17 10:13:03.993704744 +0000
+++ pjson/2022-06-20T100703Z.json	2022-06-20 10:07:03.176344999 +0000
@@ -27854,7 +27854,7 @@
"Datum_neu": 1646179200000,
-        "F\u00e4lle_Meldedatum": 1364,
+        "F\u00e4lle_Meldedatum": 1365,
-        "F\u00e4lle_Meldedatum": 2045,
+        "F\u00e4lle_Meldedatum": 2046, …
```
=> New data set: 2022-06-20T100703Z

latest-json
```diff -u pjson/2022-06-20T100703Z.json pjson/2022-06-21T101404Z.json```:
```
--- pjson/2022-06-20T100703Z.json	2022-06-20 10:07:03.176344999 +0000
+++ pjson/2022-06-21T101404Z.json	2022-06-21 10:14:04.808401065 +0000
@@ -31362,7 +31362,7 @@
"Krh_I": null,
@@ -31616,7 +31616,7 @@
"Datum_neu": 1654732800000,
-        "F\u00e4lle_Meldedatum": 325,
+        "F\u00e4lle_Meldedatum": 324, …
```
=> New data set: 2022-06-21T101404Z

latest-json
```diff -u pjson/2022-06-21T101404Z.json pjson/2022-06-22T103402Z.json```:
```
--- pjson/2022-06-21T101404Z.json	2022-06-21 10:14:04.808401065 +0000
+++ pjson/2022-06-22T103402Z.json	2022-06-22 10:34:02.822884563 +0000
@@ -31540,7 +31540,7 @@
"Datum_neu": 1654560000000,
-        "F\u00e4lle_Meldedatum": 408,
+        "F\u00e4lle_Meldedatum": 407,
@@ -31804,15 +31804,15 @@
"Zuwachs_Genesung": 245,
-        "Inzidenz": 368.547720823305,
"Datum_neu": 1655164800000,
- …
```
=> New data set: 2022-06-22T103402Z

latest-json
```diff -u pjson/2022-06-22T103402Z.json pjson/2022-06-23T100503Z.json```:
```
--- pjson/2022-06-22T103402Z.json	2022-06-22 10:34:02.822884563 +0000
+++ pjson/2022-06-23T100503Z.json	2022-06-23 10:05:03.875874614 +0000
@@ -29830,7 +29830,7 @@
"Datum_neu": 1650672000000,
-        "F\u00e4lle_Meldedatum": 203,
+        "F\u00e4lle_Meldedatum": 202,
@@ -31426,7 +31426,7 @@
"Datum_neu": 1654300800000, …
```
=> New data set: 2022-06-23T100503Z

latest-json
```diff -u pjson/2022-06-23T100503Z.json pjson/2022-06-24T101704Z.json```:
```
--- pjson/2022-06-23T100503Z.json	2022-06-23 10:05:03.875874614 +0000
+++ pjson/2022-06-24T101704Z.json	2022-06-24 10:17:04.270165562 +0000
@@ -31314,7 +31314,7 @@
"Datum_neu": 1654041600000,
"F\u00e4lle_Meldedatum": 175,
@@ -31542,7 +31542,7 @@
"Datum_neu": 1654560000000,
"F\u00e4lle_Meldedatum": 407, …
```
=> New data set: 2022-06-24T101704Z

latest-json
```diff -u pjson/2022-06-24T101704Z.json pjson/2022-06-27T101004Z.json```:
```
--- pjson/2022-06-24T101704Z.json	2022-06-24 10:17:04.270165562 +0000
+++ pjson/2022-06-27T101004Z.json	2022-06-27 10:10:04.549994220 +0000
@@ -31894,7 +31894,7 @@
"Krh_I": null,
@@ -31918,15 +31918,15 @@
"Zuwachs_Genesung": 132,
-        "Inzidenz": 408.419842666762,
"Datum_neu": 1655424000000, …
```
=> New data set: 2022-06-27T101004Z

latest-json
```diff -u pjson/2022-06-27T101004Z.json pjson/2022-06-28T114903Z.json```:
```
--- pjson/2022-06-27T101004Z.json	2022-06-27 10:10:04.549994220 +0000
+++ pjson/2022-06-28T114903Z.json	2022-06-28 11:49:03.513681686 +0000
@@ -32032,15 +32032,15 @@
"Zuwachs_Genesung": 136,
-        "Inzidenz": 441.826215022091,
"Datum_neu": 1655683200000,
"F\u00e4lle_Meldedatum": 699,
-        "Inzidenz_RKI": 318.9,
-        "Krh_N_belegt": 308,
-        "Krh_I_belegt": 40,
+        "Krh_N_belegt": …
```
=> New data set: 2022-06-28T114903Z

latest-json
```diff -u pjson/2022-06-28T114903Z.json pjson/2022-06-29T100203Z.json```:
```
--- pjson/2022-06-28T114903Z.json	2022-06-28 11:49:03.513681686 +0000
+++ pjson/2022-06-29T100203Z.json	2022-06-29 10:02:03.997443237 +0000
@@ -30852,7 +30852,7 @@
-        "Zuwachs_Genesung": 270,
+        "Zuwachs_Genesung": 271,
"Datum_neu": 1653004800000,
@@ -30890,7 +30890,7 @@
-        "Zuwachs_Genesung": 119,
+        "Zuwachs_Genesung": 128, …
```
=> New data set: 2022-06-29T100203Z

latest-json
```diff -u pjson/2022-06-29T100203Z.json pjson/2022-06-30T102802Z.json```:
```
--- pjson/2022-06-29T100203Z.json	2022-06-29 10:02:03.997443237 +0000
+++ pjson/2022-06-30T102802Z.json	2022-06-30 10:28:03.083205046 +0000
@@ -30894,7 +30894,7 @@
"Datum_neu": 1653091200000,
-        "F\u00e4lle_Meldedatum": 69,
+        "F\u00e4lle_Meldedatum": 70,
@@ -31084,7 +31084,7 @@
"Datum_neu": 1653523200000,
-        "F\u00e4lle_Meldedatum": 66,
+        "F\u00e4lle_Meldedatum": 67, …
```
=> New data set: 2022-06-30T102802Z

latest-json
```diff -u pjson/2022-06-30T102802Z.json pjson/2022-07-01T103103Z.json```:
```
--- pjson/2022-06-30T102802Z.json	2022-06-30 10:28:03.083205046 +0000
+++ pjson/2022-07-01T103103Z.json	2022-07-01 10:31:03.186075410 +0000
@@ -31352,7 +31352,7 @@
"Datum_neu": 1654128000000,
"F\u00e4lle_Meldedatum": 217,
@@ -32070,7 +32070,7 @@
"Zuwachs_Genesung": 403,
-        "Inzidenz": 470.562879413772,
"Datum_neu": 1655769600000, …
```
=> New data set: 2022-07-01T103103Z

latest-json
```diff -u pjson/2022-07-01T103103Z.json pjson/2022-07-04T101603Z.json```:
```
--- pjson/2022-07-01T103103Z.json	2022-07-01 10:31:03.186075410 +0000
+++ pjson/2022-07-04T101603Z.json	2022-07-04 10:16:04.007694197 +0000
@@ -32150,7 +32150,7 @@
"Datum_neu": 1655942400000,
"F\u00e4lle_Meldedatum": 507,
@@ -32184,15 +32184,15 @@
"Zuwachs_Genesung": 313,
-        "Inzidenz": 549.229498185998,
"Datum_neu": 1656028800000,
- …
```
=> New data set: 2022-07-04T101603Z

latest-json
```diff -u pjson/2022-07-04T101603Z.json pjson/2022-07-05T100403Z.json```:
```
--- pjson/2022-07-04T101603Z.json	2022-07-04 10:16:04.007694197 +0000
+++ pjson/2022-07-05T100403Z.json	2022-07-05 10:04:03.610762451 +0000
@@ -24890,7 +24890,7 @@
"Datum_neu": 1639440000000,
-        "F\u00e4lle_Meldedatum": 1054,
+        "F\u00e4lle_Meldedatum": 1053,
@@ -25270,7 +25270,7 @@
"Datum_neu": 1640304000000,
-        "F\u00e4lle_Meldedatum": 188,
+        "F\u00e4lle_Meldedatum": 187, …
```
=> New data set: 2022-07-05T100403Z

latest-json
```diff -u pjson/2022-07-05T100403Z.json pjson/2022-07-06T100403Z.json```:
```
--- pjson/2022-07-05T100403Z.json	2022-07-05 10:04:03.610762451 +0000
+++ pjson/2022-07-06T100403Z.json	2022-07-06 10:04:03.631189657 +0000
@@ -24092,7 +24092,7 @@
"Datum_neu": 1637625600000,
-        "F\u00e4lle_Meldedatum": 1661,
+        "F\u00e4lle_Meldedatum": 1660,
@@ -25232,7 +25232,7 @@
"Datum_neu": 1640217600000,
-        "F\u00e4lle_Meldedatum": 403,
+        "F\u00e4lle_Meldedatum": 401, …
```
=> New data set: 2022-07-06T100403Z

latest-json
```diff -u pjson/2022-07-06T100403Z.json pjson/2022-07-07T100704Z.json```:
```
--- pjson/2022-07-06T100403Z.json	2022-07-06 10:04:03.631189657 +0000
+++ pjson/2022-07-07T100704Z.json	2022-07-07 10:07:04.362972066 +0000
@@ -29678,7 +29678,7 @@
"Datum_neu": 1650326400000,
-        "F\u00e4lle_Meldedatum": 1406,
+        "F\u00e4lle_Meldedatum": 1405,
"Hosp_Meldedatum": 36,
@@ -30210,7 +30210,7 @@
"Datum_neu": 1651536000000,
-        "F\u00e4lle_Meldedatum": 583,
+        "F\u00e4lle_Meldedatum": 582, …
```
=> New data set: 2022-07-07T100704Z

latest-json
```diff -u pjson/2022-07-07T100704Z.json pjson/2022-07-08T100204Z.json```:
```
--- pjson/2022-07-07T100704Z.json	2022-07-07 10:07:04.362972066 +0000
+++ pjson/2022-07-08T100204Z.json	2022-07-08 10:02:04.324751420 +0000
@@ -28312,7 +28312,7 @@
"Datum_neu": 1647216000000,
"F\u00e4lle_Meldedatum": 2866,
-        "Hosp_Meldedatum": 28,
+        "Hosp_Meldedatum": 30,
@@ -28350,7 +28350,7 @@
"Datum_neu": 1647302400000,
"F\u00e4lle_Meldedatum": 2596,
-        "Hosp_Meldedatum": 22,
+        "Hosp_Meldedatum": 23, …
```
=> New data set: 2022-07-08T100204Z

latest-json
```diff -u pjson/2022-07-08T100204Z.json pjson/2022-07-11T100303Z.json```:
```
--- pjson/2022-07-08T100204Z.json	2022-07-08 10:02:04.324751420 +0000
+++ pjson/2022-07-11T100303Z.json	2022-07-11 10:03:04.019265670 +0000
@@ -26486,7 +26486,7 @@
"Datum_neu": 1643068800000,
-        "F\u00e4lle_Meldedatum": 1318,
+        "F\u00e4lle_Meldedatum": 1317,
@@ -27512,7 +27512,7 @@
"Datum_neu": 1645401600000,
-        "F\u00e4lle_Meldedatum": 1484,
+        "F\u00e4lle_Meldedatum": 1483, …
```
=> New data set: 2022-07-11T100303Z

latest-json
```diff -u pjson/2022-07-11T100303Z.json pjson/2022-07-12T100404Z.json```:
```
--- pjson/2022-07-11T100303Z.json	2022-07-11 10:03:04.019265670 +0000
+++ pjson/2022-07-12T100404Z.json	2022-07-12 10:04:04.356902809 +0000
@@ -32110,7 +32110,7 @@
"Datum_neu": 1655856000000,
-        "F\u00e4lle_Meldedatum": 560,
+        "F\u00e4lle_Meldedatum": 561,
@@ -32564,12 +32564,12 @@
"Zuwachs_Genesung": 696,
-        "Inzidenz": 589.101620029455,
"Datum_neu": 1656892800000,
- …
```
=> New data set: 2022-07-12T100404Z

latest-json
```diff -u pjson/2022-07-12T100404Z.json pjson/2022-07-13T100203Z.json```:
```
--- pjson/2022-07-12T100404Z.json	2022-07-12 10:04:04.356902809 +0000
+++ pjson/2022-07-13T100203Z.json	2022-07-13 10:02:03.887001117 +0000
@@ -25156,7 +25156,7 @@
"Datum_neu": 1640044800000,
-        "F\u00e4lle_Meldedatum": 936,
+        "F\u00e4lle_Meldedatum": 935,
"Hosp_Meldedatum": 30,
@@ -28690,7 +28690,7 @@
"Datum_neu": 1648080000000,
-        "F\u00e4lle_Meldedatum": 2199,
+        "F\u00e4lle_Meldedatum": 2198, …
```
=> New data set: 2022-07-13T100203Z

latest-json
```diff -u pjson/2022-07-13T100203Z.json pjson/2022-07-14T103704Z.json```:
```
--- pjson/2022-07-13T100203Z.json	2022-07-13 10:02:03.887001117 +0000
+++ pjson/2022-07-14T103704Z.json	2022-07-14 10:37:04.332240608 +0000
@@ -32640,12 +32640,12 @@
"Zuwachs_Genesung": 559,
-        "Inzidenz": 563.957038686735,
"Datum_neu": 1657065600000,
"F\u00e4lle_Meldedatum": 563,
-        "Hosp_Meldedatum": 6,
-        "Inzidenz_RKI": 474.3,
+        "Hosp_Meldedatum": 7, …
```
=> New data set: 2022-07-14T103704Z

latest-json
```diff -u pjson/2022-07-14T103704Z.json pjson/2022-07-15T100303Z.json```:
```
--- pjson/2022-07-14T103704Z.json	2022-07-14 10:37:04.332240608 +0000
+++ pjson/2022-07-15T100303Z.json	2022-07-15 10:03:03.809582371 +0000
@@ -28652,7 +28652,7 @@
"Datum_neu": 1647993600000,
-        "F\u00e4lle_Meldedatum": 2137,
+        "F\u00e4lle_Meldedatum": 2136,
@@ -32262,7 +32262,7 @@
"Datum_neu": 1656201600000,
+        "F\u00e4lle_Meldedatum": 141, …
```
=> New data set: 2022-07-15T100303Z

latest-json
```diff -u pjson/2022-07-15T100303Z.json pjson/2022-07-18T101005Z.json```:
```
--- pjson/2022-07-15T100303Z.json	2022-07-15 10:03:03.809582371 +0000
+++ pjson/2022-07-18T101005Z.json	2022-07-18 10:10:05.533113184 +0000
@@ -23826,7 +23826,7 @@
"Datum_neu": 1637020800000,
-        "F\u00e4lle_Meldedatum": 1570,
+        "F\u00e4lle_Meldedatum": 1569,
@@ -24244,7 +24244,7 @@
"Datum_neu": 1637971200000,
-        "F\u00e4lle_Meldedatum": 769,
+        "F\u00e4lle_Meldedatum": 768, …
```
=> New data set: 2022-07-18T101005Z

latest-json
```diff -u pjson/2022-07-19T101604Z.json pjson/2022-07-19T101703Z.json```:
```
--- pjson/2022-07-19T101604Z.json	2022-07-19 10:16:04.186604113 +0000
+++ pjson/2022-07-19T101703Z.json	2022-07-19 10:17:03.822634166 +0000
@@ -33130,7 +33130,7 @@
"Hospitalisierung": 5878,
"Zuwachs_Fallzahl": 941,
-        "Zuwachs_Sterbefall": 1729,
+        "Zuwachs_Sterbefall": 0,
"Zuwachs_Krankenhauseinweisung": 15,
"Zuwachs_Genesung": 710,
@@ -33144,9 +33144,9 @@
"Krh_N_belegt": 532,
"Krh_I_belegt": 57,
-        "Fallzahl_aktiv_Zuwachs": -1498,
+        "Fallzahl_aktiv_Zuwachs": 231,
"Krh_I": null,
- …
```
=> New data set: 2022-07-19T101703Z

latest-json
```diff -u pjson/2022-07-19T101703Z.json pjson/2022-07-20T102004Z.json```:
```
--- pjson/2022-07-19T101703Z.json	2022-07-19 10:17:03.822634166 +0000
+++ pjson/2022-07-20T102004Z.json	2022-07-20 10:20:04.332149607 +0000
@@ -32452,7 +32452,7 @@
"Datum_neu": 1656633600000,
-        "F\u00e4lle_Meldedatum": 475,
+        "F\u00e4lle_Meldedatum": 476,
@@ -32794,7 +32794,7 @@
"Datum_neu": 1657411200000,
-        "F\u00e4lle_Meldedatum": 129,
+        "F\u00e4lle_Meldedatum": 130, …
```
=> New data set: 2022-07-20T102004Z

latest-json
```diff -u pjson/2022-07-20T102004Z.json pjson/2022-07-21T100403Z.json```:
```
--- pjson/2022-07-20T102004Z.json	2022-07-20 10:20:04.332149607 +0000
+++ pjson/2022-07-21T100403Z.json	2022-07-21 10:04:03.444629055 +0000
@@ -32452,7 +32452,7 @@
"Datum_neu": 1656633600000,
-        "F\u00e4lle_Meldedatum": 476,
+        "F\u00e4lle_Meldedatum": 477,
@@ -32906,12 +32906,12 @@
"Zuwachs_Genesung": 622,
-        "Inzidenz": 574.374079528719,
"Datum_neu": 1657670400000, …
```
=> New data set: 2022-07-21T100403Z

latest-json
```diff -u pjson/2022-07-21T100403Z.json pjson/2022-07-22T100403Z.json```:
```
--- pjson/2022-07-21T100403Z.json	2022-07-21 10:04:03.444629055 +0000
+++ pjson/2022-07-22T100403Z.json	2022-07-22 10:04:03.528757898 +0000
@@ -32946,10 +32946,10 @@
"Inzidenz": 571.320808937103,
"Datum_neu": 1657756800000,
-        "F\u00e4lle_Meldedatum": 266,
+        "F\u00e4lle_Meldedatum": 267,
-        "Inzidenz_RKI": 477,
@@ -32962,7 +32962,7 @@
- …
```
=> New data set: 2022-07-22T100403Z

latest-json
```diff -u pjson/2022-07-22T100403Z.json pjson/2022-07-25T102203Z.json```:
```
--- pjson/2022-07-22T100403Z.json	2022-07-22 10:04:03.528757898 +0000
+++ pjson/2022-07-25T102203Z.json	2022-07-25 10:22:03.684664609 +0000
@@ -32604,7 +32604,7 @@
"Datum_neu": 1656979200000,
-        "F\u00e4lle_Meldedatum": 717,
+        "F\u00e4lle_Meldedatum": 718,
@@ -32870,7 +32870,7 @@
"Datum_neu": 1657584000000,
-        "F\u00e4lle_Meldedatum": 719,
+        "F\u00e4lle_Meldedatum": 720, …
```
=> New data set: 2022-07-25T102203Z

latest-json
```diff -u pjson/2022-07-25T102203Z.json pjson/2022-07-26T100903Z.json```:
```
--- pjson/2022-07-25T102203Z.json	2022-07-25 10:22:03.684664609 +0000
+++ pjson/2022-07-26T100903Z.json	2022-07-26 10:09:03.769911746 +0000
@@ -29918,7 +29918,7 @@
"Krh_I": null,
@@ -32376,7 +32376,7 @@
"Datum_neu": 1656460800000,
-        "F\u00e4lle_Meldedatum": 620,
+        "F\u00e4lle_Meldedatum": 621, …
```
=> New data set: 2022-07-26T100903Z

latest-json
```diff -u pjson/2022-07-26T100903Z.json pjson/2022-07-27T100103Z.json```:
```
--- pjson/2022-07-26T100903Z.json	2022-07-26 10:09:03.769911746 +0000
+++ pjson/2022-07-27T100103Z.json	2022-07-27 10:01:03.544450579 +0000
@@ -32984,9 +32984,9 @@
"Datum_neu": 1657843200000,
-        "F\u00e4lle_Meldedatum": 1121,
+        "F\u00e4lle_Meldedatum": 1122,
-        "Hosp_Meldedatum": 23,
+        "Hosp_Meldedatum": 24,
@@ -33136,10 +33136,10 @@
"Inzidenz": 670.641905240849,
"Datum_neu": 1658188800000,
- …
```
=> New data set: 2022-07-27T100103Z

latest-json
```diff -u pjson/2022-07-28T100903Z.json pjson/2022-07-29T105604Z.json```:
```
--- pjson/2022-07-28T100903Z.json	2022-07-28 10:09:03.699931103 +0000
+++ pjson/2022-07-29T105604Z.json	2022-07-29 10:56:04.770732169 +0000
@@ -33210,12 +33210,12 @@
"Zuwachs_Genesung": 453,
-        "Inzidenz": 724.882359280147,
"Datum_neu": 1658361600000,
"F\u00e4lle_Meldedatum": 558,
-        "Inzidenz_RKI": 629.6,
@@ -33228,7 +33228,7 @@
"Inzi_SN_RKI": …
```
=> New data set: 2022-07-29T105604Z

latest-json
```diff -u pjson/2022-07-29T105604Z.json pjson/2022-08-01T100004Z.json```:
```
--- pjson/2022-07-29T105604Z.json	2022-07-29 10:56:04.770732169 +0000
+++ pjson/2022-08-01T100004Z.json	2022-08-01 10:00:05.066708235 +0000
@@ -27854,7 +27854,7 @@
"Datum_neu": 1646179200000,
-        "F\u00e4lle_Meldedatum": 1365,
+        "F\u00e4lle_Meldedatum": 1364,
-        "F\u00e4lle_Meldedatum": 2046,
+        "F\u00e4lle_Meldedatum": 2045, …
```
=> New data set: 2022-08-01T100004Z

latest-json
```diff -u pjson/2022-08-01T100004Z.json pjson/2022-08-02T113403Z.json```:
```
--- pjson/2022-08-01T100004Z.json	2022-08-01 10:00:05.066708235 +0000
+++ pjson/2022-08-02T113403Z.json	2022-08-02 11:34:03.801805594 +0000
@@ -32186,7 +32186,7 @@
"Datum_neu": 1656028800000,
-        "F\u00e4lle_Meldedatum": 491,
+        "F\u00e4lle_Meldedatum": 492,
@@ -32300,7 +32300,7 @@
"Datum_neu": 1656288000000,
-        "F\u00e4lle_Meldedatum": 730,
+        "F\u00e4lle_Meldedatum": 742, …
```
=> New data set: 2022-08-02T113403Z

latest-json
```diff -u pjson/2022-08-02T113403Z.json pjson/2022-08-03T101303Z.json```:
```
--- pjson/2022-08-02T113403Z.json	2022-08-02 11:34:03.801805594 +0000
+++ pjson/2022-08-03T101303Z.json	2022-08-03 10:13:03.536391729 +0000
@@ -32148,7 +32148,7 @@
"Datum_neu": 1655942400000,
-        "F\u00e4lle_Meldedatum": 507,
+        "F\u00e4lle_Meldedatum": 508,
@@ -32186,7 +32186,7 @@
"Datum_neu": 1656028800000,
-        "F\u00e4lle_Meldedatum": 492,
+        "F\u00e4lle_Meldedatum": 493, …
```
=> New data set: 2022-08-03T101303Z

latest-json
```diff -u pjson/2022-08-03T101303Z.json pjson/2022-08-04T100303Z.json```:
```
--- pjson/2022-08-03T101303Z.json	2022-08-03 10:13:03.536391729 +0000
+++ pjson/2022-08-04T100303Z.json	2022-08-04 10:03:03.660444737 +0000
@@ -32414,7 +32414,7 @@
"Datum_neu": 1656547200000,
-        "F\u00e4lle_Meldedatum": 488,
+        "F\u00e4lle_Meldedatum": 490,
@@ -32680,7 +32680,7 @@
"Datum_neu": 1657152000000,
-        "F\u00e4lle_Meldedatum": 461,
+        "F\u00e4lle_Meldedatum": 462, …
```
=> New data set: 2022-08-04T100303Z

latest-json
```diff -u pjson/2022-08-04T100303Z.json pjson/2022-08-05T100703Z.json```:
```
--- pjson/2022-08-04T100303Z.json	2022-08-04 10:03:03.660444737 +0000
+++ pjson/2022-08-05T100703Z.json	2022-08-05 10:07:03.898792712 +0000
@@ -30020,7 +30020,7 @@
"Datum_neu": 1651104000000,
-        "F\u00e4lle_Meldedatum": 499,
+        "F\u00e4lle_Meldedatum": 501,
@@ -31958,7 +31958,7 @@
"Datum_neu": 1655510400000,
-        "F\u00e4lle_Meldedatum": 215,
+        "F\u00e4lle_Meldedatum": 216, …
```
=> New data set: 2022-08-05T100703Z

latest-json
```diff -u pjson/2022-08-05T100703Z.json pjson/2022-08-08T100203Z.json```:
```
--- pjson/2022-08-05T100703Z.json	2022-08-05 10:07:03.898792712 +0000
+++ pjson/2022-08-08T100203Z.json	2022-08-08 10:02:03.917848814 +0000
@@ -28082,7 +28082,7 @@
"Datum_neu": 1646697600000,
-        "F\u00e4lle_Meldedatum": 2085,
+        "F\u00e4lle_Meldedatum": 2086,
@@ -28386,7 +28386,7 @@
"Datum_neu": 1647388800000,
-        "F\u00e4lle_Meldedatum": 2805,
+        "F\u00e4lle_Meldedatum": 2806, …
```
=> New data set: 2022-08-08T100203Z

latest-json
```diff -u pjson/2022-08-08T100203Z.json pjson/2022-08-09T100403Z.json```:
```
--- pjson/2022-08-08T100203Z.json	2022-08-08 10:02:03.917848814 +0000
+++ pjson/2022-08-09T100403Z.json	2022-08-09 10:04:04.136536277 +0000
@@ -33136,7 +33136,7 @@
"Datum_neu": 1658188800000,
-        "F\u00e4lle_Meldedatum": 853,
+        "F\u00e4lle_Meldedatum": 854,
@@ -33402,7 +33402,7 @@
"Datum_neu": 1658793600000,
-        "F\u00e4lle_Meldedatum": 676,
+        "F\u00e4lle_Meldedatum": 675, …
```
=> New data set: 2022-08-09T100403Z

latest-json
```diff -u pjson/2022-08-09T100403Z.json pjson/2022-08-10T101603Z.json```:
```
--- pjson/2022-08-09T100403Z.json	2022-08-09 10:04:04.136536277 +0000
+++ pjson/2022-08-10T101603Z.json	2022-08-10 10:16:04.059472005 +0000
@@ -33174,7 +33174,7 @@
"Datum_neu": 1658275200000,
-        "F\u00e4lle_Meldedatum": 688,
+        "F\u00e4lle_Meldedatum": 689,
@@ -33212,7 +33212,7 @@
"Datum_neu": 1658361600000,
-        "F\u00e4lle_Meldedatum": 557,
+        "F\u00e4lle_Meldedatum": 562, …
```
=> New data set: 2022-08-10T101603Z

latest-json
```diff -u pjson/2022-08-10T101603Z.json pjson/2022-08-11T101303Z.json```:
```
--- pjson/2022-08-10T101603Z.json	2022-08-10 10:16:04.059472005 +0000
+++ pjson/2022-08-11T101303Z.json	2022-08-11 10:13:03.473827306 +0000
@@ -27284,7 +27284,7 @@
"Datum_neu": 1644883200000,
-        "F\u00e4lle_Meldedatum": 1250,
+        "F\u00e4lle_Meldedatum": 1249,
@@ -27398,7 +27398,7 @@
"Datum_neu": 1645142400000,
-        "F\u00e4lle_Meldedatum": 903,
+        "F\u00e4lle_Meldedatum": 902, …
```
=> New data set: 2022-08-11T101303Z

latest-json
```diff -u pjson/2022-08-11T101303Z.json pjson/2022-08-12T100903Z.json```:
```
--- pjson/2022-08-11T101303Z.json	2022-08-11 10:13:03.473827306 +0000
+++ pjson/2022-08-12T100903Z.json	2022-08-12 10:09:03.543631936 +0000
@@ -28500,7 +28500,7 @@
"Datum_neu": 1647648000000,
-        "F\u00e4lle_Meldedatum": 1530,
+        "F\u00e4lle_Meldedatum": 1529,
@@ -28614,7 +28614,7 @@
"Datum_neu": 1647907200000,
-        "F\u00e4lle_Meldedatum": 2969,
+        "F\u00e4lle_Meldedatum": 2968, …
```
=> New data set: 2022-08-12T100903Z

latest-json
```diff -u pjson/2022-08-12T100903Z.json pjson/2022-08-15T100303Z.json```:
```
--- pjson/2022-08-12T100903Z.json	2022-08-12 10:09:03.543631936 +0000
+++ pjson/2022-08-15T100303Z.json	2022-08-15 10:03:04.160963375 +0000
@@ -33668,7 +33668,7 @@
"Datum_neu": 1659398400000,
-        "F\u00e4lle_Meldedatum": 554,
+        "F\u00e4lle_Meldedatum": 555,
@@ -33780,12 +33780,12 @@
"Zuwachs_Genesung": 560,
-        "Inzidenz": 428.176299436043,
"Datum_neu": 1659657600000, …
```
=> New data set: 2022-08-15T100303Z

latest-json
```diff -u pjson/2022-08-16T100604Z.json pjson/2022-08-17T100104Z.json```:
```
--- pjson/2022-08-16T100604Z.json	2022-08-16 10:06:05.110407558 +0000
+++ pjson/2022-08-17T100104Z.json	2022-08-17 10:01:04.422154776 +0000
@@ -33034,7 +33034,7 @@
"Krh_I": null,
@@ -33490,7 +33490,7 @@
"Krh_I": null,
@@ …
```
=> New data set: 2022-08-17T100104Z

latest-json
```diff -u pjson/2022-08-17T100104Z.json pjson/2022-08-18T100703Z.json```:
```
--- pjson/2022-08-17T100104Z.json	2022-08-17 10:01:04.422154776 +0000
+++ pjson/2022-08-18T100703Z.json	2022-08-18 10:07:03.322084155 +0000
@@ -33970,12 +33970,12 @@
"Zuwachs_Genesung": 526,
-        "Inzidenz": 387.04694852545,
"Datum_neu": 1660089600000,
"F\u00e4lle_Meldedatum": 411,
-        "Inzidenz_RKI": 321.3,
@@ -33988,7 +33988,7 @@
"Inzi_SN_RKI": …
```
=> New data set: 2022-08-18T100703Z

latest-json
```diff -u pjson/2022-08-18T100703Z.json pjson/2022-08-19T095504Z.json```:
```
--- pjson/2022-08-18T100703Z.json	2022-08-18 10:07:03.322084155 +0000
+++ pjson/2022-08-19T095504Z.json	2022-08-19 09:55:04.973347016 +0000
@@ -33898,7 +33898,7 @@
"Datum_neu": 1659916800000,
"F\u00e4lle_Meldedatum": 463,
@@ -34013,7 +34013,7 @@
"F\u00e4lle_Meldedatum": 309,
-        "Inzidenz_RKI": 353.5, …
```
=> New data set: 2022-08-19T095504Z

latest-json
```diff -u pjson/2022-08-25T101603Z.json pjson/2022-08-26T100604Z.json```:
```
--- pjson/2022-08-25T101603Z.json	2022-08-25 10:16:03.531559686 +0000
+++ pjson/2022-08-26T100604Z.json	2022-08-26 10:06:04.322763052 +0000
@@ -34274,12 +34274,12 @@
"Zuwachs_Genesung": 332,
-        "Inzidenz": 351.305722188297,
"Datum_neu": 1660780800000,
"F\u00e4lle_Meldedatum": 279,
-        "Inzidenz_RKI": 315.9,
@@ -34292,7 +34292,7 @@
"Inzi_SN_RKI": …
```
=> New data set: 2022-08-26T100604Z

latest-json
```diff -u pjson/2022-08-26T100604Z.json pjson/2022-08-29T100204Z.json```:
```
--- pjson/2022-08-26T100604Z.json	2022-08-26 10:06:04.322763052 +0000
+++ pjson/2022-08-29T100204Z.json	2022-08-29 10:02:04.173733160 +0000
@@ -34162,7 +34162,7 @@
"Datum_neu": 1660521600000,
-        "F\u00e4lle_Meldedatum": 453,
+        "F\u00e4lle_Meldedatum": 454,
@@ -34312,12 +34312,12 @@
"Zuwachs_Genesung": 316,
-        "Inzidenz": 345.917597614857,
"Datum_neu": 1660867200000,
- …
```
=> New data set: 2022-08-29T100204Z

latest-json
```diff -u pjson/2022-08-29T100204Z.json pjson/2022-08-30T100904Z.json```:
```
--- pjson/2022-08-29T100204Z.json	2022-08-29 10:02:04.173733160 +0000
+++ pjson/2022-08-30T100904Z.json	2022-08-30 10:09:04.694157637 +0000
@@ -30932,7 +30932,7 @@
"Datum_neu": 1653177600000,
+        "F\u00e4lle_Meldedatum": 72,
@@ -34164,7 +34164,7 @@
"Datum_neu": 1660521600000,
"F\u00e4lle_Meldedatum": 454, …
```
=> New data set: 2022-08-30T100904Z

latest-json
```diff -u pjson/2022-08-30T100904Z.json pjson/2022-08-31T101303Z.json```:
```
--- pjson/2022-08-30T100904Z.json	2022-08-30 10:09:04.694157637 +0000
+++ pjson/2022-08-31T101303Z.json	2022-08-31 10:13:03.523207352 +0000
@@ -28652,7 +28652,7 @@
"Datum_neu": 1647993600000,
-        "F\u00e4lle_Meldedatum": 2137,
+        "F\u00e4lle_Meldedatum": 2136,
@@ -28690,7 +28690,7 @@
"Datum_neu": 1648080000000,
-        "F\u00e4lle_Meldedatum": 2199,
+        "F\u00e4lle_Meldedatum": 2198, …
```
=> New data set: 2022-08-31T101303Z

latest-json
```diff -u pjson/2022-08-31T101303Z.json pjson/2022-09-01T100504Z.json```:
```
--- pjson/2022-08-31T101303Z.json	2022-08-31 10:13:03.523207352 +0000
+++ pjson/2022-09-01T100504Z.json	2022-09-01 10:05:04.254895994 +0000
@@ -22572,7 +22572,7 @@
"Datum_neu": 1634169600000,
-        "F\u00e4lle_Meldedatum": 106,
+        "F\u00e4lle_Meldedatum": 105,
@@ -23028,7 +23028,7 @@
"Datum_neu": 1635206400000,
-        "F\u00e4lle_Meldedatum": 470,
+        "F\u00e4lle_Meldedatum": 471, …
```
=> New data set: 2022-09-01T100504Z

latest-json
```diff -u pjson/2022-09-01T100504Z.json pjson/2022-09-02T100203Z.json```:
```
--- pjson/2022-09-01T100504Z.json	2022-09-01 10:05:04.254895994 +0000
+++ pjson/2022-09-02T100203Z.json	2022-09-02 10:02:04.249668497 +0000
@@ -32034,7 +32034,7 @@
"Datum_neu": 1655683200000,
-        "F\u00e4lle_Meldedatum": 698,
+        "F\u00e4lle_Meldedatum": 699,
@@ -33782,7 +33782,7 @@
"Datum_neu": 1659657600000,
-        "F\u00e4lle_Meldedatum": 312,
+        "F\u00e4lle_Meldedatum": 311, …
```
=> New data set: 2022-09-02T100203Z

latest-json
```diff -u pjson/2022-09-02T100203Z.json pjson/2022-09-05T100504Z.json```:
```
--- pjson/2022-09-02T100203Z.json	2022-09-02 10:02:04.249668497 +0000
+++ pjson/2022-09-05T100504Z.json	2022-09-05 10:05:04.889830528 +0000
@@ -34088,7 +34088,7 @@
"Datum_neu": 1660348800000,
"F\u00e4lle_Meldedatum": 96,
@@ -34468,7 +34468,7 @@
"Datum_neu": 1661212800000,
"F\u00e4lle_Meldedatum": 312, …
```
=> New data set: 2022-09-05T100504Z

latest-json
```diff -u pjson/2022-09-05T100504Z.json pjson/2022-09-06T152004Z.json```:
```
--- pjson/2022-09-05T100504Z.json	2022-09-05 10:05:04.889830528 +0000
+++ pjson/2022-09-06T152004Z.json	2022-09-06 15:20:05.296539478 +0000
@@ -34692,12 +34692,12 @@
"Zuwachs_Genesung": 440,
-        "Inzidenz": 279.643665361543,
"Datum_neu": 1661731200000,
"F\u00e4lle_Meldedatum": 357,
-        "Inzidenz_RKI": 235,
@@ -34710,7 +34710,7 @@
"Inzi_SN_RKI": …
```
=> New data set: 2022-09-06T152004Z

latest-json
```diff -u pjson/2022-09-06T152004Z.json pjson/2022-09-07T100103Z.json```:
```
--- pjson/2022-09-06T152004Z.json	2022-09-06 15:20:05.296539478 +0000
+++ pjson/2022-09-07T100103Z.json	2022-09-07 10:01:03.878922226 +0000
@@ -32834,7 +32834,7 @@
"Datum_neu": 1657497600000,
"F\u00e4lle_Meldedatum": 786,
-        "Hosp_Meldedatum": 18,
+        "Hosp_Meldedatum": 20,
@@ -32948,7 +32948,7 @@
"Datum_neu": 1657756800000,
"F\u00e4lle_Meldedatum": 267,
+        "Hosp_Meldedatum": 13, …
```
=> New data set: 2022-09-07T100103Z

latest-json
```diff -u pjson/2022-09-07T100103Z.json pjson/2022-09-08T101004Z.json```:
```
--- pjson/2022-09-07T100103Z.json	2022-09-07 10:01:03.878922226 +0000
+++ pjson/2022-09-08T101004Z.json	2022-09-08 10:10:04.897710211 +0000
@@ -33214,7 +33214,7 @@
"Datum_neu": 1658361600000,
"F\u00e4lle_Meldedatum": 562,
@@ -34010,7 +34010,7 @@
"Datum_neu": 1660176000000,
-        "F\u00e4lle_Meldedatum": 309,
+        "F\u00e4lle_Meldedatum": 307, …
```
=> New data set: 2022-09-08T101004Z

latest-json
```diff -u pjson/2022-09-08T101004Z.json pjson/2022-09-09T100404Z.json```:
```
--- pjson/2022-09-08T101004Z.json	2022-09-08 10:10:04.897710211 +0000
+++ pjson/2022-09-09T100404Z.json	2022-09-09 10:04:04.440853268 +0000
@@ -31882,7 +31882,7 @@
"Datum_neu": 1655337600000,
-        "F\u00e4lle_Meldedatum": 452,
+        "F\u00e4lle_Meldedatum": 453,
@@ -31920,7 +31920,7 @@
"Datum_neu": 1655424000000,
-        "F\u00e4lle_Meldedatum": 384,
+        "F\u00e4lle_Meldedatum": 383, …
```
=> New data set: 2022-09-09T100404Z

latest-json
```diff -u pjson/2022-09-09T100404Z.json pjson/2022-09-12T095804Z.json```:
```
--- pjson/2022-09-09T100404Z.json	2022-09-09 10:04:04.440853268 +0000
+++ pjson/2022-09-12T095804Z.json	2022-09-12 09:58:04.408161078 +0000
@@ -14630,7 +14630,7 @@
"Datum_neu": 1616112000000,
-        "F\u00e4lle_Meldedatum": 114,
+        "F\u00e4lle_Meldedatum": 113,
@@ -14858,7 +14858,7 @@
-        "F\u00e4lle_Meldedatum": 189,
+        "F\u00e4lle_Meldedatum": 190, …
```
=> New data set: 2022-09-12T095804Z

latest-json
```diff -u pjson/2022-09-12T095804Z.json pjson/2022-09-13T095604Z.json```:
```
--- pjson/2022-09-12T095804Z.json	2022-09-12 09:58:04.408161078 +0000
+++ pjson/2022-09-13T095604Z.json	2022-09-13 09:56:04.404137192 +0000
@@ -33478,7 +33478,7 @@
"Datum_neu": 1658966400000,
-        "F\u00e4lle_Meldedatum": 373,
+        "F\u00e4lle_Meldedatum": 374,
@@ -34200,7 +34200,7 @@
"Datum_neu": 1660608000000,
-        "F\u00e4lle_Meldedatum": 419,
+        "F\u00e4lle_Meldedatum": 418, …
```
=> New data set: 2022-09-13T095604Z

latest-json
```diff -u pjson/2022-09-14T100604Z.json pjson/2022-09-15T100403Z.json```:
```
--- pjson/2022-09-14T100604Z.json	2022-09-14 10:06:04.912075307 +0000
+++ pjson/2022-09-15T100403Z.json	2022-09-15 10:04:04.268061143 +0000
@@ -32986,7 +32986,7 @@
"Datum_neu": 1657843200000,
"F\u00e4lle_Meldedatum": 1123,
+        "Hosp_Meldedatum": 25,
@@ -33756,7 +33756,7 @@
"Krh_I": null, …
```
=> New data set: 2022-09-15T100403Z

latest-json
```diff -u pjson/2022-09-15T100403Z.json pjson/2022-09-16T100204Z.json```:
```
--- pjson/2022-09-15T100403Z.json	2022-09-15 10:04:04.268061143 +0000
+++ pjson/2022-09-16T100204Z.json	2022-09-16 10:02:04.484726935 +0000
@@ -31806,7 +31806,7 @@
"Datum_neu": 1655164800000,
-        "F\u00e4lle_Meldedatum": 529,
+        "F\u00e4lle_Meldedatum": 528,
@@ -33832,7 +33832,7 @@
"Krh_I": null, …
```
=> New data set: 2022-09-16T100204Z

latest-json
```diff -u pjson/2022-09-16T100204Z.json pjson/2022-09-19T100703Z.json```:
```
--- pjson/2022-09-16T100204Z.json	2022-09-16 10:02:04.484726935 +0000
+++ pjson/2022-09-19T100703Z.json	2022-09-19 10:07:04.271723525 +0000
@@ -35036,7 +35036,7 @@
"Datum_neu": 1662508800000,
-        "F\u00e4lle_Meldedatum": 262,
+        "F\u00e4lle_Meldedatum": 263,
@@ -35072,7 +35072,7 @@
"Zuwachs_Genesung": 279,
-        "Inzidenz": 276.769998922375,
"Datum_neu": 1662595200000, …
```
=> New data set: 2022-09-19T100703Z

latest-json
```diff -u pjson/2022-09-19T100703Z.json pjson/2022-09-20T100203Z.json```:
```
--- pjson/2022-09-19T100703Z.json	2022-09-19 10:07:04.271723525 +0000
+++ pjson/2022-09-20T100203Z.json	2022-09-20 10:02:04.283002908 +0000
@@ -35074,7 +35074,7 @@
"Datum_neu": 1662595200000,
-        "F\u00e4lle_Meldedatum": 247,
+        "F\u00e4lle_Meldedatum": 248,
@@ -35188,7 +35188,7 @@
"Datum_neu": 1662854400000,
-        "F\u00e4lle_Meldedatum": 46,
+        "F\u00e4lle_Meldedatum": 47, …
```
=> New data set: 2022-09-20T100203Z

latest-json
```diff -u pjson/2022-09-20T100203Z.json pjson/2022-09-21T101004Z.json```:
```
--- pjson/2022-09-20T100203Z.json	2022-09-20 10:02:04.283002908 +0000
+++ pjson/2022-09-21T101004Z.json	2022-09-21 10:10:04.587759724 +0000
@@ -34386,7 +34386,7 @@
-        "Zuwachs_Genesung": 100,
+        "Zuwachs_Genesung": 95,
"Datum_neu": 1661040000000,
@@ -34652,7 +34652,7 @@
-        "Zuwachs_Genesung": 82,
+        "Zuwachs_Genesung": 81, …
```
=> New data set: 2022-09-21T101004Z

latest-json
```diff -u pjson/2022-09-22T100803Z.json pjson/2022-09-23T101103Z.json```:
```
--- pjson/2022-09-22T100803Z.json	2022-09-22 10:08:04.267987391 +0000
+++ pjson/2022-09-23T101103Z.json	2022-09-23 10:11:04.258924241 +0000
@@ -35262,7 +35262,7 @@
"Zuwachs_Genesung": 318,
-        "Inzidenz": 269.406228672007,
"Datum_neu": 1663027200000,
"F\u00e4lle_Meldedatum": 383,
@@ -35300,7 +35300,7 @@
"Zuwachs_Genesung": 226,
-        "Inzidenz": 288.264664679047,
"Datum_neu": …
```
=> New data set: 2022-09-23T101103Z

latest-json
```diff -u pjson/2022-09-23T101103Z.json pjson/2022-09-26T100604Z.json```:
```
--- pjson/2022-09-23T101103Z.json	2022-09-23 10:11:04.258924241 +0000
+++ pjson/2022-09-26T100604Z.json	2022-09-26 10:06:04.786122754 +0000
@@ -35338,12 +35338,12 @@
"Zuwachs_Genesung": 249,
-        "Inzidenz": 282.696935953159,
"Datum_neu": 1663200000000,
"F\u00e4lle_Meldedatum": 341,
-        "Inzidenz_RKI": 251.5,
@@ -35356,7 +35356,7 @@
"Inzi_SN_RKI": …
```
=> New data set: 2022-09-26T100604Z

latest-json
```diff -u pjson/2022-09-26T100604Z.json pjson/2022-09-27T095804Z.json```:
```
--- pjson/2022-09-26T100604Z.json	2022-09-26 10:06:04.786122754 +0000
+++ pjson/2022-09-27T095804Z.json	2022-09-27 09:58:05.027143517 +0000
@@ -34846,7 +34846,7 @@
"Datum_neu": 1662076800000,
-        "F\u00e4lle_Meldedatum": 235,
+        "F\u00e4lle_Meldedatum": 236,
@@ -34998,7 +34998,7 @@
"Datum_neu": 1662422400000,
-        "F\u00e4lle_Meldedatum": 298,
+        "F\u00e4lle_Meldedatum": 299, …
```
=> New data set: 2022-09-27T095804Z

latest-json
```diff -u pjson/2022-09-27T095804Z.json pjson/2022-09-28T100103Z.json```:
```
--- pjson/2022-09-27T095804Z.json	2022-09-27 09:58:05.027143517 +0000
+++ pjson/2022-09-28T100103Z.json	2022-09-28 10:01:04.286812570 +0000
@@ -35492,10 +35492,10 @@
"Inzidenz": 305.506663314056,
-        "F\u00e4lle_Meldedatum": 380,
+        "F\u00e4lle_Meldedatum": 381,
-        "Inzidenz_RKI": 247,
@@ -35508,7 +35508,7 @@
- …
```
=> New data set: 2022-09-28T100103Z

latest-json
```diff -u pjson/2022-09-28T100103Z.json pjson/2022-09-29T100403Z.json```:
```
--- pjson/2022-09-28T100103Z.json	2022-09-28 10:01:04.286812570 +0000
+++ pjson/2022-09-29T100403Z.json	2022-09-29 10:04:04.346463252 +0000
@@ -34012,7 +34012,7 @@
"Datum_neu": 1660176000000,
"F\u00e4lle_Meldedatum": 307,
@@ -34164,7 +34164,7 @@
"Datum_neu": 1660521600000,
"F\u00e4lle_Meldedatum": 454,
-        "Hosp_Meldedatum": 15,
+        "Hosp_Meldedatum": 16, …
```
=> New data set: 2022-09-29T100403Z

latest-json
```diff -u pjson/2022-09-29T100403Z.json pjson/2022-09-30T094604Z.json```:
```
--- pjson/2022-09-29T100403Z.json	2022-09-29 10:04:04.346463252 +0000
+++ pjson/2022-09-30T094604Z.json	2022-09-30 09:46:04.418190330 +0000
@@ -33896,7 +33896,7 @@
"Datum_neu": 1659916800000,
-        "F\u00e4lle_Meldedatum": 464,
+        "F\u00e4lle_Meldedatum": 463,
@@ -33934,7 +33934,7 @@
"Datum_neu": 1660003200000,
-        "F\u00e4lle_Meldedatum": 458,
+        "F\u00e4lle_Meldedatum": 459, …
```
=> New data set: 2022-09-30T094604Z

latest-json
```diff -u pjson/2022-10-04T110403Z.json pjson/2022-10-05T101404Z.json```:
```
--- pjson/2022-10-04T110403Z.json	2022-10-04 11:04:04.116543450 +0000
+++ pjson/2022-10-05T101404Z.json	2022-10-05 10:14:04.687520890 +0000
@@ -35264,7 +35264,7 @@
"Datum_neu": 1663027200000,
-        "F\u00e4lle_Meldedatum": 387,
+        "F\u00e4lle_Meldedatum": 388,
@@ -35416,7 +35416,7 @@
"Datum_neu": 1663372800000,
-        "F\u00e4lle_Meldedatum": 96,
+        "F\u00e4lle_Meldedatum": 97, …
```
=> New data set: 2022-10-05T101404Z

latest-json
```diff -u pjson/2022-10-05T101404Z.json pjson/2022-10-06T101303Z.json```:
```
--- pjson/2022-10-05T101404Z.json	2022-10-05 10:14:04.687520890 +0000
+++ pjson/2022-10-06T101303Z.json	2022-10-06 10:13:04.012300847 +0000
@@ -35264,7 +35264,7 @@
"Datum_neu": 1663027200000,
-        "F\u00e4lle_Meldedatum": 388,
+        "F\u00e4lle_Meldedatum": 389,
@@ -35494,7 +35494,7 @@
"F\u00e4lle_Meldedatum": 381, …
```
=> New data set: 2022-10-06T101303Z

latest-json
```diff -u pjson/2022-10-06T101303Z.json pjson/2022-10-07T103904Z.json```:
```
--- pjson/2022-10-06T101303Z.json	2022-10-06 10:13:04.012300847 +0000
+++ pjson/2022-10-07T103904Z.json	2022-10-07 10:39:04.585273582 +0000
@@ -35532,7 +35532,7 @@
"Datum_neu": 1663632000000,
"F\u00e4lle_Meldedatum": 365,
-        "Hosp_Meldedatum": 9,
@@ -35570,7 +35570,7 @@
"Datum_neu": 1663718400000,
"F\u00e4lle_Meldedatum": 328,
+        "Hosp_Meldedatum": 8, …
```
=> New data set: 2022-10-07T103904Z

latest-json
```diff -u pjson/2022-10-07T103904Z.json pjson/2022-10-10T100403Z.json```:
```
--- pjson/2022-10-07T103904Z.json	2022-10-07 10:39:04.585273582 +0000
+++ pjson/2022-10-10T100403Z.json	2022-10-10 10:04:03.914356377 +0000
@@ -35908,12 +35908,12 @@
"Zuwachs_Genesung": 252,
-        "Inzidenz": 461.2,
"Datum_neu": 1664496000000,
"F\u00e4lle_Meldedatum": 481,
-        "Inzidenz_RKI": 401.9,
@@ -35926,7 +35926,7 @@ …
```
=> New data set: 2022-10-10T100403Z

latest-json
```diff -u pjson/2022-10-10T100403Z.json pjson/2022-10-11T102504Z.json```:
```
--- pjson/2022-10-10T100403Z.json	2022-10-10 10:04:03.914356377 +0000
+++ pjson/2022-10-11T102504Z.json	2022-10-11 10:25:04.655229466 +0000
@@ -35872,7 +35872,7 @@
"Datum_neu": 1664409600000,
-        "F\u00e4lle_Meldedatum": 449,
+        "F\u00e4lle_Meldedatum": 451,
@@ -35910,7 +35910,7 @@
"Datum_neu": 1664496000000,
-        "F\u00e4lle_Meldedatum": 481,
+        "F\u00e4lle_Meldedatum": 479, …
```
=> New data set: 2022-10-11T102504Z

latest-json
```diff -u pjson/2022-10-11T102504Z.json pjson/2022-10-12T101103Z.json```:
```
--- pjson/2022-10-11T102504Z.json	2022-10-11 10:25:04.655229466 +0000
+++ pjson/2022-10-12T101103Z.json	2022-10-12 10:11:03.903047262 +0000
@@ -35454,7 +35454,7 @@
"Datum_neu": 1663459200000,
-        "F\u00e4lle_Meldedatum": 54,
+        "F\u00e4lle_Meldedatum": 55,
-        "F\u00e4lle_Meldedatum": 381,
+        "F\u00e4lle_Meldedatum": 380, …
```
=> New data set: 2022-10-12T101103Z

latest-json
```diff -u pjson/2022-10-13T101303Z.json pjson/2022-10-14T100804Z.json```:
```
--- pjson/2022-10-13T101303Z.json	2022-10-13 10:13:03.993738867 +0000
+++ pjson/2022-10-14T100804Z.json	2022-10-14 10:08:04.652761943 +0000
@@ -35758,7 +35758,7 @@
"Datum_neu": 1664150400000,
-        "F\u00e4lle_Meldedatum": 538,
+        "F\u00e4lle_Meldedatum": 539,
@@ -35872,7 +35872,7 @@
"Datum_neu": 1664409600000,
-        "F\u00e4lle_Meldedatum": 450,
+        "F\u00e4lle_Meldedatum": 448, …
```
=> New data set: 2022-10-14T100804Z

latest-json
```diff -u pjson/2022-10-17T110604Z.json pjson/2022-10-18T101103Z.json```:
```
--- pjson/2022-10-17T110604Z.json	2022-10-17 11:06:04.398867210 +0000
+++ pjson/2022-10-18T101103Z.json	2022-10-18 10:11:04.333229608 +0000
@@ -31846,7 +31846,7 @@
"Datum_neu": 1655251200000,
"F\u00e4lle_Meldedatum": 368,
@@ -31884,7 +31884,7 @@
"Datum_neu": 1655337600000,
"F\u00e4lle_Meldedatum": 453,
+        "Hosp_Meldedatum": 6, …
```
=> New data set: 2022-10-18T101103Z

latest-json
```diff -u pjson/2022-10-18T101103Z.json pjson/2022-10-19T095603Z.json```:
```
--- pjson/2022-10-18T101103Z.json	2022-10-18 10:11:04.333229608 +0000
+++ pjson/2022-10-19T095603Z.json	2022-10-19 09:56:03.874656766 +0000
@@ -34732,7 +34732,7 @@
"Datum_neu": 1661817600000,
-        "F\u00e4lle_Meldedatum": 315,
+        "F\u00e4lle_Meldedatum": 314,
@@ -35378,7 +35378,7 @@
"Datum_neu": 1663286400000,
-        "F\u00e4lle_Meldedatum": 254,
+        "F\u00e4lle_Meldedatum": 253, …
```
=> New data set: 2022-10-19T095603Z

latest-json
```diff -u pjson/2022-10-21T100004Z.json pjson/2022-10-24T101403Z.json```:
```
--- pjson/2022-10-21T100004Z.json	2022-10-21 10:00:04.429232877 +0000
+++ pjson/2022-10-24T101403Z.json	2022-10-24 10:14:04.274161291 +0000
@@ -36064,7 +36064,7 @@
"Datum_neu": 1664841600000,
"F\u00e4lle_Meldedatum": 859,
-        "Hosp_Meldedatum": 33,
+        "Hosp_Meldedatum": 32,
@@ -36138,7 +36138,7 @@
"Datum_neu": 1665014400000,
-        "F\u00e4lle_Meldedatum": 637,
+        "F\u00e4lle_Meldedatum": 638, …
```
=> New data set: 2022-10-24T101403Z

latest-json
```diff -u pjson/2022-10-24T101403Z.json pjson/2022-10-25T095804Z.json```:
```
--- pjson/2022-10-24T101403Z.json	2022-10-24 10:14:04.274161291 +0000
+++ pjson/2022-10-25T095804Z.json	2022-10-25 09:58:04.947310529 +0000
-        "F\u00e4lle_Meldedatum": 380,
+        "F\u00e4lle_Meldedatum": 381,
@@ -36442,9 +36442,9 @@
"Datum_neu": 1665705600000,
-        "F\u00e4lle_Meldedatum": 527,
+        "F\u00e4lle_Meldedatum": 528,
- …
```
=> New data set: 2022-10-25T095804Z

latest-json
```diff -u pjson/2022-10-25T095804Z.json pjson/2022-10-26T100004Z.json```:
```
--- pjson/2022-10-25T095804Z.json	2022-10-25 09:58:04.947310529 +0000
+++ pjson/2022-10-26T100004Z.json	2022-10-26 10:00:04.741561879 +0000
@@ -33592,7 +33592,7 @@
"Datum_neu": 1659225600000,
-        "F\u00e4lle_Meldedatum": 58,
+        "F\u00e4lle_Meldedatum": 59,
@@ -33668,7 +33668,7 @@
"Datum_neu": 1659398400000,
-        "F\u00e4lle_Meldedatum": 554,
+        "F\u00e4lle_Meldedatum": 553, …
```
=> New data set: 2022-10-26T100004Z

latest-json
```diff -u pjson/2022-10-26T100004Z.json pjson/2022-10-27T100504Z.json```:
```
--- pjson/2022-10-26T100004Z.json	2022-10-26 10:00:04.741561879 +0000
+++ pjson/2022-10-27T100504Z.json	2022-10-27 10:05:04.703710414 +0000
@@ -36592,7 +36592,7 @@
"Zuwachs_Genesung": 850,
-        "Inzidenz": 588.203599267215,
"Datum_neu": 1666051200000,
"F\u00e4lle_Meldedatum": 718,
@@ -36630,15 +36630,15 @@
"Zuwachs_Genesung": 911,
-        "Inzidenz": 605.80480620712,
"Datum_neu": …
```
=> New data set: 2022-10-27T100504Z

latest-json
```diff -u pjson/2022-10-27T100504Z.json pjson/2022-10-28T100104Z.json```:
```
--- pjson/2022-10-27T100504Z.json	2022-10-27 10:05:04.703710414 +0000
+++ pjson/2022-10-28T100104Z.json	2022-10-28 10:01:05.061823221 +0000
-        "F\u00e4lle_Meldedatum": 381,
+        "F\u00e4lle_Meldedatum": 380,
@@ -36378,7 +36378,7 @@
"Krh_I": null, …
```
=> New data set: 2022-10-28T100104Z

latest-json
```diff -u pjson/2022-10-28T100104Z.json pjson/2022-11-01T105904Z.json```:
```
--- pjson/2022-10-28T100104Z.json	2022-10-28 10:01:05.061823221 +0000
+++ pjson/2022-11-01T105904Z.json	2022-11-01 10:59:04.859035673 +0000
-        "F\u00e4lle_Meldedatum": 380,
+        "F\u00e4lle_Meldedatum": 381,
@@ -35872,7 +35872,7 @@
"Datum_neu": 1664409600000,
-        "F\u00e4lle_Meldedatum": 448,
+        "F\u00e4lle_Meldedatum": 449, …
```
=> New data set: 2022-11-01T105904Z

latest-json
```diff -u pjson/2022-11-02T110304Z.json pjson/2022-11-03T105708Z.json```:
```
--- pjson/2022-11-02T110304Z.json	2022-11-02 11:03:04.950746252 +0000
+++ pjson/2022-11-03T105708Z.json	2022-11-03 10:57:08.565528313 +0000
@@ -36746,7 +36746,7 @@
"Datum_neu": 1666396800000,
-        "F\u00e4lle_Meldedatum": 196,
+        "F\u00e4lle_Meldedatum": 194,
@@ -36901,10 +36901,10 @@
"F\u00e4lle_Meldedatum": 374,
-        "Inzidenz_RKI": 404.4,
-        "Krh_N_belegt": 1189,
- …
```
=> New data set: 2022-11-03T105708Z

latest-json
```diff -u pjson/2022-11-04T105505Z.json pjson/2022-11-07T110504Z.json```:
```
--- pjson/2022-11-04T105505Z.json	2022-11-04 10:55:05.744340253 +0000
+++ pjson/2022-11-07T110504Z.json	2022-11-07 11:05:04.599280821 +0000
-        "F\u00e4lle_Meldedatum": 381,
+        "F\u00e4lle_Meldedatum": 382,
@@ -36328,7 +36328,7 @@
"Datum_neu": 1665446400000,
-        "F\u00e4lle_Meldedatum": 808,
+        "F\u00e4lle_Meldedatum": 809,
"Hosp_Meldedatum": 30, …
```
=> New data set: 2022-11-07T110504Z

latest-json
```diff -u pjson/2022-11-08T110304Z.json pjson/2022-11-09T112903Z.json```:
```
--- pjson/2022-11-08T110304Z.json	2022-11-08 11:03:05.405205889 +0000
+++ pjson/2022-11-09T112903Z.json	2022-11-09 11:29:03.785868177 +0000
@@ -23484,7 +23484,7 @@
"Datum_neu": 1636243200000,
-        "F\u00e4lle_Meldedatum": 229,
+        "F\u00e4lle_Meldedatum": 230,
@@ -23750,7 +23750,7 @@
"Datum_neu": 1636848000000,
-        "F\u00e4lle_Meldedatum": 294,
+        "F\u00e4lle_Meldedatum": 293, …
```
=> New data set: 2022-11-09T112903Z

latest-json
```diff -u pjson/2022-11-09T112903Z.json pjson/2022-11-10T114005Z.json```:
```
--- pjson/2022-11-09T112903Z.json	2022-11-09 11:29:03.785868177 +0000
+++ pjson/2022-11-10T114005Z.json	2022-11-10 11:40:05.450763738 +0000
@@ -33632,7 +33632,7 @@
"Datum_neu": 1659312000000,
"F\u00e4lle_Meldedatum": 573,
-        "Hosp_Meldedatum": 30,
@@ -34886,7 +34886,7 @@
"Datum_neu": 1662163200000,
"F\u00e4lle_Meldedatum": 108, …
```
=> New data set: 2022-11-10T114005Z

latest-json
```diff -u pjson/2022-11-10T115703Z.json pjson/2022-11-11T112204Z.json```:
```
--- pjson/2022-11-10T115703Z.json	2022-11-10 11:57:04.287498203 +0000
+++ pjson/2022-11-11T112204Z.json	2022-11-11 11:22:04.584447387 +0000
@@ -33632,7 +33632,7 @@
"Datum_neu": 1659312000000,
"F\u00e4lle_Meldedatum": 573,
-        "Hosp_Meldedatum": 30,
@@ -34352,7 +34352,7 @@
"Datum_neu": 1660953600000,
-        "F\u00e4lle_Meldedatum": 87,
+        "F\u00e4lle_Meldedatum": 88, …
```
=> New data set: 2022-11-11T112204Z

latest-json
```diff -u pjson/2022-11-14T104904Z.json pjson/2022-11-15T100703Z.json```:
```
--- pjson/2022-11-14T104904Z.json	2022-11-14 10:49:04.731345190 +0000
+++ pjson/2022-11-15T100703Z.json	2022-11-15 10:07:04.274970218 +0000
@@ -36896,7 +36896,7 @@
"Zuwachs_Genesung": 609,
-        "Inzidenz": 456.194547217932,
"Datum_neu": 1666742400000,
"F\u00e4lle_Meldedatum": 371,
@@ -36934,7 +36934,7 @@
"Zuwachs_Genesung": 548,
-        "Inzidenz": 449.728797729804,
"Datum_neu": …
```
=> New data set: 2022-11-15T100703Z

latest-json
```diff -u pjson/2022-11-17T105704Z.json pjson/2022-11-18T115504Z.json```:
```
--- pjson/2022-11-17T105704Z.json	2022-11-17 10:57:04.633636316 +0000
+++ pjson/2022-11-18T115504Z.json	2022-11-18 11:55:04.572063880 +0000
@@ -37314,7 +37314,7 @@
"Zuwachs_Genesung": null,
-        "Inzidenz": 275.333165702791,
"Datum_neu": 1667692800000,
"F\u00e4lle_Meldedatum": 43,
@@ -37352,7 +37352,7 @@
"Zuwachs_Genesung": 809,
-        "Inzidenz": 265.095729013255,
"Datum_neu": …
```
=> New data set: 2022-11-18T115504Z

latest-json
```diff -u pjson/2022-11-18T115504Z.json pjson/2022-11-21T125304Z.json```:
```
--- pjson/2022-11-18T115504Z.json	2022-11-18 11:55:04.572063880 +0000
+++ pjson/2022-11-21T125304Z.json	2022-11-21 12:53:04.746945728 +0000
@@ -37392,7 +37392,7 @@
"Datum_neu": 1667865600000,
-        "F\u00e4lle_Meldedatum": 209,
+        "F\u00e4lle_Meldedatum": 210,
@@ -37430,7 +37430,7 @@
"Datum_neu": 1667952000000, …
```
=> New data set: 2022-11-21T125304Z

latest-json
```diff -u pjson/2022-11-21T125304Z.json pjson/2022-11-22T110504Z.json```:
```
--- pjson/2022-11-21T125304Z.json	2022-11-21 12:53:04.746945728 +0000
+++ pjson/2022-11-22T110504Z.json	2022-11-22 11:05:04.719374117 +0000
@@ -36404,7 +36404,7 @@
"Datum_neu": 1665619200000,
-        "F\u00e4lle_Meldedatum": 546,
+        "F\u00e4lle_Meldedatum": 547,
@@ -36708,7 +36708,7 @@
"Datum_neu": 1666310400000,
-        "F\u00e4lle_Meldedatum": 411,
+        "F\u00e4lle_Meldedatum": 412, …
```
=> New data set: 2022-11-22T110504Z

latest-json
```diff -u pjson/2022-11-22T110504Z.json pjson/2022-11-23T110103Z.json```:
```
--- pjson/2022-11-22T110504Z.json	2022-11-22 11:05:04.719374117 +0000
+++ pjson/2022-11-23T110103Z.json	2022-11-23 11:01:04.071086138 +0000
@@ -37656,15 +37656,15 @@
"Zuwachs_Genesung": 403,
-        "Inzidenz": 143.324113653508,
"Datum_neu": 1668470400000,
+        "F\u00e4lle_Meldedatum": 139,
-        "Inzidenz_RKI": 123.9,
-        "Krh_N_belegt": 757,
- …
```
=> New data set: 2022-11-23T110103Z

latest-json
```diff -u pjson/2022-11-23T110103Z.json pjson/2022-11-24T111403Z.json```:
```
--- pjson/2022-11-23T110103Z.json	2022-11-23 11:01:04.071086138 +0000
+++ pjson/2022-11-24T111403Z.json	2022-11-24 11:14:04.031120505 +0000
@@ -37202,7 +37202,7 @@
"Datum_neu": 1667433600000,
-        "F\u00e4lle_Meldedatum": 315,
+        "F\u00e4lle_Meldedatum": 314,
@@ -37240,7 +37240,7 @@
"Datum_neu": 1667520000000,
-        "F\u00e4lle_Meldedatum": 206,
+        "F\u00e4lle_Meldedatum": 205, …
```
=> New data set: 2022-11-24T111403Z

latest-json
```diff -u pjson/2022-11-24T111403Z.json pjson/2022-11-25T110204Z.json```:
```
--- pjson/2022-11-24T111403Z.json	2022-11-24 11:14:04.031120505 +0000
+++ pjson/2022-11-25T110204Z.json	2022-11-25 11:02:04.849079880 +0000
@@ -36556,7 +36556,7 @@
"Datum_neu": 1665964800000,
-        "F\u00e4lle_Meldedatum": 662,
+        "F\u00e4lle_Meldedatum": 661,
@@ -36594,7 +36594,7 @@
"Datum_neu": 1666051200000,
-        "F\u00e4lle_Meldedatum": 721,
+        "F\u00e4lle_Meldedatum": 722, …
```
=> New data set: 2022-11-25T110204Z

latest-json
```diff -u pjson/2022-11-25T110204Z.json pjson/2022-11-28T115004Z.json```:
```
--- pjson/2022-11-25T110204Z.json	2022-11-25 11:02:04.849079880 +0000
+++ pjson/2022-11-28T115004Z.json	2022-11-28 11:50:04.452210096 +0000
@@ -36064,7 +36064,7 @@
"Datum_neu": 1664841600000,
"F\u00e4lle_Meldedatum": 859,
-        "Hosp_Meldedatum": 32,
+        "Hosp_Meldedatum": 30,
@@ -36292,7 +36292,7 @@
"Datum_neu": 1665360000000,
"F\u00e4lle_Meldedatum": 866,
-        "Hosp_Meldedatum": 40,
+        "Hosp_Meldedatum": 37, …
```
=> New data set: 2022-11-28T115004Z

latest-json
```diff -u pjson/2022-11-28T115004Z.json pjson/2022-11-29T112803Z.json```:
```
--- pjson/2022-11-28T115004Z.json	2022-11-28 11:50:04.452210096 +0000
+++ pjson/2022-11-29T112803Z.json	2022-11-29 11:28:04.307778623 +0000
@@ -37732,7 +37732,7 @@
"Zuwachs_Genesung": 670,
-        "Inzidenz": 115.3,
"Datum_neu": 1668643200000,
"F\u00e4lle_Meldedatum": 102,
@@ -37770,9 +37770,9 @@
"Zuwachs_Genesung": 215,
-        "Inzidenz": 110.636157907971,
"Datum_neu": 1668729600000,
- …
```
=> New data set: 2022-11-29T112803Z

latest-json
```diff -u pjson/2022-11-30T110603Z.json pjson/2022-12-01T110304Z.json```:
```
--- pjson/2022-11-30T110603Z.json	2022-11-30 11:06:04.395552371 +0000
+++ pjson/2022-12-01T110304Z.json	2022-12-01 11:03:04.863294044 +0000
@@ -37164,7 +37164,7 @@
"Datum_neu": 1667347200000,
-        "F\u00e4lle_Meldedatum": 343,
+        "F\u00e4lle_Meldedatum": 342,
@@ -37964,7 +37964,7 @@
"Datum_neu": 1669161600000,
"F\u00e4lle_Meldedatum": 147,
+        "Hosp_Meldedatum": 7,
"Inzidenz_RKI": 89.3, …
```
=> New data set: 2022-12-01T110304Z

latest-json
```diff -u pjson/2022-12-01T110304Z.json pjson/2022-12-02T110403Z.json```:
```
--- pjson/2022-12-01T110304Z.json	2022-12-01 11:03:04.863294044 +0000
+++ pjson/2022-12-02T110403Z.json	2022-12-02 11:04:04.354232701 +0000
@@ -36176,7 +36176,7 @@
"Datum_neu": 1665100800000,
-        "F\u00e4lle_Meldedatum": 669,
+        "F\u00e4lle_Meldedatum": 668,
@@ -37734,7 +37734,7 @@
"Datum_neu": 1668643200000,
-        "F\u00e4lle_Meldedatum": 102,
+        "F\u00e4lle_Meldedatum": 103, …
```
=> New data set: 2022-12-02T110403Z

latest-json
```diff -u pjson/2022-12-05T110404Z.json pjson/2022-12-06T105004Z.json```:
```
--- pjson/2022-12-05T110404Z.json	2022-12-05 11:04:04.557183204 +0000
+++ pjson/2022-12-06T105004Z.json	2022-12-06 10:50:05.343947765 +0000
@@ -37962,7 +37962,7 @@
"Datum_neu": 1669161600000,
-        "F\u00e4lle_Meldedatum": 147,
+        "F\u00e4lle_Meldedatum": 146,
@@ -38036,7 +38036,7 @@
"Zuwachs_Genesung": 108,
-        "Inzidenz": 112.3,
"Datum_neu": 1669334400000, …
```
=> New data set: 2022-12-06T105004Z

latest-json
```diff -u pjson/2022-12-06T105004Z.json pjson/2022-12-07T111603Z.json```:
```
--- pjson/2022-12-06T105004Z.json	2022-12-06 10:50:05.343947765 +0000
+++ pjson/2022-12-07T111603Z.json	2022-12-07 11:16:04.067330021 +0000
@@ -38306,7 +38306,7 @@
"Datum_neu": 1669939200000,
"F\u00e4lle_Meldedatum": 123,
"Inzidenz_RKI": 128.4,
"Krh_N_belegt": 637,
@@ -38342,7 +38342,7 @@
"Inzidenz": 134.703114336003,
"Datum_neu": 1670025600000,
-        "F\u00e4lle_Meldedatum": 60,
+        "F\u00e4lle_Meldedatum": 61,
"Hosp_Meldedatum": …
```
=> New data set: 2022-12-07T111603Z

latest-json
```diff -u pjson/2022-12-08T114303Z.json pjson/2022-12-09T111403Z.json```:
```
--- pjson/2022-12-08T114303Z.json	2022-12-08 11:43:04.332607594 +0000
+++ pjson/2022-12-09T111403Z.json	2022-12-09 11:14:04.353040419 +0000
@@ -29994,7 +29994,7 @@
"Krh_I": null,
@@ -37356,7 +37356,7 @@
"Datum_neu": 1667779200000,
"F\u00e4lle_Meldedatum": 308,
-        "Hosp_Meldedatum": 15, …
```
=> New data set: 2022-12-09T111403Z

latest-json
```diff -u pjson/2022-12-12T110503Z.json pjson/2022-12-13T110204Z.json```:
```
--- pjson/2022-12-12T110503Z.json	2022-12-12 11:05:04.166045954 +0000
+++ pjson/2022-12-13T110204Z.json	2022-12-13 11:02:04.579356843 +0000
@@ -38266,7 +38266,7 @@
"Datum_neu": 1669852800000,
-        "F\u00e4lle_Meldedatum": 138,
+        "F\u00e4lle_Meldedatum": 139,
@@ -38304,7 +38304,7 @@
"Datum_neu": 1669939200000,
-        "F\u00e4lle_Meldedatum": 125,
+        "F\u00e4lle_Meldedatum": 126, …
```
=> New data set: 2022-12-13T110204Z

latest-json
```diff -u pjson/2022-12-13T110204Z.json pjson/2022-12-14T110603Z.json```:
```
--- pjson/2022-12-13T110204Z.json	2022-12-13 11:02:04.579356843 +0000
+++ pjson/2022-12-14T110603Z.json	2022-12-14 11:06:04.201405633 +0000
@@ -37470,7 +37470,7 @@
"Datum_neu": 1668038400000,
"F\u00e4lle_Meldedatum": 128,
+        "Hosp_Meldedatum": 7,
@@ -37660,7 +37660,7 @@
"Datum_neu": 1668470400000,
"F\u00e4lle_Meldedatum": 139,
-        "Hosp_Meldedatum": 13, …
```
=> New data set: 2022-12-14T110603Z

latest-json
```diff -u pjson/2022-12-19T114005Z.json pjson/2022-12-20T112503Z.json```:
```
--- pjson/2022-12-19T114005Z.json	2022-12-19 11:40:06.088224195 +0000
+++ pjson/2022-12-20T112503Z.json	2022-12-20 11:25:04.386748698 +0000
@@ -37759,7 +37759,7 @@
{
"Datum": "18.11.2022",
-        "Fallzahl": 271047,
+        "Fallzahl": 271048,
"ObjectId": 987,
"Sterbefall": null,
"Genesungsfall": null,
@@ -37772,7 +37772,7 @@
"Datum_neu": 1668729600000,
-        "F\u00e4lle_Meldedatum": 222,
+        "F\u00e4lle_Meldedatum": 223,
@@ -37797,7 +37797,7 @@
{ …
```
=> New data set: 2022-12-20T112503Z

latest-json
```diff -u pjson/2022-12-20T112503Z.json pjson/2022-12-21T105103Z.json```:
```
--- pjson/2022-12-20T112503Z.json	2022-12-20 11:25:04.386748698 +0000
+++ pjson/2022-12-21T105103Z.json	2022-12-21 10:51:04.367821339 +0000
@@ -36292,7 +36292,7 @@
"Datum_neu": 1665360000000,
"F\u00e4lle_Meldedatum": 866,
-        "Hosp_Meldedatum": 37,
+        "Hosp_Meldedatum": 36,
@@ -37886,7 +37886,7 @@
"Datum_neu": 1668988800000,
-        "F\u00e4lle_Meldedatum": 277,
+        "F\u00e4lle_Meldedatum": 278, …
```
=> New data set: 2022-12-21T105103Z

latest-json
```diff -u pjson/2022-12-21T105103Z.json pjson/2022-12-22T110204Z.json```:
```
--- pjson/2022-12-21T105103Z.json	2022-12-21 10:51:04.367821339 +0000
+++ pjson/2022-12-22T110204Z.json	2022-12-22 11:02:04.960435314 +0000
@@ -38228,7 +38228,7 @@
"Datum_neu": 1669766400000,
-        "F\u00e4lle_Meldedatum": 216,
+        "F\u00e4lle_Meldedatum": 217,
@@ -38266,7 +38266,7 @@
"Datum_neu": 1669852800000,
-        "F\u00e4lle_Meldedatum": 208,
+        "F\u00e4lle_Meldedatum": 209, …
```
=> New data set: 2022-12-22T110204Z

latest-json
```diff -u pjson/2022-12-22T110204Z.json pjson/2022-12-23T124204Z.json```:
```
--- pjson/2022-12-22T110204Z.json	2022-12-22 11:02:04.960435314 +0000
+++ pjson/2022-12-23T124204Z.json	2022-12-23 12:42:04.550561550 +0000
@@ -34886,7 +34886,7 @@
"Datum_neu": 1662163200000,
"F\u00e4lle_Meldedatum": 108,
@@ -35418,7 +35418,7 @@
"Datum_neu": 1663372800000,
"F\u00e4lle_Meldedatum": 97, …
```
=> New data set: 2022-12-23T124204Z

latest-json
```diff -u pjson/2022-12-27T110404Z.json pjson/2022-12-28T104703Z.json```:
```
--- pjson/2022-12-27T110404Z.json	2022-12-27 11:04:04.548704733 +0000
+++ pjson/2022-12-28T104703Z.json	2022-12-28 10:47:03.868217880 +0000
@@ -38570,7 +38570,7 @@
"Datum_neu": 1670544000000,
-        "F\u00e4lle_Meldedatum": 247,
+        "F\u00e4lle_Meldedatum": 248,
@@ -38684,7 +38684,7 @@
"Datum_neu": 1670803200000,
-        "F\u00e4lle_Meldedatum": 201,
+        "F\u00e4lle_Meldedatum": 202, …
```
=> New data set: 2022-12-28T104703Z

latest-json
```diff -u pjson/2022-12-29T105003Z.json pjson/2022-12-30T104404Z.json```:
```
--- pjson/2022-12-29T105003Z.json	2022-12-29 10:50:04.011483023 +0000
+++ pjson/2022-12-30T104404Z.json	2022-12-30 10:44:04.491782155 +0000
@@ -38762,7 +38762,7 @@
"Datum_neu": 1670976000000,
"F\u00e4lle_Meldedatum": 194,
-        "Hosp_Meldedatum": 19,
+        "Hosp_Meldedatum": 18,
@@ -39064,13 +39064,13 @@
"Inzidenz": 211.034879126405,
"Datum_neu": 1671667200000,
-        "F\u00e4lle_Meldedatum": 158,
+        "F\u00e4lle_Meldedatum": 159, …
```
=> New data set: 2022-12-30T104404Z

latest-json
```diff -u pjson/2022-12-30T104404Z.json pjson/2023-01-02T112604Z.json```:
```
--- pjson/2022-12-30T104404Z.json	2022-12-30 10:44:04.491782155 +0000
+++ pjson/2023-01-02T112604Z.json	2023-01-02 11:26:05.164772560 +0000
@@ -35466,7 +35466,7 @@
"Krh_I": null,
@@ -36074,7 +36074,7 @@
"Krh_I": null,
@@ …
```
=> New data set: 2023-01-02T112604Z

latest-json
```diff -u pjson/2023-01-02T112604Z.json pjson/2023-01-03T105804Z.json```:
```
--- pjson/2023-01-02T112604Z.json	2023-01-02 11:26:05.164772560 +0000
+++ pjson/2023-01-03T105804Z.json	2023-01-03 10:58:04.437405236 +0000
@@ -36188,7 +36188,7 @@
"Krh_I": null,
@@ -36226,7 +36226,7 @@
"Krh_I": null,
@@ …
```
=> New data set: 2023-01-03T105804Z

latest-json
```diff -u pjson/2023-01-03T105804Z.json pjson/2023-01-04T105004Z.json```:
```
--- pjson/2023-01-03T105804Z.json	2023-01-03 10:58:04.437405236 +0000
+++ pjson/2023-01-04T105004Z.json	2023-01-04 10:50:04.513267733 +0000
@@ -38306,7 +38306,7 @@
"Datum_neu": 1669939200000,
"F\u00e4lle_Meldedatum": 205,
-        "Hosp_Meldedatum": 16,
+        "Hosp_Meldedatum": 17,
@@ -38354,7 +38354,7 @@
"Krh_I": null, …
```
=> New data set: 2023-01-04T105004Z

latest-json
```diff -u pjson/2023-01-05T105503Z.json pjson/2023-01-06T105203Z.json```:
```
--- pjson/2023-01-05T105503Z.json	2023-01-05 10:55:04.334967899 +0000
+++ pjson/2023-01-06T105203Z.json	2023-01-06 10:52:04.068805442 +0000
@@ -34010,7 +34010,7 @@
"Datum_neu": 1660176000000,
-        "F\u00e4lle_Meldedatum": 307,
+        "F\u00e4lle_Meldedatum": 306,
@@ -34200,7 +34200,7 @@
"Datum_neu": 1660608000000,
-        "F\u00e4lle_Meldedatum": 417,
+        "F\u00e4lle_Meldedatum": 416, …
```
=> New data set: 2023-01-06T105203Z

latest-json
```diff -u pjson/2023-01-09T105504Z.json pjson/2023-01-10T104308Z.json```:
```
--- pjson/2023-01-09T105504Z.json	2023-01-09 10:55:04.650477933 +0000
+++ pjson/2023-01-10T104308Z.json	2023-01-10 10:43:09.240669473 +0000
@@ -38760,7 +38760,7 @@
"Datum_neu": 1670976000000,
-        "F\u00e4lle_Meldedatum": 195,
@@ -38988,7 +38988,7 @@
"Datum_neu": 1671494400000,
-        "F\u00e4lle_Meldedatum": 234,
+        "F\u00e4lle_Meldedatum": 235, …
```
=> New data set: 2023-01-10T104308Z

latest-json
```diff -u pjson/2023-01-10T104308Z.json pjson/2023-01-11T104304Z.json```:
```
--- pjson/2023-01-10T104308Z.json	2023-01-10 10:43:09.240669473 +0000
+++ pjson/2023-01-11T104304Z.json	2023-01-11 10:43:04.613287426 +0000
@@ -39294,7 +39294,7 @@
"Datum_neu": 1672185600000,
"F\u00e4lle_Meldedatum": 162,
-        "Hosp_Meldedatum": 20,
+        "Hosp_Meldedatum": 21,
@@ -39330,7 +39330,7 @@
"Datum_neu": 1672272000000,
-        "F\u00e4lle_Meldedatum": 109,
+        "F\u00e4lle_Meldedatum": 110, …
```
=> New data set: 2023-01-11T104304Z

latest-json
```diff -u pjson/2023-01-11T104304Z.json pjson/2023-01-12T105403Z.json```:
```
--- pjson/2023-01-11T104304Z.json	2023-01-11 10:43:04.613287426 +0000
+++ pjson/2023-01-12T105403Z.json	2023-01-12 10:54:04.420502454 +0000
@@ -39370,7 +39370,7 @@
"Datum_neu": 1672358400000,
"F\u00e4lle_Meldedatum": 110,
@@ -39518,7 +39518,7 @@
"Zuwachs_Genesung": 215,
-        "Inzidenz": 140.091238909444,
"Datum_neu": 1672704000000, …
```
=> New data set: 2023-01-12T105403Z

latest-json
```diff -u pjson/2023-01-12T105403Z.json pjson/2023-01-13T110704Z.json```:
```
--- pjson/2023-01-12T105403Z.json	2023-01-12 10:54:04.420502454 +0000
+++ pjson/2023-01-13T110704Z.json	2023-01-13 11:07:04.747635382 +0000
@@ -33934,7 +33934,7 @@
"Datum_neu": 1660003200000,
-        "F\u00e4lle_Meldedatum": 460,
+        "F\u00e4lle_Meldedatum": 461,
@@ -35910,7 +35910,7 @@
"Datum_neu": 1664496000000,
-        "F\u00e4lle_Meldedatum": 477,
+        "F\u00e4lle_Meldedatum": 478, …
```
=> New data set: 2023-01-13T110704Z

latest-json
```diff -u pjson/2023-01-13T110704Z.json pjson/2023-01-16T113604Z.json```:
```
--- pjson/2023-01-13T110704Z.json	2023-01-13 11:07:04.747635382 +0000
+++ pjson/2023-01-16T113604Z.json	2023-01-16 11:36:05.331608117 +0000
@@ -39594,7 +39594,7 @@
"Zuwachs_Genesung": 159,
-        "Inzidenz": 127.159739933187,
"Datum_neu": 1672876800000,
"F\u00e4lle_Meldedatum": 72,
@@ -39632,15 +39632,15 @@
"Zuwachs_Genesung": 139,
-        "Inzidenz": 121.412407054851,
"Datum_neu": …
```
=> New data set: 2023-01-16T113604Z

latest-json
```diff -u pjson/2023-01-16T113604Z.json pjson/2023-01-17T110203Z.json```:
```
--- pjson/2023-01-16T113604Z.json	2023-01-16 11:36:05.331608117 +0000
+++ pjson/2023-01-17T110203Z.json	2023-01-17 11:02:04.262327222 +0000
@@ -39746,15 +39746,15 @@
"Zuwachs_Genesung": 26,
-        "Inzidenz": 111.354574517763,
"Datum_neu": 1673222400000,
-        "F\u00e4lle_Meldedatum": 83,
-        "Inzidenz_RKI": 91.1,
-        "Krh_N_belegt": 806,
- …
```
=> New data set: 2023-01-17T110203Z

latest-json
```diff -u pjson/2023-01-17T110203Z.json pjson/2023-01-18T110103Z.json```:
```
--- pjson/2023-01-17T110203Z.json	2023-01-17 11:02:04.262327222 +0000
+++ pjson/2023-01-18T110103Z.json	2023-01-18 11:01:04.214021839 +0000
@@ -37822,7 +37822,7 @@
"Krh_I": null,
@@ -38874,7 +38874,7 @@
"Datum_neu": 1671235200000,
-        "F\u00e4lle_Meldedatum": 69,
+        "F\u00e4lle_Meldedatum": 70, …
```
=> New data set: 2023-01-18T110103Z

latest-json
```diff -u pjson/2023-01-18T110103Z.json pjson/2023-01-19T110703Z.json```:
```
--- pjson/2023-01-18T110103Z.json	2023-01-18 11:01:04.214021839 +0000
+++ pjson/2023-01-19T110703Z.json	2023-01-19 11:07:04.156902034 +0000
@@ -35036,7 +35036,7 @@
"Datum_neu": 1662508800000,
-        "F\u00e4lle_Meldedatum": 263,
+        "F\u00e4lle_Meldedatum": 264,
@@ -35416,7 +35416,7 @@
"Datum_neu": 1663372800000,
-        "F\u00e4lle_Meldedatum": 97,
+        "F\u00e4lle_Meldedatum": 96, …
```
=> New data set: 2023-01-19T110703Z

latest-json
```diff -u pjson/2023-01-19T110703Z.json pjson/2023-01-20T110504Z.json```:
```
--- pjson/2023-01-19T110703Z.json	2023-01-19 11:07:04.156902034 +0000
+++ pjson/2023-01-20T110504Z.json	2023-01-20 11:05:04.675271041 +0000
@@ -38418,7 +38418,7 @@
"Datum_neu": 1670198400000,
-        "F\u00e4lle_Meldedatum": 293,
+        "F\u00e4lle_Meldedatum": 294,
@@ -39152,7 +39152,7 @@
"Krh_I": null, …
```
=> New data set: 2023-01-20T110504Z

latest-json
```diff -u pjson/2023-01-20T110504Z.json pjson/2023-01-23T121304Z.json```:
```
--- pjson/2023-01-20T110504Z.json	2023-01-20 11:05:04.675271041 +0000
+++ pjson/2023-01-23T121304Z.json	2023-01-23 12:13:04.813716849 +0000
@@ -39304,7 +39304,7 @@
"Krh_I": null,
@@ -39380,7 +39380,7 @@
"Krh_I": null,
@@ …
```
=> New data set: 2023-01-23T121304Z

latest-json
```diff -u pjson/2023-01-23T121304Z.json pjson/2023-01-24T110504Z.json```:
```
--- pjson/2023-01-23T121304Z.json	2023-01-23 12:13:04.813716849 +0000
+++ pjson/2023-01-24T110504Z.json	2023-01-24 11:05:05.133381344 +0000
@@ -40012,15 +40012,15 @@
"Zuwachs_Genesung": 147,
-        "Inzidenz": 61.2450159847696,
"Datum_neu": 1673827200000,
"F\u00e4lle_Meldedatum": 60,
-        "Inzidenz_RKI": 48.8,
-        "Krh_N_belegt": 710,
-        "Krh_I_belegt": 61,
+        "Krh_N_belegt": …
```
=> New data set: 2023-01-24T110504Z

latest-json
```diff -u pjson/2023-01-25T113304Z.json pjson/2023-01-26T112804Z.json```:
```
--- pjson/2023-01-25T113304Z.json	2023-01-25 11:33:04.704255332 +0000
+++ pjson/2023-01-26T112804Z.json	2023-01-26 11:28:04.671568576 +0000
@@ -37620,7 +37620,7 @@
"Datum_neu": 1668384000000,
-        "F\u00e4lle_Meldedatum": 260,
+        "F\u00e4lle_Meldedatum": 259,
@@ -39178,7 +39178,7 @@
"Datum_neu": 1671926400000,
-        "F\u00e4lle_Meldedatum": 24,
+        "F\u00e4lle_Meldedatum": 25, …
```
=> New data set: 2023-01-26T112804Z

latest-json
```diff -u pjson/2023-01-26T112804Z.json pjson/2023-01-27T110903Z.json```:
```
--- pjson/2023-01-26T112804Z.json	2023-01-26 11:28:04.671568576 +0000
+++ pjson/2023-01-27T110903Z.json	2023-01-27 11:09:04.364235892 +0000
@@ -39722,7 +39722,7 @@
"Krh_I": null,
@@ -39798,7 +39798,7 @@
"Krh_I": null,
@@ …
```
=> New data set: 2023-01-27T110903Z

latest-json
```diff -u pjson/2023-01-30T105004Z.json pjson/2023-01-31T104204Z.json```:
```
--- pjson/2023-01-30T105004Z.json	2023-01-30 10:50:04.614666860 +0000
+++ pjson/2023-01-31T104204Z.json	2023-01-31 10:42:04.587429946 +0000
@@ -38798,7 +38798,7 @@
"Datum_neu": 1671062400000,
-        "F\u00e4lle_Meldedatum": 216,
+        "F\u00e4lle_Meldedatum": 217,
@@ -40014,7 +40014,7 @@
"Datum_neu": 1673827200000,
-        "F\u00e4lle_Meldedatum": 60,
+        "F\u00e4lle_Meldedatum": 59, …
```
=> New data set: 2023-01-31T104204Z

latest-json
```diff -u pjson/2023-01-31T104204Z.json pjson/2023-02-01T103204Z.json```:
```
--- pjson/2023-01-31T104204Z.json	2023-01-31 10:42:04.587429946 +0000
+++ pjson/2023-02-01T103204Z.json	2023-02-01 10:32:04.968986325 +0000
@@ -39330,7 +39330,7 @@
"Datum_neu": 1672272000000,
-        "F\u00e4lle_Meldedatum": 110,
+        "F\u00e4lle_Meldedatum": 111,
@@ -40204,7 +40204,7 @@
"Datum_neu": 1674259200000,
-        "F\u00e4lle_Meldedatum": 19,
+        "F\u00e4lle_Meldedatum": 20, …
```
=> New data set: 2023-02-01T103204Z

latest-json
```diff -u pjson/2023-02-01T103204Z.json pjson/2023-02-02T105304Z.json```:
```
--- pjson/2023-02-01T103204Z.json	2023-02-01 10:32:04.968986325 +0000
+++ pjson/2023-02-02T105304Z.json	2023-02-02 10:53:04.487076900 +0000
@@ -39710,7 +39710,7 @@
"Datum_neu": 1673136000000,
-        "F\u00e4lle_Meldedatum": 13,
+        "F\u00e4lle_Meldedatum": 12,
@@ -40166,7 +40166,7 @@
"Datum_neu": 1674172800000,
-        "F\u00e4lle_Meldedatum": 46, …
```
=> New data set: 2023-02-02T105304Z

latest-json
```diff -u pjson/2023-02-02T105304Z.json pjson/2023-02-07T110704Z.json```:
```
--- pjson/2023-02-02T105304Z.json	2023-02-02 10:53:04.487076900 +0000
+++ pjson/2023-02-07T110704Z.json	2023-02-07 11:07:04.683983012 +0000
@@ -34998,7 +34998,7 @@
"Datum_neu": 1662422400000,
-        "F\u00e4lle_Meldedatum": 299,
+        "F\u00e4lle_Meldedatum": 300,
@@ -39532,7 +39532,7 @@
"Krh_I": null, …
```
=> New data set: 2023-02-07T110704Z

latest-json
```diff -u pjson/2023-02-14T110203Z.json pjson/2023-02-21T111104Z.json```:
```
--- pjson/2023-02-14T110203Z.json	2023-02-14 11:02:04.361624289 +0000
+++ pjson/2023-02-21T111104Z.json	2023-02-21 11:11:04.510261001 +0000
@@ -36102,7 +36102,7 @@
"Datum_neu": 1664928000000,
"F\u00e4lle_Meldedatum": 920,
+        "Hosp_Meldedatum": 13,
@@ -40092,7 +40092,7 @@
"Datum_neu": 1674000000000,
"F\u00e4lle_Meldedatum": 53,
+        "Hosp_Meldedatum": 10, …
```
=> New data set: 2023-02-21T111104Z

latest-json
```diff -u pjson/2023-02-21T111104Z.json pjson/2023-02-28T121604Z.json```:
```
--- pjson/2023-02-21T111104Z.json	2023-02-21 11:11:04.510261001 +0000
+++ pjson/2023-02-28T121604Z.json	2023-02-28 12:16:04.698526319 +0000
@@ -35036,7 +35036,7 @@
"Datum_neu": 1662508800000,
-        "F\u00e4lle_Meldedatum": 264,
+        "F\u00e4lle_Meldedatum": 263,
@@ -35264,7 +35264,7 @@
"Datum_neu": 1663027200000,
-        "F\u00e4lle_Meldedatum": 389,
+        "F\u00e4lle_Meldedatum": 388, …
```
=> New data set: 2023-02-28T121604Z

latest-json
```diff -u pjson/2023-02-28T121604Z.json pjson/2023-03-07T110104Z.json```:
```
--- pjson/2023-02-28T121604Z.json	2023-02-28 12:16:04.698526319 +0000
+++ pjson/2023-03-07T110104Z.json	2023-03-07 11:01:05.173948857 +0000
@@ -40596,7 +40596,7 @@
"Krh_I": null,
@@ -40786,7 +40786,7 @@
"Krh_I": null,
@@ …
```
=> New data set: 2023-03-07T110104Z

latest-json
```diff -u pjson/2023-03-07T110104Z.json pjson/2023-03-14T105303Z.json```:
```
--- pjson/2023-03-07T110104Z.json	2023-03-07 11:01:05.173948857 +0000
+++ pjson/2023-03-14T105303Z.json	2023-03-14 10:53:04.191854290 +0000
@@ -38848,7 +38848,7 @@
"Krh_I": null,
+        "SterbeF_Sterbedatum": 3,
@@ -40282,7 +40282,7 @@
"Datum_neu": 1674432000000,
"F\u00e4lle_Meldedatum": 73,
+        "Hosp_Meldedatum": 8, …
```
=> New data set: 2023-03-14T105303Z

latest-json
```diff -u pjson/2023-03-14T105303Z.json pjson/2023-03-21T110504Z.json```:
```
--- pjson/2023-03-14T105303Z.json	2023-03-14 10:53:04.191854290 +0000
+++ pjson/2023-03-21T110504Z.json	2023-03-21 11:05:04.470664532 +0000
@@ -39684,7 +39684,7 @@
"Krh_I": null,
@@ -39722,7 +39722,7 @@
"Krh_I": null,
@@ …
```
=> New data set: 2023-03-21T110504Z
