latest-json

```diff -u pjson/2020-11-11T110304Z.json pjson/2020-11-12T110404Z.json```:
```
--- pjson/2020-11-11T110304Z.json	2020-11-11 11:03:04.237234203 +0000
+++ pjson/2020-11-12T110404Z.json	2020-11-12 11:04:04.717783616 +0000
@@ -5257,7 +5257,7 @@
"F\u00e4lle_Meldedatum": 64,
-        "Hosp_Meldedatum": 0
+        "Hosp_Meldedatum": 1
}
},
{
@@ -5476,7 +5476,7 @@
"F\u00e4lle_Meldedatum": 155,
-        "SterbeF_Meldedatum": 3,
+        "SterbeF_Meldedatum": 4,
"Hosp_Meldedatum": 4
}
},
@@ -5494,7 +5494,7 @@
"Zuwachs_Genesung": 69,
-        "Inzidenz": 112.1,
"F\u00e4lle_Meldedatum": 178, …
```

New data set: 2020-11-12T110404Z

---

latest-json

```diff -u pjson/2020-11-13T110903Z.json pjson/2020-11-14T110304Z.json```:
```
--- pjson/2020-11-13T110903Z.json	2020-11-13 11:09:04.115986969 +0000
+++ pjson/2020-11-14T110304Z.json	2020-11-14 11:03:04.618845849 +0000
@@ -5320,7 +5320,7 @@
-        "F\u00e4lle_Meldedatum": 92,
+        "F\u00e4lle_Meldedatum": 94,
"Hosp_Meldedatum": 5
@@ -5430,7 +5430,7 @@
-        "F\u00e4lle_Meldedatum": 34,
+        "F\u00e4lle_Meldedatum": 33, …
```

New data set: 2020-11-14T110304Z

---

latest-json

```diff -u pjson/2020-11-19T112104Z.json pjson/2020-11-20T110303Z.json```:
```
--- pjson/2020-11-19T112104Z.json	2020-11-19 11:21:04.375907263 +0000
+++ pjson/2020-11-20T110303Z.json	2020-11-20 11:03:04.134065745 +0000
@@ -5078,7 +5078,7 @@
"Datum_neu": 1602806400000,
-        "F\u00e4lle_Meldedatum": 44,
"Hosp_Meldedatum": 7
@@ -5320,7 +5320,7 @@
-        "F\u00e4lle_Meldedatum": 95,
+        "F\u00e4lle_Meldedatum": 96, …
```

New data set: 2020-11-20T110303Z

---

latest-json

```diff -u pjson/2020-11-26T110903Z.json pjson/2020-11-26T112103Z.json```:
```
--- pjson/2020-11-26T110903Z.json	2020-11-26 11:09:03.141599322 +0000
+++ pjson/2020-11-26T112103Z.json	2020-11-26 11:21:03.683008133 +0000
@@ -172,7 +172,7 @@
"Datum_neu": 1583539200000,
-        "F\u00e4lle_Meldedatum": null,
"SterbeF_Meldedatum": null,
"Hosp_Meldedatum": null
@@ -194,7 +194,7 @@
"Datum_neu": 1583625600000,
-        "F\u00e4lle_Meldedatum": null,
+        "F\u00e4lle_Meldedatum": 0,
"SterbeF_Meldedatum": null, …
```

New data set: 2020-11-26T112103Z

---

latest-json

```diff -u pjson/2020-12-02T111803Z.json pjson/2020-12-03T111703Z.json```:
```
--- pjson/2020-12-02T111803Z.json	2020-12-02 11:18:03.341869304 +0000
+++ pjson/2020-12-03T111703Z.json	2020-12-03 11:17:03.294037878 +0000
@@ -5680,7 +5680,7 @@
"F\u00e4lle_Meldedatum": 33,
"Inzidenz_RKI": null
}
},
@@ -5887,7 +5887,7 @@
"F\u00e4lle_Meldedatum": 123,
-        "Hosp_Meldedatum": 9,
+        "Hosp_Meldedatum": 10,
"Inzidenz_RKI": null
}
},
@@ -6048,7 +6048,7 @@
"F\u00e4lle_Meldedatum": 234, …
```

New data set: 2020-12-03T111703Z

---

latest-json

```diff -u pjson/2020-12-09T122204Z.json pjson/2020-12-09T123003Z.json```:
```
--- pjson/2020-12-09T122204Z.json	2020-12-09 12:22:04.779973568 +0000
+++ pjson/2020-12-09T123003Z.json	2020-12-09 12:30:03.963396857 +0000
@@ -201,6 +201,30 @@
"sqlType": "sqlTypeOther",
"domain": null,
"defaultValue": null
+    },
+    {
+      "name": "Fallzahl_aktiv_Zuwachs",
+      "type": "esriFieldTypeInteger",
+      "alias": "Fallzahl_aktiv_Zuwachs",
+      "sqlType": "sqlTypeOther",
+      "domain": null,
+      "defaultValue": null
+    },
+    {
+      "name": "Krh_N",
+      "type": "esriFieldTypeInteger",
+      "alias": "Krh_N",
+      "sqlType": "sqlTypeOther",
+ …
```

New data set: 2020-12-09T123003Z

---

latest-json

```diff -u pjson/2021-05-24T100703Z.json pjson/2021-05-25T100303Z.json```:
```
--- pjson/2021-05-24T100703Z.json	2021-05-24 10:07:03.202845653 +0000
+++ pjson/2021-05-25T100303Z.json	2021-05-25 10:03:03.876249943 +0000
@@ -14088,7 +14088,7 @@
"Datum_neu": 1619740800000,
-        "F\u00e4lle_Meldedatum": 106,
+        "F\u00e4lle_Meldedatum": 107,
@@ -14647,12 +14647,12 @@
"Zuwachs_Genesung": 110,
-        "Inzidenz": 83.3,
"Datum_neu": 1621209600000, …
```

New data set: 2021-05-25T100303Z

---

latest-json

```diff -u pjson/2021-06-04T100203Z.json pjson/2021-06-05T100203Z.json```:
```
--- pjson/2021-06-04T100203Z.json	2021-06-04 10:02:03.568639687 +0000
+++ pjson/2021-06-05T100203Z.json	2021-06-05 10:02:03.755165819 +0000
@@ -15010,12 +15010,12 @@
"Zuwachs_Genesung": 50,
-        "Inzidenz": 36.3,
"Datum_neu": 1622160000000,
"F\u00e4lle_Meldedatum": 25,
-        "Inzidenz_RKI": 34.1,
@@ -15024,7 +15024,7 @@ …
```

New data set: 2021-06-05T100203Z

---

latest-json

```diff -u pjson/2021-06-07T100403Z.json pjson/2021-06-08T100203Z.json```:
```
--- pjson/2021-06-07T100403Z.json	2021-06-07 10:04:03.155433232 +0000
+++ pjson/2021-06-08T100203Z.json	2021-06-08 10:02:03.598860690 +0000
@@ -785,7 +785,7 @@
-        "Zuwachs_Genesung": 1,
+        "Zuwachs_Genesung": 0,
"Datum_neu": 1584921600000,
@@ -818,7 +818,7 @@
-        "Zuwachs_Genesung": 2,
+        "Zuwachs_Genesung": 1, …
```

New data set: 2021-06-08T100203Z

---

latest-json

```diff -u pjson/2021-06-19T100503Z.json pjson/2021-06-20T100504Z.json```:
```
--- pjson/2021-06-19T100503Z.json	2021-06-19 10:05:03.751672944 +0000
+++ pjson/2021-06-20T100504Z.json	2021-06-20 10:05:04.414106381 +0000
@@ -15505,12 +15505,12 @@
"Zuwachs_Genesung": 24,
-        "Inzidenz": 10.0578325370883,
"Datum_neu": 1623456000000,
"F\u00e4lle_Meldedatum": 3,
-        "Inzidenz_RKI": 10.1,
@@ -15519,7 +15519,7 @@ …
```

New data set: 2021-06-20T100504Z

---

latest-json

```diff -u pjson/2021-06-20T100504Z.json pjson/2021-06-21T095203Z.json```:
```
--- pjson/2021-06-20T100504Z.json	2021-06-20 10:05:04.414106381 +0000
+++ pjson/2021-06-21T095203Z.json	2021-06-21 09:52:03.680583144 +0000
@@ -15538,12 +15538,12 @@
"Zuwachs_Genesung": 13,
-        "Inzidenz": 8.1,
"Datum_neu": 1623542400000,
"F\u00e4lle_Meldedatum": 1,
-        "Inzidenz_RKI": 8.1,
@@ -15552,7 +15552,7 @@ …
```

New data set: 2021-06-21T095203Z

---

latest-json

Auto-update 'latest-json'.

---

latest-json

```diff -u pjson/2021-07-18T101104Z.json pjson/2021-07-19T100603Z.json```:
```
--- pjson/2021-07-18T101104Z.json	2021-07-18 10:11:04.242336202 +0000
+++ pjson/2021-07-19T100603Z.json	2021-07-19 10:06:03.939012639 +0000
@@ -16961,12 +16961,12 @@
"Zuwachs_Genesung": 4,
-        "Inzidenz": 5.2,
"Datum_neu": 1625961600000,
"F\u00e4lle_Meldedatum": 0,
-        "Inzidenz_RKI": 5,
@@ -16976,7 +16976,7 @@ …
```

New data set: 2021-07-19T100603Z

---

latest-json

```diff -u pjson/2021-07-19T100603Z.json pjson/2021-07-20T100504Z.json```:
```
--- pjson/2021-07-19T100603Z.json	2021-07-19 10:06:03.939012639 +0000
+++ pjson/2021-07-20T100504Z.json	2021-07-20 10:05:04.145787747 +0000
@@ -17206,8 +17206,8 @@
"Inzidenz_RKI": 8.1,
"Fallzahl_aktiv": 63,
-        "Krh_N_belegt": 121,
-        "Krh_I_belegt": 30,
+        "Krh_N_belegt": null,
+        "Krh_I_belegt": null,
"Fallzahl_aktiv_Zuwachs": 9,
"Krh_I": null,
@@ -17215,7 +17215,7 @@
"Inzi_SN_RKI": 3.5,
-        "Mutation": 128,
+        "Mutation": null,
}
}, …
```

New data set: 2021-07-20T100504Z

---

latest-json

```diff -u pjson/2021-08-02T120803Z.json pjson/2021-08-03T100703Z.json```:
```
--- pjson/2021-08-02T120803Z.json	2021-08-02 12:08:03.354782866 +0000
+++ pjson/2021-08-03T100703Z.json	2021-08-03 10:07:03.860237468 +0000
@@ -13767,7 +13767,7 @@
"Datum_neu": 1617840000000,
-        "F\u00e4lle_Meldedatum": 144,
@@ -16827,7 +16827,7 @@
"Datum_neu": 1625616000000, …
```

New data set: 2021-08-03T100703Z

---

latest-json

```diff -u pjson/2021-08-03T100703Z.json pjson/2021-08-04T102003Z.json```:
```
--- pjson/2021-08-03T100703Z.json	2021-08-03 10:07:03.860237468 +0000
+++ pjson/2021-08-04T102003Z.json	2021-08-04 10:20:03.322535835 +0000
@@ -9449,7 +9449,7 @@
-        "F\u00e4lle_Meldedatum": 292,
+        "F\u00e4lle_Meldedatum": 293,
@@ -17543,7 +17543,7 @@
"Datum_neu": 1627430400000,
"F\u00e4lle_Meldedatum": 17,
"Inzidenz_RKI": 11, …
```

New data set: 2021-08-04T102003Z

---

latest-json

```diff -u pjson/2021-08-10T102004Z.json pjson/2021-08-11T100504Z.json```:
```
--- pjson/2021-08-10T102004Z.json	2021-08-10 10:20:04.399601987 +0000
+++ pjson/2021-08-11T100504Z.json	2021-08-11 10:05:04.160445436 +0000
@@ -17745,7 +17745,7 @@
"Inzidenz": 10.7762491468803,
"Datum_neu": 1627948800000,
"Inzidenz_RKI": 9.2,
@@ -17847,7 +17847,7 @@
"Inzidenz": 10.7762491468803,
"Datum_neu": 1628208000000,
+        "F\u00e4lle_Meldedatum": 9, …
```

New data set: 2021-08-11T100504Z

---

latest-json

```diff -u pjson/2021-08-12T100103Z.json pjson/2021-08-13T100203Z.json```:
```
--- pjson/2021-08-12T100103Z.json	2021-08-12 10:01:03.706541805 +0000
+++ pjson/2021-08-13T100203Z.json	2021-08-13 10:02:03.219963388 +0000
@@ -10095,7 +10095,7 @@
"Datum_neu": 1608508800000,
-        "F\u00e4lle_Meldedatum": 435,
+        "F\u00e4lle_Meldedatum": 434,
"Hosp_Meldedatum": 47,
@@ -15683,7 +15683,7 @@
"Krh_I": null, …
```

New data set: 2021-08-13T100203Z

---

latest-json

```diff -u pjson/2021-08-14T100103Z.json pjson/2021-08-16T101004Z.json```:
```
--- pjson/2021-08-14T100103Z.json	2021-08-14 10:01:04.012678753 +0000
+++ pjson/2021-08-16T101004Z.json	2021-08-16 10:10:04.419641265 +0000
@@ -10605,7 +10605,7 @@
"Datum_neu": 1609804800000,
-        "F\u00e4lle_Meldedatum": 390,
+        "F\u00e4lle_Meldedatum": 389,
@@ -17033,7 +17033,7 @@
"Datum_neu": 1626134400000,
"F\u00e4lle_Meldedatum": 20, …
```

New data set: 2021-08-16T101004Z

---

latest-json

```diff -u pjson/2021-08-16T112203Z.json pjson/2021-08-17T100603Z.json```:
```
--- pjson/2021-08-16T112203Z.json	2021-08-16 11:22:03.267789089 +0000
+++ pjson/2021-08-17T100603Z.json	2021-08-17 10:06:03.757671927 +0000
@@ -13291,7 +13291,7 @@
-        "F\u00e4lle_Meldedatum": 190,
+        "F\u00e4lle_Meldedatum": 189,
@@ -17879,12 +17879,12 @@
"Zuwachs_Genesung": 6,
-        "Inzidenz": 10.7762491468803,
"Datum_neu": 1628294400000, …
```

New data set: 2021-08-17T100603Z

---

latest-json

```diff -u pjson/2021-08-18T100303Z.json pjson/2021-08-19T100602Z.json```:
```
--- pjson/2021-08-18T100303Z.json	2021-08-18 10:03:03.999087243 +0000
+++ pjson/2021-08-19T100602Z.json	2021-08-19 10:06:02.686608046 +0000
@@ -13665,7 +13665,7 @@
"Datum_neu": 1617580800000,
-        "F\u00e4lle_Meldedatum": 63,
+        "F\u00e4lle_Meldedatum": 62,
@@ -15161,7 +15161,7 @@
"Datum_neu": 1621382400000,
-        "F\u00e4lle_Meldedatum": 81, …
```

New data set: 2021-08-19T100602Z

---

latest-json

```diff -u pjson/2021-08-19T100602Z.json pjson/2021-08-20T102503Z.json```:
```
--- pjson/2021-08-19T100602Z.json	2021-08-19 10:06:02.686608046 +0000
+++ pjson/2021-08-20T102503Z.json	2021-08-20 10:25:03.838039782 +0000
@@ -9857,7 +9857,7 @@
-        "F\u00e4lle_Meldedatum": 430,
+        "F\u00e4lle_Meldedatum": 429,
@@ -9959,7 +9959,7 @@
"Datum_neu": 1608163200000,
-        "F\u00e4lle_Meldedatum": 515,
+        "F\u00e4lle_Meldedatum": 514, …
```

New data set: 2021-08-20T102503Z

---

latest-json

```diff -u pjson/2021-08-24T100602Z.json pjson/2021-08-24T102603Z.json```:
```
--- pjson/2021-08-24T100602Z.json	2021-08-24 10:06:02.675503199 +0000
+++ pjson/2021-08-24T102603Z.json	2021-08-24 10:26:03.139844398 +0000
@@ -18344,16 +18344,16 @@
{
"Datum": "21.08.2021",
-        "Fallzahl": null,
+        "Fallzahl": 31212,
"ObjectId": 533,
"Sterbefall": null,
-        "Genesungsfall": null,
+        "Genesungsfall": 29836,
"Anzeige_Indikator": null,
"Hospitalisierung": null,
-        "Zuwachs_Genesung": null,
+        "Zuwachs_Genesung": 4, …
```

New data set: 2021-08-24T102603Z

---

latest-json

```diff -u pjson/2021-09-06T102002Z.json pjson/2021-09-07T100204Z.json```:
```
--- pjson/2021-09-06T102002Z.json	2021-09-06 10:20:02.764282495 +0000
+++ pjson/2021-09-07T100204Z.json	2021-09-07 10:02:04.104176012 +0000
@@ -265,7 +265,7 @@
-        "Zuwachs_Genesung": null,
+        "Zuwachs_Genesung": 0,
"Datum_neu": 1583539200000,
@@ -299,7 +299,7 @@
-        "Zuwachs_Genesung": null,
+        "Zuwachs_Genesung": 0,
"BelegteBetten": …
```

New data set: 2021-09-07T100204Z

---

latest-json

```diff -u pjson/2021-09-09T100303Z.json pjson/2021-09-10T100804Z.json```:
```
--- pjson/2021-09-09T100303Z.json	2021-09-09 10:03:03.804441771 +0000
+++ pjson/2021-09-10T100804Z.json	2021-09-10 10:08:04.178634227 +0000
@@ -18799,9 +18799,9 @@
"Inzidenz": 37.896476166529,
"Datum_neu": 1630627200000,
-        "F\u00e4lle_Meldedatum": 24,
+        "F\u00e4lle_Meldedatum": 23,
"Inzidenz_RKI": 34,
"Fallzahl_aktiv": 422,
@@ -18867,7 +18867,7 @@
"Datum_neu": 1630800000000,
- …
```

New data set: 2021-09-10T100804Z

---

latest-json

```diff -u pjson/2022-05-18T101403Z.json pjson/2022-05-19T103304Z.json```:
```
--- pjson/2022-05-18T101403Z.json	2022-05-18 10:14:04.022141029 +0000
+++ pjson/2022-05-19T103304Z.json	2022-05-19 10:33:04.204831467 +0000
@@ -15012,7 +15012,7 @@
"Datum_neu": 1616976000000,
"F\u00e4lle_Meldedatum": 126,
-        "Hosp_Meldedatum": 22,
+        "Hosp_Meldedatum": 21,
@@ -15050,7 +15050,7 @@
"Datum_neu": 1617062400000,
"F\u00e4lle_Meldedatum": 221, …
```

New data set: 2022-05-19T103304Z

---

latest-json

```diff -u pjson/2022-08-22T100503Z.json pjson/2022-08-23T105803Z.json```:
```
--- pjson/2022-08-22T100503Z.json	2022-08-22 10:05:04.135042089 +0000
+++ pjson/2022-08-23T105803Z.json	2022-08-23 10:58:03.640692363 +0000
@@ -26216,7 +26216,7 @@
-        "Zuwachs_Genesung": 510,
+        "Zuwachs_Genesung": 490,
"Datum_neu": 1642464000000,
@@ -26254,7 +26254,7 @@
-        "Zuwachs_Genesung": 359,
+        "Zuwachs_Genesung": 350, …
```

New data set: 2022-08-23T105803Z

---

latest-json

```diff -u pjson/2022-12-12T110204Z.json pjson/2022-12-12T110503Z.json```:
```
--- pjson/2022-12-12T110204Z.json	2022-12-12 11:02:04.661927599 +0000
+++ pjson/2022-12-12T110503Z.json	2022-12-12 11:05:04.166045954 +0000
@@ -38434,7 +38434,7 @@
-        "H_Inzidenz": 10.59,
+        "H_Inzidenz": 10.86,
"H_Zeitraum": null,
"H_Datum": null,
"Datum_Bett": "04.12.2022"
@@ -38472,7 +38472,7 @@
-        "H_Inzidenz": 11.03,
+        "H_Inzidenz": 11.48,
"H_Zeitraum": null,
"H_Datum": null,
"Datum_Bett": "05.12.2022"
@@ -38510,7 +38510,7 @@ …
```

New data set: 2022-12-12T110503Z

---

latest-json

```diff -u pjson/2022-12-19T112504Z.json pjson/2022-12-19T114005Z.json```:
```
--- pjson/2022-12-19T112504Z.json	2022-12-19 11:25:04.779349589 +0000
+++ pjson/2022-12-19T114005Z.json	2022-12-19 11:40:06.088224195 +0000
@@ -37759,7 +37759,7 @@
{
"Datum": "18.11.2022",
-        "Fallzahl": 271046,
+        "Fallzahl": 271047,
"ObjectId": 987,
"Sterbefall": null,
"Genesungsfall": null,
@@ -37797,7 +37797,7 @@
{
"Datum": "19.11.2022",
-        "Fallzahl": 271123,
+        "Fallzahl": 271124,
"ObjectId": 988,
"Sterbefall": null,
"Genesungsfall": null,
@@ -37835,7 +37835,7 @@
{
"Datum": "20.11.2022",
- …
```

New data set: 2022-12-19T114005Z
